Repository projectdiscovery/nuclei-templates, pull requests merged in 2020-11, with the labels that each got.

#555 Adding Wordpress Plugin Scanner
  .nuclei-ignore
  fuzzing/wp-plugin-scan.yaml
  wordlists/wp-plugins.txt
Labels: Status: On Hold

#613 Added check for spoofable SPF records
  dns/mx-service-detector.yaml
  dns/spoofable-spf-records-ptr.yaml
Labels: Type: Discussion

#438 Add README.py and update README.md
  .github/README.py
  README.md
Labels: Status: Review Needed

#627 Favicon recon
  technologies/favicon-detection.yaml
Labels: Status: On Hold

#591 Add iis-shortname template
  security-misconfiguration/iis-shortname.yaml
Labels: Status: On Hold

#625 Swapped put-method-enabled to DSL for multi-req
  security-misconfiguration/put-method-enabled.yaml
Labels: Type: Enhancement

#601 Adding Unencrypted F5 Cookie disclosure
  tokens/unencrypted-bigip-ltm-cookie.yaml
Labels: Status: Review Needed
