Repository projectdiscovery/nuclei-templates, pull requests merged in 2020-09, with the labels that each got.

#434 More templates to Lotus Domino + workflow to bind them together
  cves/CVE-2005-2428.yaml
  technologies/lotus-domino-version.yaml
  workflows/lotus-domino-workflow.yaml
Labels: Status: Revision Needed

#429 Create wordpress-emails-verification-for-woocommerce.yaml
  vulnerabilities/wordpress-emails-verification-for-woocommerce.yaml
Labels: Status: Review Needed

#329 drafting ntlm-directories for fix
  files/ntlm-directories.yaml
Labels: help wanted

#450 Update kubernetes-pods.yaml
  panels/kubernetes-pods.yaml
Labels: Type: Discussion
