Repository projectdiscovery/nuclei-templates, pull requests merged in 2020-08, with the labels that each got.

#353 Update CVE-2018-1000129.yaml
  cves/CVE-2018-1000129.yaml
Labels: Status: Accepted

#365 drafting CVE-2017-7529
  cves/CVE-2017-7529.yaml
Labels: help wanted

#362 Update favicon-detection.yaml
  technologies/favicon-detection.yaml
Labels: Status: Review Needed

#378 robots.txt file module, lotus domino technology module and extension fixing
  files/robots.txt.yaml
  panels/traefik-dashboard.yaml
  technologies/tech-detect.yaml
Labels: Status: Completed
