Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-05, with the labels that each got.

#1380 Added CVE-2017-12629
  cves/2017/CVE-2017-12629.yaml
Labels: Status: Completed

#1372 Added CVE-2017-3506
  cves/2017/CVE-2017-3506.yaml
Labels: Status: Completed

#1303 OOB Template updates (WIP)
  cves/2017/CVE-2017-9506.yaml
Labels: Status: Completed

#1302 Adding CVE-2020-7247 🔥 🔥
  cves/2020/CVE-2020-7247.yaml
Labels: Status: Completed

#962 add hashicorp-consul-rce
  vulnerabilities/other/hashicorp-consul-rce.yaml
Labels: Status: Completed

#1327 Adding Showdoc < 2.8.6 File Upload RCE
  vulnerabilities/other/showdoc-file-upload-rce.yaml
Labels: Status: Completed

#1410 Create rdp-detect.yaml
  network/rdp-detect.yaml
Labels: Status: Completed

#583 Tabnabbing template added
  miscellaneous/tabnabbing-check.yaml
Labels: Status: Completed

#1499 Update springboot-httptrace.yaml
  misconfiguration/springboot/springboot-httptrace.yaml
Labels: Type: Discussion

#1494 Security Checks for Magento - Templates and workflow
  cves/2020/CVE-2020-5776.yaml
  cves/2020/CVE-2020-5777.yaml
  exposed-panels/magento-admin-panel.yaml
  exposures/configs/magento-config.yaml
  technologies/magento-detect.yaml
  technologies/magmi-detect.yaml
  vulnerabilities/magento/magento-2-exposed-api.yaml
  vulnerabilities/magento/magento-cacheleak.yaml
  vulnerabilities/magento/magento-unprotected-dev-files.yaml
  workflows/magento-workflow.yaml
Labels: Status: Completed

#1517 Adding Jenkins default login
  default-logins/jenkins/jenkins-default.yaml
  exposed-panels/jenkins-login.yaml
Labels: Status: Completed

#1543 Add detection for JavaServer Faces and detection for vulnerable PrimeFaces 5.x EL Injection (CVE 2017 1000486)
  cves/2017/CVE-2017-1000486.yaml
  technologies/jsf-detection.yaml
Labels: Status: Completed

#1562 Bitbucker takeover matcher update
  takeovers/bitbucket-takeover.yaml
Labels: Type: Bug
