Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-04, with the labels that each got.

#1262 Added mysql native pass bruteforce template
  network/mysql-native-cred-bruteforce.yaml
Labels: Status: Completed, documentation

#1196 Added new check for Laravel debug mode enabled.
  misconfiguration/laravel-debug-enabled.yaml
  misconfiguration/laravel-debug-error.yaml
Labels: Status: Completed

#1362 Chamilo 1.11.14 LMS sql injection
  vulnerabilities/other/chamilo-lms-sqli.yaml
Labels: Status: Review Needed
