Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-02, with the labels that each got.

#799 Fixed typo in CVE-2020-12116 template
  cves/2020/CVE-2020-12116.yaml
Labels: Status: Review Needed

#845 Make swagger-api.yaml more complete
  exposures/apis/swagger-api.yaml
Labels: Status: Accepted

#967 Add CVE-2020-1185X Variants & Its Workflow
  cves/2020/CVE-2020-11853.yaml
  cves/2020/CVE-2020-11854.yaml
  workflows/micro-focus-workflow.yaml
Labels: Status: Completed

#981 Adding CVE-2021-3129
  cves/2021/CVE-2021-3129.yaml
Labels: Status: Completed
