Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-09, with the labels that each got.

#2512 Webpack Sourcemap Disclosure
  exposures/files/webpack-sourcemap-disclosure.yaml
Labels: Status: Completed

#2444 Added CVE-2021-32819
  cves/2021/CVE-2021-32819.yaml
Labels: Status: Completed

#2481 Added a CVE and template for missing security headers reporting
  cves/2019/CVE-2019-12616.yaml
  cves/2019/CVE-2019-9618.yaml
  cves/2020/CVE-2020-7209.yaml
  default-logins/abb/cs141-default-login.yaml
  miscellaneous/missing-csp.yaml
  miscellaneous/missing-hsts.yaml
  miscellaneous/missing-x-content-type-options.yaml
  miscellaneous/missing-x-frame-options.yaml
  misconfiguration/http-missing-security-headers.yaml
  vulnerabilities/other/mcafee-epo-rce.yaml
Labels: good first issue

#2553 Added vidyo-super default-creds Template
  default-logins/vidyo/vidyo-default-credentials.yaml
Labels: Status: Completed

#2627 Added CVE Annotation workflow
  .github/workflows/cve-annotate.yml
  .github/workflows/template-validate.yml
  .github/workflows/templates-stats.yml
Labels: Status: On Hold

#2561 CVE-2015-7450 (IBM WebSphere Java Object Deserialization RCE)
  cves/2015/CVE-2015-7450.yaml
Labels: Status: Completed

#2681 OMIGOD - Open Management Infrastructure RCE
  cves/2021/CVE-2021-38647.yaml
Labels: Status: In Progress

#2692 Metadata attribute update
  cves/2019/CVE-2019-1010287.yaml
  cves/2019/CVE-2019-12593.yaml
  cves/2020/CVE-2020-13167.yaml
  cves/2020/CVE-2020-14864.yaml
  cves/2021/CVE-2021-26295.yaml
  default-logins/abb/cs141-default-login.yaml
  dns/elasticbeantalk-takeover.yaml
  technologies/abyss-web-server.yaml
  technologies/iplanet-web-server.yaml
  technologies/kubernetes/kubernetes-enterprise-manager.yaml
  technologies/kubernetes/kubernetes-mirantis.yaml
  technologies/oracle/oracle-iplanet-web-server.yaml
  vulnerabilities/generic/top-xss-params.yaml
  vulnerabilities/other/bullwark-momentum-lfi.yaml
  vulnerabilities/other/sick-beard-xss.yaml
Labels: Status: Completed
