Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-01, with the labels that each got.

#715 Add CVE-2020-10148
  cves/CVE-2020-10148.yaml
  workflows/solarwinds-orion-workflow.yaml
Labels: Status: Completed

#713 Create composer-config.yaml
  files/composer-config.yaml
Labels: Status: Completed

#720 [WIP] ASP.NET Debugging Enabled detect
  security-misconfiguration/aspx-debug-mode.yaml
Labels: Status: In Progress

#767 Added CVE-2021-22873
  cves/2021/CVE-2021-22873.yaml
Labels: Status: Accepted
