Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-11, with the labels that each got.

#3032 wordpress-rdf-user-enum
  vulnerabilities/wordpress/rdf-user-enumeration.yaml
Labels: hacktoberfest-accepted

#3097 Create CVE-2019-1821.yaml
  cves/2019/CVE-2019-1821.yaml
Labels: Status: In Progress

#2889 Add ms-active-directory-certificate-services-detect.yaml
  exposed-panels/ms-adcs-detect.yaml
Labels: Status: Completed
