Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-07, with the labels that each got.

#1733 Added CVE-2018-1000130/ CVE-2018-2628/ CVE-2018-2628/ CVE-2019-3401/ CVE-2020-1938/ oracle-bi-default-login/ jolokia-heap-disclosure
  cves/2017/CVE-2017-9822.yaml
  cves/2018/CVE-2018-1000130.yaml
  cves/2018/CVE-2018-2628.yaml
  cves/2018/CVE-2018-2893.yaml
  cves/2018/CVE-2018-8715.yaml
  cves/2020/CVE-2020-1938.yaml
  default-logins/oracle/oracle-bi-default-credentials.yaml
  vulnerabilities/jolokia/jolokia-heap-info-disclosure.yaml
Labels: Status: Completed

#1870 Added CONTRIBUTING.md and Pull Request template
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Status: Review Needed

#1897 Create ceros-takeover.yaml
  takeovers/ceros-takeover.yaml
Labels: Type: Discussion

#1885 git-logs
  exposures/configs/git-config.yaml
Labels: Status: Completed

#2141 Create CVE-2018-20985.yaml
  cves/2018/CVE-2018-20985.yaml
Labels: Status: On Hold

#1958 QVISDVR JSF ViewState Deserialization RCE
  iot/qvisdvr-deserialization-rce.yaml
Labels: Status: Completed

#782 Create github-page-files.yml
  exposures/files/github-gemfile-files.yaml
  exposures/files/github-page-config.yaml
Labels: Status: Completed

#2143 Added DNSSEC Detection
  dns/dnssec-detection.yaml
Labels: Status: Completed
