Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-03, with the labels that each got.

#1015 hmc
  exposed-panels/hmc-hybris-panel.yaml
Labels: Status: Completed

#909 Add poc CVE Apache Struts2
  cves/2007/CVE-2007-4556.yaml
  cves/2012/CVE-2012-0392.yaml
  cves/2013/CVE-2013-1965.yaml
  cves/2013/CVE-2013-2251.yaml
  cves/2016/CVE-2016-3081.yaml
  cves/2017/CVE-2017-12611.yaml
  cves/2017/CVE-2017-5638.yaml
  cves/2017/CVE-2017-9791.yaml
  cves/2017/CVE-2017-9805.yaml
  cves/2018/CVE-2018-11776.yaml
  cves/2020/CVE-2020-17530.yaml
  exposures/logs/struts-debug-mode.yaml
Labels: Status: In Progress

#900 Added DVWA default login
  default-logins/dvwa/dvwa-default-login.yaml
Labels: Status: Completed

#946 Adding CVE-2018-18778
  cves/2018/CVE-2018-18778.yaml
Labels: Status: Completed

#921 Add CVE-2015-3306
  cves/2015/CVE-2015-3306.yaml
Labels: Status: Available, Status: Completed

#1066 Add teacherease-xss and parentlink-xss to /vulnerabilities/other/
  vulnerabilities/other/parentlink-xss.yaml
Labels: Status: In Progress

#984 Create CVE-2020-24186.yaml
  cves/2020/CVE-2020-24186.yaml
  workflows/wordpress-workflow.yaml
Labels: Status: Completed

#920 Add CVE-2017-3881
  cves/2017/CVE-2017-3881.yaml
Labels: Status: Completed

#755 Create openam-ldap-injection.yaml
  technologies/openam-detection.yaml
  vulnerabilities/other/bullwark-momentum-lfi.yaml
Labels: Status: Completed

#1071 Adminer Template update
  exposed-panels/adminer-panel.yaml
Labels: Status: Completed

#1096 Wordpress plugin fuzzing
  fuzzing/wp-plugin-scan.yaml
  helpers/wordlists/wp-plugins.txt
Labels: Status: Completed

#1124 Add CVE-2020-35489 Detection
  cves/2020/CVE-2020-35489.yaml
  workflows/wordpress-workflow.yaml
Labels: Status: Review Needed

#1144 removing redundant boolean check
  cves/2019/CVE-2019-11869.yaml
  cves/2020/CVE-2020-17518.yaml
  exposures/configs/circleci-config.yaml
  exposures/configs/composer-config.yaml
  exposures/configs/docker-compose-config.yml
  misconfiguration/put-method-enabled.yaml
  vulnerabilities/other/powercreator-cms-rce.yaml
Labels: enhancement
