Repository projectdiscovery/nuclei-templates, pull requests merged in 2021-06, with the labels that each got.

#1616 Added CVE-2020-11978 & Airflow Workflow
  cves/2020/CVE-2020-11978.yaml
  cves/2020/CVE-2020-13927.yaml
  default-logins/apache/airflow-default-credentials.yaml
  exposed-panels/airflow-exposure.yaml
  exposed-panels/airflow-panel.yaml
  exposures/configs/airflow-configuration-exposure.yaml
  misconfiguration/airflow/airflow-debug.yaml
  misconfiguration/airflow/unauthenticated-airflow.yaml
  technologies/airflow-detect.yaml
  workflows/airflow-workflow.yaml
Labels: Status: Completed

#1631 SAP NetWeaver update
  cves/2020/CVE-2020-6287.yaml
  exposed-panels/sap-netweaver-portal.yaml
  exposed-panels/sap-recon-detect.yaml
  helpers/payloads/CVE-2020-6287.xml
  misconfiguration/sap/sap-directory-listing.yaml
  misconfiguration/sap/sap-netweaver-info-leak.yaml
  network/sap-router-info-leak.yaml
  network/sap-router.yaml
  technologies/sap-netweaver-as-java-detect.yaml
  technologies/sap-netweaver-detect.yaml
  technologies/sap-netweaver-webgui.yaml
  workflows/sap-netweaver-workflow.yaml
Labels: Type: Bug, Type: Enhancement

#1556 Added file based templates 🎉
  file/android/adb-backup-enabled.yaml
  file/android/biometric-detect.yaml
  file/android/certificate-validation.yaml
  file/android/content-scheme.yaml
  file/android/debug-enabled.yaml
  file/android/dynamic-broadcast-receiver.yaml
  file/android/file-scheme.yaml
  file/android/provider-path.yaml
  file/android/webview-addjavascript-interface.yaml
  file/android/webview-javascript.yaml
  file/android/webview-load-url.yaml
  file/android/webview-universal-access.yaml
  file/keys/amazon-mws-auth-token.yaml
  file/keys/aws-access-id.yaml
  file/keys/aws-cognito.yaml
  file/keys/cloudinary.yaml
  file/keys/credentials.yaml
  file/keys/dynatrace-token.yaml
  file/keys/facebook-client-id.yaml
  file/keys/facebook-secret.yaml
  file/keys/firebase-database.yaml
  file/keys/gcp-service-account.yaml
  file/keys/google-api.yaml
  file/keys/linkedin-id.yaml
  file/keys/mailchimp-api.yaml
  file/keys/mailgun-api.yaml
  file/keys/paypal-braintree-token.yaml
  file/keys/pictatic-api-key.yaml
  file/keys/private-key.yaml
  file/keys/s3-bucket.yaml
  file/keys/sendgrid-api.yaml
  file/keys/shopify-custom-token.yaml
  file/keys/shopify-private-token.yaml
  file/keys/shopify-shared-secret.yaml
  file/keys/shopify-token.yaml
  file/keys/slack-api.yaml
  file/keys/slack-webhook.yaml
  file/keys/square-access-token.yaml
  file/keys/square-oauth-secret.yaml
  file/keys/stripe-api-key.yaml
  file/keys/twilio-api.yaml
  file/keys/twitter-secret.yaml
Labels: Status: Completed

#1636 Update CVE-2018-18069.yaml
  cves/2018/CVE-2018-18069.yaml
Labels: Status: Review Needed

#1763 Added status to CVE-2012-3153
  cves/2012/CVE-2012-3153.yaml
Labels: Status: Completed

#1757 New template added
  misconfiguration/phpmyadmin-sql.php-server.yaml
  technologies/webmodule-ee.yaml
  vulnerabilities/wordpress/alfacgiapi-wordpress.yaml
  vulnerabilities/wordpress/wp-123contactform-plugin-listing.yaml
Labels: Status: Completed

#1747 Create CVE-2021-21389
  cves/2021/CVE-2021-21389.yaml
Labels: Status: Completed

#1811 Added sprintful-takeover
  takeovers/sprintful-takeover.yaml
Labels: Status: Completed

#1829 Detect javascript environment configs.
  exposures/configs/javascript-env.yaml
Labels: Status: Completed

#1813 Add detection of KEYCLOAK
  exposed-panels/key-cloak-admin-panel.yaml
Labels: Status: Completed
