Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-11, with the labels that each got.

#5931 Update netlify-takeover.yaml
  takeovers/netlify-takeover.yaml
Labels: Done

#5937 Update CVE-2019-14696.yaml
  cves/2019/CVE-2019-14696.yaml
Labels: Done

#5938 Update CNVD-2021-09650.yaml
  cnvd/2021/CNVD-2021-09650.yaml
  vulnerabilities/ruijie/ruijie-networks-rce.yaml
Labels: Done

#5926 Create werkzeug-debug.yaml
  misconfiguration/debug/werkzeug-debug.yaml
Labels: Done

#5928 Create xnat-default-login.yaml
  default-logins/xnat-default-login.yaml
Labels: Done

#5942 Update severity
  default-logins/activemq/activemq-default-login.yaml
Labels: Done

#5910 Create Moxa-Nport.yaml
  exposed-panels/nport-web-console.yaml
Labels: Hacktoberfest, Done

#5944 Create cloud-run-default-page.yaml
  technologies/google/cloud-run-default-page.yaml
Labels: Done

#5923 Create rekognition-image-validation-debug-exposed.yaml
  misconfiguration/rekognition-image-validation.yaml
Labels: Done

#5940 Fixed werkzeug-debug.yaml
  misconfiguration/debug/flask-werkzeug-debug.yaml
Labels: Done

#5945 Add openbsd relayd fingerprint
  exposed-panels/qnap/qnap-qts-panel.yaml
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#5925 Create hangfire-dashboard.yaml
  exposed-panels/hangfire-dashboard.yaml
Labels: Done

#5903 Create nginx-admin-panel.yaml
  exposed-panels/nginx-admin-panel.yaml
Labels: Hacktoberfest, Done

#5929 Update fingerprinthub-web-fingerprints.yaml
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#5953 Create coming-soon-page-detect.yaml
  technologies/coming-soon-page-detect.yaml
Labels: Done

#5951 Create gira-homeserver-homepage.yaml
  exposed-panels/gira-homeserver-homepage.yaml
Labels: Done

#5947 Create ampache-panel.yaml
  exposed-panels/ampache-panel.yaml
Labels: Done

#5958 Create global-traffic-statistics-exposed.yaml
  misconfiguration/global-traffic-statistics.yaml
Labels: Done

#5954 Create smarterstats-setup-exposed.yaml
  misconfiguration/smarterstats-setup.yaml
Labels: Done

#5955 Create questdb-console-exposed.yaml
  misconfiguration/questdb-console.yaml
Labels: Done

#5904 Create CVE-2022-22242.yaml
  cves/2022/CVE-2022-22242.yaml
Labels: Hacktoberfest, Done

#5902 Add php-detect
  technologies/php-detect.yaml
Labels: Done

#5957 Create hfs-panel-exposed.yaml
  misconfiguration/hfs-exposure.yaml
Labels: Done

#5962 Create espeasy-mega-exposure.yaml
  misconfiguration/espeasy-mega-exposure.yaml
Labels: Done

#5948 Create ampache-update-exposure.yaml
  misconfiguration/ampache-update-exposure.yaml
Labels: Done

#5950 Create CVE-2022-42233.yaml
  cves/2022/CVE-2022-42233.yaml
Labels: Done

#5949 Create CVE-2021-40661.yaml
  cves/2021/CVE-2021-40661.yaml
Labels: Done

#5952 Create CVE-2022-38870.yaml
  cves/2022/CVE-2022-38870.yaml
Labels: Done

#5963 Ricardomaia glpi detect
  exposed-panels/glpi-authentication.yaml
  exposed-panels/glpi-login.yaml
  exposed-panels/glpi-panel.yaml
  technologies/glpi-project-detect.yaml
Labels: Done

#5892 Update and merging glpi-panel.yaml
  exposed-panels/glpi-authentication.yaml
  exposed-panels/glpi-login.yaml
  exposed-panels/glpi-panel.yaml
  technologies/glpi-project-detect.yaml
Labels: Done

#5964 ActiveMQ OpenWire transport Detection
  network/detection/activemq-openwire-transport-detect.yaml
Labels: Done

#5965 Apache ActiveMQ Detection
  network/detection/apache-activemq-detect.yaml
Labels: Done

#5966 RabbitMQ Detection
  network/detection/rabbitmq-detect.yaml
Labels: Done

#5872 Create labkey-server-detect.yaml
  exposed-panels/labkey-server-login.yaml
Labels: Hacktoberfest, Done

#5967 Create ourmgmt3-panel.yaml
  exposed-panels/ourmgmt3-panel.yaml
Labels: Done

#5679 Update fortios-panel.yaml
  exposed-panels/fortinet/fortios-panel.yaml
Labels: Done

#5748 Added template for CVE-2021-25003
  cves/2021/CVE-2021-25003.yaml
Labels: Hacktoberfest, Done

#5901 feat: added version detection geowebserver
  technologies/geo-webserver-detect.yaml
  workflows/geowebserver-workflow.yaml
Labels: Hacktoberfest, Done

#5887 Added template for CVE-2022-0817
  cves/2022/CVE-2022-0817.yaml
Labels: Hacktoberfest, Done

#5727 Update github-personal-token.yaml
  file/keys/github/github-personal-token.yaml
Labels: Done

#5694 fix: Remove content-type header check for matrix
  technologies/matrix-detect.yaml
Labels: waiting for more info

#3845 add CVE-2022-0824
  cves/2022/CVE-2022-0824.yaml
Labels: Done

#5981 mailhog panel
  exposed-panels/mailhog-panel.yaml
Labels: Done

#5986 Added payroll-management-system-panel.yaml
  exposed-panels/payroll-management-system-panel.yaml
Labels: Done

#5988 Create deluge-webui-panel.yaml
  exposed-panels/deluge-webui-panel.yaml
Labels: Done

#5989 Create airnotifier-detect.yaml
  exposed-panels/airnotifier-panel.yaml
Labels: Done

#5990 MikroTik RouterOS API Detection
  network/detection/mikrotik-routeros-api-detect.yaml
Labels: Done

#5607 Create samsung-printer-default-login
  default-logins/samsung/samsung-printer-default-login.yaml
Labels: Done

#5996 template fix
  cves/2021/CVE-2021-24997.yaml
Labels: Done

#5984 Update webeditors.yaml
  exposed-panels/webeditors.yaml
Labels: Done

#5991 Create wiren-board-webui.yaml
  exposed-panels/wiren-board-webui.yaml
Labels: Done

#5971 Create CVE-2022-42749.yaml
  cves/2022/CVE-2022-42749.yaml
Labels: Done

#5968 Create CVE-2022-42746.yaml
  cves/2022/CVE-2022-42746.yaml
Labels: Done

#5969 Create CVE-2022-42747.yaml
  cves/2022/CVE-2022-42747.yaml
Labels: Done

#6004 Create ntop-panel-exposed.yaml
  misconfiguration/ntop-panel-exposed.yaml
Labels: Done

#5994 Added template for CVE-2022-0785
  cves/2022/CVE-2022-0785.yaml
Labels: Done

#5985 Added template for CVE-2022-0788
  cves/2022/CVE-2022-0788.yaml
Labels: Done

#5886 Added template for CVE-2022-0867
  cves/2022/CVE-2022-0867.yaml
Labels: Done

#6007 Create confluence-dashboard.yaml
  misconfiguration/confluence-dashboard.yaml
Labels: Done

#6006 Create linktap-gateway-exposure.yaml
  misconfiguration/linktap-gateway-exposure.yaml
Labels: Done

#6003 Added template for CVE-2022-2373
  cves/2022/CVE-2022-2373.yaml
Labels: Done

#6010 Create datahub-metadata-default-login.yaml
  default-logins/datahub/datahub-metadata-default-login.yaml
Labels: Done

#6011 Create ace-admin-dashboard.yaml
  misconfiguration/ace-admin-dashboard.yaml
Labels: Done

#6012 Create pa11y-dashboard.yaml
  misconfiguration/pa11y-dashboard.yaml
Labels: Done

#6013 Create codis-dashboard.yaml
  misconfiguration/codis-dashboard.yaml
Labels: Done

#6005 Create system-properties-exposure.yaml
  misconfiguration/system-properties-exposure.yaml
Labels: Done

#6015 Create hydra-dashboard.yaml
  misconfiguration/hydra-dashboard.yaml
Labels: Done

#5483 Create zebra-printer-detect
  iot/zebra-printer-detect.yaml
Labels: Done

#6017 Create ray-dashboard.yaml
  misconfiguration/ray-dashboard.yaml
Labels: Done

#6018 Create puppetdb-dashboard.yaml
  misconfiguration/puppetdb-dashboard.yaml
Labels: Done

#6019 Create unifi-wizard.yaml
  misconfiguration/installer/unifi-wizard-install.yaml
Labels: Done

#6020 Create openmage-install.yaml
  misconfiguration/installer/openmage-install.yaml
Labels: Done

#6021 Create testrail-install.yaml
  misconfiguration/installer/testrail-install.yaml
Labels: Done

#6022 Create uvdesk-install.yaml
  misconfiguration/installer/uvdesk-install.yaml
Labels: Done

#5995 Create git-logs-exposure-detect.yaml
  exposures/logs/git-exposure.yaml
Labels: Done

#5556 Add CVE-2022-40359
  cves/2022/CVE-2022-40359.yaml
  exposed-panels/kfm/kaes-file-manager.yaml
  exposed-panels/kfm/kfm-login-panel.yaml
Labels: Done

#5577 Add CVE-2022-26263
  cves/2022/CVE-2022-26263.yaml
Labels: Hacktoberfest, Done

#5978 feat: added lansweeper login version detect
  exposed-panels/lansweeper-login.yaml
Labels: Done

#5983 fix: remove LANCOM 1790VA-4G matcher to fix false negative
  exposed-panels/lancom-router-panel.yaml
Labels: Done

#6014 Add three new GitLab CVE templates
  cves/2022/CVE-2022-0735.yaml
  cves/2022/CVE-2022-1162.yaml
  cves/2022/CVE-2022-2185.yaml
Labels: Done

#6027 Create parse-dashboard.yaml
  exposed-panels/parse-dashboard.yaml
Labels: Done

#6028 Create dplus-dashboard.yaml
  exposed-panels/dplus-dashboard.yaml
Labels: Done

#6002 Tomcat Manager: detection and bf templates fixes for newver versions
  exposed-panels/apache/public-tomcat-manager.yaml
Labels: Done

#6031 Create elastic-hd-dashboard.yaml
  misconfiguration/elastic-hd-dashboard.yaml
Labels: Done

#6023 Add: Mongoose Server fingerprint
  technologies/mongoose-server.yaml
Labels: Done

#6032 Ansible AWX Detection Template
  technologies/ansible-awx-detect.yaml
Labels: Done

#5912 Added template for CVE-2022-1952
  cves/2022/CVE-2022-1952.yaml
Labels: Hacktoberfest, Done

#5980 Add CVE-2008-6465
  cves/2008/CVE-2008-6465.yaml
Labels: Done

#6025 Add JumpServer panel
  exposed-panels/jumpserver-panel.yaml
Labels: Done

#6034 Release Enhancements
  cves/2008/CVE-2008-6465.yaml
  cves/2022/CVE-2022-1952.yaml
  default-logins/datahub/datahub-metadata-default-login.yaml
  default-logins/samsung/samsung-printer-default-login.yaml
  exposed-panels/hydra-dashboard.yaml
  exposed-panels/wiren-board-webui.yaml
  iot/zebra-printer-detect.yaml
  misconfiguration/confluence-dashboard.yaml
  misconfiguration/ntop-panel-exposed.yaml
  network/detection/ibm-d2b-database-server.yaml
  network/detection/mikrotik-routeros-api.yaml
  technologies/aem-detect.yaml
  technologies/ansible-awx-detect.yaml
  technologies/basic-auth-detect.yaml
  technologies/bigip-detect.yaml
  technologies/emqx-detect.yaml
  technologies/favicon-detect.yaml
  technologies/hikvision-detect.yaml
  technologies/jsf-detect.yaml
  technologies/mongoose-server.yaml
  workflows/aem-workflow.yaml
  workflows/cisco-meraki-workflow.yaml
  workflows/dahua-workflow.yaml
  workflows/hikvision-workflow.yaml
  workflows/mautic-workflow.yaml
  workflows/opensns-workflow.yaml
  workflows/ricoh-workflow.yaml
Labels: Done

#6042 Fix jenkin typos
  cves/2018/CVE-2018-1000861.yaml
  vulnerabilities/jenkins/unauthenticated-jenkins.yaml
Labels: Done

#6035 Update matching features
  exposed-panels/xiaomi-wireless-router-login.yaml
Labels: Done

#6038 PQube 3 Power Analyzers
  iot/pqube-power-analyzers.yaml
Labels: Done

#6047 POP3 Detection
  network/detection/pop3-detect.yaml
Labels: Done

#6043 Update graphql-detect.yaml
  technologies/graphql-detect.yaml
Labels: Done

#6046 ESMTP Detection
  network/detection/esmtp-detect.yaml
Labels: Done

#5725 Add Dell iDRAC CVE-2018-1207.yaml to iDRAC workflow
  workflows/dell-idrac-workflow.yaml
Labels: Done

#6033 Create tekton-dashboard.yaml
  exposed-panels/tekton-dashboard.yaml
Labels: Done

#6048 Imap Detection
  network/detection/imap-detect.yaml
Labels: Done

#6040 Update template - CVE-2022-0346
  cves/2022/CVE-2022-0346.yaml
Labels: Done

#5973 feat: major change on led-imediacloud template
  exposed-panels/led-imediacloud-panel.yaml
  exposed-panels/xibocms-login.yaml
Labels: Done

#6026 Fix jumpserver match
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#6001 Added template for CVE-2022-2379
  cves/2022/CVE-2022-2379.yaml
Labels: Done

#6039 Added template for CVE-2022-1442
  cves/2022/CVE-2022-1442.yaml
Labels: Done

#6053 Create tornado-server-login.yaml
  technologies/tornado-server-login.yaml
Labels: Done

#6054 Create typo3-exception-debug.yaml
  misconfiguration/typo3-debug-mode.yaml
Labels: Done

#6056 Telnet Detection
  network/detection/telnet-detect.yaml
Labels: Done

#6058 MS .NET Remoting Detect
  network/detection/dotnet-remoting-service-detect.yaml
Labels: Done

#6064 Fix VisionHub Default Login Template
  default-logins/visionhub/visionhub-default-login.yaml
Labels: Done

#5580 Add CVE-2021-43510
  cves/2021/CVE-2021-43510.yaml
Labels: Status: Completed, Done

#5515 Add CVE-2020-21012
  cves/2020/CVE-2020-21012.yaml
Labels: Status: Completed, Done

#5521 Add CVE-2020-29284
  cves/2020/CVE-2020-29284.yaml
Labels: Status: Completed, Done

#6065 Delete ftp-default-credentials.yaml
  network/ftp-default-credentials.yaml
Labels: Status: Completed, Done

#5517 Add CVE-2020-24903
  cves/2020/CVE-2020-24903.yaml
Labels: Done

#5516 Add CVE-2020-24902
  cves/2020/CVE-2020-24902.yaml
Labels: Done

#5535 Add CVE-2022-0349
  cves/2022/CVE-2022-0349.yaml
Labels: Done

#6062 Added template for CVE-2022-3484
  cves/2022/CVE-2022-3484.yaml
Labels: Done

#6045 Enhancing FTP response code
  network/ftp-anonymous-login.yaml
Labels: Status: Completed, Done

#6051 Add template to detect SOGo software instance
  technologies/sogo-detect.yaml
Labels: Done

#6070 Create tasmota-config-webui.yaml
  misconfiguration/tasmota-config-webui.yaml
Labels: Done

#6071 Create tasmota-install.yaml
  misconfiguration/installer/tasmota-install.yaml
Labels: Done

#6075 Create phpMemcachedAdmin-panel.yaml
  misconfiguration/phpmemcached-admin-panel.yaml
Labels: Done

#6057 Fix tech tags in technologies folder
  technologies/adobe/adobe-coldfusion-detect.yaml
  technologies/adobe/adobe-coldfusion-error-detect.yaml
  technologies/angular-detect.yaml
  technologies/apollo-server-detect.yaml
  technologies/geo-webserver-detect.yaml
  technologies/hanwang-detect.yaml
  technologies/hp-blade-admin-detect.yaml
  technologies/json-server.yaml
  technologies/landesk/landesk-csa.yaml
  technologies/landesk/landesk-ma.yaml
  technologies/magento-detect.yaml
  technologies/magmi-detect.yaml
  technologies/microstrategy-detect.yaml
  technologies/osquery-fleet-detect.yaml
  technologies/roundcube-webmail-portal.yaml
  technologies/sap/sap-netweaver-detect.yaml
  technologies/sap/sap-netweaver-webgui.yaml
  technologies/sap/sap-web-dispatcher-admin-portal.yaml
  technologies/sap/sap-web-dispatcher.yaml
  technologies/snipeit-panel.yaml
  technologies/swag-instance-default-page.yaml
  technologies/telerik/telerik-dialoghandler-detect.yaml
  technologies/thinkcmf-detect.yaml
  technologies/vmware/vmware-site-recovery-manager.yaml
  technologies/vmware/vmware-vrealize-detect.yaml
  technologies/yeswiki-detect.yaml
Labels: Done

#6077 Added 2 template for detecting wagtail CMS and Mezzanine CMS
  exposed-panels/wagtail-cms-detect.yaml
Labels: Done

#6076 Update wuzhicms-sqli.yaml
  vulnerabilities/other/wuzhicms-sqli.yaml
Labels: Done

#6073 Create tooljet-default-login.yaml
  default-logins/tooljet/tooljet-default-login.yaml
Labels: Done

#6079 Create hetzner-cloud-detect.yaml
  technologies/hetzner-cloud-detect.yaml
Labels: Done

#6078 Create apache-licenserc.yaml
  exposures/files/apache-licenserc.yaml
Labels: Done

#6088 Unauthenticated Mercurial Detect
  misconfiguration/unauth-mercurial.yaml
Labels: Done

#6087 Create apache-jmeter-dashboard.yaml
  exposed-panels/apache-jmeter-dashboard.yaml
Labels: Done

#6083 Create CVE-2022-40881.yaml
  cves/2022/CVE-2022-40881.yaml
Labels: Done

#6099 Detect Haproxy Exporter
  misconfiguration/haproxy-exporter-metrics.yaml
Labels: Done

#6090 Update hubspot-takeover.yaml
  takeovers/hubspot-takeover.yaml
Labels: Done

#5480 Create secui-waf-detect
  technologies/secui-waf-detect.yaml
Labels: Done

#3125 gitlab, github & discord file templates
  file/keys/github-recovery-code.yaml
Labels: Status: Completed, Done

#3684 Create CVE-2020-13121.yaml
  cves/2020/CVE-2020-13121.yaml
Labels: Status: Completed, Done

#6085 Delete cowrie-honeypot-detect.yaml
  network/cowrie-honeypot-detect.yaml
Labels: Status: Completed, Done

#6094 Unauthenticated Selenium Grid Console
  misconfiguration/unauth-selenium-grid-console.yaml
Labels: Status: Completed, Done

#6068 Create notion-detect.yaml
  technologies/notion-detect.yaml
Labels: Status: Completed, Done

#5498 fix: false negative sophos-fw-version-detect
  exposed-panels/sophos-fw-version-detect.yaml
Labels: Status: Completed, Done

#6102 Create blackbox-exporter-metrics.yaml
  misconfiguration/blackbox-exporter-metrics.yaml
Labels: Status: Completed, Done

#6092 Unauthenticated Selenium Grid
  exposed-panels/selenium-grid.yaml
Labels: Status: Completed, Done

#6069 Create bootstrap-admin-panel.yaml
  misconfiguration/bootstrap-admin-panel-template.yaml
Labels: Status: Completed, Done

#6086 Create np-data-cache.yaml
  exposed-panels/np-data-cache.yaml
Labels: Status: Completed, Done

#6098 Detect MongoDB Exporter
  misconfiguration/mongodb-exporter-metrics.yaml
Labels: Status: Completed, Done

#5722 fix: false negative keycloak
  exposed-panels/key-cloak-admin-panel.yaml
Labels: Status: Review Needed

#6115 Update pop3-detect.yaml
  network/detection/pop3-detect.yaml
Labels: Status: Completed, Done

#6116 Create fastpanel-hosting-control-panel
  exposed-panels/fastpanel-hosting-control-panel.yaml
Labels: Done

#6123 Update crlf-injection.yaml
  vulnerabilities/generic/crlf-injection.yaml
Labels: Done

#6112 Create api-giphy.yaml
  token-spray/api-giphy.yaml
Labels: Done
