Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-05, with the labels that each got.

#4325 Create CVE-2019-12962.yaml
  cves/2019/CVE-2019-12962.yaml
Labels: good first issue

#4312 Create CVE-2022-1040.yaml
  cves/2022/CVE-2022-1040.yaml
Labels: Status: On Hold

#4335 Update CVE-2022-1388.yaml
  cves/2022/CVE-2022-1388.yaml
Labels: good first issue, waiting for more info

#4384 Create CVE-2022-21705.yaml
  cves/2022/CVE-2022-21705.yaml
Labels: good first issue

#4419 Add CVE-2022-1598
  cves/2022/CVE-2022-1598.yaml
Labels: Type: Epic

#3468 Update CVE-2017-10271.yaml
  cves/2017/CVE-2017-10271.yaml
Labels: Status: Completed
