Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-08, with the labels that each got.

#4909 Create omni-commerce-connect-detect.yaml
  technologies/omni-commerce-connect-detect.yaml
Labels: Done

#4969 Create hybris-default-login.yaml
  default-logins/hybris/hybris-default-login.yaml
Labels: Done

#4956 Create CVE-2016-10367.yaml
  cves/2016/CVE-2016-10367.yaml
Labels: Done

#4959 new: template to detect WebSphere Liberty pages
  technologies/default-websphere-liberty.yaml
Labels: Done

#3893 Create CVE-2019-9915.yaml
  cves/2019/CVE-2019-9915.yaml
Labels: Done

#4964 Create carrental-xss.yaml
  vulnerabilities/other/carrental-xss.yaml
Labels: Done

#4881 Create ems-sqli.yaml
  vulnerabilities/other/ems-sqli.yaml
Labels: Done

#4938 Create angular-detect.yaml
  technologies/angular-detect.yaml
Labels: Done

#4971 Login Templates
  exposed-panels/cisco/cisco-vmanage-login.yaml
  exposed-panels/jamf-login.yaml
  exposed-panels/rundeck-login.yaml
  exposed-panels/vmware-hcx-login.yaml
  exposed-panels/vmware-nsx-login.yaml
Labels: Done

#4948 rdp tempalte update
  network/rdp-detect.yaml
Labels: Done

#4952 Create CVE-2019-11370.yaml
  cves/2019/CVE-2019-11370.yaml
Labels: Done

#4974 Added ftm-manager-panel.yaml
  exposed-panels/ftm-manager-panel.yaml
Labels: Done

#4970 Create CVE-2019-10717.yaml
  cves/2019/CVE-2019-10717.yaml
Labels: Done

#4966 Create CVE-2022-32028.yaml
  cves/2022/CVE-2022-32028.yaml
Labels: Done

#4961 Create CVE-2022-32024.yaml
  cves/2022/CVE-2022-32024.yaml
Labels: Done

#4965 Create CVE-2022-32026.yaml
  cves/2022/CVE-2022-32026.yaml
Labels: Done

#4960 Create CVE-2022-32022.yaml
  cves/2022/CVE-2022-32022.yaml
Labels: Done

#4985 Create CVE-2022-1906.yaml
  cves/2022/CVE-2022-1906.yaml
Labels: Done

#4982 Create solarview-compact-xss.yaml
  vulnerabilities/other/solarview-compact-xss.yaml
Labels: Done

#4983 Create jamf-setup-assistant.yaml
  exposed-panels/jamf-setup-assistant.yaml
Labels: Done

#4988 symfony template update
  exposures/configs/symfony-profiler.yaml
  misconfiguration/symfony-debug.yaml
Labels: Done

#4987 Create CVE-2022-0660
  cves/2022/CVE-2022-0660.yaml
Labels: Done

#4986 Change hardcoded password
  network/vsftpd-detection.yaml
Labels: Done

#4999 Create microfocus-vibe-panel.yaml
  exposed-panels/microfocus-vibe-panel.yaml
Labels: Done

#4998 Create microfocus-filr-panel.yaml
  exposed-panels/microfocus-filr-panel.yaml
Labels: Done

#4992 Delete microweber-stored-xss.yaml
  vulnerabilities/microweber/microweber-stored-xss.yaml
Labels: Done

#1345 Create CVE-2020-14750.yaml
  cves/2020/CVE-2020-14750.yaml
Labels: Done

#4913 Create crystal-live-http-server-lfi.yaml
  vulnerabilities/other/crystal-live-server-lfi.yaml
Labels: Done

#4937 Create sap-spartacus-detect.yaml
  technologies/sap-spartacus-detect.yaml
Labels: Done

#4958 Create CVE-2022-31793.yaml
  cves/2022/CVE-2022-31793.yaml
Labels: Done

#5003 Create wp-athlon-manage-calameo-publications-xss.yaml
  vulnerabilities/wordpress/calameo-publications-xss.yaml
Labels: Done

#5004 Create wp-avchat-3-xss.yaml
  vulnerabilities/wordpress/avchat-video-chat-xss.yaml
Labels: Done

#5008 Update omnia-mpx-lfi.yaml
  vulnerabilities/other/omnia-mpx-lfi.yaml
Labels: Done

#5010 Create CVE-2021-21799.yaml
  cves/2021/CVE-2021-21799.yaml
Labels: Done

#5011 Create CVE-2021-21800.yaml
  cves/2021/CVE-2021-21800.yaml
Labels: Done

#5012 Create CVE-2021-21805.yaml
  cves/2021/CVE-2021-21805.yaml
Labels: Done

#5015 Create mitel-panel-detect.yaml
  exposed-panels/mitel-panel-detect.yaml
Labels: Done

#5007 Update grafana-public-signup.yaml
  misconfiguration/grafana-public-signup.yaml
Labels: Done

#5019 Create CVE-2022-34048.yaml
  cves/2022/CVE-2022-34048.yaml
Labels: Done

#5016 vRealize Log Insight Login Detect
  exposed-panels/vrealize-loginsight-panel.yaml
Labels: Done

#4905 Create CVE-2022-0968
  cves/2022/CVE-2022-0968.yaml
Labels: Done

#4903 Detect Oracle WebCenter Sites
  technologies/oracle/oracle-webcenter-sites.yaml
Labels: Done

#2811 Added CVE-2021-24370
  cves/2021/CVE-2021-24370.yaml
Labels: Done

#5024 Create CVE-2022-0599.yaml
  cves/2022/CVE-2022-0599.yaml
Labels: Done

#5023 Added CVE-2021-24910.yaml
  cves/2021/CVE-2021-24910.yaml
Labels: Done

#5032 Create procfile-config.yaml
  exposures/configs/procfile-config.yaml
Labels: Done

#5031 Create pipeline-configuration.yaml
  exposures/files/pipeline-configuration.yaml
Labels: Done

#5030 Create bitbucket-pipelines.yaml
  exposures/files/bitbucket-pipelines.yaml
Labels: Done

#5033 Create pantheon-upstream.yaml
  exposures/files/pantheon-upstream.yaml
Labels: Done

#5039 Create jboss-juddi.yaml
  exposed-panels/jboss-juddi.yaml
Labels: Done

#5040 Create oracle-cgi-printenv.yaml
  exposures/configs/oracle-cgi-printenv.yaml
Labels: Done

#5036 Added intelbras-detect
  exposed-panels/intelbras-panel.yaml
Labels: Done

#5041 Create liferay-resource-leak.yaml
  vulnerabilities/j2ee/liferay-resource-leak.yaml
Labels: Done

#5029 Create CVE-2022-32159.yaml
  cves/2022/CVE-2022-32159.yaml
Labels: Done

#5042 Create jenkins-openuser-register.yaml
  misconfiguration/jenkins/jenkins-openuser-register.yaml
Labels: Done

#5043 Create oracle-test-cgi.yaml
  exposures/files/oracle-test-cgi.yaml
Labels: Done

#5044 Create weiphp-panel.yaml
  exposed-panels/weiphp-panel.yaml
Labels: Done

#5045 Create liferay-axis.yaml
  misconfiguration/liferay/liferay-axis.yaml
Labels: Done

#5051 Update CVE-2022-2487.yaml
  cves/2022/CVE-2022-2487.yaml
Labels: Done

#5046 Create liferay-jsonws.yaml
  misconfiguration/liferay/liferay-jsonws.yaml
Labels: Done

#5047 Create liferay-api.yaml
  misconfiguration/liferay/liferay-api.yaml
Labels: Done

#5048 Create ilch-admin-panel.yaml
  exposed-panels/ilch-admin-panel.yaml
Labels: Done

#5038 Added generic J2EE LFI scan
  vulnerabilities/generic/generic-j2ee-lfi.yaml
Labels: Done

#5050 CVE-2019-10692
  vulnerabilities/wordpress/CVE-2019-10692.yaml
Labels: Done

#5053 Create yeswiki-xss.yaml
  vulnerabilities/other/yeswiki-xss.yaml
Labels: Done

#5052 Create CVE-2022-36883.yaml
  cves/2022/CVE-2022-36883.yaml
Labels: Done

#5054 Create yeswiki-xss2.yaml
  vulnerabilities/other/yeswiki-stored-xss.yaml
Labels: Done

#5055 Create yeswiki-sql.yaml
  vulnerabilities/other/yeswiki-sql.yaml
Labels: Done

#5059 Added webp server LFI
  vulnerabilities/webp-server-go/webp-server-go-lfi.yaml
Labels: Done

#5018 Create CVE-2020-8772.yaml
  cves/2020/CVE-2020-8772.yaml
Labels: Done

#5061 Create CVE-2022-35493.yaml
  cves/2022/CVE-2022-35493.yaml
Labels: Done

#5062 Create mybb-forum-install.yaml
  exposed-panels/mybb/mybb-forum-install.yaml
Labels: Done

#5058 Create mybb-forum-detect.yaml
  exposed-panels/mybb-forum-detect.yaml
Labels: Done

#5057 Create yeswiki-detect.yaml
  technologies/yeswiki-detect.yaml
Labels: Done

#5037 Fixed VirusTotal and SecurityTrails API tests
  token-spray/api-securitytrails.yaml
  token-spray/api-virustotal.yaml
Labels: Done

#5005 Create wp-blogroll-fun-xss.yaml
  vulnerabilities/wordpress/wp-blogroll-fun-xss.yaml
Labels: Done

#4991 Log4j
  vulnerabilities/cisco/cisco-unified-communications-log4j.yaml
  vulnerabilities/cisco/cisco-vmanage-log4j.yaml
  vulnerabilities/other/graylog-log4j.yaml
  vulnerabilities/other/jamf-pro-log4j.yaml
  vulnerabilities/other/metabase-log4j.yaml
  vulnerabilities/other/rundeck-log4j.yaml
  vulnerabilities/vmware/vmware-hcx-log4j.yaml
  vulnerabilities/vmware/vmware-nsx-log4j.yaml
  vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
Labels: Done

#5063 Create codeception-config.yaml
  exposures/configs/codeception-config.yaml
Labels: Done

#5064 Create pubspec-config.yaml
  exposures/configs/pubspec-config.yaml
Labels: Done

#5065 Create pre-commit-config.yaml
  exposures/configs/pre-commit-config.yaml
Labels: Done

#5066 Create angular-json.yaml
  exposures/files/angular-json.yaml
Labels: Done

#5067 Create build-properties.yaml
  exposures/files/build-properties.yaml
Labels: Done

#5069 Create CVE-2022–31656.yaml
  cves/2022/CVE-2022–31656.yaml
Labels: Done

#5072 Create CVE-2022-31269.yaml
  cves/2022/CVE-2022-31269.yaml
Labels: Done

#5073 Create CNVD-2017-03561.yaml
  cnvd/2017/CNVD-2017-03561.yaml
Labels: Done

#5056 Updated CVE-2022-22965.yaml
  cves/2022/CVE-2022-22965.yaml
Labels: good first issue, Done

#5074 Create mobile-management-panel.yaml
  exposed-panels/mobile-management-panel.yaml
Labels: Done

#5075 Create e-mobile-panel.yaml
  exposed-panels/e-mobile-panel.yaml
Labels: Done

#5080 Create reddittoprss-xss.yaml
  vulnerabilities/other/reddittop-rss-xss.yaml
Labels: Done

#5081 Create kavita-lfi.yaml
  vulnerabilities/other/kavita-lfi.yaml
Labels: Done

#5082 Create tableau-service-manager.yaml
  exposed-panels/tableau-service-manager.yaml
Labels: Done

#5083 Create kavita-panel-detect.yaml
  exposed-panels/kavita-panel-detect.yaml
Labels: Done

#5084 Create pghero-dashboard-exposure.yaml
  misconfiguration/pghero-dashboard-exposure.yaml
Labels: Done

#5085 Create CVE-2022-31798.yaml
  cves/2022/CVE-2022-31798.yaml
Labels: Done

#5088 Create CVE-2022-31126.yaml
  cves/2022/CVE-2022-31126.yaml
Labels: Done

#5091 Create dzzoffice-xss.yaml
  vulnerabilities/other/dzzoffice-xss.yaml
Labels: Done

#5099 Added fastcgi-echo-detection template
  exposures/logs/fastcgi-echo.yaml
Labels: Done

#5086 Fixed jupyter-notebook false-positive
  exposed-panels/jupyter-notebook.yaml
Labels: Done

#5094 Update and rename CVE-2022-32159.yaml to CVE-2022-32195.yaml
  cves/2022/CVE-2022-32195.yaml
Labels: Done

#5097 Create dzzoffice-install.yaml
  exposed-panels/dzzoffice/dzzoffice-install.yaml
Labels: Done

#5098 Create pichome-panel.yaml
  exposed-panels/pichome-panel.yaml
Labels: Done

#5096 Create dzzoffice-panel.yaml
  exposed-panels/dzzoffice/dzzoffice-panel.yaml
Labels: Done

#5100 Create led-imediacloud-panel.yaml
  exposed-panels/led-imediacloud-panel.yaml
Labels: Done

#5105 Update concrete5-install.yaml
  exposed-panels/concrete5/concrete5-install.yaml
Labels: Done

#5106 Create CVE-2022-28955.yaml
  cves/2022/CVE-2022-28955.yaml
Labels: Done

#5104 Added concrete-xss
  vulnerabilities/concrete/concrete-xss.yaml
Labels: good first issue

#5113 Create pipfile-config.yaml
  exposures/configs/pipfile-config.yaml
Labels: Done

#5114 Create pipfile-lock.yaml
  exposures/files/pipfile-lock.yaml
Labels: Done

#5107 Create CVE-2022-31846.yaml
  cves/2022/CVE-2022-31846.yaml
Labels: Done

#5108 Create CVE-2020-12127.yaml
  cves/2020/CVE-2020-12127.yaml
Labels: Done

#5112 Create CVE-2021-35488.yaml
  cves/2021/CVE-2021-35488.yaml
Labels: Done

#5013 Create CVE-2022-23348.yaml
  cves/2022/CVE-2022-23348.yaml
Labels: Done

#5110 Create CVE-2022-31847.yaml
  cves/2022/CVE-2022-31847.yaml
Labels: Done

#5115 Create pyproject-toml.yaml
  exposures/configs/pyproject-toml.yaml
Labels: Done

#5116 Create phpsec-config.yaml
  exposures/configs/phpsec-config.yaml
Labels: Done

#5118 Create behat-config.yaml
  exposures/configs/behat-config.yaml
Labels: Done

#5119 Update ocs-inventory-login.yaml
  exposed-panels/ocs-inventory-login.yaml
Labels: Done

#5117 Update thruk-xss.yaml
  vulnerabilities/other/thruk-xss.yaml
Labels: Done

#5120 Create nagios3-panel.yaml
  exposed-panels/nagios-panel.yaml
Labels: Done

#5121 Create nagios-xi-panel.yaml
  exposed-panels/nagios-xi-panel.yaml
Labels: Done

#5123 Create uwsgi-ini.yaml
  exposures/files/uwsgi-ini.yaml
Labels: Done

#5130 network script updates
  network/cowrie-honeypot-detect.yaml
  network/detect-addpac-voip-gateway.yaml
  network/detect-rsyncd.yaml
  network/expn-mail-detect.yaml
  network/ftp-default-credentials.yaml
  network/gopher-detection.yaml
  network/iplanet-imap-detect.yaml
  network/java-rmi-detect.yaml
  network/memcached-stats.yaml
  network/mongodb-detect.yaml
  network/openssh-detection.yaml
  network/printers-info-leak.yaml
  network/rdp-detect.yaml
  network/sap-router.yaml
  network/smb-v1-detection.yaml
  network/smtp-detection.yaml
  network/starttls-mail-detect.yaml
  network/totemomail-smtp-detect.yaml
  network/unauth-ftp.yaml
  network/weblogic-iiop-detect.yaml
  network/weblogic-t3-detect.yaml
Labels: good first issue, Done

#5109 Create CVE-2022-31845.yaml
  cves/2022/CVE-2022-31845.yaml
Labels: Done

#5141 Create olt-web-interface.yaml
  exposed-panels/olt-web-interface.yaml
Labels: Done

#5162 Add a word match 'wp-login.php' for wordpress
  technologies/wordpress-detect.yaml
Labels: Done

#5142 Create gargoyle-router.yaml
  exposed-panels/gargoyle-router.yaml
Labels: Done

#5147 Create novus-ip-camera.yaml
  iot/novus-ip-camera.yaml
Labels: Done

#5143 Create fiori-launchpad.yaml
  exposed-panels/fiori-launchpad.yaml
Labels: Done

#5148 Create syncthru-web-service.yaml
  exposed-panels/syncthru-web-service.yaml
Labels: Done

#5131 Create ipdiva-mediation-panel.yaml
  exposed-panels/ipdiva-mediation-panel.yaml
Labels: Done

#5133 Update phppgadmin-panel Template
  exposed-panels/phppgadmin-panel.yaml
Labels: Done

#5135 Create CVE-2020-12478.yaml
  cves/2020/CVE-2020-12478.yaml
Labels: Done

#5136 Create teampass-panel.yaml
  exposed-panels/teampass-panel.yaml
Labels: Done

#5139 Create nconf-panel.yaml
  exposed-panels/nconf-panel.yaml
Labels: Done

#5140 Create star-network-utility-detect.yaml
  exposed-panels/star-network-utility.yaml
Labels: Done

#5150 add template phpminiadmin-panel
  exposed-panels/phpminiadmin-panel.yaml
Labels: Done

#5155 Create kkfileview-panel.yaml
  exposed-panels/kkfileview-panel.yaml
Labels: Done

#5156 Create CVE-2022-29349.yaml
  cves/2022/CVE-2022-29349.yaml
Labels: Done

#5157 Create CVE-2021-43734.yaml
  cves/2021/CVE-2021-43734.yaml
Labels: Done

#5163 Create CVE-2018-20463.yaml
  cves/2018/CVE-2018-20463.yaml
Labels: good first issue, Done

#5165 Create ez-publish-panel.yaml
  exposed-panels/ez-publish-panel.yaml
Labels: Done

#5169 Adding magento-sensitive-information-disclosure.yaml
  exposures/configs/magento-information-disclosure.yaml
Labels: Done

#5132 Create CVE-2022-29272.yaml
  cves/2022/CVE-2022-29272.yaml
Labels: Done

#5184 Create emerge-workflow.yaml
  workflows/emerge-workflow.yaml
Labels: Done

#5183 Create azure-workflow.yaml
  workflows/azure-workflow.yaml
Labels: Done

#5137 Create nagvis-panel.yaml
  exposed-panels/nagvis-panel.yaml
Labels: Done

#5127 Create roxy-fileman.yaml
  exposed-panels/roxy-fileman.yaml
Labels: Done

#5128 Create roxyfileman-fileupload.yaml
  misconfiguration/roxyfileman-fileupload.yaml
Labels: Done

#5186 Update and rename misconfiguration/unauthenticated-influxdb.yaml to c…
  cves/2019/CVE-2019-20933.yaml
  misconfiguration/unauthenticated-influxdb.yaml
Labels: Done

#5129 Create CVE-2018-20526.yaml
  cves/2018/CVE-2018-20526.yaml
Labels: Done
