Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-07, with the labels that each got.

#4734 Added cloudfoundry-detect template
  technologies/cloudfoundry-detect.yaml
Labels: good first issue

#4753 Added CVE-2020-8644 Template
  cves/2020/CVE-2020-8644.yaml
Labels: Type: Epic

#4824 Add CVE-2021-36450.yaml
  cves/2021/CVE-2021-36450.yaml
Labels: good first issue

#3263 Added Jexboss Backdoor Webshell
  vulnerabilities/backdoor/jexboss-backdoor.yaml
Labels: Status: Completed

#941 Create weiphp-sql-injection
  vulnerabilities/other/weiphp-sql-injection.yaml
Labels: Status: On Hold

#4923 Create CVE-2022-1937.yaml
  cves/2022/CVE-2022-1937.yaml
Labels: Done

#4916 Create CVE-2022-0954
  cves/2022/CVE-2022-0921.yaml
Labels: Done

#4901 Create CVE-2022-0963
  cves/2022/CVE-2022-0963.yaml
Labels: Done

#4919 Added (NetMake) ScriptCase Detect Template
  exposed-panels/scriptcase/scriptcase-panel.yaml
  exposed-panels/scriptcase/scriptcase-prod-login.yaml
Labels: good first issue, Done

#4925 Create analytify-plugin-xss.yaml
  vulnerabilities/wordpress/analytify-plugin-xss.yaml
Labels: Done

#4931 Create springboot-flyway.yaml
  misconfiguration/springboot/springboot-flyway.yaml
Labels: Done

#4929 Create springboot-caches.yaml
  misconfiguration/springboot/springboot-caches.yaml
Labels: Done

#4932 Update springboot templates
  misconfiguration/springboot/springboot-autoconfig.yaml
  misconfiguration/springboot/springboot-beans.yaml
  misconfiguration/springboot/springboot-configprops.yaml
  misconfiguration/springboot/springboot-dump.yaml
  misconfiguration/springboot/springboot-env.yaml
  misconfiguration/springboot/springboot-health.yaml
  misconfiguration/springboot/springboot-heapdump.yaml
  misconfiguration/springboot/springboot-httptrace.yaml
  misconfiguration/springboot/springboot-info.yaml
  misconfiguration/springboot/springboot-loggers.yaml
  misconfiguration/springboot/springboot-mappings.yaml
  misconfiguration/springboot/springboot-metrics.yaml
  misconfiguration/springboot/springboot-threaddump.yaml
  misconfiguration/springboot/springboot-trace.yaml
  vulnerabilities/springboot/springboot-actuators-jolokia-xxe.yaml
Labels: Done

#4933 Create CVE-2020-13405
  cves/2020/CVE-2020-13405.yaml
Labels: Done

#4924 Create goanywhere-mft-login.yaml
  exposed-panels/goanywhere-mft-login.yaml
Labels: Done

#4894 Create nextcloud-owncloud-detect.yaml
  technologies/nextcloud-owncloud-detect.yaml
Labels: Done

#4922 Added Landesk_CSA Template
  technologies/landesk/landesk-csa.yaml
  technologies/landesk/landesk-ma.yaml
Labels: good first issue

#4940 Template for Archibus Web Central
  exposed-panels/archibus-webcentral-panel.yaml
Labels: Done

#4936 Create CVE-2022-33119.yaml
  cves/2022/CVE-2022-33119.yaml
Labels: Done

#4920 Added GLPI Detect Template
  technologies/glpi-project-detect.yaml
Labels: Done

#4946 Add CVE-2022-0594.yaml
  cves/2022/CVE-2022-0594.yaml
Labels: Done

#4890 Added goanywhere-log4j-rce
  vulnerabilities/other/goanywhere-mft-log4j-rce.yaml
Labels: Status: On Hold

#4917 Create stored-xss-mwb
  vulnerabilities/microweber/microweber-stored-xss.yaml
Labels: Done

#4949 Added CVE-2021-24236
  cves/2021/CVE-2021-24236.yaml
Labels: Done
