Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-09, with the labels that each got.

#5273 Added Intrusive tags
  cnvd/2021/CNVD-2021-49104.yaml
  cves/2016/CVE-2016-3088.yaml
  cves/2017/CVE-2017-15715.yaml
  cves/2017/CVE-2017-6090.yaml
  cves/2018/CVE-2018-15961.yaml
  cves/2020/CVE-2020-12800.yaml
  cves/2020/CVE-2020-17518.yaml
  cves/2020/CVE-2020-23972.yaml
  cves/2020/CVE-2020-24186.yaml
  cves/2020/CVE-2020-25213.yaml
  cves/2020/CVE-2020-28871.yaml
  cves/2020/CVE-2020-35489.yaml
  cves/2021/CVE-2021-21978.yaml
  cves/2021/CVE-2021-22005.yaml
  cves/2021/CVE-2021-24236.yaml
  cves/2021/CVE-2021-3378.yaml
  cves/2021/CVE-2021-40870.yaml
  cves/2022/CVE-2022-0595.yaml
  cves/2022/CVE-2022-0963.yaml
  cves/2022/CVE-2022-26352.yaml
  vulnerabilities/other/cisco-rv-series-rce.yaml
  vulnerabilities/other/core-chuangtian-cloud-rce.yaml
  vulnerabilities/other/dixell-xweb500-filewrite.yaml
  vulnerabilities/seeyon/zhiyuan-file-upload.yaml
  vulnerabilities/weaver/oa-v9-uploads-file.yaml
  vulnerabilities/wordpress/ait-csv-import-export-rce.yaml
Labels: Type: Enhancement, Done

#5275 Added fileupload , replaced upload -> fileupload tag
  cnvd/2021/CNVD-2021-49104.yaml
  cves/2017/CVE-2017-12615.yaml
  cves/2018/CVE-2018-20526.yaml
  cves/2019/CVE-2019-20183.yaml
  cves/2020/CVE-2020-17518.yaml
  cves/2020/CVE-2020-23972.yaml
  cves/2020/CVE-2020-24186.yaml
  cves/2020/CVE-2020-25213.yaml
  cves/2020/CVE-2020-28871.yaml
  cves/2021/CVE-2021-21978.yaml
  cves/2021/CVE-2021-22005.yaml
  cves/2021/CVE-2021-24236.yaml
  cves/2021/CVE-2021-3378.yaml
  cves/2021/CVE-2021-40870.yaml
  cves/2022/CVE-2022-0595.yaml
  cves/2022/CVE-2022-26352.yaml
  misconfiguration/cx-cloud-upload-detect.yaml
  misconfiguration/roxyfileman-fileupload.yaml
  misconfiguration/unauthenticated-popup-upload.yaml
  vulnerabilities/other/core-chuangtian-cloud-rce.yaml
  vulnerabilities/other/dixell-xweb500-filewrite.yaml
  vulnerabilities/other/powercreator-cms-rce.yaml
  vulnerabilities/seeyon/zhiyuan-file-upload.yaml
  vulnerabilities/weaver/oa-v9-uploads-file.yaml
  vulnerabilities/wordpress/ait-csv-import-export-rce.yaml
  vulnerabilities/wordpress/wordpress-rce-simplefilelist.yaml
Labels: Done

#5258 Add mfiles web service detection
  exposed-panels/mfiles-web-detect.yaml
Labels: Done

#5276 Create CVE-2021-43574.yaml
  cves/2021/CVE-2021-43574.yaml
Labels: Done

#5274 Create CVE-2021-24917.yaml
  cves/2021/CVE-2021-24917.yaml
Labels: Done

#5259 Create osticket-panel.yaml
  exposed-panels/osticket-panel.yaml
Labels: Done

#5260 Create osticket-install.yaml
  exposed-panels/osticket/osticket-install.yaml
Labels: Done

#5278 Create aem-debugging-libraries.yaml
  misconfiguration/aem/aem-debugging-libraries.yaml
Labels: Done

#5261 Created CVE 2021 46069
  cves/2021/CVE-2021-46069.yaml
Labels: Done

#5262 Create CVE 2021 46072
  cves/2021/CVE-2021-46072.yaml
Labels: Done

#5263 Create CVE 2021 46071
  cves/2021/CVE-2021-46071.yaml
Labels: Done

#5265 CREATE CVE-2021-46068
  cves/2021/CVE-2021-46068.yaml
Labels: Done

#5267 CREATE CVE-2021-46073
  cves/2021/CVE-2021-46073.yaml
Labels: Done

#5268 Update generic-windows-lfi.yaml
  vulnerabilities/generic/generic-windows-lfi.yaml
Labels: Done

#5208 Create drupal-detect.yaml
  technologies/drupal-detect.yaml
Labels: Done

#5279 Create aem-acs-common.yaml
  misconfiguration/aem/aem-acs-common.yaml
Labels: Done

#5285 Update vms template
  cves/2021/CVE-2021-46068.yaml
  cves/2021/CVE-2021-46069.yaml
  cves/2021/CVE-2021-46071.yaml
  cves/2021/CVE-2021-46072.yaml
Labels: Done

#5266 Update generic-linux-lfi.yaml
  vulnerabilities/generic/generic-linux-lfi.yaml
Labels: Done

#5283 CREATE CVE-2022-29007
  cves/2022/CVE-2022-29007.yaml
Labels: Done

#5284 CREATE CVE-2022-29009
  cves/2022/CVE-2022-29009.yaml
Labels: Done

#5280 CREATE CVE-2022-29006
  cves/2022/CVE-2022-29006.yaml
Labels: Done

#5125 Create CVE-2015-4074.yaml
  cves/2015/CVE-2015-4074.yaml
Labels: Done

#5172 Create CVE-2016-6601.yaml
  cves/2016/CVE-2016-6601.yaml
Labels: Done

#5124 Create CVE-2015-7245.yaml
  cves/2015/CVE-2015-7245.yaml
Labels: Done

#5302 Create CVE-2014-8676.yaml
  cves/2014/CVE-2014-8676.yaml
Labels: Done

#5289 Create cvent.yaml
  exposed-panels/cvent-panel-detect.yaml
Labels: Done

#5301 Create 3com-nj2000-default-login.yaml
  default-logins/3com/3com-nj2000-default-login.yaml
Labels: Done

#5305 Create omniampx-panel.yaml
  exposed-panels/omniampx-panel.yaml
Labels: Done

#5291 Create CVE-2021-42663.yaml
  cves/2021/CVE-2021-42663.yaml
Labels: Done

#5292 Create CVE-2021-42667.yaml
  cves/2021/CVE-2021-42667.yaml
Labels: Done

#5310 Create graphql-playground.yaml
  misconfiguration/graphql/graphql-playground.yaml
Labels: Done

#5311 Create ec2-instance-information.yaml
  misconfiguration/ec2-instance-information.yaml
Labels: Done

#5309 Added appsmith web login signature
  exposed-panels/appsmith-web-login.yaml
Labels: Done

#5312 Create aws-xray-application.yaml
  misconfiguration/aws-xray-application.yaml
Labels: Done

#5313 Create redis-exception-error.yaml
  exposures/logs/redis-exception-error.yaml
Labels: Done

#5314 Create hivequeue-agent.yaml
  misconfiguration/hivequeue-agent.yaml
Labels: Done

#5296 Create CVE-2022-36642.yaml
  cves/2022/CVE-2022-36642.yaml
Labels: Done

#5282 CREATE CVE-2022-29005
  cves/2022/CVE-2022-29005.yaml
Labels: Done

#5281 CREATE CVE-2022-29004
  cves/2022/CVE-2022-29004.yaml
Labels: Done

#3496 Added CVE-2020-13258
  cves/2020/CVE-2020-13258.yaml
Labels: Done

#5315 Create webalizer-xtended-stats.yaml
  exposed-panels/exposed-webalizer.yaml
  exposures/logs/webalizer-xtended-stats.yaml
Labels: Done

#5320 Create CVE-2022-2376.yaml
  cves/2022/CVE-2022-2376.yaml
Labels: Done

#5321 Create server-status.yaml
  misconfiguration/server-status.yaml
Labels: Done

#5322 Create V2924-admin-panel.yaml
  exposed-panels/v2924-admin-panel.yaml
Labels: Done

#5318 Create CNVD-2022-42853.yaml
  cnvd/2022/CNVD-2022-42853.yaml
Labels: Done

#5323 Add detection template for JHipster
  technologies/jhipster-detect.yaml
Labels: Done

#5336 Add CVE-2018-16139.yaml
  cves/2018/CVE-2018-16139.yaml
Labels: Done

#5340 ruckus-wireless-admin-login-panel
  exposed-panels/ruckus-wireless-admin-login
Labels: Done

#5341 Fix WordPress plugin template descriptions
  vulnerabilities/wordpress/alfacgiapi-wordpress.yaml
  vulnerabilities/wordpress/dzs-zoomsounds-listing.yaml
  vulnerabilities/wordpress/easy-media-gallery-pro-listing.yaml
  vulnerabilities/wordpress/wordpress-redirection-plugin-listing.yaml
  vulnerabilities/wordpress/wp-123contactform-plugin-listing.yaml
  vulnerabilities/wordpress/wp-arforms-listing.yaml
  vulnerabilities/wordpress/wp-email-subscribers-listing.yaml
  vulnerabilities/wordpress/wp-idx-broker-platinum-listing.yaml
  vulnerabilities/wordpress/wp-iwp-client-listing.yaml
  vulnerabilities/wordpress/wp-mstore-plugin-listing.yaml
  vulnerabilities/wordpress/wp-plugin-1-flashgallery-listing.yaml
  vulnerabilities/wordpress/wp-plugin-lifterlms.yaml
  vulnerabilities/wordpress/wp-plugin-utlimate-member.yaml
  vulnerabilities/wordpress/wp-qards-listing.yaml
  vulnerabilities/wordpress/wp-sfwd-lms-listing.yaml
  vulnerabilities/wordpress/wp-super-forms.yaml
  vulnerabilities/wordpress/wp-sym404.yaml
Labels: good first issue, Type: Enhancement, Done

#5332 Create corebos-htaccess.yaml
  misconfiguration/corebos-htaccess.yaml
Labels: Done

#5335 Added CVE-2022-37299
  cves/2022/CVE-2022-37299.yaml
Labels: Done

#5342 Add CVE-2022-31474.yaml
  cves/2022/CVE-2022-31474.yaml
Labels: Done

#5333 Create corebos-panel.yaml
  exposed-panels/corebos-panel.yaml
Labels: Done

#5343 Create CVE-2022-23854.yaml
  cves/2022/CVE-2022-23854.yaml
Labels: Done

#5339 Create schneider-electric-pelco-videoxpert-core-admin-portal-lfi.yaml
  vulnerabilities/videoxpert-lfi.yaml
Labels: Done

#5331 update wp-sym404.yaml
  vulnerabilities/wordpress/wp-sym404.yaml
Labels: Done

#5253 fix: Update the template to avoid false positives
  contributors.json
  vulnerabilities/generic/generic-j2ee-lfi.yaml
  vulnerabilities/thinkcmf/thinkcmf-arbitrary-code-execution.yaml
Labels: Done

#5237 Added CVE-2022-38794
  cves/2022/CVE-2022-38794.yaml
Labels: Done

#5344 Create ccm-detect.yaml
  exposed-panels/ccm-detect.yaml
Labels: Done

#4110 Backdoor check for Sony IP cameras
  iot/sony-camera-backdoor.yaml
Labels: Done

#5345 Update sitecore-version.yaml
  technologies/sitecore-version.yaml
Labels: Done

#5317 Update CVE 2022 35405
  cves/2022/CVE-2022-35405.yaml
Labels: good first issue

#5325 Create 3DPrint-arbitrary-file-upload.yaml
  vulnerabilities/wordpress/3DPrint-arbitrary-file-upload.yaml
Labels: Done

#5348 Create footprints.yaml
  exposed-panels/footprints-panel.yaml
Labels: Done

#5354 Enhanced Firebase config Disclosure Template
  exposures/configs/firebase-config-exposure.yaml
Labels: Done

#5355 Create codemeter-webadmin.yaml
  misconfiguration/codemeter-webadmin.yaml
Labels: Done

#5366 CVE 2022 0678
  cves/2022/CVE-2022-0678.yaml
Labels: Done

#5369 Create iSpyConnect-detect.yaml
  technologies/ispyconnect-detect.yaml
Labels: Done

#5350 Create CVE-2022-35413.yaml
  cves/2022/CVE-2022-35413.yaml
Labels: Done

#5368 Create CVE-2022-29775.yaml
  cves/2022/CVE-2022-29775.yaml
Labels: Done

#5352 Create wapples-firewall-lfi.yaml
  vulnerabilities/other/wapples-firewall-lfi.yaml
Labels: Done

#5360 Create CVE-2022-34590.yaml
  cves/2022/CVE-2022-34590.yaml
Labels: Done

#5362 Create CVE-2022-38637.yaml
  cves/2022/CVE-2022-38637.yaml
Labels: Done

#5363 Create hms-panel.yaml
  exposed-panels/hospital-management-panel.yaml
Labels: Done

#5361 Create CVE-2022-32094.yaml
  cves/2022/CVE-2022-32094.yaml
Labels: Done

#5364 Create hms-xss.yaml
  vulnerabilities/other/hospital-management-xss.yaml
Labels: Done

#5375 Create CVE-2022-40734.yaml
  cves/2022/CVE-2022-40734.yaml
Labels: Done

#5365 Create hms-xss-2.yaml
  vulnerabilities/other/hospital-management-xss2.yaml
Labels: Done

#3124 checks for github and gitlab recovery codes and discord backup codes
  exposures/tokens/discord/discord-backup-code.yaml
  exposures/tokens/github/github-recovery-code.yaml
  exposures/tokens/gitlab/gitlab-recovery-code.yaml
Labels: Done

#5376 Create ventrilo-config.yaml
  exposures/configs/ventrilo-config.yaml
Labels: Done

#5377 Create vscode-sftp.yaml
  exposures/files/vscode-sftp.yaml
Labels: Done

#5378 Create tox-ini.yaml
  exposures/configs/tox-ini.yaml
Labels: Done

#5379 Create redis-config.yaml
  exposures/configs/redis-config.yaml
Labels: Done

#5386 Naming screenshot output with url_encoded BaseURL.
  headless/screenshot.yaml
Labels: Done

#5380 Create atom-sync-remote.yaml
  exposures/files/atom-sync-remote.yaml
Labels: Done

#5387 Create cloud-metadata.yaml
  misconfiguration/cloud-metadata.yaml
Labels: Done

#5384 Create CVE-2021-24214.yaml
  cves/2021/CVE-2021-24214.yaml
Labels: Done

#5373 Create phpldap-admin.yaml
  exposed-panels/phpldap-admin.yaml
Labels: Done

#5383 Add CVE-2022-31299
  cves/2022/CVE-2022-31299.yaml
Labels: Done

#5391 Create sentinelone-console.yaml
  exposed-panels/sentinelone-console.yaml
Labels: Done

#5392 Create webroot-login.yaml
  exposed-panels/webroot-login.yaml
Labels: Done

#5393 Create bitdefender-gravityzone.yaml
  exposed-panels/bitdefender-gravityzone.yaml
Labels: Done

#5394 Create darktrace-threat-visualizer.yaml
  exposed-panels/darktrace-threat-visualizer.yaml
Labels: Done

#5396 Create datadog-login.yaml
  exposed-panels/datadog-login.yaml
Labels: Done

#5419 Create CVE-2022-36804.yaml
  cves/2022/CVE-2022-36804.yaml
Labels: Done

#5424 Update CVE-2021-39320.yaml
  .new-additions
  cves/2021/CVE-2021-39320.yaml
  cves/2022/CVE-2022-36804.yaml
Labels: Done

#5422 Update CVE-2022-31373.yaml
  cves/2022/CVE-2022-31373.yaml
Labels: Done

#5423 Update CVE-2021-41878.yaml
  cves/2021/CVE-2021-41878.yaml
Labels: Done

#5406 Create CVE-2022-39960.yaml
  cves/2022/CVE-2022-39960.yaml
Labels: Done

#5407 Add CVE-2022-34121
  cves/2022/CVE-2022-34121.yaml
Labels: Done

#5412 feat: Added `zte-backdoor` template
  network/backdoor/backdoored-zte.yaml
Labels: Done

#4860 Create CVE-2022-29078.yaml
  cves/2022/CVE-2022-29078.yaml
Labels: Done

#5417 Create bitbucket-public-repo.yaml
  misconfiguration/bitbucket-public-repository.yaml
Labels: Done

#5397 Create CVE-2022-2544.yaml
  cves/2022/CVE-2022-2544.yaml
Labels: Done

#5427 Update xss-deprecated-header.yaml
  misconfiguration/xss-deprecated-header.yaml
Labels: Done

#5356 Bash Scanner!
  file/bash/bash.yaml
Labels: good first issue, Done

#5414 Update FP workspace-one-uem.yaml
  exposed-panels/workspace-one-uem.yaml
  exposed-panels/workspaceone-uem-dashboard.yaml
Labels: Done

#5382 Update CVE-2022-35405.yaml
  cves/2022/CVE-2022-35405.yaml
Labels: Done

#5418 Update liferay-jsonws
  misconfiguration/liferay/liferay-jsonws.yaml
Labels: Done

#5429 Create CVE-2020-2733
  cves/2020/CVE-2020-2733.yaml
Labels: Done

#5430 Update CVE-2017-8917.yaml
  cves/2017/CVE-2017-8917.yaml
Labels: Done

#5439 Create moveit-transfer-detect.yaml
  technologies/moveit-transfer-detect.yaml
Labels: Done

#5433 Create oracle-business-intelligence.yaml
  exposed-panels/oracle-business-intelligence.yaml
Labels: Done

#5168 Fix false postive CVE-2017-10271
  cves/2017/CVE-2017-10271.yaml
Labels: Status: Review Needed

#5434 Create sendgrid-env.yaml
  exposures/files/sendgrid-env.yaml
Labels: Done

#5444 Add a proper and unique id
  misconfiguration/proxy/open-proxy-localhost.yaml
Labels: Type: Bug

#5448 Create CVE-2016-10368.yaml
  cves/2016/CVE-2016-10368.yaml
Labels: Done

#5447 Create CVE-2021-25104.yaml
  cves/2021/CVE-2021-25104.yaml
Labels: Done

#5449 Takeover no longer exists for brightcove-takeover.yaml
  takeovers/brightcove-takeover.yaml
Labels: Done

#5432 CVE-2017-14186
  cves/2017/CVE-2017-14186.yml
Labels: Done

#5450 Added template for CVE-2021-36873
  cves/2021/CVE-2021-36873.yaml
Labels: Done

#5395 Added ManageEngine ADSelfService Version Detection Template
  exposed-panels/zoho/manageengine-adselfservice.yaml
Labels: good first issue

#5452 Create age-gate-xss.yaml
  vulnerabilities/wordpress/age-gate-xss.yaml
Labels: Done

#5451 Fix typo
  misconfiguration/http-missing-security-headers.yaml
Labels: Done

#5456 Added Web Page Test - Server Side Request Forgery (SSRF)
  exposed-panels/webpagetest-panel.yaml
  vulnerabilities/other/webpagetest-ssrf.yaml
Labels: Done

#5416 Create CVE-2022-31814.yaml
  cves/2022/CVE-2022-31814.yaml
Labels: Done

#5408 Fix CVE-2022-2486
  cves/2022/CVE-2022-2486.yaml
Labels: Done

#5459 Create aem-bulkeditor.yaml
  misconfiguration/aem/aem-bulkeditor.yaml
Labels: Done

#5460 Create aem-felix-console.yaml
  default-logins/aem/aem-felix-console.yaml
Labels: Done

#5461 Create aem-list-custom.yaml
  misconfiguration/aem/aem-list-custom.yaml
Labels: Done

#5462 Create aem-dump-contentnode.yaml
  misconfiguration/aem/aem-dump-contentnode.yaml
Labels: Done

#5464 Added template for CVE-2022-2546
  cves/2022/CVE-2022-2546.yaml
Labels: Done

#5463 Create CVE-2019-8086.yaml
  cves/2019/CVE-2019-8086.yaml
Labels: Done

#5299 Create CVE-2022-2551.yaml
  cves/2022/CVE-2022-2551.yaml
Labels: Done

#5490 Create CVE-2020-13820.yaml
  cves/2020/CVE-2020-13820.yaml
Labels: Done

#5425 Update api-screenshotapi.yaml
  token-spray/api-screenshotapi.yaml
Labels: Done

#5489 Added template for CVE-2022-2633
  cves/2022/CVE-2022-2633.yaml
Labels: Done

#5492 Create aircube-login.yaml
  exposed-panels/aircube-login.yaml
Labels: Done

#5493 Create zend-server-test-page.yaml
  technologies/zend-server-test-page.yaml
Labels: Done

#5443 Create CVE-2021-22911.yaml
  cves/2022/CVE-2021-22911.yaml
Labels: Done

#5474 Create CVE-2022-1910.yaml
  cves/2022/CVE-2022-1910.yaml
Labels: Done

#5484 Create wampserver-homepage.yaml
  exposed-panels/wampserver-homepage.yaml
Labels: Done

#5486 Update CVE-2020-36289.yaml
  cves/2020/CVE-2020-36289.yaml
Labels: Done

#5499 Create atlassian-bamboo-build.yaml
  misconfiguration/atlassian-bamboo-build.yaml
Labels: Done
