Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-03, with the labels that each got.

#3776 Added CVE-2022-22536 (SAP Memory Pipes(MPI) Desynchronization) Detection
  cves/2022/CVE-2022-22536.yaml
Labels: Status: Blocked

#3825 [false-positive] WordPress Contact Form 7 Plugin - Unrestricted File Upload
  cves/2020/CVE-2020-35489.yaml
Labels: Status: Completed

#3999 Add microsoft iis version detect
  technologies/microsoft/microsoft-iis-version.yaml
Labels: good first issue
