Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-01, with the labels that each got.

#3540 Adding contributors.json from gh commit logs
  contributors.json
Labels: Status: Review Needed, Type: Enhancement

#3500 Update credentials-disclosure.yaml
  exposures/tokens/generic/credentials-disclosure.yaml
Labels: help wanted

#1532 add gophish default credential template
  default-logins/gophish/gophish-default-credentials.yaml
Labels: Status: Completed

#1324 Add versa-default-login template
  default-logins/versa/versa-default-login.yaml
  exposed-panels/versa-sdwan.yaml
Labels: Status: Completed

#1828 jboss-default-login.yaml
  default-logins/jboss/jmx-default-login.yaml
Labels: Status: Completed
