Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-12, with the labels that each got.

#6194 Update wordpress-takeover.yaml
  takeovers/wordpress-takeover.yaml
Labels: Done

#6153 Add detection of Persis software.
  exposed-panels/persis-panel.yaml
Labels: Done

#6154 Create cudatel-panel.yaml
  exposed-panels/cudatel-panel.yaml
Labels: Done

#6155 Create asus-router-login.yaml
  exposed-panels/asus-router-panel.yaml
Labels: Done

#6189 Add vbulletin-detect.yaml
  technologies/vbulletin-detect.yaml
Labels: Done

#6197 Create etherpad-open.yaml
  misconfiguration/unauth-etherpad.yaml
Labels: Done

#6121 Update public-tomcat-manager.yaml
  exposed-panels/apache/public-tomcat-manager.yaml
Labels: Done

#6160 Create CVE-2022-3506.yaml
  cves/2022/CVE-2022-3506.yaml
Labels: Done

#6159 Create wp-related-post-xss
  vulnerabilities/wordpress/wp-related-post-xss
Labels: Done

#6161 Create vodafone-vox-ui.yaml
  exposed-panels/vodafone-voxui-panel.yaml
Labels: good first issue, Done

#6180 Create workerman-websocket-detect.yaml
  technologies/workerman-websocket-detect.yaml
Labels: Done

#6162 Add detection of Dradis Professional Edition software.
  exposed-panels/dradis-pro-panel.yaml
Labels: Done

#6184 Create backpack-admin-login.yaml
  exposed-panels/backpack/backpack-admin-panel.yaml
Labels: Done

#5247 Create wordpress-unauthenticated-private-messages.yaml
  cves/2022/CVE-2022-2034.yaml
Labels: good first issue, Status: Completed, Done

#6166 Add detection of Rise Up learning platform.
  exposed-panels/riseup-panel.yaml
Labels: Status: Completed, Done

#6140 Versa Network Templates
  default-logins/versa/versa-flexvnf-default-login.yaml
  exposed-panels/versa/versa-director-login.yaml
  exposed-panels/versa/versa-flexvnf-panel.yaml
  exposed-panels/versa/versa-sdwan.yaml
  technologies/versa-flexvnf-server.yaml
  technologies/versa/versa-analytics-server
  technologies/versa/versa-director-api.yaml
  technologies/versa/versa-networks-detect.yaml
Labels: Status: Completed, Done

#6187 Create jetbrains-webservers.yaml
  exposures/files/jetbrains-webservers.yaml
Labels: Done

#6190 Create sftp-deployment-config.yaml
  exposures/configs/sftp-deployment-config.yaml
Labels: Done

#6198 Create npmrc-authtoken.yaml
  exposures/files/npmrc-authtoken.yaml
Labels: Done

#6196 Create openstack-user-secrets.yaml
  exposures/files/openstack-user-secrets.yaml
Labels: Done

#5889 CISCO WebVPN detect
  exposed-panels/cisco/cisco-webvpn-detect.yaml
Labels: Done

#6207 Update open-redirect.yaml
  vulnerabilities/generic/open-redirect.yaml
Labels: Status: Completed, Done

#6208 Update CVE-2022-23131.yaml
  cves/2022/CVE-2022-23131.yaml
Labels: Status: Completed, Done

#6209 Update and rename technologies/influxdb-detect.yaml to exposed-panels…
  exposed-panels/influxdb-panel.yaml
  technologies/influxdb-version-detect
Labels: Status: Completed, Done

#1388 Create nsicg-default-password
  default-logins/nsicg/nsicg-default-login.yaml
Labels: Status: Completed, Done

#6127 Dropbear sshd CBC Mode Ciphers Detection
  network/detection/dropbear-cbc-ciphers.yaml
Labels: Status: Completed, Done

#6129 Dropbear Weak MAC Algorithms Detection
  network/misconfig/dropbear-weakmac.yaml
Labels: Status: Completed, Done

#6128 Dropbear sshd Weak Key Exchange Algorithms Detection
  network/misconfig/dropbear-weakalgo.yaml
Labels: Status: Completed, Done

#6212 Create mikrotik-routeros-old.yaml
  exposed-panels/mikrotik/mikrotik-routeros-old.yaml
  exposed-panels/mikrotik/mikrotik-routeros.yaml
Labels: Status: Completed, Done

#5519 Add CVE-2020-26248
  cves/2020/CVE-2020-26248.yaml
Labels: Status: Completed, Done

#6195 Add opencart-detect.yaml
  exposed-panels/opencart-login.yaml
Labels: Done

#6216 superadmin-ui
  exposed-panels/superadmin-ui-panel.yaml
Labels: Status: Completed, Done

#6215 flahscookie-superadmin.yaml
  exposed-panels/flahscookie-superadmin-panel.yaml
Labels: Status: Completed, Done

#6214 Create dqs-superadmin.yaml
  exposed-panels/dqs-superadmin-panel.yaml
Labels: Status: Completed, Done

#6205 Create goliath-detect.yaml
  technologies/goliath-detect.yaml
Labels: Status: Completed, Done

#6111 Add ldap-anonymous-login template
  network/default-login/ldap-anonymous-login.yaml
Labels: Status: Completed, Done

#6238 Update meteor-takeover.yaml
  takeovers/meteor-takeover.yaml
Labels: Done

#6242 Update cargocollective-takeover.yaml
  takeovers/cargocollective-takeover.yaml
Labels: Done

#6241 Update anima-takeover.yaml
  takeovers/anima-takeover.yaml
Labels: Done

#6240 Update and rename campaignmonitor.yaml to campaignmonitor-takeover.yaml
  takeovers/campaignmonitor-takeover.yaml
Labels: Done

#6243 Update getresponse-takeover.yaml
  takeovers/getresponse-takeover.yaml
Labels: Done

#6245 "Update cargocollective-takeover.yaml"
  takeovers/cargocollective-takeover.yaml
Labels: Done

#6246 Update uberflip-takeover.yaml
  takeovers/uberflip-takeover.yaml
Labels: Done

#6249 Update airee-takeover.yaml
  takeovers/airee-takeover.yaml
Labels: Done

#6250 Update heroku-takeover.yaml
  takeovers/heroku-takeover.yaml
Labels: Done

#6252 Update readthedocs-takeover.yaml
  takeovers/readthedocs-takeover.yaml
Labels: Done

#6253 Update ngrok-takeover.yaml
  takeovers/ngrok-takeover.yaml
Labels: Done

#6251 Update jetbrains-takeover.yaml
  takeovers/jetbrains-takeover.yaml
Labels: Done

#6254 Update agilecrm-takeover.yaml
  takeovers/agilecrm-takeover.yaml
Labels: Done

#6264 Update wishpond-takeover.yaml
  takeovers/wishpond-takeover.yaml
Labels: Done

#6266 Update zendesk-takeover.yaml
  takeovers/zendesk-takeover.yaml
Labels: Done

#6267 Update smugmug-takeover.yaml
  takeovers/smugmug-takeover.yaml
Labels: Done

#6269 Update pantheon-takeover.yaml
  takeovers/pantheon-takeover.yaml
Labels: Done

#6273 Update mashery-takeover.yaml
  takeovers/mashery-takeover.yaml
Labels: Done

#6274 Update launchrock-takeover.yaml
  takeovers/launchrock-takeover.yaml
Labels: Done

#6275 Update bigcartel-takeover.yaml
  takeovers/bigcartel-takeover.yaml
Labels: Done

#6276 Update canny-takeover.yaml
  takeovers/canny-takeover.yaml
Labels: Done

#6277 Update aws-bucket-takeover.yaml
  takeovers/aws-bucket-takeover.yaml
Labels: Done

#6261 Add template to detect JCMS instance
  exposed-panels/jcms-panel.yaml
Labels: Done

#6268 Create pypiserver-detect.yaml
  technologies/pypiserver-detect.yaml
Labels: Done

#6280 Update strikingly-takeover.yaml
  takeovers/strikingly-takeover.yaml
Labels: Done

#6282 Update intercom-takeover.yaml
  takeovers/intercom-takeover.yaml
Labels: Done

#6278 Update gemfury-takeover.yaml
  takeovers/gemfury-takeover.yaml
Labels: Done

#6235 Created template aircube-dashboard-login
  exposed-panels/aircube-dashboard-panel.yaml
Labels: Done

#6234 Created template netris-dashboard-login
  exposed-panels/netris-dashboard-panel.yaml
Labels: Done

#6232 Created template metaview-explorer-installer
  misconfiguration/installer/metaview-explorer-installer.yaml
Labels: Done

#6233 Created template mag-dashboard-login
  exposed-panels/mag-dashboard-panel.yaml
Labels: Done

#6256 added Reflected XSS for ZendFramework1
  vulnerabilities/zend/zend-v1-xss.yaml
Labels: good first issue, Done

#6286 Cisco Finger Daemon Detection
  network/detection/cisco-finger-detect.yaml
Labels: Done

#6288 Add template for CVE-2021-20323
  cves/2021/CVE-2021-20323.yaml
Labels: good first issue, Done

#6294 Update github-takeover.yaml
  takeovers/github-takeover.yaml
Labels: Done

#6281 Update teamwork-takeover.yaml
  takeovers/teamwork-takeover.yaml
Labels: Done

#6221 Update PEGA detection template
  exposed-panels/pega-web-panel.yaml
Labels: Done

#6201 Update apache-solr-file-read.yaml
  vulnerabilities/apache/apache-solr-file-read.yaml
Labels: Done

#6203 Create routes-ini.yaml
  exposures/files/routes-ini.yaml
Labels: Done

#6237 Create CVE-2019-6802.yaml
  cves/2019/CVE-2019-6802.yaml
Labels: Done

#6222 Added template for CVE-2022-0948
  cves/2022/CVE-2022-0948.yaml
Labels: Done

#6211 Added template for CVE-2022-0826
  cves/2022/CVE-2022-0826.yaml
Labels: Done

#6296 Added template for CVE-2021-24827
  cves/2021/CVE-2021-24827.yaml
Labels: Done

#6204 Create homeworks-illumination.yaml
  iot/homeworks-illumination.yaml
Labels: Done

#6292 Create leadpages-takeover.yaml
  takeovers/leadpages-takeover.yaml
Labels: Done

#6206 Update putty-private-key-disclosure.yaml
  exposures/files/putty-private-key-disclosure.yaml
Labels: Done

#6224 Update error-logs.yaml
  exposures/logs/error-logs.yaml
Labels: Done

#6298 Update npmrc-authtoken.yaml
  exposures/files/npmrc-authtoken.yaml
Labels: Done

#6227 Create finger-detect.yaml
  network/detection/finger-detect.yaml
Labels: Done

#6300 Fix False Positive for PyPI Server Detect
  technologies/pypiserver-detect.yaml
Labels: Done

#6301 Update self-signed-ssl.yaml
  ssl/self-signed-ssl.yaml
Labels: Done

#6302 Update dir-listing.yaml
  miscellaneous/dir-listing.yaml
Labels: Status: Completed, Done

#6230 Update elasticsearch.yaml
  misconfiguration/elasticsearch.yaml
Labels: Done

#6228 Create rpcbind-portmapper-detect.yaml
  network/detection/rpcbind-portmapper-detect.yaml
Labels: Done

#6258 Added nps-auth-bypass
  vulnerabilities/nps/nps-auth-bypass.yaml
Labels: good first issue, Done

#6263 Update uservoice-takeover.yaml
  takeovers/uservoice-takeover.yaml
Labels: Done

#6265 Update hatenablog-takeover.yaml
  takeovers/hatenablog-takeover.yaml
Labels: Done

#6229 Create config-json.yaml
  exposures/configs/config-json.yaml
Labels: Done

#6305 Folder Updation
  default-logins/ruckus/ruckus-wireless-default-login.yaml
  default-logins/steve/steve-default-login.yaml
  default-logins/xnat/xnat-default-login.yaml
Labels: Done

#6295 VMware NSX Manager XStream Pre-authenticated RCE
  cves/2022/CVE-2022-37042.yaml
  vulnerabilities/vmware/vmware-nsx-stream-rce.yaml
Labels: Done

#6351 Added template for easyscripts-installer
  misconfiguration/installer/easyscripts-installer.yaml
Labels: Done

#6350 Added template for CVE-2022-2314
  cves/2022/CVE-2022-2314.yaml
Labels: Done

#6344 Create microfocus-admin-server.yaml
  exposed-panels/microfocus-admin-server.yaml
Labels: good first issue, Done

#6345 Create qibocms-file-download.yaml
  vulnerabilities/qibocms-file-download.yaml
Labels: Done

#6348 Create verizon-router-panel.yaml
  exposed-panels/verizon-router-panel.yaml
Labels: Done

#6310 Create CVE-2022-45917.yaml
  cves/2022/CVE-2022-45917.yaml
Labels: Done

#6347 Create icecast-server-detect.yaml
  technologies/icecast-server-detect.yaml
Labels: Done

#6337 Added Profile header for additional WAP coverage on CJServer hosts
  vulnerabilities/generic/oob-header-based-interaction.yaml
Labels: Done

#6313 Database credentials.yaml
  exposures/files/database-credentials.yaml
Labels: Done

#6312 Create planet-estream-panel.yaml
  exposed-panels/planet-estream-panel.yaml
Labels: Done

#6314 Golangci config.yaml
  exposures/configs/golangci-config.yaml
Labels: Done

#6315 Kube apiserver keys.yaml
  exposures/files/kubernetes-etcd-keys.yaml
Labels: Done

#6320 Npm debug log
  exposures/logs/npm-debug-log.yaml
Labels: Done

#6349 Added template for CVE-2021-25099
  cves/2021/CVE-2021-25099.yaml
Labels: Done

#6317 Svn wc db
  exposures/files/svn-wc-db.yaml
Labels: Done

#6316 Stestr config
  exposures/configs/stestr-config.yaml
Labels: Done

#6311 Create ilias-panel.yaml
  exposed-panels/ilias-panel.yaml
Labels: Done

#6318 Badarg log
  exposures/logs/badarg-log.yaml
Labels: Done

#6353 filename update
  exposures/configs/phpinfo-files.yaml
Labels: Done

#6373 Sitemap Detect
  miscellaneous/sitemap-detect.yaml
Labels: Done

#6377 added windows path
  cves/2021/CVE-2021-43734.yaml
Labels: Status: Completed, Done

#6356 Added template for CVE-2022-4050
  cves/2022/CVE-2022-4050.yaml
Labels: Done

#6359 CVE-2018-17422 (matcher update)
  cves/2018/CVE-2018-17422.yaml
Labels: Done

#6360 Create lutron-default-login.yaml
  default-logins/lutron/lutron-default-login.yaml
Labels: Done

#6361 Create pagespeed-detect.yaml
  technologies/pagespeed-detect.yaml
Labels: Done

#6364 Create unauth-zwave-mqtt.yaml
  misconfiguration/unauth-zwave-mqtt.yaml
Labels: Done

#6368 Create websheets-config.yaml
  exposures/configs/websheets-config.yaml
Labels: Done

#6369 Create salesforce-credentials.yaml
  exposures/files/salesforce-credentials.yaml
Labels: Done

#6370 Create production-log.yaml
  exposures/logs/production-log.yaml
Labels: Done

#6371 Update credential-exposure.yaml
  file/keys/credential-exposure.yaml
Labels: Done

#6372 Create mautic-Unauthorized-upgrade
  misconfiguration/unauth-mautic-upgrade.yaml
Labels: Status: Completed, Done

#6272 Update feedpress-takeover.yaml
  takeovers/feedpress-takeover.yaml
Labels: Done

#6365 Add detection of SPARK instance
  exposed-panels/spark-panel.yaml
Labels: Done

#6352 Add additional backup extension
  exposures/backups/zip-backup-files.yaml
Labels: Done

#6367 Update insecure-firebase-database.yaml
  misconfiguration/google/insecure-firebase-database.yaml
Labels: Done

#6355 Added template for CVE-2022-1595
  cves/2022/CVE-2022-1595.yaml
Labels: Done

#6192 Update CVE-2021-41773.yaml
  cves/2021/CVE-2021-41773.yaml
Labels: Done

#6213 Create mikrotik-httpproxy.yaml
  technologies/mikrotik-httpproxy.yaml
Labels: Status: Completed, Done

#6375 Detect Mysql
  network/detection/mysql-detect.yaml
Labels: Status: Completed, Done

#6374 Create zyxel-exportlog-lfd.yaml
  vulnerabilities/zyxel/unauth-lfd-zhttpd.yaml
Labels: Status: Completed, Done

#6382 Templates Release
  cves/2022/CVE-2022-1595.yaml
  exposed-panels/gyra-master-admin.yaml
  exposed-panels/ilias-panel.yaml
  exposed-panels/pega-web-panel.yaml
  exposures/logs/firebase-debug-log.yaml
  exposures/logs/npm-debug-log.yaml
  miscellaneous/sitemap-detect.yaml
  vulnerabilities/qibocms-file-download.yaml
Labels: Status: Completed, Done

#6390 carel-platvisor-panel
  iot/carel-plantvisor-panel.yaml
Labels: Done

#6389 Create xfinity-panel.yml
  exposed-panels/xfinity-panel.yaml
Labels: Done

#6335 Create exposed-dockerd.yaml
  network/exposed-dockerd.yaml
Labels: Done

#6395 Create amazon-ec2-detect.yaml
  technologies/aws/amazon-ec2-detect.yaml
Labels: Done

#6387 Added template for CVE-2022-0786
  cves/2022/CVE-2022-0786.yaml
Labels: Done

#5976 Create CVE-2022-25082
  cves/2022/CVE-2022-25082.yaml
Labels: Done

#6399 minor-update
  cves/2022/CVE-2022-25082.yaml
Labels: Done

#6401 Added template for webuzo-admin-panel
  exposed-panels/webuzo-admin-panel.yaml
Labels: Done

#6402 Added template for creatio-login-panel
  exposed-panels/creatio-login-panel.yaml
Labels: Done

#6403 Create posthog-admin-panel.yaml
  exposed-panels/posthog-admin-panel.yaml
Labels: Done

#6406 Create Loxone-Login.yaml
  exposed-panels/loxone-panel.yaml
Labels: Done

#6260 Update credential-exposure.yaml
  file/keys/credential-exposure.yaml
Labels: Done

#6259 Update credentials-disclosure.yaml
  exposures/tokens/generic/credentials-disclosure.yaml
Labels: Done
