Repository projectdiscovery/nuclei-templates, pull requests merged in 2022-10, with the labels that each got.

#5482 Update hp-color-laserjet-detect.yaml
  iot/hp-color-laserjet-detect.yaml
Labels: Done

#5481 Create somansa-dlp-detect
  exposed-panels/somansa-dlp-detect.yaml
Labels: Done

#5487 Update fingerprinthub-web-fingerprints
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#5503 Create remedy-axis-login.yaml
  exposed-panels/remedy-axis-login.yaml
Labels: Done

#5505 Add Gitea Signup
  misconfiguration/gitea-public-signup.yaml
Labels: Done

#5508 Unauthenticated kubecost detect
  misconfiguration/unauth-kubecost.yaml
Labels: Done

#5509 Add CVE-2022-38553
  cves/2022/CVE-2022-38553.yaml
Labels: Done

#5526 fix: false negative xenforo-detect template
  exposed-panels/xenforo-login.yaml
  technologies/xenforo-detect.yaml
Labels: Done

#5501 Create prtg-weak-login.yaml
  default-logins/prtg-default-login.yaml
Labels: Done

#5514 Add CVE-2020-20285
  cves/2020/CVE-2020-20285.yaml
Labels: Done

#5524 Create unauthenticated-duplicator-disclosure.yaml
  vulnerabilities/wordpress/unauthenticated-duplicator-disclosure.yaml
Labels: Done

#5471 Added Z-BlogPHP Exposed Admin Panel Template
  exposed-panels/zblog-exposed-admin-panel.yaml
Labels: good first issue, Done

#5543 feat: added version detection looker-panel.yaml
  exposed-panels/looker-panel.yaml
Labels: Hacktoberfest, Done

#5550 Create CVE-2022-0679.yaml
  cves/2022/CVE-2022-0679.yaml
Labels: Hacktoberfest, Done

#5539 Create api-opsgenie.yaml
  token-spray/api-opsgenie.yaml
Labels: Hacktoberfest, Done

#5540 Create api-newrelic.yaml
  token-spray/api-newrelic.yaml
Labels: Hacktoberfest, Done

#5542 Create api-ticketmaster.yaml
  token-spray/api-ticketmaster.yaml
Labels: Hacktoberfest, Done

#5549 Create logger1000-detect
  exposed-panels/sungrow-logger1000-detect.yaml
Labels: Hacktoberfest, Done

#5548 Create room-alert-detect
  exposed-panels/room-alert-detect.yaml
Labels: Hacktoberfest, Done

#5536 Add CVE-2022-0412
  cves/2022/CVE-2022-0412.yaml
Labels: Done

#5555 Update CVE-2022-0679.yaml
  cves/2022/CVE-2022-0679.yaml
Labels: Done

#5561 Create CVE-2022-30512.yaml
  cves/2022/CVE-2022-30512.yaml
Labels: Done

#5552 Create CVE-2022-38817.yaml
  cves/2022/CVE-2022-38817.yaml
Labels: Hacktoberfest, Done

#5554 Create smtp2go-detect.yaml
  technologies/smtp2go-detect.yaml
Labels: Hacktoberfest, Done

#5533 Add CVE-2022-2467
  cves/2022/CVE-2022-2467.yaml
Labels: Done

#5537 Add CVE-2022-1768
  cves/2022/CVE-2022-1768.yaml
Labels: Done

#5566 feat: Created Hugo detection
  technologies/hugo-detect.yaml
Labels: Done

#5565 Added template for CVE-2021-24227
  cves/2021/CVE-2021-24227.yaml
Labels: Done

#5560 feat: add regex version buildbot-panel template
  exposed-panels/buildbot-panel.yaml
Labels: Done

#5568 Create CVE-2022-30514.yaml
  cves/2022/CVE-2022-30514.yaml
Labels: Done

#5574 Create arris-modem-detect
  exposed-panels/arris-modem-detect.yaml
Labels: Done

#5572 feat: added version detection nextcloud
  technologies/nextcloud-detect.yaml
Labels: Hacktoberfest, Done

#5571 Create glpi-detect.yaml
  tech/glpi-status-page.yaml
Labels: good first issue, Hacktoberfest, Done

#5569 Added additional check for shopware 6
  technologies/shopware-detect.yaml
Labels: good first issue, Hacktoberfest, Done

#5583 Added template for CVE-2021-24150
  cves/2021/CVE-2021-24150.yaml
Labels: Hacktoberfest, Done

#5584 Added template for CVE-2022-0781
  cves/2022/CVE-2022-0781.yaml
Labels: Done

#5593 Create CVE-2022-25356.yaml
  cves/2022/CVE-2022-25356.yaml
Labels: Done

#5594 Create nuget-package-config.yaml
  exposures/files/nuget-package-config.yaml
Labels: Hacktoberfest, Done

#5591 feat: created harbor-panel.yaml
  exposed-panels/harbor-panel.yaml
Labels: duplicate

#5596 Added apple-httpserver
  technologies/apple-httpserver.yaml
Labels: Hacktoberfest, Done

#5597 Adde axel-webserver
  exposed-panels/axel-webserver.yaml
Labels: Done

#5598 Added neobox-web-server-detect
  exposed-panels/neobox-panel.yaml
Labels: Hacktoberfest, Done

#5599 Adde extron-cms-detect
  exposed-panels/extron-cms-panel.yaml
Labels: Hacktoberfest, Done

#5595 Adde apache-mesos-detect
  exposed-panels/apache/apache-mesos-panel.yaml
Labels: Done

#5601 Added wms-server
  technologies/wms-server-detect.yaml
Labels: Hacktoberfest, Done

#5586 Create sass-lint.yaml
  exposures/files/sass-lint.yaml
Labels: Hacktoberfest, Done

#5614 Add classification
  cves/2019/CVE-2019-8086.yaml
Labels: Done

#5589 Update npm-log-file.yaml
  exposures/logs/npm-log-file.yaml
Labels: Hacktoberfest, Done

#5588 Create CVE-2020-11450.yaml
  cves/2020/CVE-2020-11450.yaml
Labels: Done

#5590 Create php-mailer.yaml
  exposed-panels/php-mailer.yaml
Labels: Hacktoberfest, Done

#5610 Create qualtrics-detect.yaml
  exposed-panels/qualtrics-login.yaml
Labels: Done

#5618 Create rollup-js-config.yaml
  exposures/configs/rollup-js-config.yaml
Labels: Hacktoberfest, Done

#5620 Create locust-exposure.yaml
  misconfiguration/locust-exposure.yaml
Labels: Hacktoberfest, Done

#5616 fix: false negative pbootcms-detect template
  technologies/pbootcms-detect.yaml
Labels: Hacktoberfest, Done

#5626 Added template for CVE-2022-33965
  cves/2022/CVE-2022-33965.yaml
Labels: Hacktoberfest, Done

#5629 Create guard-config.yaml
  exposures/configs/guard-config.yaml
Labels: Hacktoberfest, Done

#5622 fix: false negative at hivemanager-login-panel
  exposed-panels/hivemanager-login-panel.yaml
Labels: Hacktoberfest, Done

#5621 Create babel-config-exposure.yaml
  exposures/configs/babel-config-exposure.yaml
Labels: Hacktoberfest, Done

#5617 Create favicon-detection
  technologies/favicon-detection.yaml
Labels: Hacktoberfest, Done

#5608 Create nordex-control-wind-farm-portal.yaml
  exposed-panels/nordex-wind-farm-portal.yaml
Labels: Hacktoberfest, Done

#5609 Create x-recruiting-header.yaml
  miscellaneous/x-recruiting-header.yaml
Labels: Hacktoberfest, Done

#5600 Added google-frontend-httpserver
  technologies/google-frontend-httpserver.yaml
Labels: Hacktoberfest, Done

#5633 Create apache-drill-exposure.yaml
  misconfiguration/apache-drill-exposure.yaml
Labels: Hacktoberfest, Done

#5606 Added CVE-2022-40083
  cves/2022/CVE-2022-40083.yaml
Labels: Done

#5635 Create npm-anonymous-cli.yaml
  exposures/files/npm-anonymous-cli.yaml
Labels: Hacktoberfest, Done

#5636 feat: added aqua enterprise detection
  technologies/aqua-enterprise-detect.yaml
Labels: Hacktoberfest, Done

#5632 Update laravel-env.yaml
  exposures/configs/laravel-env.yaml
Labels: Hacktoberfest, Done

#5645 Update OAST tags
  vulnerabilities/cisco/cisco-unified-communications-log4j.yaml
  vulnerabilities/cisco/cisco-vmanage-log4j.yaml
  vulnerabilities/other/graylog-log4j.yaml
  vulnerabilities/other/jamf-pro-log4j.yaml
  vulnerabilities/other/metabase-log4j.yaml
  vulnerabilities/other/opennms-log4j-jndi-rce.yaml
  vulnerabilities/other/rundeck-log4j.yaml
  vulnerabilities/vmware/vmware-hcx-log4j.yaml
  vulnerabilities/vmware/vmware-nsx-log4j.yaml
  vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
Labels: Done

#5647 Update shell-history.yaml
  misconfiguration/shell-history.yaml
Labels: Done

#5653 Update nextcloud-detect.yaml
  technologies/nextcloud-detect.yaml
Labels: Done

#5655 Update jmx-default-login.yaml
  default-logins/jboss/jmx-default-login.yaml
Labels: Done

#5656 Update and rename misconfiguration/apache/apache-tomcat-snoop.yaml to…
  .nuclei-ignore
  cves/2007/CVE-2007-2449.yaml
Labels: Done

#5663 FP - Fix | Update CVE-2020-14179.yaml
  cves/2020/CVE-2020-14179.yaml
Labels: Done

#5641 Create zimbra-detect.yaml
  technologies/zimbra-detect.yaml
Labels: good first issue, Hacktoberfest, Done

#5587 Added CVE-2022-27593 and CVE-2022-40684
  cves/2022/CVE-2022-27593.yaml
Labels: Hacktoberfest, Done

#5642 Update samsung-printer-detect.yaml
  exposed-panels/samsung-printer-detect.yaml
Labels: Hacktoberfest, Done

#5611 feat: update gitbook-detect
  technologies/gitbook-detect.yaml
Labels: Hacktoberfest, Done

#5496 Added template for CVE-2022-0434
  cves/2022/CVE-2022-0434.yaml
Labels: Hacktoberfest, Done

#5646 Create fortitester-login-panel.yaml
  exposed-panels/forti/fortimail-panel.yaml
  exposed-panels/forti/fortinet-fortigate-panel.yaml
  exposed-panels/forti/fortinet-panel.yaml
  exposed-panels/forti/fortitester-login-panel.yaml
  exposed-panels/forti/fortiweb-panel.yaml
  workflows/fortinet-workflow.yaml
Labels: Hacktoberfest, Done

#5649 Create fortiadc-panel.yaml
  exposed-panels/forti/fortiadc-panel.yaml
Labels: Hacktoberfest, Done

#5650 Create fortiap-panel.yaml
  exposed-panels/fortinet/fortiap-panel.yaml
Labels: Hacktoberfest, Done

#5604 Added template for CVE-2022-0535
  cves/2022/CVE-2022-0535.yaml
Labels: Hacktoberfest, Done

#5651 Create envoy-admin-exposure.yaml
  misconfiguration/envoy-admin-exposure.yaml
Labels: Hacktoberfest, Done

#5652 Create flureedb-console.yaml
  exposed-panels/flureedb-admin-console.yaml
Labels: Hacktoberfest, Done

#5654 fix: false negative mantis-panel
  exposed-panels/mantis-detect.yaml
  exposed-panels/mantisbt-panel.yaml
  workflows/mantisbt-workflow.yaml
Labels: Hacktoberfest, Done

#5644 Create tomcat-scripts-cookie.yaml
  misconfiguration/tomcat-cookie-exposed.yaml
Labels: Hacktoberfest, Done

#5671 fix: false negative qnap-qts-panel
  exposed-panels/qnap/qnap-qts-panel.yaml
Labels: Hacktoberfest, Done

#5670 Added CVE-2017-5689
  cves/2017/CVE-2017-5689.yaml
Labels: Done

#5673 Update pyproject-toml.yaml
  exposures/configs/pyproject-toml.yaml
Labels: Done

#5661 Create flatpress-xss.yaml
  vulnerabilities/other/flatpress-xss.yaml
Labels: Hacktoberfest, Done

#5660 Create CVE-2021-41432.yaml
  cves/2021/CVE-2021-41432.yaml
Labels: Hacktoberfest, Done

#5659 Added template for CVE-2018-19287
  cves/2018/CVE-2018-19287.yaml
Labels: Done

#5500 Create vmware-horizon-version.yaml
  technologies/vmware/vmware-horizon-version.yaml
Labels: Hacktoberfest, Done

#1271 Create seeyon-unauth
  misconfiguration/seeyon-unauth.yaml
Labels: Done

#5664 fix: false negative gogs-panel template
  exposed-panels/gogs-login.yaml
  exposed-panels/gogs-panel.yaml
Labels: Hacktoberfest, Done

#5667 Create fortios-exposed-admin-panel.yaml
  exposed-panels/fortinet/fortios-panel.yaml
Labels: Hacktoberfest, Done

#5662 Update CVE-2019-3403.yaml
  cves/2019/CVE-2019-3403.yaml
Labels: Done

#5657 Added Mautic Cve
  cves/2021/CVE-2021-27909.yaml
Labels: Hacktoberfest, Done

#5625 Create CVE-2019-18957.yaml
  cves/2019/CVE-2019-18957.yaml
Labels: Hacktoberfest, Done

#5538 Microsoft FTP Service Detection
  network/detection/cql-native-transport.yaml
  network/detection/microsoft-ftp-service.yaml
Labels: Hacktoberfest, Done

#5502 update flywheel takeover template to reflect new language
  takeovers/flywheel-takeover.yaml
Labels: Done

#5553 feat: Create CVE-2021-24940 template
  cves/2021/CVE-2021-24940.yaml
Labels: Hacktoberfest, Done

#5676 Create dataiku-default-login.yaml
  default-logins/dataiku/dataiku-default-login.yaml
Labels: Hacktoberfest, Done

#5703 Delete omnia-mpx-lfi.yaml
  vulnerabilities/other/omnia-mpx-lfi.yaml
Labels: duplicate, Status: Completed

#5677 Create dataiku-panel.yaml
  exposed-panels/dataiku-panel.yaml
Labels: Hacktoberfest, Done

#5681 style: rename aptus-detect template
  exposed-panels/aptus-panel.yaml
Labels: Done

#5680 feat: create piwigo panel detection
  exposed-panels/piwigo-panel.yaml
Labels: Hacktoberfest, Done

#5684 refactor: move from exposed-panel to technologies
  exposed-panels/total-web-solutions-panel.yaml
Labels: Hacktoberfest, Done

#5695 Create springboot-features.yaml
  misconfiguration/springboot/springboot-features.yaml
Labels: Hacktoberfest, Done

#5696 Create springboot-auditevents.yaml
  misconfiguration/springboot/springboot-auditevents.yaml
Labels: Hacktoberfest, Done

#5697 Create springboot-jolokia.yaml
  misconfiguration/springboot/springboot-jolokia.yaml
Labels: Hacktoberfest, Done

#5700 Create springboot-logfile.yaml
  misconfiguration/springboot/springboot-logfile.yaml
Labels: Hacktoberfest, Done

#5699 Create CVE-2022-41473.yaml
  cves/2022/CVE-2022-41473.yaml
Labels: Hacktoberfest, Done

#5701 Create springboot-loggerconfig.yaml
  misconfiguration/springboot/springboot-loggerconfig.yaml
Labels: Hacktoberfest, Done

#5702 fix: false negative opengear-panel
  exposed-panels/opengear-login.yaml
  exposed-panels/opengear-panel.yaml
Labels: Done

#5705 Create processwire-login.yaml
  default-logins/processwire-login.yaml
Labels: Hacktoberfest, Done

#5706 Delete elasticbeantalk-takeover.yaml
  dns/elasticbeantalk-takeover.yaml
Labels: Done

#5715 Revert "Delete elasticbeantalk-takeover.yaml"
  dns/elasticbeantalk-takeover.yaml
Labels: Done

#5709 Create travis-ci-disclosure.yaml
  exposures/files/travis-ci-disclosure.yaml
Labels: Hacktoberfest, Done

#5693 feat: create bmc-discovery-panel template
  exposed-panels/bmc/bmc-discovery-panel.yaml
Labels: Hacktoberfest, Done

#5683 fix: false negative totemomail-panel
  exposed-panels/totemomail-detect.yaml
  exposed-panels/totemomail-panel.yaml
Labels: Hacktoberfest, Done

#5711 Create iot-vdme-simulator.yaml
  misconfiguration/iot-vdme-simulator.yaml
Labels: Hacktoberfest, Done

#5712 Create novnc-login-panel.yaml
  exposed-panels/novnc-login-panel.yaml
Labels: Hacktoberfest, Done

#5714 Create cakephp-config.yaml
  exposures/configs/cakephp-config.yaml
Labels: Hacktoberfest, Done

#5716 Create oracle-atg-commerce.yaml
  technologies/oracle/oracle-atg-commerce.yaml
Labels: Hacktoberfest, Done

#5687 Weak Cipher Detection
  ssl/weak-cipher-suites.yaml
Labels: Hacktoberfest, Done

#5708 Create loqate-api-key.yaml
  exposures/tokens/loqate/loqate-api-key.yaml
Labels: Hacktoberfest, Done

#5707 Delete CVE-2007-2449.yaml
  cves/2007/CVE-2007-2449.yaml
Labels: Hacktoberfest, Done

#5730 Update vmware-nsx-log4j.yaml
  vulnerabilities/vmware/vmware-nsx-log4j.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5733 Update metabase-log4j.yaml
  vulnerabilities/other/metabase-log4j.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5729 Added template for CVE-2022-1574
  cves/2022/CVE-2022-1574.yaml
Labels: Hacktoberfest, Done

#5734 Update rundeck-log4j.yaml
  vulnerabilities/other/rundeck-log4j.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5736 Update exposed-sqlite-manager.yaml
  misconfiguration/exposed-sqlite-manager.yaml
Labels: Hacktoberfest, Done

#5721 GNU Inetutils FTPd Detect
  network/detection/gnu-inetutils-ftpd-detect.yaml
Labels: Hacktoberfest, Done

#5720 MikroTik FTP server Detect
  network/detection/mikrotik-ftp-server-detect.yaml
Labels: Hacktoberfest, Done

#5719 ProFTPD Server Detect
  network/detection/proftpd-server-detect.yaml
Labels: Hacktoberfest, Done

#5718 Xlight FTP Service Detect
  network/detection/xlight-ftp-service-detect.yaml
Labels: Hacktoberfest, Done

#5723 Update tomcat-detect.yaml
  technologies/apache/tomcat-detect.yaml
Labels: Hacktoberfest, Done

#5739 Update cisco-vmanage-log4j.yaml
  vulnerabilities/cisco/cisco-vmanage-log4j.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5740 Update mobileiron-log4j-jndi-rce.yaml
  vulnerabilities/mobileiron/mobileiron-log4j-jndi-rce.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5741 Update jamf-log4j-jndi-rce.yaml
  vulnerabilities/jamf/jamf-log4j-jndi-rce.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5742 Update graylog-log4j.yaml
  vulnerabilities/other/graylog-log4j.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5743 Update vmware-operation-manager-log4j.yaml
  vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5744 Update vmware-siterecovery-log4j-rce.yaml
  vulnerabilities/other/vmware-siterecovery-log4j-rce.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5745 Update CVE-2020-14181.yaml
  cves/2020/CVE-2020-14181.yaml
Labels: Priority: Critical, Hacktoberfest, Done

#5746 Create sonic-wall-application.yaml
  exposed-panels/sonic-wall-application.yaml
Labels: Hacktoberfest, Done

#5747 Create springboot-status.yaml
  misconfiguration/springboot/springboot-status.yaml
Labels: Hacktoberfest, Done

#5738 Add Joomla! detect template with version detection capabilities
  technologies/joomla-detect.yaml
Labels: Hacktoberfest, Done

#5749 Add Open Journal Systems (OJS) detect
  technologies/open-journal-systems.yaml
Labels: Hacktoberfest, Done

#5750 Create aerocms-sqli.yaml
  vulnerabilities/other/aerocms-sqli.yaml
Labels: good first issue, Hacktoberfest, Done
