Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-08, with the labels that each got.

#7791 Add negative filter for rocketmq unauth
  network/misconfig/apache-rocketmq-broker-unauth.yaml
Labels: good first issue, Done

#7793 Metadata update CVE-2023-35078.yaml
  http/cves/2023/CVE-2023-35078.yaml
Labels: Done

#7798 Updated matcher alibaba-anyproxy-lfi
  http/vulnerabilities/other/alibaba-anyproxy-lfi.yaml
Labels: Done

#7804 Create CVE-2023-37580.yaml (Zimbra XSS)
  http/cves/2023/CVE-2023-37580.yaml
Labels: Done

#7799 fix dbeaver-credentials false-positive
  http/exposures/configs/dbeaver-credentials.yaml
Labels: Done

#7806 Rename gozi-malware.yaml to gozi-malware-c2.yaml
  ssl/c2/gozi-malware-c2.yaml
Labels: Done

#7805 Supporting translated adminer
  http/exposed-panels/adminer-panel.yaml
Labels: Done

#5959 Create CVE-2022-40843
  http/cves/2022/CVE-2022-40843.yaml
Labels: Done

#5277 Create CVE 2019 14750
  http/cves/2019/CVE-2019-14750.yaml
Labels: Done

#7809 Elasticbeanstalk typo
  dns/elasticbeanstalk-takeover.yaml
Labels: Done

#7800 fix nginx-module-vts-xss false-positive
  .nuclei-ignore
  http/vulnerabilities/other/nginx-module-vts-xss.yaml
Labels: Done

#7065 Create apache-solr-91-rce.yaml
  http/vulnerabilities/apache/apache-solr-rce.yaml
Labels: Done, defcon31

#7789 Create CVE-2023-1698.yaml
  http/cves/2023/CVE-2023-1698.yaml
Labels: Done

#7810 Create openstack-config.yaml
  http/misconfiguration/openstack-config.yaml
Labels: Done

#7811 Create CVE-2022-0169.yaml
  http/cves/2022/CVE-2022-0169.yaml
Labels: Done

#7797 added: oracle-reports-detect
  http/misconfiguration/oracle-reports-services.yaml
Labels: Done

#7818 Updated matcher
  http/exposed-panels/episerver-panel.yaml
Labels: good first issue, Done

#7820 FP Fix- empire-c2.yaml
  http/exposed-panels/c2/empire-c2.yaml
Labels: Done

#7819 Create CVE-2023-35082.yaml
  http/cves/2023/CVE-2023-35082.yaml
Labels: Done

#7822 fix jupyter-notebook-rce
  http/vulnerabilities/jupyter-notebook-rce.yaml
Labels: Done

#7825 Update FN CVE-2021-24472.yaml
  http/cves/2021/CVE-2021-24472.yaml
Labels: Done

#7857 Create CVE-2023-39143.yaml (PaperCut Path Traversal Detection) KEV 🔥
  http/cves/2023/CVE-2023-39143.yaml
Labels: Done

#7846 Create CVE-2023-39120.yaml
  http/cves/2023/CVE-2023-39120.yaml
Labels: good first issue, Done

#7861 reference fix
  http/cves/2020/CVE-2020-10199.yaml
Labels: Done

#7863 Create bsphp-info.yaml
  http/vulnerabilities/bsphp-info.yaml
Labels: Done

#7862 Create discuz-path-disclosure.yaml
  http/vulnerabilities/discuz/discuz-api-pathinfo.yaml
Labels: Done

#7844 Netmizer (netmizer-cmd-rce) , (netmizer-data-listing)
  http/vulnerabilities/netmizer/netmizer-cmd-rce.yaml
  http/vulnerabilities/netmizer/netmizer-data-listing.yaml
Labels: Done

#7847 Create CVE-2023-22478.yaml (KubePi <= v1.6.4 LoginLogsSearch)
  http/cves/2023/CVE-2023-22478.yaml
Labels: Done

#7848 Create CVE-2022-2414.yaml (FreeIPA XXE) 🔥
  http/cves/2022/CVE-2022-2414.yaml
Labels: Done

#7850 Create clodop-printer-lfi.yaml
  http/vulnerabilities/other/clodop-printer-lfi.yaml
Labels: Done

#7869 fix headers -> header
  http/cves/2023/CVE-2023-2178.yaml
Labels: Done

#7860 Create clickhouse-unauth-api.yaml
  http/misconfiguration/clickhouse-unauth-api.yaml
Labels: Done

#7854 Create avcon6-download-action-lfi.yaml
  http/vulnerabilities/other/avcon6-lfi.yaml
Labels: Done

#7852 Create socks5-vpn-config.yaml
  http/exposures/files/socks5-vpn-config.yaml
Labels: Done

#7849 Create sonarqube-search-projects.yaml
  http/misconfiguration/sonarqube-projects-disclosure.yaml
Labels: Done

#7845 Create CVE-2023-22480.yaml (KubeOperator Foreground kubeconfig Download) 🔥
  http/cves/2023/CVE-2023-22480.yaml
Labels: Done

#7841 Create CVE-2018-12909.yaml
  http/cves/2018/CVE-2018-12909.yaml
Labels: Done

#7839 Create sangfor-cphp-rce.yaml
  http/vulnerabilities/other/sangfor-cphp-rce.yaml
Labels: Done

#7835 Create kedacom-network-lfi.yaml
  http/vulnerabilities/other/kodak-network-lfi.yaml
Labels: Done

#7833 Create CNVD-2021-43984.yaml
  http/cnvd/2021/CNVD-2021-43984.yaml
Labels: Done

#7821 Create CVE-2018-18809.yaml (KEV) 🔥
  http/cves/2018/CVE-2018-18809.yaml
Labels: Done, defcon31

#7823 Create CVE-2019-7192.yaml (KEV) 🔥
  http/cves/2019/CVE-2019-7192.yaml
Labels: Done, defcon31

#7871 Create yzmcms-installer.yaml
  http/misconfiguration/installer/yzmcms-installer.yaml
Labels: Done

#7827 Create acti-video-lfi.yaml
  http/vulnerabilities/other/acti-video-lfi.yaml
Labels: Done

#7830 Create CNVD-2021-41972.yaml
  http/cnvd/2021/CNVD-2021-41972.yaml
Labels: Done

#7855 Create avcon6-org-execl-download-lfi.yaml
  http/vulnerabilities/other/avcon6-execl-lfi.yaml
Labels: Done

#7875 Create zzzcms-info-disclosure.yaml
  http/vulnerabilities/zzzcms/zzzcms-info-disclosure.yaml
Labels: Done

#7873 Create zzzcms-ssrf.yaml
  http/vulnerabilities/zzzcms/zzzcms-ssrf.yaml
Labels: Done

#7872 Create CVE-2018-7653.yaml
  http/cves/2018/CVE-2018-7653.yaml
Labels: Done

#7876 Create joomla-department-sqli.yaml
  http/vulnerabilities/joomla/joomla-department-sqli.yaml
Labels: Done

#7836 Create kodak-network-panel.yaml
  http/exposed-panels/kodak-network-panel.yaml
Labels: Done

#7832 Create acenet-panel.yaml
  http/exposed-panels/acenet-panel.yaml
Labels: Done

#7834 Create mpsec-isg1000-panel.yaml
  http/exposed-panels/mpsec-isg1000-panel.yaml
Labels: Done

#7877 Fixed Bug in variables CVE-2021-1497.yaml
  http/cves/2021/CVE-2021-1497.yaml
Labels: Done

#7829 Create acti-panel.yaml
  http/exposed-panels/acti-panel.yaml
Labels: Done

#7878 Crawlab File - Arbitrary File Read
  http/vulnerabilities/other/crawlab-lfi.yaml
Labels: Done

#7883 strict matcher with redirects
  http/default-logins/bloofoxcms-default-login.yaml
Labels: Done

#7886 Create combodo-itop-installer.yaml
  http/misconfiguration/installer/combodo-itop-installer.yaml
Labels: Done

#7887 Create openmediavault-default-login.yaml
  http/default-logins/openmediavault/openmediavault-default-login.yaml
Labels: Done

#7868 Fix samba-detect.yaml
  network/detection/samba-detect.yaml
Labels: Done

#7866 Fix Ibm-d2b-database-server.yaml
  network/detection/ibm-d2b-database-server.yaml
Labels: good first issue, Done

#7867 Fix pgsql-detect.yaml
  network/detection/pgsql-detect.yaml
Labels: Done

#7865 Fix Apache-rocketmq-broker-unauth.yaml
  network/misconfig/apache-rocketmq-broker-unauth.yaml
Labels: good first issue, Done

#7870 feat: added malware templates
  file/malware/basicrat-malware.yaml
  file/malware/cerber-malware.yaml
  file/malware/crunchrat-malware.yaml
  file/malware/hydracrypt-malware.yaml
  file/malware/macos-bella-malware.yaml
  file/malware/petya-malware-variant-1.yaml
  file/malware/petya-malware-variant-3.yaml
  file/malware/petya-malware-variant-bitcoin.yaml
  file/malware/pony-stealer-malware.yaml
  file/malware/powerware-malware.yaml
  file/malware/wannacry-malware.yaml
  file/malware/zrypt-malware.yaml
Labels: Done

#7881 TerraMaster TOS - User Enumeration
  http/cves/2020/CVE-2020-28185.yaml
Labels: Done

#7879 TamronOS IPTV - Arbitrary User Creation
  http/vulnerabilities/other/tamronos-user-creation.yaml
Labels: Done

#7897 WiseGiga NAS - LFI
  http/vulnerabilities/other/wisegiga-nas-lfi.yaml
Labels: Done

#7893 Webmin - Default Login
  http/default-logins/webmin-default-login.yaml
Labels: Done

#7894 Webmin < 1.920 - Authenticated Remote Code Execution
  http/cves/2019/CVE-2019-15642.yaml
Labels: Done

#7903 CVE-2017-8229
  http/cves/2017/CVE-2017-8229.yaml
Labels: Done

#7889 CVE-2023-4174/CVE-2023-4173/TerraMaster-RCE/panabit-ixcache-date-config-rce
  http/cves/2023/CVE-2023-4174.yaml
  http/vulnerabilities/other/eaa-app-lfi.yaml
  http/vulnerabilities/other/panabit-ixcache-rce.yaml
Labels: good first issue, Done

#7577 Create CVE-2022-46443.yaml
  http/cves/2022/CVE-2022-46443.yaml
Labels: Done

#7904 Create CVE-2021-22707.yaml
  http/cves/2021/CVE-2021-22707.yaml
Labels: Done

#7892 Fewer false positives in generic-env.yaml
  http/vulnerabilities/generic/generic-env.yaml
Labels: Done

#7902 fix [FP]uptimerobot-takeover
  http/takeovers/uptimerobot-takeover.yaml
Labels: Done

#7826 Update python-scanner.yaml
  file/python/python-scanner.yaml
Labels: good first issue, Done

#7837 Creating url-extension-inspector.yaml template
  file/url-analyse/url-extension-inspector.yaml
Labels: Done

#7908 Update url-extension-inspector.yaml
  file/url-analyse/url-extension-inspector.yaml
Labels: Done

#7909 Create ecology-oa-file-sqli.yaml
  http/vulnerabilities/other/ecology-oa-file-sqli.yaml
Labels: Done

#7907 Update sonarqube-login.yaml
  http/exposed-panels/sonarqube-login.yaml
Labels: Done

#7912 Create evse-web-panel.yaml
  http/exposed-panels/evlink/evse-web-panel.yaml
Labels: Done

#7911 Create evlink-panel.yaml
  http/exposed-panels/evlink/evlink-panel.yaml
Labels: Done

#7910 Lexmark Command Injection ZDI-CAN-19470 Pwn2Own Toronto 2022 🔥
  http/cves/2023/CVE-2023-26067.yaml
Labels: Done

#7917 Added erigon-server-detect template
  http/technologies/erigon-server-detect.yaml
Labels: Done

#7921 Added geth-server-detect template
  http/technologies/geth-server-detect.yaml
Labels: Done

#7920 Added nethermind-server-detect template
  http/technologies/nethermind-server-detect.yaml
Labels: Done

#7919 Added besu-server-detect template
  http/technologies/besu-server-detect.yaml
Labels: Done

#7925 Fix unauth-psql.yaml false positive
  network/misconfig/unauth-psql.yaml
Labels: Done

#7926 Fix apache-rocketmq-broker-unauth.yaml
  network/misconfig/apache-rocketmq-broker-unauth.yaml
Labels: Done

#7924 Havoc C2 - Detection
  network/jarm/c2/havoc-c2-jarm.yaml
  ssl/c2/havoc-c2.yaml
Labels: Done

#7928 Create CVE-2021-24409.yaml
  http/cves/2021/CVE-2021-24409.yaml
Labels: Done

#7935 Added istio-envoy header detection to tech-detect
  http/technologies/tech-detect.yaml
Labels: good first issue, Done

#7931 Update CVE-2021-36260.yaml :: Suggestion to avoid FN
  http/cves/2021/CVE-2021-36260.yaml
Labels: Done

#7929 Create CVE-2021-25065
  http/cves/2021/CVE-2021-25065
Labels: Done

#7927 Create CVE-2015-9323.yaml
  http/cves/CVE-2015-9323.yaml
Labels: Done

#7939 Fix FP Manage Engine AD Search
  http/misconfiguration/manage-engine-ad-search.yaml
Labels: Done

#7940 Update phpinfo-files.yaml
  http/exposures/configs/phpinfo-files.yaml
Labels: Done

#7942 AWS metadata description informs that it could be other cloud provider
  http/misconfiguration/proxy/metadata-aws.yaml
Labels: Done

#7938 add CVE-2022-46463 template
  http/cves/2022/CVE-2022-46463.yaml
Labels: Done

#7945 Create wp-real-estate-xss.yaml
  http/vulnerabilities/wordpress/wp-real-estate-xss.yaml
Labels: Done

#7943 Update mobileiron-login.yaml
  http/exposed-panels/mobileiron-login.yaml
Labels: Done

#7950 Move back CVE-2015-9323.yaml to the 2015 directory
  http/cves/2015/CVE-2015-9323.yaml
Labels: good first issue, Done

#7946 Update sonicwall-sslvpn-panel.yaml :: Sugestion to avoid FN
  http/exposed-panels/sonicwall-sslvpn-panel.yaml
Labels: Done

#7954 Network CVE Remediation - Update
  network/cves/2015/CVE-2015-3306.yaml
  network/cves/2016/CVE-2016-2004.yaml
  network/cves/2016/CVE-2016-3510.yaml
  network/cves/2017/CVE-2017-3881.yaml
  network/cves/2017/CVE-2017-5645.yaml
  network/cves/2018/CVE-2018-2628.yaml
  network/cves/2018/CVE-2018-2893.yaml
  network/cves/2020/CVE-2020-11981.yaml
  network/cves/2020/CVE-2020-1938.yaml
  network/cves/2020/CVE-2020-7247.yaml
  network/cves/2021/CVE-2021-44521.yaml
  network/cves/2022/CVE-2022-0543.yaml
  network/cves/2022/CVE-2022-24706.yaml
  network/cves/2022/CVE-2022-31793.yaml
  network/cves/2023/CVE-2023-33246.yaml
Labels: Done

#7998 Apache CouchDB - Unauthenticated Access
  http/misconfiguration/apache/apache-couchdb-unauth.yaml
Labels: Done

#7956 CAIMORE Gateway Default Login - Detect
  http/default-logins/caimore/caimore-default-login.yaml
Labels: Done

#7906 CVE-2023-4173 , flir-ax8-rce , ruijie-excu-shell 🔥
  http/cves/2023/CVE-2023-4173.yaml
  http/vulnerabilities/other/flir-ax8-rce.yaml
  http/vulnerabilities/ruijie/ruijie-excu-shell.yaml
Labels: Done

#7941 Update dedecms-detect.yaml
  http/technologies/dedecms-detect.yaml
Labels: good first issue, Done

#7995 Feiyuxing Information - Exposure
  http/misconfiguration/feiyuxing-info-leak.yaml
Labels: Done

#7955 CAIMORE Gateway - Remote Code Execution
  http/vulnerabilities/other/caimore-gateway-rce.yaml
Labels: Done

#8002 Added short description for kodak network panel
  http/exposed-panels/kodak-network-panel.yaml
Labels: Done

#8001 Add missing descriptions CVE-2021-44139, CVE-2023-38205, CVE-2023-34960
  http/cves/2021/CVE-2021-44139.yaml
  http/cves/2023/CVE-2023-34960.yaml
  http/cves/2023/CVE-2023-38205.yaml
Labels: Done

#7999 Hanta-Internet-behavior-management-system-RCE
  http/vulnerabilities/others/hanta-rce.yaml
Labels: Done

#8008 Create hongfan-ioffice-lfi.yaml
  http/vulnerabilities/other/hongfan-ioffice-lfi.yaml
Labels: Done

#8003 Create CVE-2022-39986.yaml (RaspAP 2.8.7 - RCE)
  http/cves/2022/CVE-2022-39986.yaml
Labels: Done

#8012 Add RedisInsight
  http/misconfiguration/unauth-redis-insight.yaml
Labels: Done

#8011 Add Defacement
  http/miscellaneous/defaced-website-detect.yaml
Labels: Done

#7947 Create CVE-2022-1756.yaml
  http/cves/2022/CVE-2022-1756.yaml
Labels: Done

#8009 fix: templates with generic tag should not depend on specific tech
  http/cves/2016/CVE-2016-4975.yaml
  http/cves/2019/CVE-2019-6802.yaml
  http/exposures/configs/cgi-printenv.yaml
  http/exposures/configs/msmtp-config.yaml
  http/exposures/tokens/amazon/aws-access-secret-key.yaml
  http/exposures/tokens/generic/credentials-disclosure.yaml
  http/exposures/tokens/generic/jdbc-connection-string.yaml
  http/exposures/tokens/generic/jwt-token.yaml
  http/exposures/tokens/generic/shoppable-token.yaml
  http/miscellaneous/crypto-mining-malware.yaml
  http/miscellaneous/email-extractor.yaml
  http/miscellaneous/exposed-file-upload-form.yaml
  http/miscellaneous/old-copyright.yaml
  http/miscellaneous/x-recruiting-header.yaml
  http/miscellaneous/xml-schema-detect.yaml
  http/misconfiguration/akamai/akamai-s3-cache-poisoning.yaml
Labels: good first issue, Done

#8016 Create request-baskets-exposure.yaml
  http/misconfiguration/request-baskets-exposure.yaml
Labels: Done

#8025 H3C CVM - Arbitrary File Upload
  http/vulnerabilities/other/h3c-cvm-arbitrary-file-upload.yaml
Labels: Done

#8015 Maltrail <= v0.54 - Unauthenticated OS Command Injection
  http/vulnerabilities/other/maltrail-rce.yaml
Labels: Done

#8028 Create navicat-server-panel.yaml
  http/exposed-panels/navicat-server-panel.yaml
Labels: Done

#8043 Create landray-oa-erp-data-rce.yaml
  http/vulnerabilities/other/landray-oa-erp-data-rce.yaml
Labels: Done

#8050 Updated headless-open-redirect
  headless/headless-open-redirect.yaml
Labels: Done

#8047 Create CNVD-2023-08743.yaml
  http/cnvd/2023/CNVD-2023-08743.yaml
Labels: Done

#8019 Update clubhouse.yaml
  http/osint/clubhouse.yaml
  http/osint/medium.yaml
  http/osint/vampr.yaml
Labels: Done

#8021 Create ibm-openadmin-panel.yaml
  http/exposed-panels/ibm-openadmin-panel.yaml
Labels: Done

#8030 Create easyreport-default-login.yaml
  http/default-logins/easyreport/easyreport-default-login.yaml
Labels: Done

#8035 Create jinhe-oa-c6-lfi.yaml
  http/vulnerabilities/jinhe/jinhe-oa-c6-lfi.yaml
Labels: Done

#8039 Create CVE-2019-1898.yaml
  http/cves/2019/CVE-2019-1898.yaml
Labels: Done

#8040 Create hongfan-ioffice-rce.yaml
  http/vulnerabilities/other/hongfan-ioffice-rce.yaml
Labels: Done

#8048 Create apache-druid-log4j.yaml 🔥
  http/vulnerabilities/other/apache-druid-log4j.yaml
Labels: Done

#8051 Create CVE-2021-41460.yaml
  http/cves/2021/CVE-2021-41460.yaml
Labels: Done

#8022 Fix FP aws-bucket-takeover.yaml
  http/takeovers/aws-bucket-takeover.yaml
Labels: Done

#8052 Create 74cms-weixin-sqli.yaml
  http/vulnerabilities/74cms/74cms-weixin-sqli.yaml
Labels: Done

#8054 Create hikvision-isecure-center-rce.yaml
  http/vulnerabilities/other/hikvision-isecure-center-rce.yaml
Labels: Done

#8041 Fixed FP - CVE-2020-28185
  http/cves/2020/CVE-2020-28185.yaml
Labels: Done

#7915 fix CVE-2022-31879 (false-positive)
  http/cves/2022/CVE-2022-31879.yaml
Labels: Done

#8049 Fixed FP - openai-key
  file/keys/npm-accesstoken.yaml
  file/keys/openai-key.yaml
Labels: Done

#8046 Create chatgpt-web-unauth.yaml
  http/misconfiguration/chatgpt-web-unauth.yaml
Labels: Done

#8045 Create hongfan-ioffice-sqli.yaml
  http/vulnerabilities/other/hongfan-ioffice-sqli.yaml
Labels: Done

#8036 Create nacos-default-password.yaml
  http/default-logins/nacos/nacos-default-login.yaml
Labels: Done

#8034 Create feiyuxing-default-login.yaml
  http/default-logins/feiyuxing/feiyuxing-default-login.yaml
Labels: Done

#8031 Create hikivision-env.yaml
  http/misconfiguration/hikivision-env.yaml
Labels: Done

#8024 Added exposed-panels/kasm-panel.yaml
  http/exposed-panels/kasm-login-panel.yaml
Labels: Done

#7944 Exposed core dump file detection
  http/exposures/files/core-dump.yaml
Labels: Done

#7948 Adding one more path in prometheus-metrics.yaml
  http/exposures/configs/prometheus-metrics.yaml
Labels: Done

#7949 Add extractor to drupal-detect
  http/technologies/drupal-detect.yaml
Labels: Done

#7952 Added description fields where missing in the ssl templates
  ssl/detect-ssl-issuer.yaml
  ssl/mismatched-ssl-certificate.yaml
  ssl/ssl-dns-names.yaml
Labels: Done
