Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-01, with the labels that each got.

#6451 removed-interact-url
  cves/2020/CVE-2020-35476.yaml
Labels: Status: Completed, Done

#6452 added regex
  cves/2021/CVE-2021-28151.yaml
Labels: Status: Completed, Done

#6448 Create api-zerbounce.yaml
  token-spray/api-zerbounce.yaml
Labels: Done

#6438 Postgresql detection template
  network/detection/pgsql-detect.yaml
Labels: Done

#6447 Added CVE-2022-24816
  cves/2022/CVE-2022-24816.yaml
Labels: good first issue, Done

#6450 Added template for CVE-2022-0784
  cves/2022/CVE-2022-0784.yaml
Labels: Done

#6453 Added template for CVE-2021-24946
  cves/2021/CVE-2021-24946.yaml
Labels: Done

#6461 Netsparker Enterprise Installer
  misconfiguration/installer/netsparker-enterprise-installer.yaml
Labels: Done

#6455 Create mpftvc-admin-panel.yaml
  exposed-panels/mpftvc-admin-panel.yaml
Labels: Done

#6463 Netsparker Panel
  exposed-panels/netsparker-panel.yaml
Labels: Done

#6466 Add Lenovo Fan & Power Controller Detection
  exposed-panels/lenovo-fp-panel.yaml
Labels: Done

#6470 Update appsettings-file-disclosure.yaml
  exposures/files/appsettings-file-disclosure.yaml
Labels: Done

#6468 Create akamai-s3-cache-poisoning.yaml 🔥
  misconfiguration/akamai/akamai-arl-xss.yaml
  misconfiguration/akamai/akamai-s3-cache-poisoning.yaml
Labels: Done

#6473 Create mobiproxy-dashboard.yaml
  exposures/mobiproxy-dashboard.yaml
Labels: Done

#6472 Create freepbx-administration-panel.yaml
  exposed-panels/freepbx-administration-panel.yaml
Labels: Done

#6458 optimizely admin panel detection
  exposed-panels/episerver-panel.yaml
Labels: Done

#6477 ImpressPages installation wizard
  misconfiguration/installer/impresspages-installer.yaml
Labels: Done

#6478 OrangeHrm Installer
  misconfiguration/installer/orangehrm-installer.yaml
Labels: Done

#6489 Create monstra-installer.yaml
  misconfiguration/installer/monstra-installer.yaml
Labels: Done

#6490 Updating old-copyright.yaml for 2023
  miscellaneous/old-copyright.yaml
Labels: good first issue, Done

#6496 update matcher
  exposures/configs/zend-config-file.yaml
Labels: Done

#6483 Create CVE-2022-44877.yaml
  cves/2022/CVE-2022-44877.yaml
Labels: Done

#6492 Create CVE-2018-11473.yaml
  cves/2018/CVE-2018-11473.yaml
Labels: Done

#6493 Create CVE-2018-11227.yaml
  cves/2018/CVE-2018-11227.yaml
Labels: Done

#6491 Create default-cakephp-page.yaml
  technologies/default-cakephp-page.yaml
Labels: Done

#6484 Create phpcli-stack-trace.yaml
  misconfiguration/phpcli-stack-trace.yaml
Labels: Done

#6421 Sni Addition
  vulnerabilities/amazon/amazon-ec2-ssrf.yaml
  vulnerabilities/other/digital-ocean-ssrf.yaml
Labels: Done

#6464 Add StackHawk API key exposure
  file/keys/stackhawk-api-key.yaml
Labels: good first issue, Done

#6471 Adding template for EmpireC2 default api login
  .new-additions
  cves/2020/CVE-2020-11110.yaml
  cves/2022/CVE-2022-45917.yaml
  default-logins/empire/empirec2-default-login.yaml
Labels: Done

#6502 Create CVE-2022-0234.yaml
  cves/2022/CVE-2022-0234.yaml
Labels: Done

#6488 Added HashiCorp Consul / Enterprise - Server Side Request Forgery
  cves/2022/CVE-2022-29153.yaml
Labels: Done

#6506 Tengine Default Page
  technologies/default-tengine-page.yaml
Labels: Done

#6505 Symfony Default Page
  technologies/default-symfony-page.yaml
Labels: Done

#6508 Create dash-panel-detect.yaml
  technologies/dash-panel-detect.yaml
Labels: Done

#6509 Create ovpn-config-exposed.yaml
  exposures/configs/ovpn-config-exposed.yaml
Labels: Done

#6497 PMM Installation Wizard
  misconfiguration/installer/pmm-installer.yaml
Labels: Done

#6521 Ntop Detect
  technologies/ntop-detect.yaml
Labels: Done

#6524 Citrix Hypervisor Page Detection
  technologies/citrix-hypervisor-page.yaml
Labels: Done

#6520 Create ldap-account-manager-panel.yaml
  exposed-panels/ldap-account-manager-panel.yaml
Labels: Done

#6384 Modoboa Login Panel & Storybook Login Panel - Detect
  exposed-panels/modoboa-panel.yaml
  exposed-panels/storybook-panel.yaml
Labels: Done

#6522 RunCloud Default Page
  technologies/default-runcloud-page.yaml
Labels: Done

#6169 Create webdav-exposed.yaml
  misconfiguration/webdav-enabled.yaml
Labels: Done

#6528 Create api-ipdata.yaml
  token-spray/api-ipdata.yaml
Labels: Done

#6530 Create springboot-eureka.yaml
  misconfiguration/springboot/spring-eureka.yaml
Labels: Done

#6512 Update apache-solr-log4j-rce.yaml
  vulnerabilities/apache/apache-solr-log4j-rce.yaml
Labels: Done

#6511 Update elasticsearch5-log4j-rce.yaml
  vulnerabilities/other/elasticsearch5-log4j-rce.yaml
Labels: Done

#6539 Added template for ntopng-traffic-dashboard
  misconfiguration/ntopng-traffic-dashboard.yaml
Labels: Done

#6304 Fix matched OS version information
  network/detection/rdp-detect.yaml
Labels: Done

#6547 added waf bypass html payload
  misconfiguration/aem/aem-childrenlist-xss.yaml
Labels: Done

#6548 Create saltgui-panel.yaml
  exposed-panels/saltgui-panel.yaml
Labels: Done

#6553 Xerox Workcentre Detect
  technologies/xerox-workcentre-detect.yaml
Labels: Done

#6552 Create froxlor-database-backup-file.yaml
  exposures/backups/froxlor-database-backup.yaml
Labels: Done

#6517 Create snapdrop-detect.yaml
  iot/snapdrop-detect.yaml
Labels: Done

#6519 Update kafka-manager-panel.yaml
  misconfiguration/apache/kafka-manager-unauth.yaml
Labels: Done

#6518 Create sap-successfactors-detect.yaml
  exposed-panels/sap-successfactors-detect.yaml
Labels: Done

#6231 Updated openapi template
  exposures/apis/openapi.yaml
Labels: good first issue, Done

#6495 updated for case sensitive matcher
  miscellaneous/dir-listing.yaml
Labels: Done

#6555 Create kafka-manager-panel.yaml
  technologies/apache/kafka-manager-panel.yaml
Labels: Done

#6525 fix: fix false positive on nagios default
  default-logins/nagios/nagios-default-login.yaml
Labels: Done

#6551 Create CVE-2022-28117.yaml
  cves/2022/CVE-2022-28117.yaml
Labels: Done

#6516 Create ldap-account-manager.yaml
  misconfiguration/unauth-ldap-account-manager.yaml
Labels: Done

#6507 Create aws-secret-key.yaml
  exposures/tokens/amazon/aws-access-secret-key.yaml
Labels: Done

#6540 Create CVE-2017-11165.yaml
  cves/2017/CVE-2017-11165.yaml
Labels: Done

#6556 Update and rename exposures/mobiproxy-dashboard.yaml to exposures/mis…
  exposures/misconfiguration/mobiproxy-dashboard.yaml
Labels: Done

#6534 Added template for CVE-2022-36537
  cves/2022/CVE-2022-36537.yaml
Labels: Done

#6557 Fixed text error
  cves/2021/CVE-2021-42258.yaml
  exposed-panels/axigen-webadmin.yaml
Labels: Done

#6523 Create CVE-2008-3273.yaml
  cves/2010/CVE-2010-1429.yaml
Labels: Done

#6554 Create froxlor-reflected-xss.yaml
  vulnerabilities/froxlor-xss.yaml
Labels: Done

#6558 update severity
  exposures/backups/froxlor-database-backup.yaml
Labels: Done

#6546 Added template mylittleadmin-panel
  exposed-panels/mylittleadmin-panel.yaml
Labels: Done

#6501 Create CVE-2020-23697.yaml
  cves/2020/CVE-2020-23697.yaml
Labels: Done

#6510 Add template for SAP Analytics Cloud
  exposed-panels/sap-cloud-analytics.yaml
Labels: Done

#6561 Create rsshub-detect.yaml
  technologies/rsshub-detect.yaml
Labels: Done

#6563 Create machform-admin-panel.yaml
  exposed-panels/machform-admin-panel.yaml
Labels: Done

#6564 Create CVE-2022-47966.yaml
  cves/2022/CVE-2022-47966.yaml
Labels: Status: Completed, Done

#6568 Create tooljet-panel.yaml
  exposed-panels/tooljet-panel.yaml
Labels: Done

#6566 Update CVE-2017-5638.yaml
  cves/2017/CVE-2017-5638.yaml
Labels: Done

#6498 Update fingerprint of openEuler
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#6567 add template mylittlebackup-panel
  exposed-panels/mylittlebackup-panel.yaml
Labels: Done

#6571 Create CVE-2022-21587.yaml
  cves/2022/CVE-2022-21587.yaml
Labels: Status: Completed, Done

#6572 Create CVE-2022-1168.yaml
  cves/2022/CVE-2022-1168.yaml
Labels: Done

#6576 Add Hunchentoot httpd
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#6581 Add support to detect Tornado
  technologies/tech-detect.yaml
Labels: Done

#6590 Create sound4-disclosure2.yaml
  ‎‎misconfiguration/sound4-directory-listing.yaml
Labels: Done

#6584 Create CVE-2019-15501
  cves/2019/CVE-2019-15501.yaml
Labels: Done

#6578 Add detection support for uvicorn
  technologies/tech-detect.yaml
Labels: Done

#6592 Revert "Add detection support for uvicorn"
  technologies/tech-detect.yaml
Labels: Done

#6582 Added sqlbuddy-panel Template
  exposed-panels/sqlbuddy-panel.yaml
Labels: Done

#6591 Create esphome-dashboard.yaml
  misconfiguration/esphome-dashboard.yaml
Labels: Done

#6587 Create tikiwiki-xss.yaml
  vulnerabilities/other/tikiwiki-xss.yaml
Labels: Done

#6580 Add support to detect ESPHome
  exposed-panels/esphome-panel.yaml
Labels: Done

#6585 Create alms-xss
  vulnerabilities/other/academy-lms-xss.yaml
Labels: Done

#6583 Create CVE-2022-39195.yaml
  cves/2022/CVE-2022-39195.yaml
Labels: Done

#6579 Support for detecting Connect Box devices
  exposed-panels/connect-box-login.yaml
Labels: Done

#6586 Create slims-xss.yaml
  vulnerabilities/other/slims-xss.yaml
Labels: Done

#6422 Deep link issue in android
  file/android/deep-link-detect.yaml
Labels: Done

#6606 trailing space fixed
  exposed-panels/unauthenticated-frp.yaml
  misconfiguration/openbmcs/openbmcs-ssrf.yaml
  vulnerabilities/wordpress/wp-grimag-open-redirect.yaml
Labels: Status: Completed, Done

#6605 moved to misconfiguration
  misconfiguration/sound4-directory-listing.yaml
Labels: Status: Completed, Done

#6607 Dork -> Query Fix
  cves/2017/CVE-2017-10075.yaml
  cves/2022/CVE-2022-0234.yaml
  cves/2022/CVE-2022-1168.yaml
  cves/2022/CVE-2022-1442.yaml
  cves/2022/CVE-2022-25356.yaml
  cves/2022/CVE-2022-26263.yaml
  cves/2022/CVE-2022-33965.yaml
  cves/2022/CVE-2022-3484.yaml
  exposed-panels/aerohive-netconfig-ui.yaml
  exposed-panels/claris-filemaker-webdirect.yaml
  exposed-panels/code-server-login.yaml
  exposed-panels/looker-panel.yaml
  exposed-panels/novnc-login-panel.yaml
  exposed-panels/sap-successfactors-detect.yaml
  exposed-panels/vmware-cloud-director.yaml
  exposed-panels/xds-amr-status.yaml
  exposures/backups/froxlor-database-backup.yaml
  iot/snapdrop-detect.yaml
  misconfiguration/unauth-ldap-account-manager.yaml
  technologies/dash-panel-detect.yaml
  technologies/default-parallels-plesk.yaml
  technologies/gitbook-detect.yaml
  technologies/joomla-detect.yaml
  technologies/puppet-node-manager-detect.yaml
  technologies/vbulletin-detect.yaml
  vulnerabilities/froxlor-xss.yaml
Labels: Done

#6610 TeamSpeak 3 ServerQuery Detection
  network/detection/teamspeak3-detect
Labels: Done

#6612 SaltStack Config Panel
  exposed-panels/saltstack-config-panel.yaml
Labels: Done

#6617 Added default-lighttpd-placeholder-page.yaml
  technologies/default-lighttpd-placeholder-page.yaml
Labels: Done

#6604 Create webalizer-script-logs.yaml
  misconfiguration/webalizer-statistics.yaml
Labels: Done

#6619 Create nagiosxi-installer.yaml
  misconfiguration/installer/nagiosxi-installer.yaml
Labels: Done

#6533 Added template for headless-open-redirect
  headless/headless-open-redirect.yaml
Labels: Done

#6601 Create pendinginstallvzw-web-configuration.yaml
  exposures/configs/cypress-web-config.yaml
Labels: Done

#6600 Create rethinkdb-administration-console.yaml
  misconfiguration/rethinkdb-admin-console.yaml
Labels: Done

#6596 Create pulsar-admin-detect.yaml
  exposed-panels/pulsar360-admin-panel.yaml
Labels: Done

#6620 Create pulsar-adminui-panel.yaml
  exposed-panels/pulsar-adminui-panel.yaml
Labels: Done

#6599 Create completeview-web-client.yaml
  exposed-panels/completeview-web-panel.yaml
Labels: Done

#5558 Create exposed-file-upload-form.yaml
  miscellaneous/exposed-file-upload-form.yaml
Labels: Done

#6595 Fix 'Apusic' not distinguish between uppercase and lowercase letters
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#6594 Create CVE-2022-32429.yaml
  cves/2022/CVE-2022-32429.yaml
Labels: Done

#5857 Added New Exposed Panel FortiOS Management Interface Login Template
  exposed-panels/fortinet/fortios-management-panel.yaml
Labels: good first issue, Done

#6603 Fixed 8 templates in misconfiguration/proxy/ - added newlines at the end of raw requests
  misconfiguration/proxy/metadata-aws.yaml
  misconfiguration/proxy/metadata-azure.yaml
  misconfiguration/proxy/metadata-digitalocean.yaml
  misconfiguration/proxy/metadata-google.yaml
  misconfiguration/proxy/metadata-hetzner.yaml
  misconfiguration/proxy/metadata-openstack.yaml
  misconfiguration/proxy/metadata-oracle.yaml
  misconfiguration/proxy/open-proxy-internal.yaml
Labels: Done

#5643 Create CVE-2017-1000163.yaml
  cves/2017/CVE-2017-1000163.yaml
Labels: Done

#6609 Add support to detect Syncthing panels
  misconfiguration/syncthing-dashboard.yaml
Labels: Done

#6618 Add Nemlio API Docs Detection to Swagger Template
  exposures/apis/swagger-api.yaml
Labels: Done

#6623 Enhance swagger ui shodan-query- Update
  exposures/apis/swagger-api.yaml
Labels: Done

#6611 Support to detect myStrom plugs
  exposed-panels/mystrom-panel.yaml
Labels: Done

#6631 Fix - azure-takeover-detection.yaml
  dns/azure-takeover-detection.yaml
Labels: Done

#6628 Create accueil-wampserver.yaml
  exposures/configs/accueil-wampserver.yaml
Labels: Done

#6627 Create redis-enterprise-detect.yaml
  exposed-panels/redis-enterprise-panel.yaml
Labels: Done

#6630 Fix - exposed-panels/server-backup-manager-se.yaml
  exposed-panels/server-backup-manager-se.yaml
Labels: Done

#6638 ExaGrid Manager Panel
  exposed-panels/exagrid-manager-panel.yaml
Labels: Done

#6634 Create connectwise-control-detect
  technologies/connectwise-control-detect.yaml
Labels: Done

#6640 EWM Manager Panel
  exposed-panels/ewm-manager-panel.yaml
Labels: Done

#6626 Add Weblate
  technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#6629 Create setup-github-enterprise.yaml
  misconfiguration/setup-github-enterprise.yaml
Labels: Done

#6643 Support to detect Transmission webinterfaces
  misconfiguration/transmission-dashboard.yaml
Labels: Done

#6644 Support to detect OpenHAB instance
  technologies/openhap-detect.yaml
Labels: Done

#6646 Unauthenticated Axyom Network Manager
  misconfiguration/unauth-axyom-network-manager.yaml
Labels: Done

#6647 SevOne NMS Network Manager
  exposed-panels/sevone-nms-network-manager.yaml
Labels: Done

#6652 Update webeditors.yaml
  exposed-panels/webeditors.yaml
Labels: Done

#6616 Add support to detect Ulanzi clocks
  iot/ulanzi-clock.yaml
Labels: Done
