Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-11, with the labels that each got.

#8511 FN Fix - Phpmyadmin Default Login
  http/default-logins/phpmyadmin/phpmyadmin-default-login.yaml
Labels: Done

#8512 Create webtrees-install.yaml
  http/misconfiguration/installer/webtrees-install.yaml
Labels: Done

#8513 Create webcalendar-install.yaml
  http/misconfiguration/installer/webcalendar-install.yaml
Labels: Done

#8514 Create orangescrum-install.yaml
  http/misconfiguration/installer/orangescrum-install.yaml
Labels: Done

#8472 CVE-2023-4547
  http/cves/2023/CVE-2023-4547.yaml
Labels: Hacktoberfest, Done

#8505 Create CVE-2023-4415.yaml
  http/cves/2023/CVE-2023-4169.yaml
Labels: Hacktoberfest, Done

#8519 Add template to detect ServiceNow login panel
  http/exposed-panels/servicenow-panel.yaml
Labels: Done

#8517 Create ruckus-smartzone-install.yaml
  http/misconfiguration/installer/ruckus-smartzone-install.yaml
Labels: Done

#8516 Create ruckus-unleashed-install.yaml
  http/misconfiguration/installer/ruckus-unleashed-install.yaml
Labels: Done

#8522 Added CVE-2023-43795 (GeoServer WPS - Server Side Request Forgery) 🔥
  http/cves/2023/CVE-2023-43795.yaml
Labels: Done

#8528 Added CVE-2023-22518 (Atlassian Confluence Server - Improper Authorization)
  http/cves/2023/CVE-2023-22518.yaml
Labels: Done

#8531 Updated CVE-2023-22518
  http/cves/2023/CVE-2023-22518.yaml
Labels: Done

#8506 Create CVE-2023-33629.yaml
  http/cves/2023/CVE-2023-33629.yaml
Labels: Hacktoberfest, Done

#8534 Update backdoor templates path
  http/vulnerabilities/backdoor/antsword-backdoor.yaml
  http/vulnerabilities/backdoor/fatpipe-backdoor.yaml
  http/vulnerabilities/backdoor/kevinlab-bems-backdoor.yaml
  http/vulnerabilities/backdoor/kevinlab-hems-backdoor.yaml
  http/vulnerabilities/backdoor/maccmsv10-backdoor.yaml
  http/vulnerabilities/backdoor/php-zerodium-backdoor-rce.yaml
Labels: Done

#8509 Fix FP ecology-oa-file-sqli.yaml
  http/vulnerabilities/other/ecology-oa-file-sqli.yaml
Labels: Hacktoberfest, Done

#8536 Create sugarcrm-install.yaml
  http/misconfiguration/installer/sugarcrm-install.yaml
Labels: Done

#8526 searchreplacedb2 exposure
  http/misconfiguration/searchreplacedb2-exposure.yaml
Labels: Done

#8539 Create hostinger.txt
  helpers/wordpress/plugins/hostinger.txt
Labels: Done

#8538 Office Web Apps Server Full Read - Server Side Request Forgery 🔥 & Login Panel
  http/exposed-panels/office-webapps-panel.yaml
  http/vulnerabilities/microsoft/office-webapps-ssrf.yaml
Labels: Done

#8547 fixed FP in CVE-2021-28164
  http/cves/2021/CVE-2021-28164.yaml
Labels: Done

#8555 Updated processmaker-lfi
  http/vulnerabilities/other/processmaker-lfi.yaml
Labels: Done

#8535 Less history
  http/misconfiguration/less-history.yaml
Labels: Done

#8557 Create fusionauth-admin-panel.yaml
  http/exposed-panels/fusionauth-admin-panel.yaml
Labels: Done

#8556 Create fusionauth-admin-setup.yaml
  http/misconfiguration/fusionauth-admin-setup.yaml
Labels: Done

#8554 Update CVE-2021-30151.yaml
  http/cves/2021/CVE-2021-30151.yaml
Labels: Done

#8559 Create untangle-admin-setup.yaml
  http/misconfiguration/untangle-admin-setup.yaml
Labels: Done

#7268 Add detection and default login of Dell Remote Power Management unit.
  default-logins/dell/dell-remote-power-management-default-login.yaml
  technologies/dell/dell-dpi-panel.yaml
Labels: Done

#8550 Create CVE-2023-34020.yaml
  http/cves/2023/CVE-2023-34020.yaml
Labels: Done

#8537 Create homer-panel.yaml
  http/exposed-panels/homer-panel.yaml
Labels: Done

#8118 CVE-2023-4596
  http/cves/2023/CVE-2023-40068.yaml
Labels: Done

#8544 Added header detection for Adobe Experience Manager in web fingerprint template
  http/technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#8533 DB command history (currently: MySQL)
  http/misconfiguration/mysql-history.yaml
Labels: Done

#8548 Added hikvision-js-Files-upload
  http/vulnerabilities/hikvision/hikvision-js-files-upload.yaml
Labels: good first issue, Done

#8540 Update quasar-rat-c2.yaml
  ssl/c2/quasar-rat-c2.yaml
Labels: good first issue, Done

#8562 Update hikvision-js-files-upload.yaml
  http/vulnerabilities/hikvision/hikvision-js-files-upload.yaml
Labels: Done

#8564 Fix shadowd WAF fingerprint
  http/fuzzing/waf-fuzz.yaml
  http/technologies/waf-detect.yaml
Labels: Done

#8565 misc fixes
  http/cves/2021/CVE-2021-28164.yaml
Labels: Done

#8476 CVE-2023-4911 Looney Tunables Linux Local Privesc
  code/cves/CVE-2023-4911.yaml
Labels: Done

#8568 Rename code/cves/CVE-2023-4911.yaml to code/cves/2023/CVE-2023-4911.yaml
  code/cves/2023/CVE-2023-4911.yaml
Labels: Done

#8560 Create CVE-2023-1719.yaml (Bitrix Component XSS via 'log_cnt' 🔥 )
  http/cves/2023/CVE-2023-1719.yaml
Labels: Done

#8529 Added Apache ActiveMQ CVE-2023-46604 RCE
  network/cves/2023/CVE-2023-46604.yaml
Labels: Done

#8569 Fix description for docker-hub-login-check
  http/credential-stuffing/cloud/docker-hub-login-check.yaml
Labels: Done

#8561 Extracting the app_name from manage.py to know where to look for settings.py
  http/exposures/files/django-secret-key.yaml
Labels: Done

#8573 Create CVE-2022-35653.yaml (Moodle LTI module Reflected - Cross-Site Scripting) 🔥
  http/cves/2022/CVE-2022-35653.yaml
Labels: Done

#8572 Update yii-debugger.yaml
  http/exposures/configs/yii-debugger.yaml
Labels: good first issue, Done

#8579 Create librespeed-panel.yaml
  http/exposed-panels/librespeed-panel.yaml
Labels: Done

#8580 Create rdweb-detect.yaml
  http/exposed-panels/rdweb-panel.yaml
Labels: Done

#8583 Update rdweb-panel.yaml
  http/exposed-panels/rdweb-panel.yaml
Labels: Done

#8582 Updated .yamllint
  .yamllint
Labels: Done

#8585 Create tautulli-unauth.yaml
  http/exposed-panels/unauth/tautulli-unauth.yaml
Labels: Done

#8587 Create librephotos-panel.yaml
  http/exposed-panels/librephotos-panel.yaml
Labels: Done

#8586 Create imprivata-installer.yaml
  http/misconfiguration/installer/imprivata-installer.yaml
Labels: Done

#8571 ( CVE-2020-24701) OX Appsuite - Cross-Site Scripting & Login Panel 🔥
  http/cves/2020/CVE-2020-24701.yaml
  http/exposed-panels/appsuite-panel.yaml
Labels: Done

#8577 Update CVE-2021-28164.yaml fix typo
  http/cves/2021/CVE-2021-28164.yaml
Labels: Done

#8592 Depre protocol fix
  http/default-logins/goip-default-login.yaml
  http/vulnerabilities/other/podcast-generator-ssrf.yaml
Labels: Done

#8567 Honeypot Templates by UnaPibaGeek 🔥
  http/honeypot/citrix-honeypot-detect.yaml
  http/honeypot/dionaea-http-honeypot-detect.yaml
  http/honeypot/elasticpot-honeypot-detect.yaml
  http/honeypot/snare-honeypot-detect.yaml
  network/honeypot/adbhoney-honeypot-cnxn-detect.yaml
  network/honeypot/adbhoney-honeypot-shell-detect.yaml
  network/honeypot/conpot-siemens-honeypot-detect.yaml
  network/honeypot/cowrie-ssh-honeypot-detect.yaml
  network/honeypot/dionaea-ftp-honeypot-detect.yaml
  network/honeypot/dionaea-mqtt-honeypot-detect.yaml
  network/honeypot/dionaea-mysql-honeypot-detect.yaml
  network/honeypot/dionaea-smb-honeypot-detect.yaml
  network/honeypot/gaspot-honeypot-detect.yaml
  network/honeypot/mailoney-honeypot-detect.yaml
  network/honeypot/redis-honeypot-detect.yaml
Labels: Priority: High, Done

#8581 Create ssh-password-auth.yaml
  javascript/enumeration/ssh-password-auth.yaml
Labels: Done

#8382 CVE-2021-45382
  http/cves/2021/CVE-2021-45382.yaml
Labels: Hacktoberfest, Done

#8602 GameOver(lay) - Local Privilege Escalation in Ubuntu Kernel 🔥
  code/cves/2023/CVE-2023-32629.yaml
Labels: Done

#8578 Added Apache Tomcat Stack Trace Detection Template
  http/misconfiguration/tomcat-stacktraces.yaml
Labels: Done

#8604 SSH Server CBC Mode Ciphers Enabled
  javascript/enumeration/ssh-cbc-mode-ciphers.yaml
Labels: Done

#8603 SSH Weak Key Exchange Algorithms Enabled
  javascript/enumeration/ssh-weakkey-exchange-algo.yaml
Labels: Done

#8612 Create php-cs-cache.yaml
  http/exposures/files/php-cs-cache.yaml
Labels: Done

#8621 Create azuredeploy-json.yaml
  http/exposures/files/azuredeploy-json.yaml
Labels: Done

#8597 add : add validation to cve 2021-28164 template
  http/cves/2021/CVE-2021-28164.yaml
Labels: good first issue, Done

#8618 Update tech-detect.yaml - add interactsh
  http/technologies/tech-detect.yaml
Labels: good first issue, Done

#8321 CVE-2021-35395
  http/cves/2021/CVE-2021-35395.yaml
Labels: Hacktoberfest, Done

#8625 Added Template for CVE-2023-47246 (SysAid Server - Remote Code Execution)
  http/cves/2023/CVE-2023-47246.yaml
Labels: Done

#8623 Create phinx-config.yaml
  http/exposures/configs/phinx-config.yaml
Labels: Done

#8607 SSH Host Keys < 2048 Bits Considered Weak
  javascript/enumeration/ssh-weak-public-key.yaml
Labels: Done

#8617 SSH Weak Algorithms Supported
  javascript/enumeration/ssh-weak-algo-supported.yaml
Labels: Done

#8626 Create auth-json.yaml
  http/exposures/files/auth-json.yaml
Labels: Done

#8620 WS_FTP Ad Hoc - Panel Detect
  http/exposed-panels/adhoc-transfer-panel.yaml
Labels: Done

#8627 Update worksites-takeover.yaml
  http/takeovers/worksites-takeover.yaml
Labels: Done

#8630 aws-sftp-detect
  network/detection/aws-sftp-detect.yaml
Labels: Done

#8624 Create jsconfig-json.yaml
  http/exposures/configs/jsconfig-json.yaml
Labels: Done

#8622 Create node-express-status.yaml
  http/misconfiguration/node-express-status.yaml
Labels: Done

#8614 Create CVE-2021-33690.yaml (SAP NetWeaver Development Infrastructure - SSRF) 🔥
  http/cves/2021/CVE-2021-33690.yaml
Labels: Done

#8606 Create apdisk-disclosure.yaml
  http/exposures/files/apdisk-disclosure.yaml
Labels: Done

#8594 Add template to detect user enumeration in Microsoft Exchange due to a misconfiguration.
  http/misconfiguration/ms-exchange-user-enum.yaml
Labels: Done

#8588 Add template to detect the MDM silverback
  http/technologies/silverback-detect.yaml
Labels: Done

#8633 Create CVE-2022-1170.yaml
  http/cves/2022/CVE-2022-1170.yaml
Labels: Done

#8638 Create vite-config.yaml
  http/exposures/configs/vite-config.yaml
Labels: Done

#8610 Fix false negatives and typos in Redis CVE-2022-0543.yaml and exposed…
  network/cves/2022/CVE-2022-0543.yaml
  network/exposures/exposed-redis.yaml
Labels: Done

#8641 Update and rename CVE-2023-32629.yaml to CVE-2023-2640.yaml
  code/cves/2023/CVE-2023-2640.yaml
Labels: Done

#8640 Rename CVE-2023-40068.yaml to CVE-2023-4596.yaml
  http/cves/2023/CVE-2023-4596.yaml
Labels: Done

#8637 fix fp CVE-2021-21234.yaml
  http/cves/2021/CVE-2021-21234.yaml
Labels: Done

#8649 Update CVE-2023-4966.yaml
  http/cves/2023/CVE-2023-4966.yaml
Labels: Done

#8631 Create moveit-sftp-detect.yaml
  network/detection/moveit-sftp-detect.yaml
Labels: Done

#8634 Update FN CVE-2022-0864.yaml
  http/cves/2022/CVE-2022-0864.yaml
Labels: Done

#8643 Log4j fix
  http/vulnerabilities/apache/apache-ofbiz-log4j-rce.yaml
  http/vulnerabilities/apache/apache-solr-log4j-rce.yaml
  http/vulnerabilities/apache/log4j/jamf-pro-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-cloudcenter-suite-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-unified-communications-log4j.yaml
  http/vulnerabilities/cisco/cisco-vmanage-log4j.yaml
  http/vulnerabilities/code42/code42-log4j-rce.yaml
  http/vulnerabilities/jamf/jamf-log4j-jndi-rce.yaml
  http/vulnerabilities/mobileiron/mobileiron-log4j-jndi-rce.yaml
  http/vulnerabilities/other/elasticsearch5-log4j-rce.yaml
  http/vulnerabilities/other/f-secure-policymanager-log4j-rce.yaml
  http/vulnerabilities/other/fortiportal-log4j-rce.yaml
  http/vulnerabilities/other/goanywhere-mft-log4j-rce.yaml
  http/vulnerabilities/other/graylog-log4j.yaml
  http/vulnerabilities/other/jitsi-meet-log4j-rce.yaml
  http/vulnerabilities/other/logstash-log4j-rce.yaml
  http/vulnerabilities/other/metabase-log4j.yaml
  http/vulnerabilities/other/opennms-log4j-jndi-rce.yaml
  http/vulnerabilities/other/pega-log4j-rce.yaml
  http/vulnerabilities/other/rundeck-log4j.yaml
  http/vulnerabilities/other/sonicwall-nsm-log4j-rce.yaml
  http/vulnerabilities/other/splunk-enterprise-log4j-rce.yaml
  http/vulnerabilities/other/unifi-network-log4j-rce.yaml
  http/vulnerabilities/other/vmware-siterecovery-log4j-rce.yaml
  http/vulnerabilities/other/xenmobile-server-log4j.yaml
  http/vulnerabilities/springboot/springboot-log4j-rce.yaml
  http/vulnerabilities/vmware/vmware-hcx-log4j.yaml
  http/vulnerabilities/vmware/vmware-nsx-log4j.yaml
  http/vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
  http/vulnerabilities/vmware/vrealize-operations-log4j-rce.yaml
Labels: Done

#8576 AWS service detection template
  http/technologies/aws/aws-detect.yaml
Labels: Done

#8645 Updated the vulnerability for the CVE-2023-22515
  http/cves/2023/CVE-2023-22515.yaml
Labels: good first issue, Done

#8644 Grafana login path update
  http/exposed-panels/grafana-detect.yaml
Labels: Done

#8642 XXL-JOB executor - Unauthorized Access
  http/vulnerabilities/other/xxljob-executor-unauth.yaml
Labels: Done

#8498 Create CVE-2016-8706
  javascript/cves/2016/CVE-2016-8706.yaml
Labels: Done

#8658 Create CVE-2023-5375.yaml
  http/cves/2023/CVE-2023-5375.yaml
Labels: Done

#8661 Fixed FP - editor-exposure
  http/exposures/configs/editor-exposure.yaml
Labels: Done

#8656 Create mosparo-install.yaml
  http/misconfiguration/installer/mosparo-install.yaml
Labels: Done

#8660 Fixed FP - kubernetes-etcd-keys
  http/exposures/files/kubernetes-etcd-keys.yaml
Labels: Done

#8662 Update wildcard-postmessage.yaml
  http/misconfiguration/wildcard-postmessage.yaml
Labels: Done

#8655 Update sangfor-sysuser-conf.yaml (Issue 8615)
  http/vulnerabilities/other/sangfor-sysuser-conf.yaml
Labels: Done

#8667 Fixed - Tableau server build extraction regex
  http/technologies/tableau-server-detect.yaml
Labels: Done

#8668 Fix Redis Detection (redis-detect.yaml)
  network/detection/redis-detect.yaml
Labels: Done

#8664 Create structurizr-default-login.yaml
  http/default-logins/structurizr/structurizr-default-login.yaml
Labels: Done

#8682 CVE 2018 25031 - Swagger Payload
  helpers/payloads/CVE-2018-25031.js
  helpers/payloads/swagger-payload.yaml
Labels: Done

#8670 Create CVE-2023-39796.yaml
  http/cves/2023/CVE-2023-39796.yaml
Labels: Done

#8659 Fixed FP - CVE-2021-40149
  http/cves/2021/CVE-2021-40149.yaml
Labels: Done

#8648 FIX CVE-2023-0600.yaml
  http/cves/2023/CVE-2023-0600.yaml
Labels: good first issue, Done

#8686 Rename swagger-payload.yaml to swagger-payload
  helpers/payloads/swagger-payload
Labels: Done

#8665 Create structurizr-panel.yaml
  http/exposed-panels/structurizr-panel.yaml
Labels: Done

#8446 Update CVE-2018-18778.yaml
  http/cves/2018/CVE-2018-18778.yaml
Labels: Hacktoberfest, Done

#8676 Update CVE-2022-29303.yaml
  http/cves/2022/CVE-2022-29303.yaml
Labels: Done

#8654 fix(template): Improve joomla-com-booking-component.yaml rules.
  http/vulnerabilities/joomla/joomla-com-booking-component.yaml
Labels: Done

#8690 Create CVE-2023-26347.yaml (Adobe Coldfusion - Authentication Bypass) 🔥
  http/cves/2023/CVE-2023-26347.yaml
Labels: Done

#8684 Create CVE-2023-49103.yaml
  http/cves/2023/CVE-2023-49103.yaml
Labels: Done

#8680 Fixed argocd detection template
  http/exposed-panels/argocd-login.yaml
Labels: Done

#8692 FP SMB Enum - Fix
  javascript/enumeration/smb-enum.yaml
Labels: Done

#8687 Create CVE-2023-30258.yaml
  http/cves/2023/CVE-2023-30258.yaml
Labels: Done

#8698 Create clever-takeover.yaml
  http/takeovers/clever-takeover.yaml
Labels: Done

#8663 fix oast fp CVE-2014-4210.yaml
  http/cves/2014/CVE-2014-4210.yaml
Labels: Done

#8713 SSH Wordlists
  helpers/wordlists/ssh-passwords.txt
  helpers/wordlists/ssh-users.txt
Labels: Done

#8693 Afterlogic templates - CVE's and Panel
  http/cves/2021/CVE-2021-26292.yaml
  http/cves/2021/CVE-2021-26294.yaml
  http/exposed-panels/afterlogic-webmail-login.yaml
Labels: Done

#8709 Update crush-ftp-login.yaml
  http/exposed-panels/crush-ftp-login.yaml
Labels: Done

#8704 Add template to detect 4D technology
  http/technologies/4D-detect.yaml
Labels: Done

#8724 Endpoint Update CVE-2023-49103
  http/cves/2023/CVE-2023-49103.yaml
Labels: Done
