Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-06, with the labels that each got.

#7336 Updated springboot-heapdump
  http/misconfiguration/springboot/springboot-heapdump.yaml
Labels: Done

#7337 release prep
  http/misconfiguration/aem/aem-secrets.yaml
  http/misconfiguration/ibm-websphere-xml.yaml
Labels: Done

#7333 CVE-2023-27482: Authentication Bypass in Home Assistant 🔥
  http/cves/2023/CVE-2023-27482.yaml
Labels: Done

#7334 CVE-2023-32315 [Administration Console authentication bypass in Openf…
  http/cves/2023/CVE-2023-32315.yaml
Labels: Done

#7341 Update metadata
  http/cves/2021/CVE-2021-37305.yaml
  http/exposed-panels/eclipse-birt-panel.yaml
  http/exposed-panels/jedox-web-panel.yaml
  http/exposed-panels/repetier-server-panel.yaml
  http/exposures/apis/jeecg-boot-swagger.yaml
  http/misconfiguration/teslamate-unauth-access.yaml
  http/vulnerabilities/avtech/avtech-auth-bypass.yaml
  http/vulnerabilities/avtech/avtech-dvr-ssrf.yaml
  http/vulnerabilities/avtech/avtech-unauth-file-download.yaml
  http/vulnerabilities/avtech/avtech-verification-bypass.yaml
  http/vulnerabilities/weaver/ecology/ecology-mysql-config.yaml
  network/cves/2016/CVE-2016-3510.yaml
Labels: Done

#7342 Create CVE-2023-1362.yaml
  http/cves/2023/CVE-2023-1362.yaml
Labels: Done

#7343 MOVEit Transfer Template Update
  http/technologies/moveit-transfer-detect.yaml
Labels: good first issue, Done

#7355 CVEs added
  http/cves/2021/CVE-2021-24731.yaml
  http/cves/2021/CVE-2021-27124.yaml
  http/cves/2021/CVE-2021-40908.yaml
  http/cves/2021/CVE-2021-40968.yaml
  http/cves/2021/CVE-2021-40969.yaml
  http/cves/2021/CVE-2021-40970.yaml
  http/cves/2021/CVE-2021-40971.yaml
  http/cves/2021/CVE-2021-40972.yaml
  http/cves/2021/CVE-2021-40973.yaml
  http/cves/2021/CVE-2021-43725.yaml
  http/cves/2022/CVE-2022-28022.yaml
  http/cves/2022/CVE-2022-28023.yaml
  http/cves/2022/CVE-2022-31879.yaml
  http/cves/2022/CVE-2022-31974.yaml
  http/cves/2022/CVE-2022-31975.yaml
  http/cves/2022/CVE-2022-31976.yaml
  http/cves/2022/CVE-2022-31977.yaml
  http/cves/2022/CVE-2022-31978.yaml
  http/cves/2022/CVE-2022-31980.yaml
  http/cves/2022/CVE-2022-31981.yaml
  http/cves/2022/CVE-2022-31982.yaml
  http/cves/2022/CVE-2022-31983.yaml
  http/cves/2022/CVE-2022-31984.yaml
  http/cves/2023/CVE-2023-0948.yaml
  http/cves/2023/CVE-2023-2122.yaml
  http/cves/2023/CVE-2023-2130.yaml
  http/cves/2023/CVE-2023-29622.yaml
  http/cves/2023/CVE-2023-29623.yaml
  http/exposed-panels/spotweb-login-panel.yaml
Labels: Done

#7308 fix vmware-vcenter-ssrf-false positive
  http/vulnerabilities/vmware/vmware-vcenter-ssrf.yaml
Labels: Done

#7354 Fix CVE-2021-43798.yaml false positive
  http/cves/2021/CVE-2021-43798.yaml
Labels: Done

#7357 updated protocol name
  http/credential-stuffing/cloud/atechmedia-codebase.yaml
  http/credential-stuffing/cloud/avnil-pdf-generator.yaml
  http/credential-stuffing/cloud/chefapi.yaml
  http/credential-stuffing/cloud/codepen.yaml
  http/credential-stuffing/cloud/datadog.yaml
  http/credential-stuffing/cloud/docker-hub.yaml
  http/credential-stuffing/cloud/gitea.yaml
  http/credential-stuffing/cloud/github.yaml
  http/credential-stuffing/cloud/postman.yaml
  http/credential-stuffing/cloud/pulmi.yaml
  http/credential-stuffing/self-hosted/grafana.yaml
  http/credential-stuffing/self-hosted/jira.yaml
Labels: Done

#7356 Create addonfinance-portal.yaml
  http/exposed-panels/addonfinance-portal.yaml
Labels: Done

#7353 Create asus-aicloud-panel.yaml
  http/exposed-panels/asus-aicloud-panel.yaml
Labels: Done

#7295 Add template to detect instance of eArcu
  http/exposed-panels/earcu-panel.yaml
Labels: Done

#7332 Create misp-panel.yaml
  http/exposed-panels/misp-panel.yaml
Labels: Done

#7359 Create sitecore-xml-xss.yaml
  http/vulnerabilities/sitecore/sitecore-xml-xss.yaml
Labels: Done

#7281 Added http/cves/2019/CVE-2019-1943.yaml Template
  http/cves/2019/CVE-2019-1943.yaml
Labels: Done

#7070 Adding CVE-2022-24706 (couchdb RCE)
  network/cves/2022/CVE-2022-24706.yaml
Labels: Done

#7361 protocol update
  network/cves/2022/CVE-2022-24706.yaml
Labels: Done

#7367 Added additional detection for open-redirect.yaml Template
  http/vulnerabilities/generic/open-redirect.yaml
Labels: good first issue, Done

#7339 Update wp-install
  http/misconfiguration/installer/wp-install.yaml
Labels: Done

#7346 Add phplist-detect.yaml
  http/technologies/phplist-detect.yaml
Labels: Done

#7340 CVE-2023-33246 - RocketMQ <= 5.1.0 Remote Code Execution
  network/cves/2023/CVE-2023-33246.yaml
Labels: Done

#7335 fix CVE-2022-1595-false positive
  http/cves/2022/CVE-2022-1595.yaml
Labels: Done

#5557 Create crypto-mining-malware.yaml
  http/miscellaneous/crypto-mining-malware.yaml
Labels: Done

#7345 Add openproject-detect.yaml
  http/technologies/openproject-detect.yaml
Labels: Done

#7364 Create CVE-2023-25157.yaml
  http/cves/2023/CVE-2023-25157.yaml
Labels: Done

#7388 Update jenkins-script.yaml
  http/vulnerabilities/jenkins/jenkins-script.yaml
Labels: Done

#7381 Create CVE-2012-4982.yaml
  http/cves/2012/CVE-2012-4982.yaml
Labels: Done

#7394 Update and rename http/exposed-panels/c2/cobalt-strike-c2.yaml to ssl…
  ssl/c2/cobalt-strike-c2.yaml
Labels: Done

#7389 Updated CVE-2023-1434.yaml template
  http/cves/2023/CVE-2023-1434.yaml
Labels: Done

#7369 Create CVE-2021-44138.yaml
  http/cves/2021/CVE-2021-44138.yaml
Labels: good first issue, Done

#7384 Create CVE-2010-1586.yaml
  http/cves/2010/CVE-2010-1586.yaml
Labels: Done

#7378 Fix false positives when user does not exist.
  http/osint/dotcards.yaml
Labels: Done

#7405 VMWare vRealize Network Insight pre-authenticated RCE CVE-2023-20887
  http/cves/2023/CVE-2023-20887.yaml
Labels: good first issue, Done

#7397 Add detection of Cryptobox instances.
  http/exposed-panels/cryptobox-panel.yaml
Labels: Done

#7412 ShadowPad C2 Infrastructure
  ssl/c2/shadowpad-c2.yaml
Labels: Done

#7377 Add StackOverflow OSINT
  http/osint/stackoverflow.yaml
Labels: Done

#7409 Exposed iClock Admin Panel
  http/exposed-panels/iclock-admin-panel.yaml
Labels: Done

#7379 Fix false positives for non-200 status codes.
  http/technologies/nacos-version.yaml
Labels: Done

#7400 Fixed matchers-condition CVE-2020-11981
  network/cves/2020/CVE-2020-11981.yaml
Labels: Done

#7396 Create facebook-page
  http/osint/facebook-page.yaml
Labels: good first issue, Done

#7380 Update webflow-takeover.yaml
  http/takeovers/webflow-takeover.yaml
Labels: Done

#7385 Create CVE-2008-7269.yaml
  http/cves/2008/CVE-2008-7269.yaml
Labels: Done

#7383 Create CVE-2013-2621.yaml
  http/cves/2013/CVE-2013-2621.yaml
Labels: good first issue, Done

#7314 Updated joomla-jvehicles-lfi.yaml
  http/vulnerabilities/joomla/joomla-jvehicles-lfi.yaml
Labels: Done

#7441 Update CVE-2016-3510.yaml
  network/cves/2016/CVE-2016-3510.yaml
Labels: Done

#7440 Update CVE-2018-2893.yaml
  network/cves/2018/CVE-2018-2893.yaml
Labels: Done

#7411 Updated CVE-2023-20887
  http/cves/2023/CVE-2023-20887.yaml
Labels: Done

#7450 Fixed CVE-2021-1497
  http/cves/2021/CVE-2021-1497.yaml
Labels: Done

#7374 Fix CVE-2021-24340-False Positive
  http/cves/2021/CVE-2021-24340.yaml
Labels: Done

#7451 Updated robots-txt-endpoint and robots-txt
  http/miscellaneous/robots-txt-endpoint.yaml
  http/miscellaneous/robots-txt.yaml
Labels: Done

#7447 FP fixed CVE-2019-3403
  http/cves/2019/CVE-2019-3403.yaml
Labels: Done

#7429 Gozi Malware - Detect
  ssl/c2/gozi-malware.yaml
Labels: Done

#7428 Bitrat C2 - Detect
  ssl/c2/bitrat-c2.yaml
Labels: Done

#7427 DcRat Server C2 - Detect
  ssl/c2/dcrat-server-c2.yaml
Labels: Done

#7425 OrcusRAT - Detect
  ssl/c2/orcus-rat-c2.yaml
Labels: Done

#7424 Empire C2 - Detect
  http/exposed-panels/c2/empire-c2.yaml
Labels: Done

#7423 Create quasar-rat-c2.yaml
  ssl/c2/quasar-rat-c2.yaml
Labels: Done

#7416 FIX: Matcher Updated for Kubecost
  http/misconfiguration/unauth-kubecost.yaml
Labels: good first issue, Done

#7421 Posh C2 - Detect
  ssl/c2/posh-c2.yaml
Labels: Done

#7417 Brute Ratel C4 - Detect
  http/exposed-panels/c2/brute-ratel-c4.yaml
Labels: Done

#7413 Viper C2 - Detect
  http/exposed-panels/c2/viper-c2.yaml
Labels: Done

#7399 Update iis-internal-ip-disclosure.yaml
  http/misconfiguration/iis-internal-ip-disclosure.yaml
Labels: Done

#7453 CVE-2017-12617
  http/cves/2017/CVE-2017-12617.yaml
Labels: Done

#7419 Covenant C2 - Detect
  ssl/c2/covenant-c2-ssl.yaml
Labels: Done

#7456 Update CVE-2012-1823.yaml
  http/cves/2012/CVE-2012-1823.yaml
Labels: Done

#7459 Update CVE-2018-20526.yaml
  http/cves/2018/CVE-2018-20526.yaml
Labels: Done

#7410 C2 -Detection [bodyhash]
  http/exposed-panels/c2/evilginx.yaml
  http/exposed-panels/c2/nh-c2.yaml
Labels: Done

#7446 Update tidb-native-password.yaml
  network/tidb-native-password.yaml
Labels: Done

#7392 Fixing tags
  dns/caa-fingerprint.yaml
  dns/cname-fingerprint.yaml
  dns/cname-service.yaml
  http/cves/2020/CVE-2020-11547.yaml
  http/exposed-panels/star-network-utility.yaml
  http/exposures/configs/kyan-credential-exposure.yaml
  http/iot/liveview-axis-camera.yaml
  http/miscellaneous/http-trace.yaml
  http/technologies/versa/versa-networks-detect.yaml
  http/token-spray/api-binaryedge.yaml
  http/token-spray/api-c99.yaml
  http/token-spray/api-chaos.yaml
  http/token-spray/api-fullhunt.yaml
  http/token-spray/api-intelx.yaml
  http/token-spray/api-securitytrails.yaml
  http/token-spray/api-shodan.yaml
  http/token-spray/api-sslmate.yaml
  http/token-spray/api-zoomeye.yaml
  http/vulnerabilities/other/sponip-network-system-ping-rce.yaml
  network/vulnerabilities/clockwatch-enterprise-rce.yaml
Labels: Done

#7438 Create CVE-2004-1965.yaml
  http/cves/2004/CVE-2004-1965.yaml
Labels: Done

#7439 Create CVE-2019-10098.yaml
  http/cves/2019/CVE-2019-10098.yaml
Labels: Done

#7431 Create CVE-2009-0347.yaml
  http/cves/2009/CVE-2009-0347.yaml
Labels: Done

#7323 VBulletin Forumrunner SQL Injection (CVE-2016-6195)
  http/cves/2016/CVE-2016-6195.yaml
Labels: Done

#7185 Fixed CVE-2013-7285 / Updated CVE-2020-26217 / Updated CVE-2021-21345 / Updated CVE-2021-39144
  http/cves/2013/CVE-2013-7285.yaml
  http/cves/2020/CVE-2020-26217.yaml
  http/cves/2021/CVE-2021-21345.yaml
  http/cves/2021/CVE-2021-39144.yaml
Labels: Done

#7461 Create CVE-2023-0630.yaml
  http/cves/2023/CVE-2023-0630.yaml
Labels: Done

#7455 Update avaya-aura-rce.yaml
  http/vulnerabilities/avaya/avaya-aura-rce.yaml
Labels: Done

#7422 Update CVE-2022-24706.yaml
  network/cves/2022/CVE-2022-24706.yaml
Labels: Done

#7443 Update CVE-2023-33246.yaml
  network/cves/2023/CVE-2023-33246.yaml
Labels: Done

#7444 Update CVE-2020-11981.yaml
  network/cves/2020/CVE-2020-11981.yaml
Labels: Done

#7437 Create CVE-2005-3634.yaml
  http/cves/2005/CVE-2005-3634.yaml
Labels: Done

#7398 Create epp-server-lfi.yaml
  http/vulnerabilities/other/epp-server-lfi.yaml
Labels: Done

#7458 Create CVE-2021-24647.yaml
  http/cves/2021/CVE-2021-24647.yaml
Labels: Done

#7464 Create rancher-dashboard.yaml
  http/exposed-panels/rancher-dashboard.yaml
Labels: Done

#7469 Update CVE-2023-32315.yaml
  http/cves/2023/CVE-2023-32315.yaml
Labels: Done

#7470 tags -update
  http/cves/2017/CVE-2017-12617.yaml
Labels: Done

#7471 Create CVE-2023-23333.yaml
  http/cves/2023/CVE-2023-23333.yaml
Labels: Done

#7477 Create nuxt-js-xss.yaml
  http/vulnerabilities/nuxt/nuxt-js-xss.yaml
Labels: Done

#7476 Create nuxt-js-semi-lfi.yaml
  http/vulnerabilities/nuxt/nuxt-js-semi-lfi.yaml
Labels: Done

#7475 Create nuxt-js-lfi.yaml
  http/vulnerabilities/nuxt/nuxt-js-lfi.yaml
Labels: Done

#7472 Create CVE-2023-34960.yaml
  http/cves/2023/CVE-2023-34960.yaml
Labels: Done

#7478 Update CVE-2017-12617.yaml
  http/cves/2017/CVE-2017-12617.yaml
Labels: Done

#7474 Create CVE-2023-24243.yaml
  http/cves/2023/CVE-2023-24243.yaml
Labels: Done

#7480 fix CVE-2019-18394 false-positive
  http/cves/2019/CVE-2019-18394.yaml
Labels: Done

#7454 Update CVE-2019-20183.yaml
  http/cves/2019/CVE-2019-20183.yaml
Labels: Done

#7465 Update roxyfileman-fileupload.yaml
  http/misconfiguration/roxyfileman-fileupload.yaml
Labels: Done

#7473 Create CVE-2022-23544.yaml
  http/cves/2022/CVE-2022-23544.yaml
Labels: Done

#7365 Add magento eol template
  http/technologies/magento-eol.yaml
  http/technologies/magento-version-detect.yaml
  workflows/magento-workflow.yaml
Labels: Done

#7485 feat: update fortinet-panel.yaml
  http/exposed-panels/fortinet/fortinet-panel.yaml
Labels: Done

#7484 Create bravia-signage.yaml
  http/misconfiguration/bravia-signage.yaml
Labels: Done

#7488 Create CVE-2023-33568.yaml
  http/cves/2023/CVE-2023-33568.yaml
Labels: Done

#7368 More effective Roundcube log disclosure template.
  http/exposures/logs/roundcube-log-disclosure.yaml
Labels: Done

#7487 Fix FP CVE-2001-0537.yaml
  http/cves/2001/CVE-2001-0537.yaml
Labels: Done

#7500 CVE-2023-34362 (MOVEit Transfer - Remote Code Execution)
  http/cves/2023/CVE-2023-34362.yaml
Labels: Done

#7503 Release PREP
  http/default-logins/riello/netman-default-login.yaml
  http/misconfiguration/symfony-fragment.yaml
  http/vulnerabilities/other/epp-server-lfi.yaml
Labels: Done

#7497 New 20 Templates
  http/exposed-panels/aws-ec2-autoscale.yaml
  http/exposed-panels/crontab-ui.yaml
  http/exposed-panels/eos-http-browser.yaml
  http/exposed-panels/glowroot-panel.yaml
  http/exposed-panels/pdi-device-page.yaml
  http/exposed-panels/selfcheck-panel.yaml
  http/exposed-panels/teradek-panel.yaml
  http/exposed-panels/tigase-xmpp-server.yaml
  http/exposed-panels/tup-openframe.yaml
  http/exposed-panels/webcomco-panel.yaml
  http/misconfiguration/apache-impala.yaml
  http/misconfiguration/aws-ec2-status.yaml
  http/misconfiguration/dynamic-container-host.yaml
  http/misconfiguration/flask-redis-docker.yaml
  http/misconfiguration/gopher-server.yaml
  http/misconfiguration/perfsonar-toolkit.yaml
  http/misconfiguration/phpnow-works.yaml
  http/misconfiguration/smokeping-grapher.yaml
  http/misconfiguration/v2x-control.yaml
  http/technologies/default-apache-miracle.yaml
Labels: Done

#7486 Fix FP - avaya-aura-rce.yaml
  http/vulnerabilities/avaya/avaya-aura-rce.yaml
Labels: Done

#7491 add(http/cves): CVE-2023-35843 & CVE-2023-35844
  http/cves/2023/CVE-2023-35843.yaml
  http/cves/2023/CVE-2023-35844.yaml
Labels: Done

#7512 Update CVE-2023-35843.yaml
  http/cves/2023/CVE-2023-35843.yaml
Labels: Done

#7272 Added templates to identify /.aws/credenitals and /.aws/config
  http/exposures/configs/aws-config.yaml
  http/exposures/configs/aws-credentials.yaml
Labels: good first issue, Done

#7502 Create CVE-2023-1454.yaml
  http/cves/2023/CVE-2023-1454.yaml
Labels: Done

#7509 Create CVE-2021-46704.yaml
  http/cves/2021/CVE-2021-46704.yaml
Labels: Done

#7498 Fixing description for http/exposed-panels/arcgis/arcgis-rest-api.yaml
  http/exposed-panels/arcgis/arcgis-rest-api.yaml
Labels: Done

#7513 Create CVE-2022-40022.yaml
  http/cves/2022/CVE-2022-40022.yaml
Labels: Done

#7510 Create CVE-2023-27372.yaml
  http/cves/2023/CVE-2023-27372.yaml
Labels: Done

#7433 Create CVE-2012-6499.yaml
  http/cves/2012/CVE-2012-6499.yaml
Labels: Done

#7326 CVE-2020-1938 minor - update
  network/cves/2020/CVE-2020-1938.yaml
Labels: Done

#7517 Create axxon-client-panel.yaml
  http/exposed-panels/axxon-client-panel.yaml
Labels: Done

#7523 odoo db template fixes
  http/exposed-panels/odoo-database-manager.yaml
  http/misconfiguration/odoo-unprotected-database.yaml
Labels: Done

#7514 Create syncserver-panel.yaml
  http/exposed-panels/syncserver-panel.yaml
Labels: Done

#7534 Added Openbullet2 Panel Detect
  http/exposed-panels/openbullet2-panel.yaml
Labels: Done

#7546 Create CNVD-2020-63964.yaml
  http/cnvd/2020/CNVD-2020-63964.yaml
Labels: Done

#7540 Create genieacs-default-jwt.yaml
  http/misconfiguration/genieacs-default-jwt.yaml
Labels: Done

#7538 Fix Github False Positive github-takeover.yaml
  http/takeovers/github-takeover.yaml
Labels: Done

#7561 added description + extractor and misc changes.
  http/cves/2021/CVE-2021-46704.yaml
  http/misconfiguration/genieacs-default-jwt.yaml
Labels: Done

#7556 Update grafana-detect.yaml
  http/exposed-panels/grafana-detect.yaml
Labels: Done

#7530 Create CVE-2023-25346.yaml
  http/cves/2023/CVE-2023-25346.yaml
Labels: Done

#7531 Create CVE-2023-26842.yaml
  http/cves/2023/CVE-2023-26842.yaml
Labels: Done

#7532 Create CVE-2023-26843.yaml
  http/cves/2023/CVE-2023-26843.yaml
Labels: Done

#7542 Create CVE-2023-0562.yaml
  http/cves/2023/CVE-2023-0562.yaml
Labels: good first issue, Done

#7541 Create CVE-2023-0563.yaml
  http/cves/2023/CVE-2023-0563.yaml
Labels: Done

#7533 Create CVE-2023-31548.yaml
  http/cves/2023/CVE-2023-31548.yaml
Labels: Done

#7555 Create CVE-2023-20889.yaml
  http/cves/2023/CVE-2023-20889.yaml
Labels: Done

#7565 Create CVE-2023-34599.yaml
  http/cves/2023/CVE-2023-34599.yaml
Labels: Done

#7554 Create CVE-2023-20888.yaml
  http/cves/2023/CVE-2023-20888.yaml
Labels: Done

#7529 Create grav-register-admin.yaml
  http/misconfiguration/grav-register-admin.yaml
Labels: Done

#7507 Create spip-install.yaml
  http/misconfiguration/installer/spip-install.yaml
Labels: Done

#6413 Nodejs File templates
  file/nodejs/admzip-path-overwrite.yaml
  file/nodejs/express-lfr.yaml
  file/nodejs/generic-path-traversal.yaml
  file/nodejs/tar-path-overwrite.yaml
  file/nodejs/xss-disable-mustache-escape.YAML
  file/nodejs/xss-serialize-javascript.yaml
  file/nodejs/zip-path-overwrite.yaml
Labels: Done

#7566 Updated spip-install.yaml: adding matcher condition
  http/misconfiguration/installer/spip-install.yaml
Labels: false-positive

#7568 Create CVE-2023-34843.yaml
  http/cves/2023/CVE-2023-34843.yaml
Labels: Done

#7560 Fix with Correct Status Code [404]
  http/misconfiguration/jetty-showcontexts-enable.yaml
Labels: Done

#7550 Create wd-mycloud-panel.yaml
  http/exposed-panels/wd-mycloud-panel.yaml
Labels: Done

#7559 Create CVE-2023-0126.yaml
  http/cves/2023/CVE-2023-0126.yaml
Labels: Done

#7548 Create CVE-2023-34598.yaml
  http/cves/2023/CVE-2023-34598.yaml
Labels: Done

#7526 Added ardace.php SQL Inj template
  http/vulnerabilities/vbulletin/arcade-php-sqli.yaml
Labels: Done

#7547 Create jsherp-boot-panel.yaml
  http/exposed-panels/jsherp-boot-panel.yaml
Labels: Done

#7569 Update metadata-aws.yaml
  http/misconfiguration/proxy/metadata-aws.yaml
Labels: Done

#7573 Create codeigniter-errorpage.yaml
  http/misconfiguration/codeigniter-errorpage.yaml
Labels: Done

#7581 Create CVE-2023-24488.yaml
  http/cves/2023/CVE-2023-24488.yaml
Labels: Done
