Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-12, with the labels that each got.

#8729 Update cache-poisoning.yaml
  http/vulnerabilities/generic/cache-poisoning.yaml
Labels: Done

#8721 Detect Matrix homeserver software and version
  http/technologies/matrix-homeserver-detect.yaml
Labels: good first issue, Done

#8740 Update and rename openwrt-default-login.yaml to openwrt-luci-panel.yaml
  http/exposed-panels/openwrt/openwrt-luci-panel.yaml
Labels: Done

#8738 Create chamilo-installer.yaml
  http/misconfiguration/installer/chamilo-installer.yaml
Labels: Done

#8739 Update matrix-homeserver-detect.yaml
  http/technologies/matrix-homeserver-detect.yaml
Labels: Done

#8726 Create prometheus-exposed-panel.yaml
  http/exposed-panels/prometheus-exposed-panel.yaml
Labels: good first issue, Done

#8728 DOMPDF configuration detection
  http/exposures/configs/dompdf-config.yaml
Labels: Done

#8744 Create phpgedview-installer.yaml
  http/misconfiguration/installer/phpgedview-installer.yaml
Labels: Done

#8755 Create dahua-wpms-rce.yaml
  http/vulnerabilities/dahua/dahua-wpms-rce.yaml
Labels: Done

#8760 Update dahua-wpms-rce.yaml
  http/vulnerabilities/dahua/dahua-wpms-rce.yaml
Labels: Done

#8759 Create yunanbao-rce.yaml
  http/vulnerabilities/other/yunanbao-rce.yaml
Labels: Done

#8756 Create huawei-authhttp-lfi.yaml
  http/vulnerabilities/huawei/huawei-authhttp-lfi.yaml
Labels: Done

#8720 feat: add CVE-2023-3368
  http/cves/2023/CVE-2023-3368.yaml
Labels: Done

#8719 Update to use the JSON extractor for nextcloud-owncloud-detect.yaml
  http/technologies/nextcloud-owncloud-detect.yaml
Labels: good first issue, Done

#8763 Fix #8669 Issue
  http/exposures/configs/editor-exposure.yaml
Labels: Done

#8639 Create CVE-2023-5556
  http/cves/2023/CVE-2023-5556.yaml
Labels: Done

#8767 Update CVE-2023-32243.yaml
  http/cves/2023/CVE-2023-32243.yaml
Labels: Done

#8768 Issue #8764
  network/backdoor/vsftpd-backdoor.yaml
Labels: Done

#8753 Update CVE-2023-39796.yaml
  http/cves/2023/CVE-2023-39796.yaml
Labels: Done

#8765 Create CVE-2023-6018.yaml
  http/cves/2023/CVE-2023-6018.yaml
Labels: Done

#8774 Create CVE-2023-49070 (Apache OFBiz <18.12.10 - Arbitrary Code Execution)
  http/cves/2023/CVE-2023-49070.yaml
Labels: good first issue, Done

#8769 Dataease Default Login & Panel
  http/default-logins/dataease/dataease-default-login.yaml
  http/exposed-panels/dataease-panel.yaml
Labels: Done

#8771 Create CVE-2023-6020.yaml
  http/cves/2023/CVE-2023-6020.yaml
Labels: Done

#8772 Create CVE-2023-6021.yaml
  http/cves/2023/CVE-2023-6021.yaml
Labels: Done

#8750 Update database-credentials.yaml
  http/exposures/files/database-credentials.yaml
Labels: Done

#8747 Create tailon-panel.yaml
  http/exposed-panels/tailon-panel.yaml
Labels: Done

#8722 Add version extraction for Element Web
  http/technologies/element-web-detect.yaml
Labels: Done

#8705 Update wordpress-debug-log.yaml
  http/vulnerabilities/wordpress/wordpress-debug-log.yaml
Labels: Done

#8688 Create CVE-2023-36144.yaml
  http/cves/2023/CVE-2023-36144.yaml
Labels: Done

#8784 tagging updates for SSL & network related templates
  network/cves/2016/CVE-2016-3510.yaml
  network/cves/2020/CVE-2020-1938.yaml
  network/cves/2022/CVE-2022-24706.yaml
  network/detection/activemq-openwire-transport-detect.yaml
  network/detection/apache-activemq-detect.yaml
  network/detection/axigen-mail-server-detect.yaml
  network/detection/bgp-detect.yaml
  network/detection/cisco-finger-detect.yaml
  network/detection/dotnet-remoting-service-detect.yaml
  network/detection/expn-mail-detect.yaml
  network/detection/iplanet-imap-detect.yaml
  network/detection/riak-detect.yaml
  network/detection/sap-router.yaml
  network/detection/smtp-detect.yaml
  network/detection/starttls-mail-detect.yaml
  network/detection/weblogic-iiop-detect.yaml
  network/detection/weblogic-t3-detect.yaml
  network/detection/ws_ftp-ssh-detect.yaml
  network/enumeration/smtp/smtp-commands-enum.yaml
  network/jarm/c2/cobalt-strike-c2-jarm.yaml
  network/jarm/c2/covenant-c2-jarm.yaml
  network/jarm/c2/deimos-c2-jarm.yaml
  network/jarm/c2/evilginx2-jarm.yaml
  network/jarm/c2/generic-c2-jarm.yaml
  network/jarm/c2/grat2-c2-jarm.yaml
  network/jarm/c2/havoc-c2-jarm.yaml
  network/jarm/c2/mac-c2-jarm.yaml
  network/jarm/c2/macshell-c2-jarm.yaml
  network/jarm/c2/merlin-c2-jarm.yaml
  network/jarm/c2/metasploit-c2-jarm.yaml
  network/jarm/c2/mythic-c2-jarm.yaml
  network/jarm/c2/posh-c2-jarm.yaml
  network/jarm/c2/shad0w-c2-jarm.yaml
  network/jarm/c2/silenttrinity-c2-jarm.yaml
  network/jarm/c2/sliver-c2-jarm.yaml
  network/misconfig/printers-info-leak.yaml
  network/misconfig/sap-router-info-leak.yaml
  ssl/c2/asyncrat-c2.yaml
  ssl/c2/bitrat-c2.yaml
  ssl/c2/cobalt-strike-c2.yaml
  ssl/c2/covenant-c2-ssl.yaml
  ssl/c2/dcrat-server-c2.yaml
  ssl/c2/gozi-malware-c2.yaml
  ssl/c2/havoc-c2.yaml
  ssl/c2/icedid.yaml
  ssl/c2/metasploit-c2.yaml
  ssl/c2/mythic-c2-ssl.yaml
  ssl/c2/orcus-rat-c2.yaml
  ssl/c2/posh-c2.yaml
  ssl/c2/quasar-rat-c2.yaml
  ssl/c2/shadowpad-c2.yaml
  ssl/deprecated-tls.yaml
  ssl/detect-ssl-issuer.yaml
  ssl/expired-ssl.yaml
  ssl/insecure-cipher-suite-detect.yaml
  ssl/revoked-ssl-certificate.yaml
  ssl/self-signed-ssl.yaml
  ssl/ssl-dns-names.yaml
  ssl/tls-version.yaml
  ssl/untrusted-root-certificate.yaml
Labels: good first issue, Done

#8193 xss
  http/cves/2023/CVE-2023-39002.yaml
Labels: Done

#8779 Additional matcher for security.txt
  http/miscellaneous/security-txt.yaml
Labels: Done

#8785 Create reportico-admin-page.yaml
  http/exposed-panels/reportico-admin-panel.yaml
Labels: Done

#8790 Update CVE-2023-3479.yaml
  http/cves/2023/CVE-2023-3479.yaml
Labels: Done

#8802 Added CVE-2023-43177 (CrushFTP < 10.5.1 RCE)
  http/cves/2023/CVE-2023-43177.yaml
Labels: Done

#8791 Create node-ecstatic-listing.yaml
  http/vulnerabilities/ecstatic/node-ecstatic-listing.yaml
Labels: Done

#8788 Create CVE-2023-22232.yaml
  http/cves/2023/CVE-2023-22232.yaml
Labels: Done

#8811 Added woodwing templates
  http/exposed-panels/woodwing-panel.yaml
  http/misconfiguration/woodwing-git.yaml
  http/misconfiguration/woodwing-phpinfo.yaml
Labels: Done

#8800 fixed weak matcher
  http/misconfiguration/unauth-celery-flower.yaml
Labels: Done

#8809 fix: false positive editor-exposure.yaml
  http/exposures/configs/editor-exposure.yaml
Labels: Done

#8205 Create CVE-2023-30534 template for cacti insecure deserialization of filter data
  http/cves/2023/CVE-2023-30534.yaml
Labels: Done

#8817 Create CVE-2021-44910.yaml
  http/cves/2021/CVE-2021-44910.yaml
Labels: Done

#8125 Detection for ZeroQlik Remote Code Execution Vulnerability (CVE-2023-41265 and CVE-2023-41266)
  http/cves/2023/CVE-2023-41265.yaml
  http/cves/2023/CVE-2023-41266.yaml
  http/technologies/confluence-detect.yaml
Labels: Status: Review Needed, waiting for more info

#8823 add CVE-2023-6553 detection template
  http/cves/2023/CVE-2023-6553.yaml
Labels: Done

#8825 Update misconfigured-docker.yaml
  http/misconfiguration/misconfigured-docker.yaml
Labels: Done

#8821 Update pgsql-detect.yaml
  network/detection/pgsql-detect.yaml
Labels: Done

#8831 Create bamboo-detect.yaml
  http/technologies/bamboo-detect.yaml
Labels: Done

#8830 Update locust-exposure.yaml
  http/misconfiguration/locust-exposure.yaml
Labels: Done

#8824 Add detection of Vue PACS instance
  http/exposed-panels/vue-pacs-panel.yaml
Labels: Done

#8834 Add CVE-2021-29200
  http/cves/2021/CVE-2021-29200.yaml
Labels: Done

#8843 Update and rename skype-blind-ssrf.yaml to CVE-2023-41763.yaml
  http/cves/2023/CVE-2023-41763.yaml
Labels: Done

#8789 Create sslvpn-client-rce.yaml
  http/vulnerabilities/other/sslvpn-client-rce.yaml
Labels: Done

#8792 Create node-ecstatic-internal-path.yaml
  http/vulnerabilities/ecstatic/node-ecstatic-internal-path.yaml
Labels: Done

#8829 Added recommended template config profile
  .github/workflows/template-validate.yml
  config/recommended.yml
Labels: Done

#8810 Create espocrm-installer.yaml
  http/misconfiguration/installer/espocrm-installer.yaml
Labels: Done

#8826 Add detection of iparapheur instance
  http/technologies/iparapheur-detect.yaml
Labels: Done

#8832 Update basic-auth-detect.yaml
  http/technologies/basic-auth-detect.yaml
Labels: Done

#8846 Create jinhe-jc6-clobfield-sqli.yaml
  http/vulnerabilities/jinhe/jinhe-jc6-sqli.yaml
Labels: Done

#8850 Create h2o-dashboard.yaml
  http/misconfiguration/h2o/h2o-dashboard.yaml
Labels: Done

#8844 Create CVE-2023-26035.yaml (ZoneMinder Snapshots - Command Injection)
  http/cves/2023/CVE-2023-26035.yaml
Labels: Done

#8673 Added 1 Presta RCE and 2 VB SQLi
  http/cves/2018/CVE-2018-8823.yaml
  http/vulnerabilities/vbulletin/vbulletin-ajaxreg-sqli.yaml
Labels: Done

#8552 Added CVE-2022-0087
  http/cves/2022/CVE-2022-0087.yaml
Labels: Done

#8854 Fixed FP in ecshop-sqli and CNVD-2020-23735
  http/cnvd/2020/CNVD-2020-23735.yaml
  http/vulnerabilities/other/ecshop-sqli.yaml
Labels: Done

#8853 fix oast fp CVE-2020-24148.yaml
  http/cves/2020/CVE-2020-24148.yaml
Labels: Done

#8845 fix fp - CVE-2023-0600.yaml
  http/cves/2023/CVE-2023-0600.yaml
Labels: Done

#8855 added cdn-cache-poisoning-aes256
  http/misconfiguration/aws/aws-ec2-status.yaml
  http/misconfiguration/aws/aws-object-listing.yaml
  http/misconfiguration/aws/aws-redirect.yaml
  http/misconfiguration/aws/aws-s3-explorer.yaml
  http/misconfiguration/aws/aws-xray-application.yaml
  http/misconfiguration/aws/awstats-listing.yaml
  http/misconfiguration/aws/cdn-cache-poisoning.yaml
Labels: Done

#8851 Create CVE-2023-6038.yaml
  http/cves/2023/CVE-2023-6038.yaml
Labels: Done

#8852 fix oast fp CVE-2019-9978.yaml
  http/cves/2019/CVE-2019-9978.yaml
Labels: Done

#8849 Create h2o-arbitary-file-read.yaml
  http/misconfiguration/h2o/h2o-arbitary-file-read.yaml
Labels: Done

#8856 feat(template): Add CVE-2023-46359.yaml ✨
  http/cves/2023/CVE-2023-46359.yaml
Labels: Done

#8812 Add SaaS DNS detection for Microsoft Entra application proxy
  dns/dns-saas-service-detection.yaml
Labels: good first issue

#8862 Create ruijie-rg-eg-web-mis-rce.yaml
  http/vulnerabilities/ruijie/ruijie-rg-eg-web-mis-rce.yaml
Labels: Done

#8841 Create api-openai.yaml
  http/token-spray/api-openai.yaml
Labels: Done

#8871 Create CVE-2015-2794.yaml
  http/cves/2015/CVE-2015-2794.yaml
Labels: Done

#8868 Create yonyou-ksoa-dept-sqli.yaml
  http/vulnerabilities/yonyou/yonyou-ksoa-dept-sqli.yaml
Labels: Done

#8863 add docker daemon exposed via http
  http/exposures/docker-daemon-exposed.yaml
Labels: Done

#8861 Create CVE-2023-46574.yaml
  http/cves/2023/CVE-2023-46574.yaml
Labels: Done

#8867 Create ruijie-rg-uac-nmc-sync-rce.yaml
  http/vulnerabilities/ruijie/ruijie-nmc-sync-rce.yaml
Labels: Done

#8872 Create CVE-2023-42343.yaml (OpenCMS XSS)
  http/cves/2023/CVE-2023-42343.yaml
Labels: Done

#8883 Create CVE-2023-41109.yaml
  http/cves/2023/CVE-2023-41109.yaml
Labels: Done

#6955 Erlang Port Mapper Daemon
  network/misconfig/erlang-daemon.yaml
Labels: Done

#8869 Create dahua-icc-backdoor-user.yaml
  http/vulnerabilities/dahua/dahua-icc-backdoor-user.yaml
Labels: Done
