Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-05, with the labels that each got.

#7098 Update CVE-2021-44228.yaml
  http/cves/2021/CVE-2021-44228.yaml
Labels: Done

#7144 Create apache-zeppelin-unauth.yaml
  http/misconfiguration/apache/apache-zeppelin-unauth.yaml
Labels: Done

#7164 Create umami-default-login.yaml
  http/default-logins/umami/umami-default-login.yaml
Labels: Done

#7162 Added WPML XSS
  http/vulnerabilities/wordpress/wpml-xss.yaml
Labels: Done

#7154 Create CVE-2017-17731.yaml
  http/cves/2017/CVE-2017-17731.yaml
Labels: Done

#7105 Create sap-spartacus-detect.yaml
  headless/technologies/sap-spartacus.yaml
Labels: Done

#6967 fix(false-positive): Improve generic phpinfo matcher 🩹
  http/cves/2020/CVE-2020-5847.yaml
  http/cves/2021/CVE-2021-40870.yaml
Labels: good first issue, Done

#7171 fix regex for win.ini
  http/cves/2021/CVE-2021-43798.yaml
Labels: Done

#7176 Updated CVE-2022-0678 Template
  http/cves/2022/CVE-2022-0678.yaml
Labels: Done

#7175 Updated CVE-2022-40879 Template
  http/cves/2022/CVE-2022-40879.yaml
Labels: Done

#7179 fixed false positive produce by the old win.ini regex
  http/cves/2021/CVE-2021-43798.yaml
Labels: Done

#7158 Sb meetup
  file/keys/postman-api-key.yaml
  http/exposures/tokens/postman/postman-key.yaml
Labels: Done

#7166 Create oracle-opera-login.yaml
  http/exposed-panels/oracle-opera-login.yaml
Labels: Done

#7187 change to default password
  http/cves/2020/CVE-2020-10199.yaml
Labels: Done

#7182 Updated CVE-2020-14883
  http/cves/2020/CVE-2020-14883.yaml
Labels: good first issue, Done

#7169 Create red-lion-panel.yaml
  http/exposed-panels/red-lion-panel.yaml
Labels: Done

#7199 Create CVE-2023-26360.yaml [Adobe Coldfusion Fileread]
  http/cves/2023/CVE-2023-26360.yaml
Labels: Done

#7183 CVE templates added
  http/cves/2021/CVE-2021-27314.yaml
  http/cves/2021/CVE-2021-27315.yaml
  http/cves/2021/CVE-2021-27316.yaml
  http/cves/2021/CVE-2021-27319.yaml
  http/cves/2021/CVE-2021-27320.yaml
  http/cves/2022/CVE-2022-24264.yaml
  http/cves/2022/CVE-2022-24265.yaml
  http/cves/2022/CVE-2022-24266.yaml
  http/cves/2022/CVE-2022-27984.yaml
  http/cves/2022/CVE-2022-27985.yaml
  http/cves/2022/CVE-2022-42095.yaml
  http/cves/2022/CVE-2022-42096.yaml
  http/cves/2022/CVE-2022-4328.yaml
  http/cves/2022/CVE-2022-45037.yaml
  http/cves/2022/CVE-2022-45038.yaml
  http/cves/2022/CVE-2022-46020.yaml
  http/cves/2023/CVE-2023-1020.yaml
  http/cves/2023/CVE-2023-30210.yaml
  http/cves/2023/CVE-2023-30212.yaml
  http/vulnerabilities/wordpress/advanced-booking-calendar-sqli.yaml
  http/vulnerabilities/wordpress/wp-autosuggest-sql-injection.yaml
Labels: Done

#7205 Create CVE-2023-25135.yaml
  http/cves/2023/CVE-2023-25135.yaml
Labels: Done

#7210 fix: fp on gemfury-takeover.yaml
  http/takeovers/gemfury-takeover.yaml
Labels: Done

#7031 Updated favicon-detect.yaml
  http/technologies/favicon-detect.yaml
Labels: Done

#7196 CVE 2022 24716
  http/cves/2022/CVE-2022-24716.yaml
Labels: Done

#7195 Fix Dell EMC ECOM Default Login credentials
  http/default-logins/dell/emcecom-default-login.yaml
Labels: Done

#7204 Create CVE-2023-31059.yaml
  http/cves/2023/CVE-2023-31059.yaml
Labels: Done

#7203 add template for sophos mobile xxe ssrf (cve-2022-3980)
  http/cves/2022/CVE-2022-3980.yaml
Labels: Done

#7170 Update All Existing Log4j Templates
  .new-additions
  http/cves/2021/CVE-2021-45046.yaml
  http/vulnerabilities/apache/apache-ofbiz-log4j-rce.yaml
  http/vulnerabilities/apache/apache-solr-log4j-rce.yaml
  http/vulnerabilities/apache/log4j/jamf-pro-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-cloudcenter-suite-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-unified-communications-log4j.yaml
  http/vulnerabilities/cisco/cisco-vmanage-log4j.yaml
  http/vulnerabilities/code42/code42-log4j-rce.yaml
  http/vulnerabilities/jamf/jamf-log4j-jndi-rce.yaml
  http/vulnerabilities/mobileiron/mobileiron-log4j-jndi-rce.yaml
  http/vulnerabilities/other/elasticsearch5-log4j-rce.yaml
  http/vulnerabilities/other/goanywhere-mft-log4j-rce.yaml
  http/vulnerabilities/other/graylog-log4j.yaml
  http/vulnerabilities/other/metabase-log4j.yaml
  http/vulnerabilities/other/opennms-log4j-jndi-rce.yaml
  http/vulnerabilities/other/rundeck-log4j.yaml
  http/vulnerabilities/other/unifi-network-log4j-rce.yaml
  http/vulnerabilities/other/vmware-siterecovery-log4j-rce.yaml
  http/vulnerabilities/other/xenmobile-server-log4j.yaml
  http/vulnerabilities/springboot/springboot-log4j-rce.yaml
  http/vulnerabilities/vmware/vmware-hcx-log4j.yaml
  http/vulnerabilities/vmware/vmware-nsx-log4j.yaml
  http/vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
  http/vulnerabilities/vmware/vrealize-operations-log4j-rce.yaml
Labels: Done

#7161 Create CVE-2019-3398.yaml
  http/cves/2019/CVE-2019-3398.yaml
Labels: Status: On Hold

#7191 Create nginx-shards.yaml
  http/exposures/logs/nginx-shards.yaml
Labels: Done

#7181 SMTP Commands Enumeration
  network/enumeration/smtp-commands-enum.yaml
Labels: Done

#7172 eclipse-panel and CVE-2021-34427.yaml
  http/exposed-panels/eclipse-birt-panel.yaml
Labels: Done

#7208 SMTP User Enumeration
  network/enumeration/smtp/smtp-user-enum.yaml
Labels: Done

#7133 Update technologies/waf-detect.yaml
  http/fuzzing/waf-fuzz.yaml
Labels: Done

#7218 Update jedox-web-panel.yaml
  http/exposed-panels/jedox-web-panel.yaml
Labels: Done

#7228 Create repetier-server-panel.yaml
  http/exposed-panels/repetier-server-panel.yaml
Labels: Done

#7234 Create avtech-auth-bypass.yaml
  http/vulnerabilities/avtech/avtech-auth-bypass.yaml
Labels: Done

#7221 Update redis-detect.yaml
  network/detection/redis-detect.yaml
Labels: Done

#7222 Update CVE-2022-0543.yaml
  network/cves/2022/CVE-2022-0543.yaml
Labels: Done

#7230 Create config-properties-exposure
  http/exposures/configs/config-properties.yaml
Labels: Done

#7202 Create CVE-2023-25717.yaml
  http/cves/2023/CVE-2023-25717.yaml
  http/cves/2023/CVE-2023-31059.yaml
Labels: Done

#7236 Create avtech-dvr-ssrf.yaml
  http/vulnerabilities/avtech/avtech-dvr-ssrf.yaml
Labels: Done

#7229 Create CVE-2023-29923.yaml
  http/cves/2023/CVE-2023-29923.yaml
Labels: Done

#7220 Update exposed-redis.yaml
  network/exposed-redis.yaml
Labels: good first issue

#7237 Create avtech-verification-bypass.yaml
  http/vulnerabilities/avtech/avtech-verification-bypass.yaml
Labels: Done

#7246 Create odoo-panel.yaml
  http/exposed-panels/odoo-panel.yaml
Labels: Done

#7242 CVE-2020-11981
  network/cves/2020/CVE-2020-11981.yaml
Labels: Done

#7247 Create CVE-2021-37305.yaml
  http/cves/2021/CVE-2021-37305.yaml
Labels: Done

#7248 Create CVE-2021-37304.yaml
  http/cves/2021/CVE-2021-37304.yaml
Labels: Done

#7249 Create jeecg-boot-swagger.yaml
  http/exposures/apis/jeecg-boot-swagger.yaml
Labels: Done

#7245 Create CVE-2023-1434.yaml
  http/cves/2023/CVE-2023-1434.yaml
Labels: Done

#7231 Create sitecore-lfi.yaml
  http/misconfiguration/sitecore-lfi.yaml
Labels: Done

#7250 Update umbraco-login.yaml
  http/exposed-panels/umbraco-login.yaml
Labels: good first issue, Done

#7254 Update CVE-2019-7256.yaml
  http/cves/2019/CVE-2019-7256.yaml
Labels: Done

#7253 Create shardingsphere-panel.yaml
  http/exposed-panels/shardingsphere-panel.yaml
Labels: Done

#7257 Rename teamspeak3-detect to teamspeak3-detect.yaml
  network/detection/teamspeak3-detect.yaml
Labels: Done

#7212 Add template for CVE-2022-22733 Apache ShardingSphere ElasticJob-UI p…
  http/cves/2022/CVE-2022-22733.yaml
Labels: good first issue, Done

#7264 Added extra check for React detection
  http/technologies/tech-detect.yaml
Labels: good first issue, Done

#7279 Create CVE-2022-2733.yaml
  http/cves/2022/CVE-2022-2733.yaml
Labels: Done

#7280 Added CVE-2023-2780
  http/cves/2023/CVE-2023-2780.yaml
Labels: Done

#7282 Adds missing 'tags' attributes to 3 templates
  http/fuzzing/valid-gmail-check.yaml
  http/miscellaneous/robots-txt-endpoint.yaml
  http/vulnerabilities/ransomware/deadbolt-ransomware.yaml
Labels: good first issue, Done

#7174 Create unauth-ztp-ping.yaml
  http/vulnerabilities/zyxel/unauth-ztp-ping.yaml
Labels: good first issue, Done

#7285 Updated wordpress-rce-simplefilelist
  http/vulnerabilities/wordpress/wordpress-rce-simplefilelist.yaml
Labels: Done

#7286 Create blazor-boot.yaml
  http/exposures/configs/blazor-boot.yaml
Labels: Done

#5357 Fix CVE-2018-1273 payload substitution
  http/cves/2018/CVE-2018-1273.yaml
Labels: Done

#7258 Add interact template
  http/exposed-panels/interactsoftware-interact.yaml
Labels: Done

#3526 Create CVE-2017-5645.yaml
  network/cves/2017/CVE-2017-5645.yaml
Labels: Done

#7278 Create aem-secrets.yaml
  http/misconfiguration/aem/aem-secrets.yaml
Labels: Done

#7184 Updated CVE-2017-9791
  http/cves/2017/CVE-2017-9791.yaml
Labels: Done

#5518 Create CVE-2020-29583.yaml
  http/cves/2020/CVE-2020-29583.yaml
Labels: Done

#7291 Create CVE-2023-29887.yaml
  http/cves/2023/CVE-2023-29887.yaml
Labels: Done

#5615 Added CVE-2021-24435.yaml
  http/cves/2021/CVE-2021-24435.yaml
Labels: Done

#5585 Create CVE-2021-39165.yaml
  http/cves/2021/CVE-2021-39165.yaml
Labels: Hacktoberfest, Done

#7276 feat: added CNVD-2023-12632.yaml
  http/cnvd/2023/CNVD-2023-12632.yaml
Labels: Done

#7124 Fix CVE-2020-35847 false positive
  http/cves/2020/CVE-2020-35847.yaml
Labels: good first issue, Done

#7213 Added CVE-2016-4437
  http/cves/2016/CVE-2016-4437.yaml
Labels: Done

#7300 CVE-2023-32243 [WordPress Elementor Lite 5.7.1 Arbitrary Password Reset]🔥
  http/cves/2023/CVE-2023-32243.yaml
Labels: Done

#7298 Create CVE-2023-2732.yaml [MStore API <= 3.9.2 - Authentication Bypass] 🔥
  http/cves/2023/CVE-2023-2732.yaml
Labels: Done

#7259 Create CVE-2023-29919.yaml
  http/cves/2023/CVE-2023-29919.yaml
Labels: Done

#7177 Added CVE-2023-2356 Template
  http/cves/2023/CVE-2023-2356.yaml
Labels: Done

#7287 Fix False Positive
  http/misconfiguration/springboot/springboot-heapdump.yaml
Labels: Done

#7304 Update yeswiki-xss.yaml
  http/vulnerabilities/other/yeswiki-xss.yaml
Labels: Done

#7256 File and Token Based Templates
  file/keys/azure/azure-connection-string.yaml
  file/keys/digitalocean/digitalocean-access-token.yaml
  file/keys/digitalocean/digitalocean-personal-access.yaml
  file/keys/digitalocean/digitalocean-refresh-token.yaml
  file/keys/figma-access-token.yaml
  http/exposures/tokens/azure/azure-connection.yaml
  http/exposures/tokens/digitalocean/digital-ocean-personal-token.yaml
  http/exposures/tokens/digitalocean/digitalocean-app-token.yaml
  http/exposures/tokens/digitalocean/digitalocean-refresh.yaml
  http/exposures/tokens/figma/figma-personal-token.yaml
Labels: Done

#7303 Create CVE-2023-2825.yaml [GitLab 16.0.0 File Path Traversal] 🔥
  http/cves/2023/CVE-2023-2825.yaml
Labels: Done

#7313 Updated xenmobile-server-log4j.yaml
  http/vulnerabilities/other/xenmobile-server-log4j.yaml
Labels: Done

#7315 Updated CNVD-2021-15822.yaml
  http/cnvd/2021/CNVD-2021-15822.yaml
Labels: Done

#7318 Updated detect-dns-over-https.yaml
  http/miscellaneous/detect-dns-over-https.yaml
Labels: Done

#7297 Add template to detect instance of iSAMS
  http/exposed-panels/isams-panel.yaml
Labels: Done

#7302 fix CVE-2014-6287.yaml
  http/cves/2014/CVE-2014-6287.yaml
Labels: Done

#7294 Add template to detect instance of Sauter moduWeb Vision
  http/exposed-panels/sauter-moduwebvision-panel.yaml
Labels: Done

#5686 Insecure Cipher Suites Detection
  ssl/insecure-cipher-suite-detect.yaml
Labels: Done

#7214 Added CVE-2020-1956
  http/cves/2020/CVE-2020-1956.yaml
Labels: Done

#7322 fix CVE-2019-0193-false positive
  http/cves/2019/CVE-2019-0193.yaml
Labels: Done

#7330 Update springboot-trace.yaml
  http/misconfiguration/springboot/springboot-trace.yaml
Labels: Done

#7329 Update springboot-env.yaml
  http/misconfiguration/springboot/springboot-env.yaml
Labels: Done

#7331 Update springboot-jolokia.yaml
  http/misconfiguration/springboot/springboot-jolokia.yaml
Labels: Done

#7324 add CVE-2018-11759.yaml tags
  http/cves/2018/CVE-2018-11759.yaml
Labels: Done

#7305 Updated CVE-2020-11981
  network/cves/2020/CVE-2020-11981.yaml
Labels: Done

#7301 Create fortinet-fortiddos-panel.yaml
  http/exposed-panels/fortinet/fortinet-fortiddos-panel.yaml
Labels: Done
