Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-10, with the labels that each got.

#8227 Update rdap-whois.yaml
  http/miscellaneous/rdap-whois.yaml
Labels: good first issue, Done

#8298 Update icewarp-open-redirect.yaml
  http/vulnerabilities/other/icewarp-open-redirect.yaml
Labels: Done

#8291 fixes multiple dns templates with false postive results
  dns/azure-takeover-detection.yaml
  dns/caa-fingerprint.yaml
  dns/detect-dangling-cname.yaml
  dns/dmarc-detect.yaml
  dns/dns-saas-service-detection.yaml
  dns/dns-waf-detect.yaml
  dns/dnssec-detection.yaml
  dns/elasticbeanstalk-takeover.yaml
  dns/mx-fingerprint.yaml
  dns/nameserver-fingerprint.yaml
  dns/ptr-fingerprint.yaml
  dns/txt-fingerprint.yaml
Labels: Done

#8300 Create CVE-2023-43261
  http/cves/2023/CVE-2023-43261.yaml
Labels: Done

#8309 removed answer in case of NXDOMAIN
  dns/azure-takeover-detection.yaml
  dns/detect-dangling-cname.yaml
Labels: Done

#8261 Create shiro-deserialization-detection.yaml
  helpers/wordlists/shiro_encrypted_keys.txt
  http/vulnerabilities/apache/shiro/shiro-deserialization-detection.yaml
Labels: Done

#8310 Update api-tatum.yaml
  http/token-spray/api-tatum.yaml
Labels: Done

#8289 Added a google bucket detecter
  file/android/google-storage-bucket.yaml
Labels: good first issue, Done

#8299 Create unauth-celery-flower.yaml
  http/misconfiguration/unauth-celery-flower.yaml
Labels: Done

#8305 Create milesight-system-log.yaml
  http/exposures/logs/milesight-system-log.yaml
Labels: Done

#8301 Create CVE-2023-33831.yaml
  http/cves/2023/CVE-2023-33831.yaml
Labels: Done

#8286 Update CVE-2019-6802.yaml
  http/cves/2019/CVE-2019-6802.yaml
Labels: good first issue, Done

#8295 Create CVE-2023-30625.yaml
  http/cves/2023/CVE-2023-30625.yaml
Labels: Done

#8272 Create CVE-2023-22432.yaml
  http/cves/2023/CVE-2023-22432.yaml
Labels: Done

#8171 Update template pi-hole-detect.yaml to detect new versions
  http/technologies/pi-hole-detect.yaml
Labels: Done

#8306 Update php-backup-files.yaml
  http/exposures/backups/php-backup-files.yaml
Labels: Done

#8316 Create CVE-2022-48197.yaml
  http/cves/2022/CVE-2022-48197.yaml
Labels: Done

#8308 Create CVE-2023-2224.yaml
  http/cves/2023/CVE-2023-2224.yaml
Labels: Done

#8319 Create sangfor-ngaf-lfi.yaml
  http/vulnerabilities/sangfor/sangfor-ngaf-lfi.yaml
Labels: Done

#8318 Exim Detect template
  network/detection/exim-detect.yaml
Labels: Done

#8315 Create CVE-2023-38501.YAML
  http/cves/2023/CVE-2023-38501.yaml
Labels: Done

#8334 Update config-json.yaml
  http/exposures/configs/config-json.yaml
Labels: Done

#8333 Update symfony-fosjrouting-bundle.yaml
  http/misconfiguration/symfony-fosjrouting-bundle.yaml
Labels: Done

#8322 Resolve some issues to capture missed items
  http/exposed-panels/sidekiq-dashboard.yaml
Labels: good first issue, Done

#8290 CVE-2023-33405.yaml
  http/cves/2023/CVE-2023-33405.yaml
  http/exposures/tokens/twilio/twilio-api-key.yaml
Labels: Done

#8332 Create xploitspy-default-login.yaml
  http/default-logins/xploitspy/xploitspy-default-login.yaml
Labels: Done

#8335 Update CVE-2020-8813.yaml
  http/cves/2020/CVE-2020-8813.yaml
Labels: Done

#8323 implement wordpress-yoast-seo-user-enumeration
  http/vulnerabilities/wordpress/wp-yoast-user-enumeration.yaml
Labels: Hacktoberfest, Done

#8337 Create CVE-2023-34259
  http/cves/2023/CVE-2023-34259.yaml
  http/iot/kyocera-printer-panel.yaml
Labels: Hacktoberfest, Done

#8339 Create phpSysInfo Exposure Template
  http/exposures/configs/phpsys-info.yaml
Labels: Hacktoberfest, Done

#8343 Create dashy-panel.yaml
  http/exposed-panels/dashy-panel.yaml
Labels: Hacktoberfest, Done

#8341 Create CVE-2023-41642.yaml
  http/cves/2023/CVE-2023-41642.yaml
Labels: Done

#8344 Create jellyseerr-login-panel.yaml
  http/exposed-panels/jellyseerr-login-panel.yaml
Labels: Hacktoberfest, Done

#8346 Create filebrowser-login-panel.yaml
  http/exposed-panels/filebrowser-login-panel.yaml
Labels: Done

#8347 Create filebrowser-unauth.yaml
  http/misconfiguration/filebrowser-unauth.yaml
Labels: Hacktoberfest, Done

#8348 Create audiobookshelf-panel.yaml
  http/exposed-panels/audiobookshelf-panel.yaml
Labels: Hacktoberfest, Done

#8349 Create portainer-panel.yaml
  http/exposed-panels/portainer-panel.yaml
Labels: Hacktoberfest, Done

#8342 Create CVE-2023-31465.yaml
  http/cves/2023/CVE-2023-31465.yaml
Labels: Hacktoberfest, Done

#8351 KLR 300N Router Panel - Detect
  http/exposed-panels/klr300n-panel.yaml
Labels: Hacktoberfest, Done

#8293 Create CVE-2023-30013.yaml
  http/cves/2023/CVE-2023-30013.yaml
Labels: Done

#8359 updated protocol name
  http/cves/2023/CVE-2023-30625.yaml
Labels: Done

#8358 Create viminfo-disclosure.yaml
  http/exposures/files/viminfo-disclosure.yaml
Labels: Hacktoberfest, Done

#8352 Create psalm-config.yaml
  http/exposures/configs/psalm-config.yaml
Labels: Hacktoberfest, Done

#8353 Create phpcs-config.yaml
  http/exposures/configs/phpcs-config.yaml
Labels: Hacktoberfest, Done

#8356 Create rakefile-disclosure.yaml
  http/exposures/configs/rakefile-disclosure.yaml
Labels: Hacktoberfest, Done

#8361 Added CVE-2023-22515
  http/cves/2023/CVE-2023-22515.yaml
Labels: Hacktoberfest, Done

#8363 Create CVE-2023-35813.yaml (Sitecore - Remote Code Execution 🔥 )
  http/cves/2023/CVE-2023-35813.yaml
Labels: Hacktoberfest, Done

#8364 Cognito Developer Authentication Sample - Detect
  http/technologies/default-amazon-cognito.yaml
Labels: Hacktoberfest, Done

#8365 Create CVE-2022-25568.yaml
  http/cves/2022/CVE-2022-25568.yaml
Labels: Hacktoberfest, Done

#8336 updated oast matchers
  http/cves/2020/CVE-2020-14750.yaml
  http/cves/2021/CVE-2021-20167.yaml
  http/vulnerabilities/other/sponip-network-system-ping-rce.yaml
Labels: Hacktoberfest, Done

#8370 Updated regex
  http/exposures/tokens/jotform/jotform-api-key.yaml
Labels: Done

#8366 exposed-gitignore - Exclude text/xml Content-Type
  http/exposures/configs/exposed-gitignore.yaml
Labels: Done

#8360 Update AWS Bucket Takeover
  http/takeovers/aws-bucket-takeover.yaml
Labels: Hacktoberfest, Done

#8312 Add template to detect instance of SphinxOnline product
  http/exposed-panels/sphinxonline-panel.yaml
Labels: Hacktoberfest, Done

#8378 Create CVE-2023-4451.yaml
  http/cves/2023/CVE-2023-4451.yaml
Labels: Done

#8381 Added CVE-2021-41749 CraftCMS SEOMatic Plugin SSTI
  http/cves/2021/CVE-2021-41749.yaml
Labels: Hacktoberfest, Done

#8383 Update phpmyadmin-setup.yaml and CVE-2022-21500.yaml
  http/cves/2022/CVE-2022-21500.yaml
  http/misconfiguration/phpmyadmin/phpmyadmin-setup.yaml
Labels: Hacktoberfest, Done

#8377 Add template to detect instance of Check Point Mobile SSL VPN product.
  http/technologies/checkpoint-mobile-detect.yaml
Labels: Hacktoberfest, Done

#8385 Add some upper case extensions for wordpress-accessible-wpconfig
  http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
Labels: good first issue, Hacktoberfest, Done

#8394 Create CVE-2023-3710.yaml
  http/cves/2023/CVE-2023-3710.yaml
Labels: good first issue, Hacktoberfest, Done

#8402 Create CVE-2021-25016.yaml
  http/cves/2021/CVE-2021-25016.yaml
Labels: Hacktoberfest, Done

#8401 Create CVE-2023-37728.yaml
  http/cves/2023/CVE-2023-37728.yaml
Labels: Hacktoberfest, Done

#8390 Update wordpress-accessible-wpconfig.yaml
  http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
Labels: Hacktoberfest, Done

#8396 Create servicenow-widget-misconfig.yaml 🔥
  http/misconfiguration/servicenow-widget-misconfig.yaml
Labels: Hacktoberfest, Done

#8400 Create kingsoft-vgm-lfi.yaml
  http/vulnerabilities/other/kingsoft-vgm-lfi.yaml
Labels: Hacktoberfest, Done

#8399 Create CVE-2022-0597.yaml
  http/cves/2022/CVE-2022-0597.yaml
Labels: Hacktoberfest, Done

#8412 Fixing weak matchers
  http/default-logins/franklin-fueling-default-login.yaml
  http/vulnerabilities/other/taiwanese-travel-lfi.yaml
  http/vulnerabilities/wordpress/wp-ellipsis-xss.yaml
Labels: Done

#8418 reduce no of request
  http/misconfiguration/servicenow-widget-misconfig.yaml
Labels: Done

#8409 Create CVE-2023-5360.yaml
  http/cves/2023/CVE-2023-5360.yaml
Labels: Hacktoberfest, Done

#8420 Update joomla-com-booking-component.yaml
  http/vulnerabilities/joomla/joomla-com-booking-component.yaml
Labels: Done

#8422 Update and rename oracle-httpserver12c.yaml to oracle-httpserver-12c.…
  http/technologies/oracle-httpserver-12c.yaml
  http/technologies/oracle-httpserver12c.yaml
Labels: Done

#8424 reverted log4j templates
  http/cves/2021/CVE-2021-44228.yaml
  http/cves/2021/CVE-2021-45046.yaml
  http/vulnerabilities/apache/apache-ofbiz-log4j-rce.yaml
  http/vulnerabilities/apache/apache-solr-log4j-rce.yaml
  http/vulnerabilities/apache/log4j/jamf-pro-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-cloudcenter-suite-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-unified-communications-log4j.yaml
  http/vulnerabilities/code42/code42-log4j-rce.yaml
  http/vulnerabilities/jamf/jamf-log4j-jndi-rce.yaml
  http/vulnerabilities/mobileiron/mobileiron-log4j-jndi-rce.yaml
  http/vulnerabilities/other/elasticsearch5-log4j-rce.yaml
  http/vulnerabilities/other/goanywhere-mft-log4j-rce.yaml
  http/vulnerabilities/other/graylog-log4j.yaml
  http/vulnerabilities/other/metabase-log4j.yaml
  http/vulnerabilities/other/opennms-log4j-jndi-rce.yaml
  http/vulnerabilities/other/rundeck-log4j.yaml
  http/vulnerabilities/other/unifi-network-log4j-rce.yaml
  http/vulnerabilities/other/vmware-siterecovery-log4j-rce.yaml
  http/vulnerabilities/other/xenmobile-server-log4j.yaml
  http/vulnerabilities/springboot/springboot-log4j-rce.yaml
  http/vulnerabilities/vmware/vmware-hcx-log4j.yaml
  http/vulnerabilities/vmware/vmware-horizon-log4j-jndi-rce.yaml
  http/vulnerabilities/vmware/vmware-nsx-log4j.yaml
  http/vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
  http/vulnerabilities/vmware/vmware-vcenter-log4j-jndi-rce.yaml
  http/vulnerabilities/vmware/vrealize-operations-log4j-rce.yaml
Labels: Done

#8395 Create springboot-prometheus.yaml
  http/misconfiguration/prometheus/prometheus-log.yaml
Labels: Hacktoberfest, Done

#8397 Atlassian Connect Descriptor - Detect
  http/technologies/atlassian-connect-descriptor.yaml
Labels: Hacktoberfest, Done

#8404 Opache control Panel - Unauthenticated Access
  http/misconfiguration/unauth-opache-control-panel.yaml
Labels: Hacktoberfest, Done

#8429 Create wp-kadence-blocks-rce.yaml
  http/vulnerabilities/wordpress/wp-kadence-blocks-rce.yaml
Labels: Hacktoberfest, Done

#8425 Add template to detect RCDevs WebADM instances
  http/exposed-panels/rcdevs-webadm-panel.yaml
Labels: Hacktoberfest, Done

#8439 Update CVE-2023-0297
  http/cves/2023/CVE-2023-0297.yaml
Labels: Hacktoberfest, Done

#8376 Elasticbeanstalk Takeover - Fix for non-vulnerable false positives
  dns/elasticbeanstalk-takeover.yaml
  http/takeovers/heroku-takeover.yaml
Labels: Done

#8432 Add new matchers and extractors for PLESK template
  http/exposed-panels/plesk-onyx-login.yaml
Labels: Done

#8426 Oracle TNS Listener - Detect
  javascript/network/detection/oracle-tns-listner.yaml
Labels: Hacktoberfest, Done

#8451 LiveBOS - Arbitrary File Read
  http/vulnerabilities/other/livebos-file-read.yaml
Labels: Done

#8456 Create webtitan-cloud-panel.yaml
  http/exposed-panels/webtitan-cloud-panel.yaml
Labels: Done

#8454 Update url-extension-inspector.yaml (avoid false positive)
  file/url-analyse/url-extension-inspector.yaml
Labels: Hacktoberfest, Done

#8447 Update servicenow-widget-misconfig.yaml
  http/misconfiguration/servicenow-widget-misconfig.yaml
Labels: Hacktoberfest, Done

#8445 Tempate to detect instance of Alcatel-Lucent OpenTouch™ Multimedia Services
  http/exposed-panels/opentouch-multimediaservices-panel.yaml
Labels: Hacktoberfest, Done

#8444 Create solarwinds-arm-detect.yaml
  http/exposed-panels/solarwinds-arm-panel.yaml
Labels: Hacktoberfest, Done

#8324 Multiple XSS in BestWebSoft Plugins
  http/cves/2017/CVE-2017-18487.yaml
  http/cves/2017/CVE-2017-18490.yaml
  http/cves/2017/CVE-2017-18491.yaml
  http/cves/2017/CVE-2017-18492.yaml
  http/cves/2017/CVE-2017-18493.yaml
  http/cves/2017/CVE-2017-18494.yaml
  http/cves/2017/CVE-2017-18496.yaml
  http/cves/2017/CVE-2017-18500.yaml
  http/cves/2017/CVE-2017-18501.yaml
  http/cves/2017/CVE-2017-18502.yaml
  http/cves/2017/CVE-2017-18505.yaml
  http/cves/2017/CVE-2017-18516.yaml
  http/cves/2017/CVE-2017-18517.yaml
  http/cves/2017/CVE-2017-18518.yaml
  http/cves/2017/CVE-2017-18527.yaml
  http/cves/2017/CVE-2017-18528.yaml
  http/cves/2017/CVE-2017-18529.yaml
  http/cves/2017/CVE-2017-18530.yaml
  http/cves/2017/CVE-2017-18532.yaml
  http/cves/2017/CVE-2017-18537.yaml
  http/cves/2017/CVE-2017-18542.yaml
  http/cves/2017/CVE-2017-18556.yaml
  http/cves/2017/CVE-2017-18557.yaml
  http/cves/2017/CVE-2017-18558.yaml
  http/cves/2017/CVE-2017-18562.yaml
  http/cves/2017/CVE-2017-18564.yaml
  http/cves/2017/CVE-2017-18565.yaml
  http/cves/2017/CVE-2017-18566.yaml
Labels: Hacktoberfest, Done

#8452 Create CVE-2023-4966.yaml (Citrix Bleed - Leaking Session Tokens)
  http/cves/2023/CVE-2023-4966.yaml
Labels: Hacktoberfest, Done

#8441 Template to detect instance of Regify product
  http/exposed-panels/regify-panel.yaml
Labels: Hacktoberfest, Done

#8455 Template to detect instances of ASYS Chronos
  http/exposed-panels/chronos-panel.yaml
Labels: Hacktoberfest, Done

#8453 Create orbit-telephone-system-detection.yaml
  http/technologies/orbit-telephone-detect.yaml
Labels: Hacktoberfest, Done

#8450 Fix tiny-file-manager
  http/exposed-panels/tiny-file-manager.yaml
Labels: Hacktoberfest, Done

#8471 Vinchin Backup & Recovery Panel
  http/exposed-panels/vinchin-panel.yaml
Labels: Hacktoberfest, Done

#8470 Create tiny-file-manager-unauth.yaml
  http/misconfiguration/tiny-file-manager-unauth.yaml
Labels: Hacktoberfest, Done

#8474 FileName Fix
  http/cves/2023/CVE-2023-45852.yaml
Labels: Hacktoberfest, Done

#8475 Fix matcher regex
  dns/caa-fingerprint.yaml
Labels: Hacktoberfest, Done

#8461 Added NextGen Mirth Connect Remote Code Execution Vulnerability (CVE-2023-43208)
  http/cves/2023/CVE-2023-37679.yaml
Labels: Hacktoberfest, Done

#8477 News and blog designer pack Wordpress plugin - LFI leading to RCE
  http/vulnerabilities/wordpress/blog-designer-pack-rce.yaml
Labels: Hacktoberfest, Done

#8427 CVE-2023-20198 Implant Detection Template
  http/vulnerabilities/backdoor/cisco-implant-detect.yaml
Labels: good first issue, Done

#8482 authelia-panel
  http/exposed-panels/authelia-panel.yaml
Labels: Hacktoberfest, Done

#8473 Update sftp-credentials-exposure.yaml
  http/exposures/configs/sftp-config-exposure.yaml
  http/exposures/configs/sftp-credentials-exposure.yaml
Labels: Done

#8480 Create mappproxy-detect.yaml
  http/technologies/mappproxy-detect.yaml
Labels: Hacktoberfest, Done

#8469 Add "js-detect" headless tech template
  headless/technologies/js-libraries-detect.yaml
Labels: Done

#8459 Add: CVE-2022-36553
  http/cves/2022/CVE-2022-36553.yaml
Labels: Hacktoberfest, Done

#8495 tautulli-panel
  http/exposed-panels/tautulli-panel.yaml
Labels: Hacktoberfest, Done

#8494 immich panel
  http/exposed-panels/immich-panel.yaml
Labels: Hacktoberfest, Done

#8493 Security onion panel
  http/exposed-panels/security-onion-panel.yaml
Labels: Hacktoberfest, Done

#8492 automatisch-panel
  http/exposed-panels/automatisch-panel.yaml
Labels: Hacktoberfest, Done

#8489 scribble-diffusion-panel
  http/exposed-panels/scribble-diffusion-panel.yaml
Labels: Hacktoberfest, Done

#8484 homebridge-panel
  http/exposed-panels/homebridge-panel.yaml
Labels: Hacktoberfest, Done

#8483 changedetection-panel
  http/exposed-panels/changedetection-panel.yaml
Labels: Hacktoberfest, Done

#8485 Memos panel detect
  http/exposed-panels/memos-panel.yaml
Labels: Hacktoberfest, Done

#8488 speedtest-panel
  http/exposed-panels/speedtest-panel.yaml
Labels: Done

#8497 Template to detect "Kiteworks PCN" instances
  http/exposed-panels/kiteworks-pcn-panel.yaml
Labels: Hacktoberfest, Done

#8490 truenas-scale-panel
  http/exposed-panels/truenas-scale-panel.yaml
Labels: Hacktoberfest, Done

#8467 Create cisco-ios-xe-panel.yaml
  http/exposed-panels/cisco/cisco-ios-xe-panel.yaml
Labels: Hacktoberfest, Done

#6663 Create goip-default-login.yaml
  http/default-logins/goip-default-login.yaml
Labels: Done, defcon31

#8487 plausible-panel
  http/exposed-panels/plausible-panel.yaml
Labels: Done

#8486 overseerr-panel
  http/exposed-panels/overseerr-panel.yaml
Labels: Hacktoberfest, Done

#8468 Add case insensitive match and signature
  http/token-spray/api-weglot.yaml
Labels: good first issue, Hacktoberfest, Done

#8457 Update ray-dashboard.yaml severity to critical
  http/misconfiguration/ray-dashboard.yaml
Labels: good first issue, Hacktoberfest

#8507 Added CVE-2023-20198 (Cisco IOS XE - Authentication Bypass)
  http/cves/2023/CVE-2023-20198.yaml
Labels: Hacktoberfest, Done

#8508 Create metform.txt
  helpers/wordpress/plugins/metform.txt
Labels: Hacktoberfest, Done

#8501 Update cisco-implant-detect.yaml
  http/vulnerabilities/backdoor/cisco-implant-detect.yaml
Labels: Hacktoberfest, Done

#8504 Create cube-105-install.yaml
  http/misconfiguration/installer/cube-105-install.yaml
Labels: Hacktoberfest, Done

#8502 Create tautulli-install.yaml
  http/misconfiguration/installer/tautulli-install.yaml
Labels: Hacktoberfest, Done

#8500 Fix CVE-2023-46747.yaml
  http/cves/2023/CVE-2023-46747.yaml
Labels: good first issue, Hacktoberfest, Done
