Repository projectdiscovery/nuclei-templates, pull requests merged in 2023-07, with the labels that each got.

#7588 Create CVE-2023-30019.yaml
  http/cves/2023/CVE-2023-30019.yaml
Labels: Done

#7582 removed request for diff ports
  http/cves/2022/CVE-2022-35405.yaml
Labels: Done

#7589 Added CVE-2023-1496
  http/cves/2023/CVE-2023-1496.yaml
Labels: Done

#7578 Update aws-bucket-takeover.yaml
  http/takeovers/aws-bucket-takeover.yaml
Labels: Done

#7519 Create CVE-2023-34659.yaml
  http/cves/2023/CVE-2023-34659.yaml
Labels: Done

#7528 Create CVE-2023-34537.yaml
  http/cves/2023/CVE-2023-34537.yaml
Labels: Done

#7567 PostgreSQL - User Enumeration
  network/enumeration/psql-user-enum.yaml
Labels: Done

#7564 PostgreSQL - Unauthenticated Access
  network/misconfig/unauth-psql.yaml
Labels: Done

#7553 Create CVE-2023-0527.yaml
  http/cves/2023/CVE-2023-0527.yaml
Labels: Done

#7232 Update webflow-takeover.yaml
  http/takeovers/webflow-takeover.yaml
Labels: Done

#7596 better extractor (using json)
  http/exposures/apis/drupal-jsonapi-user-listing.yaml
Labels: Done

#7597 Fixed CVE-2022-29153
  http/cves/2022/CVE-2022-29153.yaml
Labels: Done

#7598 updated names
  file/nodejs/express-lfr.yaml
  file/nodejs/generic-path-traversal.yaml
  file/nodejs/tar-path-overwrite.yaml
Labels: Done

#7594 Create pritunl-panel.yaml
  http/exposed-panels/pritunl-panel.yaml
Labels: Done

#7599 Create untangle-admin-login.yaml
  http/exposed-panels/untangle-admin-login.yaml
Labels: Done

#7605 Create CVE-2023-28121.yaml
  http/cves/2023/CVE-2023-28121.yaml
Labels: Done

#7504 dell idrac detection
  http/exposed-panels/dell-idrac.yaml
Labels: Done

#6024 Add ASP.NET, ASP, JSP and PHP web shell files scanner
  file/webshell/asp-webshell.yaml
  file/webshell/jsp-webshell.yaml
  file/webshell/php-webshell.yaml
Labels: Done

#7603 Update cacti-weathermap-file-write.yaml removing broken reference
  http/vulnerabilities/other/cacti-weathermap-file-write.yaml
Labels: Done

#7600 Update and rename addeventlistener-detect to addeventlistener-detect.…
  http/miscellaneous/addeventlistener-detect.yaml
Labels: Done

#7604 Heroku Takeover
  http/takeovers/heroku-takeover.yaml
Labels: good first issue, Done

#5545 Create CVE-2018-6530
  http/cves/2018/CVE-2018-6530.yaml
Labels: Done

#7606 Update CVE-2023-24488.yaml
  http/cves/2023/CVE-2023-24488.yaml
Labels: Done

#7610 Fixed FN - CVE-2023-28432
  http/cves/2023/CVE-2023-28432.yaml
Labels: Done

#7592 Create efak-panel.yaml
  http/exposed-panels/efak-panel.yaml
Labels: Done

#7572 Better bash-history matching
  http/misconfiguration/shell-history.yaml
Labels: Done

#7574 HunterMapping Trending Panels
  http/exposed-panels/arcserve-panel.yaml
  http/exposed-panels/cloudpanel-login.yaml
Labels: Done

#7614 Update dom-xss.yaml
  file/xss/dom-xss.yaml
Labels: Done

#7518 Create collibra-properties.yaml
  http/exposures/configs/collibra-properties.yaml
Labels: Done

#7591 Create shell-box.yaml
  http/exposed-panels/shell-box.yaml
Labels: Done

#7593 Create uptime-kuma-panel.yaml
  http/exposed-panels/uptime-kuma-panel.yaml
Labels: Done

#6405 CNVD-2022-86535
  http/cnvd/2022/CNVD-2022-86535.yaml
Labels: Done

#7621 Update gitlab-login-check-self-hosted.yaml
  http/credential-stuffing/self-hosted/gitlab-login-check-self-hosted.yaml
Labels: Done

#7209 Dashboard Content Enhancements
  file/android/biometric-detect.yaml
  file/android/certificate-validation.yaml
  file/android/content-scheme.yaml
  file/android/debug-enabled.yaml
  file/android/deep-link-detect.yaml
  file/android/dynamic-broadcast-receiver.yaml
  file/android/file-scheme.yaml
  file/android/provider-path.yaml
  file/android/webview-addjavascript-interface.yaml
  file/android/webview-javascript.yaml
  file/android/webview-load-url.yaml
  file/android/webview-universal-access.yaml
  file/audit/cisco/configure-aaa-service.yaml
  file/audit/cisco/configure-service-timestamps-debug.yaml
  file/audit/cisco/configure-service-timestamps-logmessages.yaml
  file/audit/cisco/disable-ip-source-route.yaml
  file/audit/cisco/disable-pad-service.yaml
  file/audit/cisco/logging-enable.yaml
  file/audit/cisco/set-and-secure-passwords.yaml
  file/audit/fortigate/auto-usb-install.yaml
  file/audit/fortigate/heuristic-scan.yaml
  file/audit/fortigate/inactivity-timeout.yaml
  file/audit/fortigate/maintainer-account.yaml
  file/audit/fortigate/password-policy.yaml
  file/audit/fortigate/remote-auth-timeout.yaml
  file/audit/fortigate/scp-admin.yaml
  file/audit/pfsense/configure-dns-server.yaml
  file/audit/pfsense/configure-session-timeout.yaml
  file/audit/pfsense/enable-https-protocol.yaml
  file/audit/pfsense/known-default-account.yaml
  file/audit/pfsense/password-protected-consolemenu.yaml
  file/audit/pfsense/set-hostname.yaml
  file/electron/electron-version-detect.yaml
  file/keys/amazon/amazon-account-id.yaml
  file/keys/amazon/amazon-mws-auth-token.yaml
  file/keys/amazon/amazon-session-token.yaml
  file/keys/amazon/amazon-sns-token.yaml
  file/keys/amazon/aws-access-id.yaml
  file/keys/amazon/aws-cognito.yaml
  file/keys/branch-key.yaml
  file/keys/cloudinary.yaml
  file/keys/code-climate-token.yaml
  file/keys/cratesio-api-key.yaml
  file/keys/credential-exposure.yaml
  file/keys/credentials.yaml
  file/keys/dynatrace-token.yaml
  file/keys/facebook/facebook-client-id.yaml
  file/keys/facebook/facebook-secret.yaml
Labels: Done

#7525 Updated php-backup extensions
  http/exposures/backups/php-backup-files.yaml
Labels: Done

#7617 updated intrusive templates
  http/cves/2017/CVE-2017-6090.yaml
  http/cves/2020/CVE-2020-17518.yaml
  http/cves/2020/CVE-2020-24186.yaml
  http/cves/2020/CVE-2020-25213.yaml
  http/cves/2020/CVE-2020-28871.yaml
  http/cves/2020/CVE-2020-35489.yaml
  http/cves/2021/CVE-2021-1499.yaml
  http/cves/2021/CVE-2021-21978.yaml
  http/cves/2021/CVE-2021-3378.yaml
  http/cves/2021/CVE-2021-43421.yaml
  http/exposed-panels/roxy-fileman.yaml
Labels: Done

#6480 node.js package manager update
  contributors.json
  http/exposures/configs/package-json.yaml
  http/exposures/files/bower-json.yaml
  http/exposures/files/npm-shrinkwrap-exposure.yaml
  http/exposures/files/pnpm-lock.yaml
  http/exposures/files/yarn-lock.yaml
Labels: Done

#7613 CVE-2023-0297.yaml
  http/cves/2023/CVE-2023-0297.yaml
Labels: Done

#7636 Update .nuclei-ignore
  .nuclei-ignore
Labels: Done

#7616 Create CVE-2023-2822.yaml
  http/cves/2023/CVE-2023-2822.yaml
Labels: Done

#7434 Create CVE-2012-5321.yaml
  http/cves/2012/CVE-2012-5321.yaml
Labels: Done

#7420 Create apache-dubbo-unauth.yaml
  network/misconfig/apache-dubbo-unauth.yaml
Labels: Done

#7408 Create apache-rocketmq-broker-unauth.yaml
  network/misconfig/apache-rocketmq-broker-unauth.yaml
Labels: Done

#7629 Pyload Panel & Default Login
  http/default-logins/pyload/pyload-default-login.yaml
  http/exposed-panels/pyload-panel.yaml
Labels: Done

#7366 Add Temporal Web UI
  http/misconfiguration/unauth-temporal-web-ui.yaml
  http/technologies/favicon-detect.yaml
Labels: Done

#7635 Fixed FP - CVE-2022-40083
  http/cves/2022/CVE-2022-40083.yaml
Labels: Done

#7466 Create open-proxy-external.yaml
  misconfiguration/proxy/open-proxy-external.yaml
Labels: Done

#7633 Hookbot Rat Panel
  http/exposed-panels/c2/hookbot-rat.yaml
Labels: Done

#7632 Esafenet CDG - Default Login
  http/default-logins/esafenet-cdg-default-login.yaml
Labels: Done

#7372 sitemap-sql
  http/vulnerabilities /other/sitemap-sql-injection.yaml
Labels: good first issue, Done

#7639 Rename universal-media-xss.yaml to universal-media-xss.yaml
  http/vulnerabilities/other/universal-media-xss.yaml
Labels: Done

#7637 CVEs added
  http/cves/2019/CVE-2019-14789.yaml
  http/cves/2019/CVE-2019-8390.yaml
  http/cves/2020/CVE-2020-19515.yaml
  http/cves/2020/CVE-2020-35984.yaml
  http/cves/2020/CVE-2020-35985.yaml
  http/cves/2020/CVE-2020-35986.yaml
  http/cves/2020/CVE-2020-35987.yaml
  http/cves/2022/CVE-2022-4295.yaml
  http/cves/2022/CVE-2022-43164.yaml
  http/cves/2022/CVE-2022-43165.yaml
  http/cves/2022/CVE-2022-43166.yaml
  http/cves/2022/CVE-2022-43167.yaml
  http/cves/2022/CVE-2022-43169.yaml
  http/cves/2022/CVE-2022-43170.yaml
  http/cves/2022/CVE-2022-43185.yaml
  http/cves/2022/CVE-2022-44944.yaml
  http/cves/2022/CVE-2022-44946.yaml
  http/cves/2022/CVE-2022-44947.yaml
  http/cves/2022/CVE-2022-44948.yaml
  http/cves/2022/CVE-2022-44949.yaml
  http/cves/2022/CVE-2022-44950.yaml
  http/cves/2022/CVE-2022-44951.yaml
  http/cves/2022/CVE-2022-44952.yaml
  http/cves/2023/CVE-2023-0514.yaml
  http/cves/2023/CVE-2023-1730.yaml
  http/cves/2023/CVE-2023-1835.yaml
  http/cves/2023/CVE-2023-1890.yaml
  http/cves/2023/CVE-2023-2023.yaml
  http/cves/2023/CVE-2023-2252.yaml
  http/cves/2023/CVE-2023-2272.yaml
  http/cves/2023/CVE-2023-26842.yaml
  http/cves/2023/CVE-2023-26843.yaml
  http/cves/2023/CVE-2023-30256.yaml
  http/cves/2023/CVE-2023-30777.yaml
  http/cves/2023/CVE-2023-31548.yaml
  http/cves/2023/CVE-2023-36287.yaml
  http/cves/2023/CVE-2023-36289.yaml
  http/cves/2023/CVE-2023-36346.yaml
  http/exposed-panels/qdpm-login-panel.yaml
  http/vulnerabilities/other/yeswiki-stored-xss.yaml
  http/vulnerabilities/wordpress/contus-video-gallery-sqli.yaml
  http/vulnerabilities/wordpress/leaguemanager-sql-injection.yaml
  http/vulnerabilities/wordpress/notificationx-sqli.yaml
  http/vulnerabilities/wordpress/zero-spam-sql-injection.yaml
Labels: Done

#7640 Mystic Stealer Panel
  http/exposed-panels/c2/mystic-stealer.yaml
Labels: Done

#7552 Create CVE-2023-33439.yaml
  http/cves/2023/CVE-2023-33439.yaml
Labels: Done

#7601 Network Directory - Restructuring
  network/backdoor/vsftpd-backdoor.yaml
  network/default-login/ftp-anonymous-login.yaml
  network/default-login/ftp-weak-credentials.yaml
  network/detection/detect-addpac-voip-gateway.yaml
  network/detection/detect-jabber-xmpp.yaml
  network/detection/expn-mail-detect.yaml
  network/detection/sap-router.yaml
  network/exposures/cisco-smi-exposure.yaml
  network/exposures/exposed-adb.yaml
  network/exposures/exposed-dockerd.yaml
  network/exposures/exposed-redis.yaml
  network/exposures/exposed-zookeeper.yaml
  network/misconfig/clamav-unauth.yaml
  network/misconfig/clickhouse-unauth.yaml
  network/misconfig/ganglia-xml-grid-monitor.yaml
  network/misconfig/memcached-stats.yaml
  network/misconfig/mongodb-unauth.yaml
  network/misconfig/mysql-native-password.yaml
  network/misconfig/printers-info-leak.yaml
  network/misconfig/sap-router-info-leak.yaml
  network/misconfig/tidb-native-password.yaml
  network/misconfig/tidb-unauth.yaml
  workflows/sap-netweaver-workflow.yaml
Labels: Done

#7634 Create leostream-default-login.yaml
  http/default-logins/leostream/leostream-default-login.yaml
Labels: Done

#7646 Release Prep
  http/cves/2018/CVE-2018-6530.yaml
  http/cves/2023/CVE-2023-36346.yaml
  http/exposed-panels/dell-idrac.yaml
  http/misconfiguration/proxy/open-proxy-external.yaml
  http/vulnerabilities/other/sitemap-sql-injection.yaml
Labels: Done

#7643 Create sunbird-dcim-panel.yaml
  http/exposed-panels/sunbird-dcim-panel.yaml
Labels: Done

#7580 Create CVE-2022-46073.yaml
  http/cves/2022/CVE-2022-46073.yaml
Labels: Done

#7651 Updated EPSS Score to CVE Templates
  network/cves/2001/CVE-2001-1473.yaml
  network/cves/2011/CVE-2011-2523.yaml
  network/cves/2015/CVE-2015-3306.yaml
  network/cves/2016/CVE-2016-2004.yaml
  network/cves/2016/CVE-2016-3510.yaml
  network/cves/2017/CVE-2017-5645.yaml
  network/cves/2018/CVE-2018-2628.yaml
  network/cves/2018/CVE-2018-2893.yaml
  network/cves/2020/CVE-2020-11981.yaml
  network/cves/2022/CVE-2022-24706.yaml
Labels: Done

#7537 Create CVE-2016-10973.yaml
  http/cves/2016/CVE-2016-10973.yaml
Labels: Done

#7647 Create rhadamanthys-stealer-panel.yaml
  http/exposed-panels/c2/rhadamanthys-stealer-panel.yaml
Labels: Done

#7579 Create CVE-2022-46071.yaml
  http/cves/2022/CVE-2022-46071.yaml
Labels: Done

#7539 Create CVE-2023-33440.yaml
  http/cves/2023/CVE-2023-33440.yaml
Labels: Done

#6135 Create CVE-2022-40127.yaml
  cves/2022/CVE-2022-40127.yaml
Labels: Done

#7645 Create d-link-auth-bypass.yaml
  cves.json-checksum.txt
  http/misconfiguration/dlink-config-dump.yaml
Labels: Done

#7649 Add CVE-2023-3479
  http/cves/2023/CVE-2023-3479.yaml
Labels: Done

#7655 Update leostream-default-login.yaml
  http/default-logins/leostream/leostream-default-login.yaml
Labels: Done

#7667 Updated the payload list and attack type of the Tomcat default login detection template
  http/default-logins/apache/tomcat-default-login.yaml
Labels: Done

#7664 CVE-2023-24489 🔥 Citrix ShareFile StorageZones Controller - RCE
  helpers/payloads/citrix_paddings.txt
  http/cves/2023/CVE-2023-24489.yaml
Labels: Done

#7661 Create sharefile-storage-server.yaml
  http/technologies/sharefile-storage-server.yaml
Labels: Done

#7672 sonarqube-default-credentials
  http/default-logins/sonarqube/sonarqube-default-login.yaml
Labels: good first issue, Done

#7668 Create sharefile-panel.yaml
  http/exposed-panels/sharefile-panel.yaml
Labels: Done

#7674 Create vercel-takeover.yaml
  http/takeovers/vercel-takeover.yaml
Labels: good first issue, Done

#7657 Update exposed-kibana.yaml
  http/misconfiguration/exposed-kibana.yaml
Labels: good first issue, Done

#7665 Create CVE-2023-2796.yaml
  http/cves/2023/CVE-2023-2796.yaml
Labels: Done

#7671 Create CVE-2022-45354.yaml
  http/cves/2022/CVE-2022-45354.yaml
Labels: Done

#7678 Create CVE-2022-4057.yaml
  http/cves/2022/CVE-2022-4057.yaml
Labels: Done

#7666 Create prometheus-promtail.yaml
  http/misconfiguration/prometheus-promtail.yaml
Labels: Done

#7656 Fixed 2021-40822
  http/cves/2021/CVE-2021-40822.yaml
Labels: good first issue, Done

#7680 fixed typo (CVE-2021-40822)
  http/cves/2021/CVE-2021-40822.yaml
Labels: Done

#7677 Create CVE-2023-29298.yaml
  http/cves/2023/CVE-2023-29298.yaml
Labels: Done

#6514 Create spnego_http.yaml
  miscellaneous/spnego.yaml
Labels: good first issue, Done

#7648 Update sitemap-sql-injection.yaml
  http/vulnerabilities/other/sitemap-sql-injection.yaml
Labels: Done

#7673 Create CVE-2023-37270.yaml
  http/cves/2023/CVE-2023-37270.yaml
Labels: Done

#7685 Update CVE-2023-37270.yaml
  http/cves/2023/CVE-2023-37270.yaml
Labels: Done

#7690 Enhanced to avoid FP
  http/exposures/configs/dbeaver-credentials.yaml
Labels: Done

#7689 Update tomcat-default-login.yaml
  http/default-logins/apache/tomcat-default-login.yaml
Labels: Done

#7692 remove -jarm
  network/jarm/c2/cobalt-strike-c2-jarm.yaml
  network/jarm/c2/covenant-c2-jarm.yaml
  network/jarm/c2/deimos-c2-jarm.yaml
  network/jarm/c2/evilginx2-jarm.yaml
  network/jarm/c2/grat2-c2-jarm.yaml
  network/jarm/c2/mac-c2-jarm.yaml
  network/jarm/c2/macshell-c2-jarm.yaml
  network/jarm/c2/merlin-c2-jarm.yaml
  network/jarm/c2/metasploit-c2-jarm.yaml
  network/jarm/c2/mythic-c2-jarm.yaml
  network/jarm/c2/posh-c2-jarm.yaml
  network/jarm/c2/shad0w-c2-jarm.yaml
  network/jarm/c2/silenttrinity-c2-jarm.yaml
  network/jarm/c2/sliver-c2-jarm.yaml
Labels: Done

#7698 FP Fix Apache Rocketmq Broker
  network/misconfig/apache-rocketmq-broker-unauth.yaml
Labels: Done

#7691 Create yealink-ctp18-default-login.yaml
  http/default-logins/yealink/yealink-default-login.yaml
Labels: good first issue, Done

#7699 Fix FN piwigo-panel.yaml
  http/exposed-panels/piwigo-panel.yaml
Labels: Done

#7704 Create CVE-2023-3460.yaml
  http/cves/2023/CVE-2023-3460.yaml
Labels: Done

#7710 Rename miscellaneous/spnego.yaml to http/miscellaneous/spnego.yaml
  http/miscellaneous/spnego.yaml
Labels: Done

#7709 anaqua-login-detect
  http/exposed-panels/anaqua-login-panel.yaml
Labels: Done

#7706 Fix variable value in emcecom-default-login.yaml
  http/default-logins/dell/emcecom-default-login.yaml
Labels: Done

#7700 Create CVE-2023-3345.yaml
  http/cves/2023/CVE-2023-3345.yaml
Labels: Done

#7602 Modified http/cves/2023/CVE-2023-32243.yaml for better detection
  http/cves/2023/CVE-2023-32243.yaml
Labels: Done

#7708 Template metadata update
  http/vulnerabilities/apache/apache-druid-kafka-connect-rce.yaml
  http/vulnerabilities/apache/apache-ofbiz-log4j-rce.yaml
  http/vulnerabilities/apache/apache-solr-log4j-rce.yaml
  http/vulnerabilities/apache/log4j/jamf-pro-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-cloudcenter-suite-log4j-rce.yaml
  http/vulnerabilities/cisco/cisco-unified-communications-log4j.yaml
  http/vulnerabilities/cisco/cisco-vmanage-log4j.yaml
  http/vulnerabilities/code42/code42-log4j-rce.yaml
  http/vulnerabilities/jamf/jamf-log4j-jndi-rce.yaml
  http/vulnerabilities/mobileiron/mobileiron-log4j-jndi-rce.yaml
  http/vulnerabilities/other/elasticsearch5-log4j-rce.yaml
  http/vulnerabilities/other/goanywhere-mft-log4j-rce.yaml
  http/vulnerabilities/other/graylog-log4j.yaml
  http/vulnerabilities/other/metabase-log4j.yaml
  http/vulnerabilities/other/opennms-log4j-jndi-rce.yaml
  http/vulnerabilities/other/rundeck-log4j.yaml
  http/vulnerabilities/other/unifi-network-log4j-rce.yaml
  http/vulnerabilities/other/vmware-siterecovery-log4j-rce.yaml
  http/vulnerabilities/other/xenmobile-server-log4j.yaml
  http/vulnerabilities/springboot/springboot-log4j-rce.yaml
  http/vulnerabilities/vmware/vmware-hcx-log4j.yaml
  http/vulnerabilities/vmware/vmware-horizon-log4j-jndi-rce.yaml
  http/vulnerabilities/vmware/vmware-nsx-log4j.yaml
  http/vulnerabilities/vmware/vmware-operation-manager-log4j.yaml
  http/vulnerabilities/vmware/vmware-vcenter-log4j-jndi-rce.yaml
  http/vulnerabilities/vmware/vrealize-operations-log4j-rce.yaml
  network/cves/2001/CVE-2001-1473.yaml
  network/cves/2011/CVE-2011-2523.yaml
  network/cves/2015/CVE-2015-3306.yaml
  network/cves/2016/CVE-2016-2004.yaml
  network/cves/2017/CVE-2017-3881.yaml
  network/cves/2017/CVE-2017-5645.yaml
  network/cves/2018/CVE-2018-2628.yaml
  network/cves/2020/CVE-2020-1938.yaml
  network/cves/2020/CVE-2020-7247.yaml
  network/cves/2021/CVE-2021-44521.yaml
  network/cves/2022/CVE-2022-0543.yaml
  network/cves/2022/CVE-2022-24706.yaml
  network/cves/2022/CVE-2022-31793.yaml
  network/cves/2023/CVE-2023-33246.yaml
Labels: Done

#7707 Create CVE-2023-28665.yaml
  http/cves/2023/CVE-2023-28665.yaml
Labels: Done

#7713 Create CVE-2023-0448.yaml
  http/cves/2023/CVE-2023-0448.yaml
Labels: Done

#7705 Create CVE-2020-17463.yaml
  http/cves/2020/CVE-2020-17463.yaml
Labels: good first issue, Done, defcon31

#7701 Create CVE-2023-1546.yaml
  http/cves/2023/CVE-2023-1546.yaml
Labels: Done

#6963 Template/graylog endpoints exposure
  http/technologies/graylog/graylog-endpoints-exposure.yaml
Labels: good first issue, Done

#7693 C2 Jarm - Detect
  network/jarm/c2/cobalt-strike-c2-jarm.yaml
  network/jarm/c2/covenant-c2-jarm.yaml
  network/jarm/c2/deimos-c2-jarm.yaml
  network/jarm/c2/evilginx2-jarm.yaml
  network/jarm/c2/grat2-c2-jarm.yaml
  network/jarm/c2/mac-c2-jarm.yaml
  network/jarm/c2/macshell-c2-jarm.yaml
  network/jarm/c2/merlin-c2-jarm.yaml
  network/jarm/c2/metasploit-c2-jarm.yaml
  network/jarm/c2/mythic-c2-jarm.yaml
  network/jarm/c2/posh-c2-jarm.yaml
  network/jarm/c2/shad0w-c2-jarm.yaml
  network/jarm/c2/silenttrinity-c2-jarm.yaml
  network/jarm/c2/sliver-c2-jarm.yaml
Labels: Done

#7718 Fixed FP - CVE-2020-13167
  http/cves/2020/CVE-2020-13167.yaml
Labels: Done

#7714 Update CVE-2021-21087.yaml
  http/cves/2021/CVE-2021-21087.yaml
Labels: Done

#7720 updated templates with outdated syntax
  http/cves/2023/CVE-2023-0448.yaml
  http/cves/2023/CVE-2023-23491.yaml
  http/cves/2023/CVE-2023-28665.yaml
  http/miscellaneous/spnego.yaml
  http/technologies/graylog/graylog-endpoints-exposure.yaml
Labels: Done

#7719 Release Prep
  http/miscellaneous/spnego-detect.yaml
  http/technologies/graylog/graylog-api-exposure.yaml
Labels: Done

#7224 Update CVE-2021-45046.yaml
  http/cves/2021/CVE-2021-45046.yaml
Labels: Done

#7722 Fix the naming and tagging on the internal ip disclosure template
  http/misconfiguration/internal-ip-disclosure.yaml
Labels: good first issue, Done

#7659 Create springboot-detect.yaml
  http/technologies/springboot-whitelabel.yaml
Labels: Done

#7732 Create CVE-2023-3765.yaml
  http/cves/2023/CVE-2023-3765.yaml
Labels: Done

#7715 Create tongda-online-user-login
  http/vulnerabilities/tongda/tongda-auth-bypass.yaml
Labels: good first issue, Done

#7726 Create skype-blind-ssrf.yaml
  http/vulnerabilities/other/skype-blind-ssrf.yaml
Labels: Done

#7737 Updated tongda-auth-bypass.yaml with metadata & fuzz tag
  http/vulnerabilities/tongda/tongda-auth-bypass.yaml
Labels: Done

#7716 Create jupyter-notebook-rce
  http/vulnerabilities/jupyter-notebook-rce.yaml
Labels: Done

#7733 Create casaos-panel.yaml
  http/exposed-panels/casaos-panel.yaml
Labels: Done

#7728 Replaced Hardcoded Nuclei Keyword
  file/keys/credential-exposure-file.yaml
  http/cves/2016/CVE-2016-10960.yaml
  http/cves/2017/CVE-2017-5521.yaml
  http/cves/2018/CVE-2018-1273.yaml
  http/cves/2018/CVE-2018-17254.yaml
  http/cves/2018/CVE-2018-3810.yaml
  http/cves/2019/CVE-2019-0230.yaml
  http/cves/2019/CVE-2019-5127.yaml
  http/cves/2020/CVE-2020-10148.yaml
  http/cves/2020/CVE-2020-13942.yaml
  http/cves/2020/CVE-2020-15568.yaml
  http/cves/2020/CVE-2020-16846.yaml
  http/cves/2020/CVE-2020-17453.yaml
  http/cves/2020/CVE-2020-23972.yaml
  http/cves/2020/CVE-2020-35729.yaml
  http/cves/2020/CVE-2020-7961.yaml
  http/cves/2021/CVE-2021-20158.yaml
  http/cves/2021/CVE-2021-22122.yaml
  http/cves/2021/CVE-2021-30151.yaml
  http/cves/2022/CVE-2022-29005.yaml
  http/misconfiguration/graphql/graphql-alias-batching.yaml
  http/token-spray/api-intelx.yaml
  http/vulnerabilities/other/alumni-management-sqli.yaml
  http/vulnerabilities/other/cvms-sqli.yaml
  http/vulnerabilities/other/ems-sqli.yaml
  http/vulnerabilities/other/loancms-sqli.yaml
  http/vulnerabilities/other/pmb-local-file-disclosure.yaml
  http/vulnerabilities/rocketchat/unauth-message-read.yaml
Labels: Done

#7727 Create CVE-2023-38205.yaml
  http/cves/2023/CVE-2023-38205.yaml
Labels: Done

#7697 Solve Issue - #6811
  http/default-logins/geoserver/geoserver-default-login.yaml
Labels: good first issue, Done, defcon31

#7449 Create CVE-2022-23102.yaml
  http/cves/2022/CVE-2022-23102.yaml
Labels: Done

#7435 Create CVE-2012-4032.yaml
  http/cves/2012/CVE-2012-4032.yaml
Labels: Done

#7738 Create CVE-2023-37462.yaml
  http/cves/2023/CVE-2023-37462.yaml
Labels: Done

#7751 fix(squirrelmail-vkeyboard-xss): adding vars, update payload & matcher
  http/vulnerabilities/squirrelmail/squirrelmail-vkeyboard-xss.yaml
Labels: Done

#7752 fix(CVE-2019-0221): add vars, update payload & matcher
  http/cves/2019/CVE-2019-0221.yaml
Labels: Done

#7753 Added path to config /wp-config.backup
  http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
Labels: Done

#7759 Create CVE-2021-44139.yaml
  http/cves/2021/CVE-2021-44139.yaml
Labels: Done

#7760 Create CVE-2023-2178.yaml
  http/cves/2023/CVE-2023-2178.yaml
Labels: good first issue, Done

#7754 Create elasticsearch-default-login.yaml
  http/default-logins/elasticsearch/elasticsearch-default-login.yaml
Labels: Done

#7761 Create CVE-2021-27670.yaml
  http/cves/2021/CVE-2021-27670.yaml
  http/exposed-panels/appspace-panel.yaml
Labels: Done

#7711 fix: FP joomla-com-fabrik-lfi.yaml
  http/vulnerabilities/other/joomla-com-fabrik-lfi.yaml
Labels: Done

#7755 Create booked-export-csv.yaml
  http/vulnerabilities/wordpress/booked-export-csv.yaml
Labels: Done

#7742 Create CVE-2023-23161.yaml
  http/cves/2023/CVE-2023-23161.yaml
Labels: Done

#7769 Fixed FP open-proxy-external.yaml
  http/misconfiguration/proxy/open-proxy-external.yaml
Labels: Done

#7765 Create CVE-2018-20608.yaml
  http/cves/2018/CVE-2018-20608.yaml
Labels: Done

#7740 Fix CVE-2021-22053.yaml false-positive
  http/cves/2021/CVE-2021-22053.yaml
Labels: Done

#7766 CasaOS Authentication Bypass (CVE-2023-37265, CVE-2023-37266)
  http/cves/2023/CVE-2023-37265.yaml
  http/cves/2023/CVE-2023-37266.yaml
Labels: Done

#7764 Update CVE-2023-2178.yaml
  http/cves/2023/CVE-2023-2178.yaml
Labels: Done

#7779 Alibaba Anyproxy fetchBody File Path Traversal
  http/vulnerabilities/other/alibaba-anyproxy-lfi.yaml
Labels: Done

#7768 Create CVE-2023-3836.yaml
  http/cves/2023/CVE-2023-3836.yaml
Labels: Done

#7776 Create cisco-smart-software-manager-on-prem.yaml
  http/exposed-panels/cisco/cisco-onprem-panel.yaml
Labels: Done

#7780 Update server-private-keys.yaml
  http/exposures/configs/server-private-keys.yaml
Labels: Done

#7778 nginxWebUI ≤ 3.5.0 runCmd - Remote Command Execution
  http/vulnerabilities/other/nginxwebui-runcmd-rce.yaml
Labels: Done

#7756 Update XSS - False positive
  .nuclei-ignore
  http/cves/2007/CVE-2007-5728.yaml
  http/cves/2011/CVE-2011-4618.yaml
  http/cves/2014/CVE-2014-4592.yaml
  http/cves/2014/CVE-2014-9608.yaml
  http/cves/2018/CVE-2018-5233.yaml
  http/cves/2018/CVE-2018-5316.yaml
  http/cves/2020/CVE-2020-11930.yaml
  http/cves/2020/CVE-2020-19295.yaml
  http/cves/2020/CVE-2020-9344.yaml
  http/cves/2021/CVE-2021-35265.yaml
  http/vulnerabilities/wordpress/wp-socialfit-xss.yaml
Labels: Done, defcon31

#7782 Generic C2 JARM
  network/jarm/c2/generic-c2-jarm.yaml
Labels: Done

#7784 request condition + strict matcher
  http/cnvd/2020/CNVD-2020-26585.yaml
Labels: Done

#7783 adding check for git credentials within config
  http/exposures/configs/git-config.yaml
Labels: good first issue, Done

#7795 updated tags
  network/cves/2011/CVE-2011-2523.yaml
  network/cves/2015/CVE-2015-3306.yaml
  network/cves/2016/CVE-2016-2004.yaml
  network/cves/2017/CVE-2017-3881.yaml
  network/cves/2017/CVE-2017-5645.yaml
  network/cves/2018/CVE-2018-2628.yaml
  network/cves/2020/CVE-2020-11981.yaml
  network/cves/2020/CVE-2020-1938.yaml
  network/cves/2022/CVE-2022-0543.yaml
  network/cves/2022/CVE-2022-24706.yaml
  network/cves/2022/CVE-2022-31793.yaml
  network/cves/2023/CVE-2023-33246.yaml
Labels: Done

#7796 Updated severity of php-fpm-status.yaml
  http/misconfiguration/php-fpm-status.yaml
Labels: Done
