Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-07, with the labels that each got.

#10164 Create chaty.yaml
  helpers/wordpress/plugins/chaty.yaml
Labels: Done

#10159 Delete http/takeovers/vercel-takeover.yaml
  http/takeovers/vercel-takeover.yaml
Labels: Done

#10133 add cve-2024-32709
  http/cves/2024/CVE-2024-32709.yaml
Labels: Done

#10163 Create apache-apollo-panel.yaml
  http/exposed-panels/apache/apache-apollo-panel.yaml
Labels: Done

#10162 Create apache-apollo-default-login.yaml
  http/default-logins/apache/apache-apollo-default-login.yaml
Labels: Done

#10161 Create dialogic-xms-console.yaml
  http/exposed-panels/dialogic-xms-console.yaml
Labels: Done

#10137 Added CVE-2024-5522 Template
  http/cves/2024/CVE-2024-5522.yaml
Labels: Done

#10160 Create dialogic-xms-default-login.yaml
  http/default-logins/dialogic/dialogic-xms-default-login.yaml
Labels: Done

#10152 Create seq-dashboard-unath.yaml
  http/misconfiguration/seq-dashboard-unath.yaml
Labels: Done

#10170 Create endpoint-protector-panel.yaml
  http/exposed-panels/endpoint-protector-panel.yaml
Labels: Done

#9757 Add sql server backup exposure
  http/exposures/backups/sql-server-dump.yaml
Labels: Done

#10169 Create CVE-2024-27292.yaml
  http/cves/2024/CVE-2024-27292.yaml
Labels: Done

#10174 Update mantisbt-anonymous-login.yaml
  http/default-logins/mantisbt/mantisbt-anonymous-login.yaml
Labels: Done

#10168 Create csv-injection.yaml
  dast/vulnerabilities/xinclude-injection.yaml
Labels: Done

#9908 Create CVE-2023-3380.yaml
  http/cves/2023/CVE-2023-3380.yaml
Labels: Done

#10181 Create sharp-multi-function-printers-local-file-disclosure.yaml
  http/vulnerabilities/other/sharp-printers-lfi.yaml
Labels: Done

#10182 Create subrion-installer.yaml
  http/misconfiguration/installer/subrion-installer.yaml
Labels: Done

#10189 Rename dast/vulnerabilities/xinclude-injection.yaml to dast/vulnerabi…
  dast/vulnerabilities/injection/xinclude-injection.yaml
Labels: Done

#10167 Create csv-injection.yaml
  dast/vulnerabilities/injection/csv-injection.yaml
Labels: Done

#10188 Create CVE-2024-33605.yaml
  http/cves/2024/CVE-2024-33605.yaml
  http/misconfiguration/forgejo-repo-exposure.yaml
  http/misconfiguration/installer/piwigo-installer.yaml
Labels: Done

#10175 Create apache-pinot-detect.yaml and apache-pinot-config.yaml
  http/exposures/configs/apache-pinot-config.yaml
  http/technologies/apache/apache-pinot-detect.yaml
Labels: Done

#10157 Create CVE-2024-29972.yaml
  http/cves/2024/CVE-2024-29972.yaml
Labels: Done

#10171 Update aws-cognito.yaml
  file/keys/amazon/aws-cognito.yaml
Labels: good first issue, Done

#10145 add CVE-2024-4434
  http/cves/2024/CVE-2024-4434.yaml
Labels: Done

#10183 add azon dominator sqli
  http/vulnerabilities/other/azon-dominator-sqli.yaml
Labels: Done

#9591 CVE-2020-10189
  http/cves/2020/CVE-2020-10189.yaml
Labels: Done

#10192 Create coolify-register-account.yaml
  http/misconfiguration/coolify-register-account.yaml
Labels: Done

#10179 Create CVE-2024-36401.yaml (GeoServer RCE in Evaluating Property Name Expressions)
  http/cves/2024/CVE-2024-36401.yaml
Labels: Done

#10184 add CVE-2024-5947
  http/cves/2024/CVE-2024-5947.yaml
Labels: Done

#10190 Create crocus-lfi.yaml
  http/vulnerabilities/other/crocus-lfi.yaml
Labels: Done

#10195 Create ruijie-nbr-default-login.yaml
  http/default-logins/ruijie/ruijie-nbr-default-login.yaml
Labels: Done

#10197 Create CVE-2024-33113.yaml
  http/cves/2024/CVE-2024-33113.yaml
Labels: Done

#10196 Jinhe OA_C6_UploadFileDownLoadnew - Arbitrary File Read
  http/vulnerabilities/jinhe/jinhe-oa-c6-upload-lfi.yaml
Labels: Done

#10198 Update CVE-2021-27748.yaml
  http/cves/2021/CVE-2021-27748.yaml
Labels: false-positive, Done

#10199 Create CVE-2023-35156.yaml
  http/cves/2023/CVE-2023-35156.yaml
Labels: Done

#10201 Create CVE-2023-35160.yaml
  http/cves/2023/CVE-2023-35160.yaml
Labels: Done

#10185 Ldap - Templates
  javascript/enumeration/ldap/ldap-metadata.yaml
Labels: Done

#10217 Create CVE-2024-33610.yaml
  http/cves/2024/CVE-2024-33610.yaml
Labels: Done

#10215 Create CVE-2024-36991.yaml (Splunk Enterprise - Local File Inclusion)
  http/cves/2024/CVE-2024-36991.yaml
Labels: Done

#10213 Update springboot-configprops.yaml
  http/misconfiguration/springboot/springboot-configprops.yaml
Labels: Done

#10202 Create CVE-2023-35161.yaml
  http/cves/2023/CVE-2023-35161.yaml
Labels: Done

#10200 Create CVE-2023-35159.yaml
  http/cves/2023/CVE-2023-35159.yaml
Labels: Done

#10223 Create label-studio-panel.yaml
  http/exposed-panels/label-studio-panel.yaml
Labels: Done

#10222 Create label-studio-signup.yaml
  http/misconfiguration/label-studio-signup.yaml
Labels: Done

#10221 Create CVE-2023-47117.yaml
  http/cves/2023/CVE-2023-47117.yaml
Labels: Done

#10212 Fixed Tomcat detection
  http/technologies/apache/tomcat-detect.yaml
Labels: good first issue, Done

#10194 Create laragon-phpinfo.yaml
  http/misconfiguration/laragon-phpinfo.yaml
Labels: Done

#10206 add CVE-2024-25852
  http/cves/2024/CVE-2024-25852.yaml
Labels: Done

#10219 Create CNVD-2021-64035.yaml
  http/cnvd/2024/CNVD-2021-64035.yaml
Labels: Done

#10180 add CVE-2024-4836
  http/cves/2024/CVE-2024-4836.yaml
Labels: Done

#10234 Create apache-cloudstack-detect.yaml
  http/technologies/apache/apache-cloudstack-detect.yaml
Labels: Done

#10232 add pingsheng sqli
  http/vulnerabilities/other/pingsheng-electronic-sqli.yaml
Labels: Done

#10231 add hj time based sqli
  http/vulnerabilities/hjsoft/hjsoft-hcm-tb-sqli.yaml
Labels: Done

#10230 add hj-hcm-sqli
  http/vulnerabilities/hjsoft/hjsoft-hcm-sqli.yaml
Labels: Done

#10229 add hj-hcm-lfi
  http/vulnerabilities/hjsoft/hjsoft-hcm-lfi.yaml
Labels: Done

#10228 add h3c campus arbitrary file upload
  http/vulnerabilities/other/h3c-cnsss-arbitrary-file-upload.yaml
Labels: Done

#10210 add CVE-2024-5084
  http/cves/2024/CVE-2024-5084.yaml
Labels: Done

#10237 Create jwk-json-leak.yaml
  http/exposures/tokens/jwk-json-leak.yaml
Labels: Done

#10240 Update jwk-json-leak.yaml
  http/exposures/tokens/jwk-json-leak.yaml
Labels: Done

#10227 add CVE-2024-6188
  http/cves/2024/CVE-2024-6188.yaml
Labels: Done

#10248 JS pre-condition - update
  javascript/audit/mysql/mysql-load-file.yaml
  javascript/backdoor/proftpd-backdoor.yaml
  javascript/cves/2012/CVE-2012-2122.yaml
  javascript/cves/2016/CVE-2016-8706.yaml
  javascript/cves/2019/CVE-2019-9193.yaml
  javascript/cves/2020/CVE-2020-7247.yaml
  javascript/cves/2023/CVE-2023-46604.yaml
  javascript/cves/2023/CVE-2023-48795.yaml
  javascript/cves/2024/CVE-2024-23897.yaml
  javascript/default-logins/redis-default-logins.yaml
  javascript/detection/oracle-tns-listener.yaml
  javascript/detection/samba-detect.yaml
  javascript/detection/ssh-auth-methods.yaml
  javascript/enumeration/checkpoint-firewall-enum.yaml
  javascript/enumeration/ldap/ldap-metadata.yaml
  javascript/enumeration/mysql/mysql-default-login.yaml
  javascript/enumeration/mysql/mysql-info.yaml
  javascript/enumeration/mysql/mysql-show-databases.yaml
  javascript/enumeration/mysql/mysql-show-variables.yaml
  javascript/enumeration/mysql/mysql-user-enum.yaml
  javascript/enumeration/pgsql/pgsql-default-db.yaml
  javascript/enumeration/pgsql/pgsql-file-read.yaml
  javascript/enumeration/pgsql/pgsql-list-database.yaml
  javascript/enumeration/pgsql/pgsql-list-password-hashes.yaml
  javascript/enumeration/pgsql/pgsql-list-users.yaml
  javascript/enumeration/pgsql/pgsql-version-detect.yaml
  javascript/enumeration/pop3/pop3-capabilities-enum.yaml
  javascript/enumeration/redis/redis-info.yaml
  javascript/enumeration/redis/redis-require-auth.yaml
  javascript/enumeration/rsync/rsync-list-modules.yaml
  javascript/enumeration/rsync/rsync-version.yaml
  javascript/enumeration/smb/smb-default-creds.yaml
  javascript/enumeration/smb/smb-enum-domains.yaml
  javascript/enumeration/smb/smb-enum.yaml
  javascript/enumeration/smb/smb-os-detect.yaml
  javascript/enumeration/smb/smb-version-detect.yaml
  javascript/enumeration/smb/smb2-capabilities.yaml
  javascript/enumeration/smb/smb2-server-time.yaml
  javascript/misconfiguration/mysql/mysql-empty-password.yaml
  javascript/misconfiguration/pgsql/pgsql-empty-password.yaml
  javascript/misconfiguration/pgsql/pgsql-extensions-rce.yaml
  javascript/misconfiguration/smb/smb-anonymous-access.yaml
  javascript/misconfiguration/smb/smb-shares.yaml
  javascript/misconfiguration/smb/smb-signing-not-required.yaml
  javascript/udp/detection/tftp-detect.yaml
Labels: Done

#10239 add enjoyrmis sqli
  http/vulnerabilities/other/enjoyrmis-sqli.yaml
Labels: Done

#10244 Next.js Cache Poisoning using X-Middleware-Prefetch
  http/vulnerabilities/nextjs/nextjs-middleware-cache.yaml
Labels: Done

#10245 Next.js Cache Poisoning using RSC
  http/vulnerabilities/nextjs/nextjs-rsc-cache.yaml
Labels: Done

#10236 add CVE-2023-4220
  http/cves/2023/CVE-2023-4220.yaml
Labels: Done

#10251 Rename CNVD-2021-64035.yaml to CNVD-2021-64035.yaml
  http/cnvd/2021/CNVD-2021-64035.yaml
Labels: Done

#10252 Fix FP CVE-2023-35161.yaml
  http/cves/2023/CVE-2023-35161.yaml
Labels: Done

#10257 Create CVE-2022-45269.yaml
  http/cves/2022/CVE-2022-45269.yaml
Labels: Done

#10260 Add 'error.ghost.org' to ghost.io takeover
  http/takeovers/ghost-takeover.yaml
Labels: good first issue, Done

#10178 Create snoop-servlet-exposure.yaml
  http/exposures/configs/snoop-servlet-exposure.yaml
Labels: Done

#10220 Create CVE-2023-44012.yaml
  http/cves/2023/CVE-2023-44012.yaml
Labels: Done

#10271 Add more matchers/extractors to the "JBoss SOA Platform" login panel detection template.
  http/exposed-panels/jboss/jboss-soa-platform.yaml
Labels: Done

#10267 add CVE-2024-2330
  http/cves/2024/CVE-2024-2330.yaml
Labels: Done

#10276 FP goip-default-login.yaml
  http/default-logins/goip-default-login.yaml
Labels: Done

#10275 Update astra-widgets.txt last version
  helpers/wordpress/plugins/astra-widgets.txt
Labels: Done

#10273 Add more matchers/extractors to the "Harbor" login panel detection template.
  http/exposed-panels/harbor-panel.yaml
Labels: Done

#10278 Fix FP ds-store-file.yaml
  http/exposures/files/ds-store-file.yaml
Labels: Done

#10256 Using different URL as we don't know who evil.com is controlled by
  dast/vulnerabilities/redirect/open-redirect.yaml
  http/vulnerabilities/generic/open-redirect-generic.yaml
Labels: Done

#10265 Better filtering of old IE-only http scripts
  http/misconfiguration/mixed-active-content.yaml
Labels: Done

#10254 CVE-2024-4879 - Jelly Template Injection Vulnerability in ServiceNow UI Macros
  http/cves/2024/CVE-2024-4879.yaml
Labels: Done

#10255 CVE-2024-5217 - ServiceNow Incomplete Input Validation in GlideExpression Script
  http/cves/2024/CVE-2024-5217.yaml
Labels: Done

#10253 Service Now - Title Injection
  http/misconfiguration/servicenow-title-injection.yaml
Labels: Done

#10281 Create CVE-2023-48728.yaml
  http/cves/2023/CVE-2023-48728.yaml
Labels: Done

#10284 Removed Duplicate of CNVD-2021-15824
  http/cnvd/2021/CNVD-2021-15824.yaml
  http/vulnerabilities/other/empirecms-xss.yaml
Labels: Done

#10282 Create CVE-2023-29204.yaml
  http/cves/2023/CVE-2023-29204.yaml
Labels: Done

#10264 add CVE-2024-1512
  http/cves/2024/CVE-2024-1512.yaml
Labels: Done

#10280 Added CVE-2023-4450
  http/cves/2023/CVE-2023-4450.yaml
Labels: good first issue, Done

#10287 Create apache-ozone-detect.yaml and apache-ozone-conf.yaml
  http/exposures/configs/apache-ozone-conf.yaml
  http/technologies/apache/apache-ozone-detect.yaml
Labels: Done

#10279 Updated CVE-2022-35914 template
  http/cves/2022/CVE-2022-35914.yaml
Labels: good first issue, Done

#10165 Update severity of polyfill-backdoor to high
  http/vulnerabilities/backdoor/polyfill-backdoor.yaml
Labels: good first issue, Done

#10295 Create wp-crontrol.txt
  helpers/wordpress/plugins/wp-crontrol.txt
Labels: Done

#10294 Added kev tag
  http/cves/2024/CVE-2024-36401.yaml
Labels: Done

#10290 add cve-2024-4257
  http/cves/2024/CVE-2024-4257.yaml
Labels: Done

#10291 add CVE-2024-6289
  http/cves/2024/CVE-2024-6289.yaml
Labels: Done

#10288 Add detection template for CVE-2024-34351.
  http/cves/2024/CVE-2024-34351.yaml
Labels: Done

#10296 Fix FP apisix-default-login.yaml
  http/default-logins/apache/apisix-default-login.yaml
Labels: Done

#10246 Active Directory Certificate Services blind detection
  http/exposures/files/adcs-certificate.yaml
Labels: Done

#10306 Update airflow-detect.yaml
  http/technologies/apache/airflow-detect.yaml
Labels: Done

#10320 Update CVE-2024-4577.yaml
  http/cves/2024/CVE-2024-4577.yaml
Labels: Done

#10324 Create adguard-panel.yaml
  http/exposed-panels/adguard-panel.yaml
Labels: Done

#10323 Create adguard-installer.yaml
  http/misconfiguration/installer/adguard-installer.yaml
Labels: Done

#10322 Create freshrss-panel.yaml
  http/exposed-panels/freshrss-panel.yaml
Labels: Done

#10308 Create CVE-2024-6646.yaml
  http/cves/2024/CVE-2024-6646.yaml
Labels: Done

#10203 Create CVE-2024-34257.yaml
  http/cves/2024/CVE-2024-34257.yaml
Labels: Done

#10304 feat: fp on iis-shortname.yaml
  http/fuzzing/iis-shortname.yaml
Labels: Done

#10312 Create freshrss-unauth.yaml
  http/misconfiguration/freshrss-unauth.yaml
Labels: Done

#10313 Create gitblit-default-login.yaml
  http/default-logins/gitblit/gitblit-default-login.yaml
Labels: Done

#10301 add CVE-2024-32238
  http/cves/2024/CVE-2024-32238.yaml
Labels: Done

#10302 add CVE-2024-6746
  network/cves/2024/CVE-2024-6746.yaml
Labels: Done

#10307 Create nacos-workflow.yaml
  workflows/nacos-workflow.yaml
Labels: Done

#10309 Create CVE-2023-43662.yaml
  http/cves/2023/CVE-2023-43662.yaml
Labels: Done

#10315 Create lvs-download-lfi.yaml
  http/vulnerabilities/other/lvs-download-lfi.yaml
Labels: Done

#10332 Update deluge-webui-panel.yaml
  http/exposed-panels/deluge-webui-panel.yaml
Labels: Done

#10331 Create deluge-default-login.yaml
  http/default-logins/deluge/deluge-default-login.yaml
Labels: Done

#10333 Create freshrss-installer.yaml
  http/misconfiguration/installer/freshrss-installer.yaml
Labels: Done

#10336 Removing unneccessary text from template description
  http/cves/2017/CVE-2017-12794.yaml
Labels: Done

#10337 Fixing vulnerability name
  http/cves/2022/CVE-2022-0140.yaml
Labels: Done

#10339 Fix FN CVE-2019-7139.yaml
  http/cves/2019/CVE-2019-7139.yaml
Labels: Done

#10341 Add an extractors to the "F5 BIGIP" login panel detection template.
  http/exposed-panels/f5-admin-interface.yaml
Labels: Done

#10340 Refactor the Tomcat template
  http/exposed-panels/tomcat/tomcat-exposed-docs.yaml
  http/exposed-panels/tomcat/tomcat-exposed.yaml
Labels: Done

#10314 Create CNVD-2023-72138
  http/cnvd/2023/CNVD-2023-72138.yaml
Labels: Done

#10289 DS_Store template had FPs on UTF-16 encoded HTML files
  http/exposures/files/ds-store-file.yaml
Labels: Done

#10316 Create ncast-lfi.yaml
  http/vulnerabilities/other/ncast-lfi.yaml
Labels: Done

#10317 Create wifisky7-rce.yaml
  http/vulnerabilities/other/wifisky7-rce.yaml
Labels: Done

#10334 FP - Fix beanstalk-service.yaml
  network/enumeration/beanstalk-service.yaml
Labels: Done

#10326 Create netflow-analyzer-panel.yaml
  http/exposed-panels/netflow-analyzer-panel.yaml
Labels: Done

#10319 Improve blind-ssrf.yaml
  dast/vulnerabilities/ssrf/blind-ssrf.yaml
Labels: Done

#10329 Create hal-management-panel.yaml
  http/exposed-panels/hal-management-panel.yaml
Labels: Done

#10153 Create CVE-2024-38526.yaml
  headless/2024/CVE-2024-38526.yaml
Labels: Done

#10358 Create fluent-smtp.txt
  helpers/wordpress/plugins/fluent-smtp.txt
Labels: Done

#10305 Added template for CVE-2022-38322
  http/cves/2022/CVE-2022-38322.yaml
Labels: Done

#10357 Create sftpgo-admin-setup.yaml
  http/misconfiguration/sftpgo-admin-setup.yaml
Labels: Done

#10328 Create netflow-default-login.yaml
  http/default-logins/netflow/netflow-default-login.yaml
Labels: Done

#10353 Refactor the Checkmarx template.
  http/exposed-panels/checkmk/checkmarx-panel.yaml
Labels: Done

#6764 add templates: thinkphp6_arbitrary_write
  vulnerabilities/thinkphp/thinkphp6-arbitrary-write.yaml
Labels: Done

#10327 Create jan-api-lfi.yaml
  http/vulnerabilities/other/jan-file-upload.yaml
Labels: Done

#10330 Create mongod-exposure.yaml
  http/misconfiguration/mongod-exposure.yaml
Labels: Done

#10335 add bazarr lfi CVE-2024-40348
  http/cves/2024/CVE-2024-40348.yaml
Labels: Done

#10262 add CVE-2023-2309
  http/cves/2023/CVE-2023-2309.yaml
Labels: Done

#10345 Create CVE-2024-4885.yaml
  http/cves/2024/CVE-2024-4885.yaml
Labels: Done

#10361 FP -Fix jan-file-upload.yaml
  http/vulnerabilities/other/jan-file-upload.yaml
Labels: Done

#10342 Fewer FP in the Apache XSS template
  http/cves/2019/CVE-2019-10092.yaml
Labels: Done

#10362 Fixed FN in exposed-svn
  http/exposures/configs/exposed-svn.yaml
Labels: Done

#10351 Update response-ssrf.yaml
  dast/vulnerabilities/ssrf/response-ssrf.yaml
Labels: Done

#10378 TFTP Service minor - update
  javascript/udp/detection/tftp-detect.yaml
Labels: Done

#10379 Update tftp-detect.yaml
  javascript/udp/detection/tftp-detect.yaml
Labels: Done

#10374 Create CVE-2024-4295.yaml
  http/cves/2024/CVE-2024-4295.yaml
Labels: Done

#10348 Create CVE-2024-6587.yaml
  http/cves/2024/CVE-2024-6587.yaml
Labels: Done

#10375 Create CVE-2024-37843.yaml
  http/cves/2024/CVE-2024-37843.yaml
Labels: Done

#10347 Create CVE-2022-34267.yaml
  http/cves/2022/CVE-2022-34267.yaml
Labels: Done
