Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-03, with the labels that each got.

#9269 [+] Added Cloudflare Rocket Loader HTML Injection
  http/misconfiguration/cloudflare-rocketloader-htmli.yaml
Labels: Done

#9252 Updated dns-rebinding.yaml
  dns/dns-rebinding.yaml
Labels: Done

#9286 Update server-backup-login.yaml
  http/exposed-panels/server-backup-login.yaml
Labels: Done

#9285 Update headless-open-redirect.yaml
  headless/headless-open-redirect.yaml
Labels: Done

#9281 Lucee default login
  http/default-logins/lucee/lucee-default-login.yaml
Labels: Done

#9280 Create CVE-2024-27199.yaml (TeamCity < 2023.11.4 - Authentication Bypass)
  http/cves/2024/CVE-2024-27199.yaml
Labels: Done

#9278 Added Lucee Unset Credentials Template
  http/vulnerabilities/other/lucee-unset-credentials.yaml
Labels: Done

#9279 Create CVE-2024-27198.yaml (TeamCity < 2023.11.4 - Authentication Bypass)
  http/cves/2024/CVE-2024-27198.yaml
Labels: Done

#9275 Add detection of Progress Web Transfer Client login panel instances
  http/exposed-panels/webtransfer-client-panel.yaml
Labels: Done

#9248 Create chanjet-tplus-unauth-update.yaml
  http/vulnerabilities/chanjet-tplus/chanjet-tplus-rce.yaml
  http/vulnerabilities/chanjet-tplus/chanjet-tplus-unauth-update.yaml
Labels: Done

#9259 Adding Missing Token
  http/exposures/tokens/dependency/dependency-track-api.yaml
  http/exposures/tokens/docker/docker-hub-pat.yaml
  http/exposures/tokens/doppler/doppler-audit-token.yaml
  http/exposures/tokens/doppler/doppler-cli-token.yaml
  http/exposures/tokens/doppler/doppler-scim-token.yaml
  http/exposures/tokens/doppler/doppler-service-account-token.yaml
  http/exposures/tokens/doppler/doppler-service-token.yaml
  http/exposures/tokens/dropbox/dropbox-access-token.yaml
  http/exposures/tokens/huggingface/huggingface-user-access-token.yaml
  http/exposures/tokens/linkedin/linkedin-client-id.yaml
  http/exposures/tokens/linkedin/linkedin-secret-key.yaml
  http/exposures/tokens/newrelic/newrelic-api-service-key.yaml
  http/exposures/tokens/newrelic/newrelic-license-key-non.yaml
  http/exposures/tokens/newrelic/newrelic-license-key.yaml
  http/exposures/tokens/odbc/odbc-connection-string.yaml
  http/exposures/tokens/okta/okta-api-token.yaml
  http/exposures/tokens/particle/particle-access-token.yaml
  http/exposures/tokens/react/react-app-password.yaml
  http/exposures/tokens/react/react-app-username.yaml
  http/exposures/tokens/salesforce/salesforce-access-token.yaml
  http/exposures/tokens/thingsboard/thingsboard-access-token.yaml
  http/exposures/tokens/truenas/truenas-api-key.yaml
  http/exposures/tokens/twitter/twitter-client-id.yaml
  http/exposures/tokens/twitter/twitter-secret-key.yaml
  http/exposures/tokens/wireguard/wireguard-preshared-key.yaml
  http/exposures/tokens/wireguard/wireguard-private-key.yaml
Labels: Done

#9282 Improved detection of CVE-2020-15227, now independent of server OS
  http/cves/2020/CVE-2020-15227.yaml
Labels: good first issue, Done

#9292 Update CVE-2017-11444.yaml
  http/cves/2017/CVE-2017-11444.yaml
  http/cves/2021/CVE-2021-27748.yaml
Labels: Done

#9295 eset-protect-detect
  http/exposed-panels/eset-protect-panel.yaml
Labels: Done

#9300 Update cloudflare-rocketloader-htmli.yaml
  http/misconfiguration/cloudflare-rocketloader-htmli.yaml
Labels: Done

#9301 Add detection of Graylog login panel instances.
  http/exposed-panels/graylog-panel.yaml
Labels: Done

#9311 Add detection of LockSelf login panel instances.
  http/exposed-panels/lockself-panel.yaml
Labels: Done

#9306 Add detection of HCP Anywhere instances.
  http/technologies/hcpanywhere-detect.yaml
Labels: Done

#9305 Add detection of PAHTool login panel instances.
  http/exposed-panels/pahtool-panel.yaml
Labels: Done

#9304 Add detection of Moodle Workplace login panel instances.
  http/exposed-panels/moodle-workplace-panel.yaml
Labels: Done

#9270 Added CVE-2023-5089 Template
  http/cves/2023/CVE-2023-5089.yaml
Labels: good first issue, Done

#9312 Add more detection criteria to the Superset template.
  http/exposed-panels/superset-login.yaml
Labels: Done

#9310 Add detection of CleanWeb login panel instances.
  http/exposed-panels/cleanweb-panel.yaml
Labels: Done

#9314 Add detection of Sonatype Nexus login panel instances.
  http/exposed-panels/nexus-panel.yaml
Labels: Done

#9313 Add detection of Atlassian Bamboo login panel instances.
  http/exposed-panels/atlassian-bamboo-panel.yaml
Labels: Done

#9315 Add detection of AdmiralCloud instances.
  http/technologies/admiralcloud-detect.yaml
Labels: Done

#9299 Fix CVE-2021-40438.yaml
  http/cves/2021/CVE-2021-40438.yaml
Labels: Done

#9320 Added README.md for phishing templates
  http/osint/README.md
  http/osint/phishing/README.md
  http/osint/user-enumeration/README.md
Labels: Done

#9323 Updated reference
  network/default-login/ldap-anonymous-login.yaml
Labels: Done

#9319 Create CVE-2023-49785.yaml (ChatGPT-Next-Web SSRF/XSS 🔥 )
  http/cves/2023/CVE-2023-49785.yaml
Labels: Done

#9328 Panel Tags
  http/technologies/arcgis-rest-api.yaml
  http/technologies/arcgis-tokens.yaml
Labels: Done

#9331 Update contributors.json
  contributors.json
Labels: Done

#9326 Create posteio-installer.yaml
  http/misconfiguration/posteio-installer.yaml
Labels: Done

#9330 osnexus-quantastor-manager-panel
  http/exposed-panels/osnexus-panel.yaml
Labels: Done

#9327 Create posteio-admin-panel.yaml
  http/exposed-panels/posteio-admin-panel.yaml
Labels: Done

#9325 Add detection of EMQX login panel instances.
  http/exposed-panels/emqx-panel.yaml
Labels: Done

#9303 Add plugin: Landray EIS WS_getAllInfos Disclosure
  http/vulnerabilities/landray/landray-eis-ws-infoleak.yaml
Labels: Done

#9341 Rename http/misconfiguration/posteio-installer.yaml to http/misconfig…
  http/misconfiguration/installer/posteio-installer.yaml
Labels: Done

#9343 Update CVE-2017-12617.yaml
  http/cves/2017/CVE-2017-12617.yaml
Labels: Done

#9338 Add detection of Skeepers login panel instances.
  http/exposed-panels/skeepers-panel.yaml
Labels: Done

#9340 Updated favicon-detect.yaml
  http/technologies/favicon-detect.yaml
Labels: Done

#9344 Update CVE-2019-17574.yaml
  http/cves/2019/CVE-2019-17574.yaml
Labels: Done

#9332 Create CVE-2024-1698.yaml
  http/cves/2024/CVE-2024-1698.yaml
Labels: Done

#9324 Add more detection criteria to the Rancher template.
  http/exposed-panels/rancher-dashboard.yaml
Labels: Done

#9355 Update google-api-enumeration-workflow.yaml
  workflows/google-api-enumeration-workflow.yaml
Labels: Done

#9353 adds to templates check to Fortinet FortiWLM login panel
  http/exposed-panels/fortinet/fortiwlm-panel.yaml
Labels: good first issue, Done

#9354 Id uniform
  javascript/default-logins/postgres-default-logins.yaml
  javascript/default-logins/redis-default-logins.yaml
  javascript/default-logins/ssh-default-logins.yaml
Labels: Done

#9351 Add detection of Bynder login panel instances.
  http/exposed-panels/bynder-panel.yaml
Labels: Done

#9357 Added legit domain to amazon-phish
  http/osint/phishing/amazon-phish.yaml
Labels: good first issue, Done

#9335 Create CVE-2023-5914.yaml
  http/cves/2024/CVE-2023-5914.yaml
Labels: Done

#9329 Adding a phishing detection template for kakao/naver login
  http/osint/phishing/kakao-login-phish.yaml
  http/osint/phishing/naver-login-phish.yaml
Labels: Done

#9360 Update redis port to 6379 and 6380
  network/detection/redis-detect.yaml
  network/exposures/exposed-redis.yaml
Labels: Done

#9254 Update CVE-2019-3403.yaml
  http/cves/2019/CVE-2019-3403.yaml
Labels: good first issue, Done

#9316 Added 2 templates to detect X-AspNetMvc-Version and X-AspNet-Version …
  http/technologies/microsoft/aspnet-version-detect.yaml
  http/technologies/microsoft/aspnetmvc-version-disclosure.yaml
Labels: Done

#9350 Create forticlientems-detect.yaml
  http/exposed-panels/forticlientems-panel.yaml
Labels: good first issue, Done

#9358 Create wing-ftp-detect.yaml
  network/detection/wing-ftp-detect.yaml
Labels: Done

#9368 Rename http/exposed-panels/forticlientems-panel.yaml to http/exposed-…
  http/exposed-panels/fortinet/forticlientems-panel.yaml
Labels: Done

#9361 Add detection of CISCO Expressway login panel instances.
  http/exposed-panels/cisco/cisco-expressway-panel.yaml
Labels: Done

#9373 lower case
  contributors.json
Labels: Done

#9371 File Based Template & Moving Directory
  file/keys/dependency/dependency-track.yaml
  file/keys/docker/dockerhub-pat.yaml
  file/keys/doppler/doppler-audit.yaml
  file/keys/doppler/doppler-cli.yaml
  file/keys/doppler/doppler-scim.yaml
  file/keys/doppler/doppler-service-account.yaml
  file/keys/doppler/doppler-service.yaml
  file/keys/dropbox/dropbox-access.yaml
  file/keys/huggingface/huggingface-user-access.yaml
  file/keys/linkedin/linkedin-client.yaml
  file/keys/linkedin/linkedin-secret.yaml
  file/keys/newrelic/newrelic-api-service.yaml
  file/keys/newrelic/newrelic-license-non.yaml
  file/keys/newrelic/newrelic-license.yaml
  file/keys/odbc/odbc-connection.yaml
  file/keys/okta/okta-api.yaml
  file/keys/particle/particle-access.yaml
  file/keys/react/reactapp-password.yaml
  file/keys/react/reactapp-username.yaml
  file/keys/salesforce/salesforce-access.yaml
  file/keys/thingsboard/thingsboard-access.yaml
  file/keys/truenas/truenas-api.yaml
  file/keys/twitter-secret.yaml
  file/keys/twitter/twitter-client.yaml
  file/keys/twitter/twitter-secret.yaml
  file/keys/wireguard/wireguard-preshared.yaml
  file/keys/wireguard/wireguard-private.yaml
Labels: Done

#9339 Update js-analyse.yaml
  file/js/js-analyse.yaml
Labels: Done

#9372 Rename CVE-2023-5914.yaml to CVE-2023-5914.yaml
  http/cves/2023/CVE-2023-5914.yaml
Labels: Done

#9364 Create CVE-2023-5830.yaml
  http/cves/2023/CVE-2023-5830.yaml
Labels: Done

#9378 reverted bruteforce tags to fuzz
  .nuclei-ignore
  cloud/enum/azure-vm-cloud-enum.yaml
  config/bugbounty.yml
  config/pentest.yml
  config/recommended.yml
  http/cves/2017/CVE-2017-17562.yaml
  http/cves/2019/CVE-2019-17382.yaml
  http/cves/2022/CVE-2022-2034.yaml
  http/cves/2022/CVE-2022-2599.yaml
  http/cves/2023/CVE-2023-24489.yaml
  http/default-logins/oracle/peoplesoft-default-login.yaml
  http/exposed-panels/adminer-panel-detect.yaml
  http/exposures/backups/php-backup-files.yaml
  http/fuzzing/cache-poisoning-fuzz.yaml
  http/fuzzing/header-command-injection.yaml
  http/fuzzing/iis-shortname.yaml
  http/fuzzing/linux-lfi-fuzzing.yaml
  http/fuzzing/mdb-database-file.yaml
  http/fuzzing/prestashop-module-fuzz.yaml
  http/fuzzing/ssrf-via-proxy.yaml
  http/fuzzing/valid-gmail-check.yaml
  http/fuzzing/waf-fuzz.yaml
  http/fuzzing/wordpress-plugins-detect.yaml
  http/fuzzing/wordpress-themes-detect.yaml
  http/fuzzing/wordpress-weak-credentials.yaml
  http/fuzzing/xff-403-bypass.yaml
  http/miscellaneous/defacement-detect.yaml
  http/miscellaneous/ntlm-directories.yaml
  http/misconfiguration/aem/aem-userinfo-servlet.yaml
  http/misconfiguration/gitlab/gitlab-user-enum.yaml
  http/misconfiguration/proxy/open-proxy-internal.yaml
  http/misconfiguration/proxy/open-proxy-localhost.yaml
  http/misconfiguration/proxy/open-proxy-portscan.yaml
  http/technologies/graylog/graylog-api-exposure.yaml
  http/vulnerabilities/tongda/tongda-auth-bypass.yaml
  http/vulnerabilities/wordpress/wp-xmlrpc-brute-force.yaml
  javascript/cves/2023/CVE-2023-34039.yaml
  javascript/default-logins/ssh-default-logins.yaml
  network/misconfig/mysql-native-password.yaml
  network/misconfig/tidb-native-password.yaml
Labels: Done

#9383 Create CVE-2024-1212.yaml (Progress Kemp LoadMaster - Unauthenticated Command Injection) 🔥
  http/cves/2024/CVE-2024-1212.yaml
Labels: Done

#9366 SOA Service Detection
  dns/soa-detect.yaml
Labels: Done

#9365 TXT Service Detector
  dns/txt-service-detect.yaml
Labels: Done

#9359 Create wing-ftp-service-detect.yaml
  http/technologies/wing-ftp-service-detect.yaml
Labels: Done

#9333 generic-db: Check for publicly accessible SQLite database files
  http/exposures/files/generic-db.yaml
Labels: Done

#9218 SPF Record Detection Template
  dns/spf-record-detect.yaml
Labels: Done

#9386 Update fingerprinthub-web-fingerprints.yaml
  http/technologies/fingerprinthub-web-fingerprints.yaml
Labels: Done

#9387 Updated microsoft-iis-version
  http/technologies/microsoft/microsoft-iis-version.yaml
Labels: Done

#9390 Drupal-install severity -update
  http/misconfiguration/installer/drupal-install.yaml
Labels: Done

#9389 Fixing CVE-2023-46604
  javascript/cves/2023/CVE-2023-46604.yaml
Labels: Done

#9399 update-workflow
  workflows/default-application-workflow.yaml
Labels: Done

#9398 tag add
  http/default-logins/alibaba/canal-default-login.yaml
Labels: Done

#9402 Create CVE-2024-27954.yaml
  http/cves/2024/CVE-2024-27954.yaml
Labels: Done

#9397 Add Directus Detect
  http/technologies/directus-detect.yaml
Labels: Done

#9395 ups network lfi add
  http/vulnerabilities/other/ups-network-lfi.yaml
Labels: good first issue, Done

#9385 Create softether-vpn-panel.yaml
  http/exposed-panels/softether-vpn-panel.yaml
Labels: Done

#9400 fix CVE-2022-45917 fp
  http/cves/2022/CVE-2022-45917.yaml
Labels: Done, community ✅

#9309 New Templates Update
  helpers/wordlists/mysql-passwords.txt
  helpers/wordlists/mysql-users.txt
  http/cves/2023/CVE-2023-6114.yaml
  http/cves/2023/CVE-2023-6567.yaml
  http/cves/2023/CVE-2023-6895.yaml
  http/default-logins/ispconfig-default-login.yaml
  http/exposed-panels/c2/ares-rat-c2.yaml
  http/exposed-panels/c2/caldera-c2.yaml
  http/exposed-panels/c2/hack5-cloud-c2.yaml
  http/exposed-panels/c2/pupyc2.yaml
  http/exposed-panels/c2/supershell-c2.yaml
  http/vulnerabilities/esafenet/esafenet-mysql-fileread.yaml
  http/vulnerabilities/idoc/idocview-2word-fileupload.yaml
  http/vulnerabilities/idoc/idocview-lfi.yaml
  http/vulnerabilities/other/office365-indexs-fileread.yaml
  javascript/audit/mysql/mysql-load-file.yaml
  javascript/enumeration/mysql/mysql-default-login.yaml
  javascript/enumeration/mysql/mysql-info.yaml
  javascript/enumeration/mysql/mysql-show-databases.yaml
  javascript/enumeration/mysql/mysql-show-variables.yaml
  javascript/enumeration/mysql/mysql-user-enum.yaml
  javascript/enumeration/pop3/pop3-capabilities-enum.yaml
  javascript/enumeration/redis/redis-info.yaml
  javascript/enumeration/redis/redis-require-auth.yaml
  javascript/enumeration/rsync/rsync-version.yaml
  javascript/enumeration/smb/smb-default-creds.yaml
  javascript/enumeration/smb/smb-enum-domains.yaml
  javascript/enumeration/smb/smb-os-detect.yaml
  javascript/enumeration/smb/smb-version-detect.yaml
  javascript/enumeration/smb/smb2-server-time.yaml
  javascript/misconfiguration/mysql/mysql-empty-password.yaml
  ssl/c2/venomrat.yaml
Labels: Done

#9405 Added CVE-2019-9632
  http/cves/2019/CVE-2019-9632.yaml
  http/vulnerabilities/esafenet/esafenet-mysql-fileread.yaml
Labels: Done

#9407 fix: template for CVE-2022-2627
  http/cves/2022/CVE-2022-2627.yaml
Labels: good first issue, Done, community ✅

#9415 Add detection of Celebrus instances.
  http/technologies/celebrus-detect.yaml
Labels: Done

#9414 Add detection of Amprion Grid Loss login panel instances.
  http/exposed-panels/amprion-gridloss-panel.yaml
Labels: Done

#9413 Add detection of SafeNet Authentication Service Self Enrollment login panel instances.
  http/exposed-panels/safenet-authentication-panel.yaml
Labels: Done

#9408 Add more detection criteria to the Dolibarr template.
  http/exposed-panels/dolibarr-panel.yaml
Labels: Done, community ✅

#9417 Add detection of PrivateBin instances.
  http/technologies/privatebin-detect.yaml
Labels: Done

#9416 Rename apache-druid-kafka-connect-rce.yaml to CVE-2023-25194.yaml
  http/cves/2023/CVE-2023-25194.yaml
Labels: Done, community ✅

#9419 Create CVE-2024-20767.yaml
  http/cves/2024/CVE-2024-20767.yaml
Labels: Done

#9422 Create CVE-2020-7247.yaml
  javascript/cves/2020/CVE-2020-7247.yaml
Labels: Done

#9428 Added HTML form detection
  http/miscellaneous/form-detection.yaml
Labels: Done

#9370 Detecting https to http redirect
  http/misconfiguration/https-to-http-redirect.yaml
Labels: Done

#9284 deployment.ini - configuration file with FTP credentials exposure
  http/exposures/configs/deployment-ini.yaml
Labels: Done

#9452 FP - Fix CVE-2022-23134.yaml
  http/cves/2022/CVE-2022-23134.yaml
Labels: Done

#9445 Create landray-eis-sqli.yaml
  http/vulnerabilities/landray/landray-eis-sqli.yaml
Labels: Done

#9444 Create dahua-eims-rce.yaml
  http/vulnerabilities/dahua/dahua-eims-rce.yaml
Labels: Done

#9163 Favicon Detection Enhancement
  http/technologies/favicon-detect.yaml
Labels: Done

#9451 Create CVE-2024-29059.yaml
  http/cves/2024/CVE-2024-29059.yaml
Labels: Done

#9447 Create huatian-oa-sqli.yaml
  http/vulnerabilities/huatian/huatian-oa-sqli.yaml
Labels: Done

#9348 feat(http): add CVE-2023-34993
  http/cves/2023/CVE-2023-34993.yaml
Labels: Done

#9455 tags add
  http/cves/2024/CVE-2024-29059.yaml
Labels: Done

#9456 add path
  http/default-logins/zabbix/zabbix-default-login.yaml
  http/vulnerabilities/jenkins/unauthenticated-jenkins.yaml
Labels: Done

#9462 Create CVE-2023-0678.yaml
  http/cves/2023/CVE-2023-0678.yaml
Labels: Done

#9461 Added template for CVE-2023-0159
  http/cves/2023/CVE-2023-0159.yaml
Labels: Done
