Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-11, with the labels that each got.

#11125 Update contributors.json
  contributors.json
Labels: Done

#11124 fix: weaver-checkserver-sqli fp
  http/vulnerabilities/weaver/weaver-checkserver-sqli.yaml
Labels: Done

#11113 CVE-2024-45216 (Apache Solr - Authentication Bypass 🔥 )
  http/cves/2024/CVE-2024-45216.yaml
Labels: Hacktoberfest, Done

#11118 Create lottie-backdoor.yaml (Lottie Player - Backdoor)
  http/vulnerabilities/backdoor/lottie-backdoor.yaml
Labels: Hacktoberfest, Done

#11105 Add detection of PGHERO instances.
  http/technologies/pghero-detect.yaml
Labels: Hacktoberfest, Done

#11107 add localai-detect
  http/technologies/localai-detect.yaml
Labels: Hacktoberfest, Done

#11106 add quivr-panel
  http/exposed-panels/quivr-panel.yaml
Labels: Hacktoberfest, Done

#11108 add CVE-2024-4841
  http/cves/2024/CVE-2024-4841.yaml
Labels: Hacktoberfest, Done

#11109 Added Cyberpanel-detect template
  http/exposed-panels/cyberpanel-panel.yaml
Labels: Hacktoberfest, Done

#11122 Create ip-webcam.yaml
  http/iot/ip-webcam.yaml
  http/technologies/favicon-detect.yaml
Labels: Hacktoberfest, Done

#11116 Added CVE-2024-6420 Template
  http/cves/2024/CVE-2024-6420.yaml
Labels: Hacktoberfest, Done

#10910 Added template for azure-blob-core-detection
  http/miscellaneous/azure-blob-core-detect.yaml
Labels: Hacktoberfest, Done

#11126 Add detection of HUBBLE instances.
  http/technologies/hubble-detect.yaml
Labels: Done

#11095 Add CVE-2019-1003000.yaml Template - Jenkins Script Security Plugin Sandbox Bypass
  http/cves/2019/CVE-2019-1003000.yaml
Labels: Hacktoberfest, Done, 🙋 Bounty claim

#11034 AWS - Cloudfront (10 Templates)
  cloud/aws/cloudfront/cloudfront-compress-object.yaml
  cloud/aws/cloudfront/cloudfront-custom-certificates.yaml
  cloud/aws/cloudfront/cloudfront-geo-restriction.yaml
  cloud/aws/cloudfront/cloudfront-insecure-protocol.yaml
  cloud/aws/cloudfront/cloudfront-integrated-waf.yaml
  cloud/aws/cloudfront/cloudfront-logging-disabled.yaml
  cloud/aws/cloudfront/cloudfront-origin-shield.yaml
  cloud/aws/cloudfront/cloudfront-security-policy.yaml
  cloud/aws/cloudfront/cloudfront-traffic-unencrypted.yaml
  cloud/aws/cloudfront/cloudfront-viewer-policy.yaml
Labels: Hacktoberfest, Done

#11132 Smtp ehlo enum
  network/enumeration/smtp/smtp-commands-enum.yaml
Labels: good first issue, Done

#11135 Merging Duplicate - CVE-2024-7928 & fastadmin-lfi
  http/cves/2024/CVE-2024-7928.yaml
  http/vulnerabilities/other/fastadmin-lfi.yaml
Labels: Done

#11089 OpenSSL Heartbleed Vulnerability
  code/cves/2014/CVE-2014-0160.yaml
Labels: Done

#11104 ASPNET and nodejs exception templates
  file/logs/aspnet-framework-exceptions.yaml
  file/logs/nodejs-framework-exceptions.yaml
Labels: good first issue, Done

#10976 fix fp
  http/misconfiguration/proxy/metadata-alibaba.yaml
Labels: Done

#10998 Removing one case of FPs
  http/fuzzing/xff-403-bypass.yaml
Labels: Hacktoberfest

#10460 Flexmls Detection
  helpers/wordpress/plugins/flexmls-idx.txt
  http/technologies/wordpress/plugins/flexmls-detect.yaml
Labels: Done

#11131 Create nexpose-panel.yaml
  http/exposed-panels/nexpose-panel.yaml
Labels: Done

#11099 add CVE-2024-6049
  http/cves/2024/CVE-2024-6049.yaml
Labels: Hacktoberfest, Done

#11137 ci(tests): fix resource not accessible by integration
  .github/workflows/tests.yml
Labels: Done

#11050 AWS - Cloudformation (3 Templates)
  cloud/aws/cloudformation/stack-notification-disabled.yaml
  cloud/aws/cloudformation/stack-policy-not-inuse.yaml
  cloud/aws/cloudformation/stack-termination-disabled.yaml
Labels: Hacktoberfest, Done

#11033 AWS - Secrets Manager (3 Templates)
  cloud/aws/secrets-manager/secret-manager-not-inuse.yaml
  cloud/aws/secrets-manager/secret-rotation-interval.yaml
  cloud/aws/secrets-manager/secrets-rotation-disabled.yaml
Labels: Hacktoberfest, Done

#11127 Add template for CVE-2019-0192 Apache Solr unsafe deserialization
  http/cves/2019/CVE-2019-0192.yaml
Labels: good first issue, Done, 🙋 Bounty claim

#11150 Update CVE-2022-0968.yaml
  http/cves/2022/CVE-2022-0968.yaml
Labels: Done

#11148 CVE-2024-8963 - Ivanti Cloud Services Appliance - Path Traversal
  http/cves/2024/CVE-2024-8963.yaml
Labels: Done

#11160 Create bigant-default-login.yaml
  http/default-logins/bigant/bigant-default-login.yaml
Labels: Done

#11159 Create CVE-2021-44260.yaml
  http/cves/2021/CVE-2021-44260.yaml
Labels: Done

#11157 Create CVE-2023-49494.yaml
  http/cves/2023/CVE-2023-49494.yaml
Labels: Done

#11145 Rename CVE-2024-32651.yaml to CVE-2024-32651.yaml (Move Directory)
  passive/cves/2024/CVE-2024-32651.yaml
Labels: Done

#11154 Create CVE-2022-31260.yaml
  http/cves/2022/CVE-2022-31260.yaml
Labels: Done

#11152 Create CVE-2022-28033.yaml
  http/cves/2022/CVE-2022-28033.yaml
Labels: Done

#11142 Create atlantis-dashboard.yaml (Atlantis Dashboard - Exposure)
  http/misconfiguration/atlantis-dashboard.yaml
Labels: Done

#11143 Create minio-console-default-login.yaml
  http/default-logins/minio/minio-object-default-login.yaml
Labels: Done

#11141 Add detection of PRONOTE login panel instances.
  http/exposed-panels/pronote-panel.yaml
Labels: Done

#11140 Add detection of HYPERPLANNING login panel instances.
  http/exposed-panels/hyperplanning-panel.yaml
Labels: Done

#11115 Multiple login panel templates
  http/exposed-panels/actifio-panel.yaml
  http/exposed-panels/adapt-panel.yaml
  http/exposed-panels/aethra-panel.yaml
  http/exposed-panels/deepmail-panel.yaml
  http/exposed-panels/quest-panel.yaml
Labels: Hacktoberfest, Done

#11139 False Positive Detection for Cloudflare in CSP
  http/miscellaneous/azure-blob-core-detect.yaml
  http/technologies/tech-detect.yaml
Labels: good first issue, Done

#11158 Create CVE-2018-10383.yaml
  http/cves/2018/CVE-2018-10383.yaml
Labels: Done

#11151 Create CVE-2022-0479.yaml
  http/cves/2022/CVE-2022-0479.yaml
Labels: Done

#11169 Update linux-lfi-fuzz.yaml
  dast/vulnerabilities/lfi/linux-lfi-fuzz.yaml
Labels: Done

#11168 fixfp phpwind-installer
  http/misconfiguration/installer/phpwind-installer.yaml
Labels: Done

#11172 Create ghe-encrypt-saml.yaml (GitHub Enterprise - Encrypted SAML Enabled)
  http/misconfiguration/ghe-encrypt-saml.yaml
Labels: Done

#11173 Create CVE-2024-9487 (GitHub Enterprise - SAML Authentication Bypass)
  http/cves/2024/CVE-2024-9487.yaml
Labels: Done

#11198 Fix FP CVE-2023-46805.yaml
  http/cves/2023/CVE-2023-46805.yaml
Labels: Done

#11193 Create panos-management-panel.yaml
  http/exposed-panels/panos-management-panel.yaml
Labels: Done

#11186 Create CVE-2024-10081.yaml (CodeChecker <= 6.24.1 Authentication Bypass)
  http/cves/2024/CVE-2024-10081.yaml
Labels: Done

#11187 Create CVE-2024-35219.yaml (OpenAPI Generator <= 7.5.0 - Arbitrary File Read/Delete)
  http/cves/2024/CVE-2024-35219.yaml
Labels: Done

#11188 Create CVE-2024-51483.yaml (Changedetection.io <= 0.47.4 Path Traversal)
  http/cves/2024/CVE-2024-51483.yaml
Labels: Done

#11189 Create CVE-2024-36117.yaml (Reposilite >= 3.3.0, < 3.5.12 Arbitrary File Read)
  http/cves/2024/CVE-2024-36117.yaml
Labels: Done

#11197 Create pgwatch2-db-exposure.yaml (Pgwatch2 DBs to monitor - Exposure)
  http/misconfiguration/pgwatch2-db-exposure.yaml
Labels: Done

#11196 Create CVE-2024-50340.yaml (Remote Access to Symfony Profiler via Injected Arguments)
  http/cves/2024/CVE-2024-50340.yaml
Labels: Done

#11194 add cve-2024-10914
  http/cves/2024/CVE-2024-10914.yaml
Labels: Done

#11162 Create CVE-2021-24934.yaml
  http/cves/2021/CVE-2021-24934.yaml
Labels: Done

#11209 Create CVE-2017-18590.yaml
  http/cves/2017/CVE-2017-18590.yaml
Labels: Done

#11208 Create CVE-2024-8673.yaml
  http/cves/2024/CVE-2024-8673.yaml
Labels: Done

#11207 Create Login Panel Templates
  http/exposed-panels/alamos-panel.yaml
  http/exposed-panels/alfresco-panel.yaml
  http/exposed-panels/alternc-panel.yaml
  http/exposed-panels/anmelden-panel.yaml
  http/technologies/amazon-ecs-defualt-page.yaml
Labels: Done

#11206 Refactor the "Thruk" template.
  http/exposed-panels/thruk-login.yaml
  http/exposed-panels/thruk-panel.yaml
  workflows/thruk-workflow.yaml
Labels: Done

#11204 Rename spring4shell-CVE-2022-22965.yaml to CVE-2022-22965.yaml for consistency
  dast/cves/2022/CVE-2022-22965.yaml
Labels: Done

#11203 Add detection of AKUITEO login panel instances.
  http/exposed-panels/akuiteo-panel.yaml
Labels: Done

#11215 Release prep - v10.0.4
  http/cves/2024/CVE-2024-51483.yaml
  http/cves/2024/CVE-2024-9487.yaml
Labels: Done

#11147 Fortinet FGFM protocol
  http/default-logins/minio/minio-object-default-login.yaml
  network/detection/fortinet-fgfm-detect.yaml
Labels: Done

#11156 Create CVE-2022-48166.yaml
  http/cves/2022/CVE-2022-48166.yaml
Labels: Done

#11155 Create CVE-2022-48164.yaml
  http/cves/2022/CVE-2022-48164.yaml
Labels: Done

#11153 Create CVE-2022-44356.yaml
  http/cves/2022/CVE-2022-44356.yaml
Labels: Done

#11216 Update contributors.json
  contributors.json
Labels: Done

#11214 Rename tag from joomla\! to joomla
  http/cves/2019/CVE-2019-9922.yaml
Labels: Done

#11163 Updated CVE-2019-0232.yaml
  http/cves/2019/CVE-2019-0232.yaml
  http/cves/2024/CVE-2024-7029.yaml
Labels: good first issue, Done

#11221 Fixing FP wordpress-wp-cron.yaml
  http/vulnerabilities/wordpress/wordpress-wp-cron.yaml
Labels: Done

#10627 Create CVE-2024-38653.yaml
  http/cves/2024/CVE-2024-38653.yaml
Labels: Done

#11222 Create CVE-2024-0012.yaml (PAN-OS Management Web Interface - Authentication Bypass 🔥 )
  http/cves/2024/CVE-2024-0012.yaml
Labels: Done

#11227 Update CVE-2024-5217.yaml
  http/cves/2024/CVE-2024-5217.yaml
Labels: Done

#11229 Wrong author CVE-2017-18590.yaml
  http/cves/2017/CVE-2017-18590.yaml
Labels: Done

#11093 fix: avoid false positives in prestashop SQLi
  http/cves/2023/CVE-2023-27847.yaml
  http/cves/2023/CVE-2023-39650.yaml
  http/cves/2024/CVE-2024-36683.yaml
Labels: Done

#11235 Added Flow -> gradio-ssrf.yaml & gradio-lfi.yaml
  http/vulnerabilities/gradio/gradio-lfi.yaml
  http/vulnerabilities/gradio/gradio-ssrf.yaml
Labels: Done

#11228 add cve-2024-9935
  http/cves/2024/CVE-2024-9935.yaml
Labels: Done

#11224 Create tactical-rmm-panel.yaml + trendmicro-apexone-panel.yaml
  http/exposed-panels/tactical-rmm-panel.yaml
  http/exposed-panels/trendmicro-apexone-panel.yaml
Labels: Done

#11200 Adding Geovision Geowebserver LFI XSS
  http/vulnerabilities/geovision-geowebserver-lfi-xss.yaml
Labels: good first issue, Done

#11236 Create CVE-2024-46938.yaml (Sitecore Experience Platform up to 10.4 Information Disclosure 🔥 )
  http/cves/2024/CVE-2024-46938.yaml
Labels: Done

#11248 Update aspx-debug-mode.yaml
  http/misconfiguration/aspx-debug-mode.yaml
Labels: Done

#11246 Update gradio-ssrf.yaml
  http/vulnerabilities/gradio/gradio-ssrf.yaml
Labels: Done

#11247 Update gradio-lfi.yaml
  http/vulnerabilities/gradio/gradio-lfi.yaml
Labels: Done

#11256 Create CVE-2022-2130.yaml
  http/cves/2022/CVE-2022-2130.yaml
Labels: Done

#11237 Add additional port 6835/tcp to Apache ActiveMQ OpenWire Transport detection
  network/detection/activemq-openwire-transport-detect.yaml
Labels: good first issue, Done

#11266 Create CVE-2024-51482.yaml
  http/cves/2024/CVE-2024-51482.yaml
Labels: Done

#11201 Create CVE-2020-24881.yaml
  http/cves/2020/CVE-2020-24881.yaml
Labels: Done, 🙋 Bounty claim
