Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-12, with the labels that each got.

#11262 add fronsetiav-xss
  http/vulnerabilities/fronsetiav-xss.yaml
Labels: Done

#11202 Add detection of DUFS instances.
  http/technologies/dufs-detect.yaml
Labels: Done

#11217 Create infoblox-nios.yaml
  http/exposed-panels/infoblox-nios-panel.yaml
Labels: Done

#11230 Added template for yongyou-YonBIP-yonbiplogin-leak
  http/vulnerabilities/yonyou/yonyou-yonbip-lfi.yaml
Labels: Done

#11257 Update projectsend-auth-bypass.yaml
  http/vulnerabilities/projectsend-auth-bypass.yaml
Labels: Done

#11260 add CVE-2024-9186
  http/cves/2024/CVE-2024-9186.yaml
Labels: Done

#11259 add CVE-2024-43919
  http/cves/2024/CVE-2024-43919.yaml
Labels: Done

#11261 add CVE-2024-50498
  http/cves/2024/CVE-2024-50498.yaml
Labels: Done

#11252 Added Blue Yonder Login Panel Detection
  http/exposed-panels/blue-yonder-panel.yaml
Labels: good first issue, Done

#11277 Update CVE-2018-7314 tags
  http/cves/2018/CVE-2018-7314.yaml
Labels: Done

#11278 Create CVE-2022-24819.yaml
  http/cves/2022/CVE-2022-24819.yaml
Labels: Done

#11282 Create CVE-2022-0250.yaml
  http/cves/2022/CVE-2022-0250.yaml
Labels: Done

#11283 Create CVE-2021-34630.yaml
  http/cves/2021/CVE-2021-34630.yaml
Labels: Done

#11274 Add detection of Twenty CRM instances.
  http/technologies/twenty-detect.yaml
Labels: Done

#11287 Create pkp-lib-open-redirect.yaml
  http/vulnerabilities/pkp-lib-open-redirect.yaml
Labels: Done

#11284 Create gtranslate-open-redirect.yaml
  http/vulnerabilities/wordpress/wp-gtranslate-open-redirect.yaml
Labels: Done

#11272 Create k8s-missing-network-policies.yaml
  cloud/kubernetes/network-policies/k8s-missing-network-policies.yaml
Labels: Done

#11263 Create CVE-2022-41800.yaml
  http/cves/2022/CVE-2022-41800.yaml
Labels: Done

#11273 Add detection of VINCE login panel instances.
  http/exposed-panels/vince-panel.yaml
Labels: Done

#11220 Create CVE-2024-10924.yaml
  http/cves/2024/CVE-2024-10924.yaml
Labels: Done

#11268 Create CVE-2024-3848.yaml
  http/cves/2024/CVE-2024-3848.yaml
Labels: Done

#11171 Create CVE-2016-8735.yaml
  http/cves/2016/CVE-2016-8735.yaml
Labels: Done, 🙋 Bounty claim

#11294 Release Prep
  helpers/wordpress/plugins/backuply.txt
  helpers/wordpress/plugins/burst-statistics.txt
Labels: Done

#11295 Update springboot-info.yaml
  http/misconfiguration/springboot/springboot-info.yaml
Labels: Done

#11175 Added template for CVE-2022-31470
  http/cves/2022/CVE-2022-31470.yaml
Labels: Done

#11210 Create CVE-2024-49380.yaml
  http/cves/2024/CVE-2024-49380.yaml
Labels: Done

#10482 Create CVE-2024-2928
  http/cves/2024/CVE-2024-2928.yaml
Labels: good first issue, Done

#10479 CREATE CVE-2024-5334
  http/cves/2024/CVE-2024-5334.yaml
Labels: good first issue, Done

#11306 Create CVE-2023-3990.yaml
  http/cves/2023/CVE-2023-3990.yaml
Labels: Done

#11305 Create CVE-2022-4375.yaml
  http/cves/2022/CVE-2022-4375.yaml
Labels: Done

#11307 Create mcms-search-xss.yaml
  http/vulnerabilities/other/mcms-search-xss.yaml
Labels: Done

#11304 Create mcms-list-sqli.yaml
  http/vulnerabilities/mingsoft/mcms-list-sqli.yaml
Labels: Done

#11303 Create mitel-arbitary-file-read.yaml
  http/vulnerabilities/mitel/mitel-arbitary-file-read.yaml
Labels: Done

#11310 added additional path
  http/exposures/files/service-account-credentials.yaml
Labels: Done

#11311 add CVE-2024-11305
  http/cves/2024/CVE-2024-11305.yaml
Labels: Done

#11299 Create dlink-dns-rce.yaml
  http/vulnerabilities/dlink/dlink-nas-rce.yaml
Labels: Done

#11144 Added template for CVE-2023-46455, CVE-2023-50094
  http/cves/2023/CVE-2023-46455.yaml
  http/cves/2023/CVE-2023-50094.yaml
Labels: Done

#11258 add CVE-2024-52433
  http/cves/2024/CVE-2024-52433.yaml
Labels: Done

#11313 Create CVE-2024-10516.yaml
  http/cves/2024/CVE-2024-10516.yaml
Labels: Done

#11290 [AWS] SQS (3 Templates)
  cloud/aws/sqs/sqs-deadletter-disabled.yaml
  cloud/aws/sqs/sqs-encryption-disabled.yaml
  cloud/aws/sqs/sqs-queue-exposed.yaml
Labels: Done

#11291 [AWS] ELB (1 - Template)
  cloud/aws/elb/elb-delete-protection-disabled.yaml
Labels: Done

#11308 Fix FN wp-enabled-registration.yaml
  http/vulnerabilities/wordpress/wp-enabled-registration.yaml
Labels: Done

#11312 Create exposed-pki-cert.yaml
  http/exposures/files/exposed-pki-cert.yaml
Labels: Done

#11316 Create CVE-2023-37599.yaml
  http/cves/2023/CVE-2023-37599.yaml
Labels: Done

#11317 Update sonicwall-sslvpn-panel.yaml
  http/exposed-panels/sonicwall-sslvpn-panel.yaml
Labels: Done

#11298 Create FeiYuXing-Ent-Router-InfoLeak.yaml
  http/vulnerabilities/feiyuxing/feiyuxing-ent-router-infoleak.yaml
Labels: Done

#11296 Create H3C-Ent-Router-InfoLeak.yaml
  http/cves/2024/CVE-2024-32238.yaml
Labels: Done

#11285 Secret Scanning Tokens & Files
  http/exposures/tokens/rapid/rapidapi-access-token.yaml
  http/exposures/tokens/readme/readme-api-token.yaml
  http/exposures/tokens/ruby/rubygems-api-key.yaml
  http/exposures/tokens/scalingo/scalingo-api-token.yaml
  http/exposures/tokens/sendbird/sendbird-access-id.yaml
  http/exposures/tokens/sendbird/sendbird-access-token.yaml
  http/exposures/tokens/sendgrid/sendgrid-api-key.yaml
  http/exposures/tokens/sendinblue/sendinblue-api-token.yaml
  http/exposures/tokens/sentry/sentry-access-token.yaml
  http/exposures/tokens/shippo/shippo-api-token.yaml
  http/exposures/tokens/shopify/shopify-private-app-access-token.yaml
  http/exposures/tokens/shopify/shopify-shared-secret.yaml
  http/exposures/tokens/sidekiq/sidekiq-secret.yaml
  http/exposures/tokens/sidekiq/sidekiq-sensitive-url.yaml
  http/exposures/tokens/slack/slack-app-token.yaml
  http/exposures/tokens/slack/slack-bot-token.yaml
  http/exposures/tokens/slack/slack-config-access-token.yaml
  http/exposures/tokens/slack/slack-config-refresh-token.yaml
  http/exposures/tokens/slack/slack-legacy-bot-token.yaml
  http/exposures/tokens/slack/slack-legacy-token.yaml
  http/exposures/tokens/slack/slack-legacy-workspace-token.yaml
  http/exposures/tokens/slack/slack-user-token.yaml
  http/exposures/tokens/slack/slack-webhook-token.yaml
  http/exposures/tokens/square/square-access.yaml
  http/exposures/tokens/squarespace/squarespace-access-token.yaml
  http/exposures/tokens/stripe/stripe-access-token.yaml
  http/exposures/tokens/sumologic/sumologic-access-id.yaml
  http/exposures/tokens/sumologic/sumologic-access-token.yaml
  http/exposures/tokens/synk/snyk-api-token.yaml
  http/exposures/tokens/telegram/telegram-bot-token.yaml
  http/exposures/tokens/travisci/travisci-access-token.yaml
  http/exposures/tokens/twitch/twitch-api-token.yaml
  http/exposures/tokens/twitter/twitter-api-key.yaml
  http/exposures/tokens/twitter/twitter-api-secret.yaml
  http/exposures/tokens/twitter/twitter-bearer-token.yaml
  http/exposures/tokens/typeform/typeform-api-token.yaml
  http/exposures/tokens/vault/vault-batch-token.yaml
  http/exposures/tokens/vault/vault-service-token.yaml
  http/exposures/tokens/yandex/yandex-access-token.yaml
  http/exposures/tokens/yandex/yandex-api-key.yaml
  http/exposures/tokens/yandex/yandex-aws-access-token.yaml
Labels: Done

#11319 added gitlab-exterprise explore
  http/exposed-panels/gitlab-explore.yaml
Labels: Done

#11318 Create backup-directory-listing.yaml
  http/exposures/backups/backup-directory-listing.yaml
Labels: Done

#11292 add aishu-anyshare-information-disclosure
  http/vulnerabilities/other/aishu-anyshare-info-exposure.yaml
Labels: Done

#11191 Create CVE-2017-1000353.yaml
  http/cves/2017/CVE-2017-1000353.yaml
Labels: Done, 🙋 Bounty claim

#11326 Update api-dbt.yaml
  http/token-spray/api-dbt.yaml
Labels: Done

#11323 Add detection of HUGINN login panel instances.
  http/exposed-panels/huginn-panel.yaml
Labels: Done

#11320 Fix Typo in Google,Fofa,Max-Request
  http/cves/2000/CVE-2000-0760.yaml
  http/cves/2023/CVE-2023-46818.yaml
  http/cves/2024/CVE-2024-45622.yaml
  http/cves/2024/CVE-2024-6781.yaml
  http/cves/2024/CVE-2024-6782.yaml
  http/cves/2024/CVE-2024-7008.yaml
  http/technologies/gitbook-detect.yaml
  http/vulnerabilities/other/panabit-ixcache-rce.yaml
  http/vulnerabilities/other/shoowbiz-xss.yaml
Labels: Done

#11322 add CVE-2024-48307
  http/cves/2024/CVE-2024-48307.yaml
Labels: Done

#11321 add CVE-2024-12209
  http/cves/2024/CVE-2024-12209.yaml
Labels: Done

#11328 Create CVE-2024-8856.yaml (WP Time Capsule Plugin - Remote Code Execution)
  http/cves/2024/CVE-2024-8856.yaml
Labels: Done

#11329 Create CVE-2024-39887.yaml (Apache Superset < 4.0.2 - SQL Injection)
  http/cves/2024/CVE-2024-39887.yaml
Labels: Done

#11335 Create CVE-2024-45293.yaml
  http/cves/2024/CVE-2024-45293.yaml
Labels: Done

#11331 Create CVE-2024-50623.yaml (Cleo - Arbitary File Read)
  http/cves/2024/CVE-2024-50623.yaml
Labels: Done

#11327 OOB - Template Engine Injection
  dast/vulnerabilities/ssti/oob/blade-oob.yaml
  dast/vulnerabilities/ssti/oob/bottle-oob.yaml
  dast/vulnerabilities/ssti/oob/chameleon-oob.yaml
  dast/vulnerabilities/ssti/oob/dotjs-oob.yaml
  dast/vulnerabilities/ssti/oob/ejs-underscore-oob.yaml
  dast/vulnerabilities/ssti/oob/erb-erubi-erubis-oob.yaml
  dast/vulnerabilities/ssti/oob/freemarker-oob.yaml
  dast/vulnerabilities/ssti/oob/groovy-oob.yaml
  dast/vulnerabilities/ssti/oob/jinja2-oob.yaml
  dast/vulnerabilities/ssti/oob/latte-oob.yaml
  dast/vulnerabilities/ssti/oob/mako-oob.yaml
  dast/vulnerabilities/ssti/oob/pugjs-oob.yaml
  dast/vulnerabilities/ssti/oob/tornado-oob.yaml
  dast/vulnerabilities/ssti/oob/velocityjs-oob.yaml
Labels: Done

#11164 Add CVE-2020-13935.yaml Template - Apache Tomcat WebSocket Frame Payload Length Validation Denial of Service
  code/cves/2020/CVE-2020-13935.yaml
Labels: 🙋 Bounty claim

#11346 Fixed [FALSE-POSITIVE] - x11-unauth-access
  javascript/misconfiguration/x11/x11-unauth-access.yaml
Labels: Done

#11343 Create CVE-2023-1119.yaml
  http/cves/2023/CVE-2023-1119.yaml
Labels: Done

#11341 Create wp-vr-view-xss.yaml
  http/vulnerabilities/wordpress/wp-vr-view-xss.yaml
Labels: Done

#11353 Create CVE-2022-2552.yaml
  http/cves/2022/CVE-2022-2552.yaml
Labels: Done

#11352 Create CVE-2019-9912.yaml
  http/cves/2019/CVE-2019-9912.yaml
Labels: Done

#11351 Create CVE-2023-6697.yaml
  http/cves/2023/CVE-2023-6697.yaml
Labels: Done

#11250 Added template for hue-wireless-lighting
  http/technologies/hue-wireless-lighting.yaml
Labels: Done

#11374 Create CVE-2024-36404.yaml (GeoServer & GeoTool - RCE)
  http/cves/2024/CVE-2024-36404.yaml
Labels: Done

#11332 Alibaba Cloud - Audit Templates
  cloud/alibaba/actiontrail/multi-region-logging-disabled.yaml
  cloud/alibaba/aliyun-code-env.yaml
  cloud/alibaba/ecs/os-patches-outdated.yaml
  cloud/alibaba/ecs/unattached-disk-encryption-disabled.yaml
  cloud/alibaba/ecs/unattached-vminstance-encryption-disabled.yaml
  cloud/alibaba/ecs/unrestricted-rdp-access.yaml
  cloud/alibaba/ecs/unrestricted-ssh-access.yaml
  cloud/alibaba/ram/custom-ram-policy-admin-priv.yaml
  cloud/alibaba/ram/max-password-retry-disabled.yaml
  cloud/alibaba/ram/mfa-console-password-disabled.yaml
  cloud/alibaba/ram/password-policy-expiration-unconfigured.yaml
  cloud/alibaba/ram/password-policy-length-unconfigured.yaml
  cloud/alibaba/ram/password-policy-lowercase-unconfigured.yaml
  cloud/alibaba/ram/password-policy-num-unconfigured.yaml
  cloud/alibaba/ram/password-policy-reuse-enabled.yaml
  cloud/alibaba/ram/password-policy-symbol-unconfigured.yaml
  cloud/alibaba/ram/password-policy-uppercase-unconfigured.yaml
  cloud/alibaba/rds/encryption-intransit-disabled.yaml
  cloud/alibaba/rds/log-connections-disabled.yaml
  cloud/alibaba/rds/log-disconnections-disabled.yaml
  cloud/alibaba/rds/log-duration-disabled.yaml
  cloud/alibaba/rds/mssql-audit-disabled.yaml
  cloud/alibaba/rds/mysql-audit-disabled.yaml
  cloud/alibaba/rds/postgresql-audit-disabled.yaml
  cloud/alibaba/rds/rds-audit-disabled.yaml
  cloud/alibaba/rds/transparent-encryption-disabled.yaml
  cloud/alibaba/security-center/scheduled-vulnscan-disabled.yaml
  cloud/alibaba/security-center/security-notification-disabled.yaml
  cloud/alibaba/security-center/security-plan-disabled.yaml
  cloud/alibaba/vpc/vpc-flow-disabled.yaml
  profiles/aliyun-cloud-config.yml
Labels: Done

#11240 Update CVE-2024-5217.yaml
  http/cves/2024/CVE-2024-5217.yaml
Labels: Done

#11245 Update CVE-2019-17382.yaml
  http/cves/2019/CVE-2019-17382.yaml
Labels: Done

#11293 Create api-jotform.yaml
  http/token-spray/api-jotform.yaml
Labels: Done

#11342 Wordpress Hunk Companion detection
  helpers/wordpress/plugins/hunk-companion.txt
  http/technologies/wordpress/plugins/hunk-companion.yaml
Labels: Done

#11382 Fixed False Negatives in cookies-without-httponly and cookies-without-secure
  http/misconfiguration/cookies-without-httponly.yaml
  http/misconfiguration/cookies-without-secure.yaml
Labels: Done

#11388 Create CVE-2024-55956.yaml
  http/cves/2024/CVE-2024-55956.yaml
Labels: Done

#11386 Create CVE-2024-10400.yaml
  http/cves/2024/CVE-2024-10400.yaml
Labels: Done

#11383 Create CVE-2024-52875.yaml
  http/cves/2024/CVE-2024-52875.yaml
Labels: Done

#11389 Enrich the JUMPSERVER template.
  http/exposed-panels/jumpserver-panel.yaml
Labels: Done

#11387 Add detection of OPENOBSERVE login panel instances.
  http/exposed-panels/openobserve-panel.yaml
Labels: Done

#11376 add easycvr-arbitrary-file-read
  http/vulnerabilities/other/easycvr-arbitrary-file-read.yaml
Labels: Done

#11345 add CVE-2024-11728
  http/cves/2024/CVE-2024-11728.yaml
Labels: Done

#11339 Cleo Detect
  http/technologies/cleo-detect.yaml
Labels: Done

#11330 Add detection of RICOH Web Image Monitor devices
  http/exposed-panels/ricoh-webimagemonitor-panel.yaml
Labels: Done

#11251 Fortinet Product Certificates
  ssl/fortinet/fortianalyzer-certificate.yaml
  ssl/fortinet/fortiauthenticator.yaml
  ssl/fortinet/fortiddos.yaml
  ssl/fortinet/fortigate-certificate.yaml
  ssl/fortinet/fortimanager-certificate.yaml
  ssl/fortinet/fortiwifi-certificate.yaml
Labels: Done

#11232 Create CVE-2024-11303.yaml
  http/cves/2024/CVE-2024-11303.yaml
Labels: Done

#11314 infinitt pacs system vuln
  http/vulnerabilities/infinitt/infinitt-pacs-file-upload.yaml
  http/vulnerabilities/infinitt/infinitt-pacs-info-leak.yaml
Labels: Done

#11081 add CVE-2024-45309
  http/cves/2024/CVE-2024-45309.yaml
Labels: Done

#10577 Added CVE-2020-15906 Template
  http/cves/2020/CVE-2020-15906.yaml
Labels: good first issue, Done

#11254 Create CVE-2024-8859.yaml
  http/cves/2024/CVE-2024-8859.yaml
Labels: Done

#11397 Fixed CVSS scoring on CVE-2024-43919
  http/cves/2024/CVE-2024-43919.yaml
Labels: Done

#11385 Alibaba Cloud - Checks (OSS, ACK)
  cloud/alibaba/ack/ack-cluster-api-public.yaml
  cloud/alibaba/ack/ack-cluster-auditing-disable.yaml
  cloud/alibaba/ack/ack-cluster-cloud-monitor-disable.yaml
  cloud/alibaba/ack/ack-cluster-health-disable.yaml
  cloud/alibaba/ack/ack-cluster-network-policies-disable.yaml
  cloud/alibaba/ack/ack-cluster-network-policies-missing.yaml
  cloud/alibaba/ack/kubernetes-dashboard-enabled.yaml
  cloud/alibaba/actiontrail/multi-region-logging-disabled.yaml
  cloud/alibaba/actiontrail/public-actiontrail-bucket.yaml
  cloud/alibaba/ecs/os-patches-outdated.yaml
  cloud/alibaba/ecs/unattached-disk-encryption-disabled.yaml
  cloud/alibaba/ecs/unattached-vminstance-encryption-disabled.yaml
  cloud/alibaba/ecs/unrestricted-rdp-access.yaml
  cloud/alibaba/ecs/unrestricted-ssh-access.yaml
  cloud/alibaba/oss/improper-bucket-sse.yaml
  cloud/alibaba/oss/sse-cmk-disabled.yaml
  cloud/alibaba/oss/sse-smk-disabled.yaml
  cloud/alibaba/ram/password-policy-expiration-unconfigured.yaml
  cloud/alibaba/ram/password-policy-length-unconfigured.yaml
  cloud/alibaba/rds/mssql-audit-disabled.yaml
  cloud/alibaba/rds/mysql-audit-disabled.yaml
  cloud/alibaba/rds/postgresql-audit-disabled.yaml
  cloud/alibaba/rds/rds-audit-disabled.yaml
  cloud/alibaba/rds/transparent-encryption-disabled.yaml
  cloud/alibaba/vpc/vpc-flow-disabled.yaml
Labels: Done

#11384 Alibaba OSS Templates
  cloud/alibaba/oss/access-logoss-disabled.yaml
  cloud/alibaba/oss/limit-networkaccess-disabled.yaml
  cloud/alibaba/oss/oos-bucket-public-access.yaml
  cloud/alibaba/oss/secure-transfeross-disabled.yaml
Labels: Done

#11408 Release Prep - v10.1.1
  cloud/alibaba/actiontrail/multi-region-logging-disabled.yaml
  cloud/alibaba/alibaba-cloud-code-env.yaml
  cloud/alibaba/ecs/os-patches-outdated.yaml
  cloud/alibaba/ecs/unattached-disk-encryption-disabled.yaml
  cloud/alibaba/ecs/unattached-vminstance-encryption-disabled.yaml
  cloud/alibaba/ecs/unrestricted-rdp-access.yaml
  cloud/alibaba/ecs/unrestricted-ssh-access.yaml
  cloud/alibaba/ram/custom-ram-policy-admin-priv.yaml
  cloud/alibaba/ram/max-password-retry-disabled.yaml
  cloud/alibaba/ram/mfa-console-password-disabled.yaml
  cloud/alibaba/ram/password-policy-expiration-unconfigured.yaml
  cloud/alibaba/ram/password-policy-length-unconfigured.yaml
  cloud/alibaba/ram/password-policy-lowercase-unconfigured.yaml
  cloud/alibaba/ram/password-policy-num-unconfigured.yaml
  cloud/alibaba/ram/password-policy-reuse-enabled.yaml
  cloud/alibaba/ram/password-policy-symbol-unconfigured.yaml
  cloud/alibaba/ram/password-policy-uppercase-unconfigured.yaml
  cloud/alibaba/rds/encryption-intransit-disabled.yaml
  cloud/alibaba/rds/log-connections-disabled.yaml
  cloud/alibaba/rds/log-disconnections-disabled.yaml
  cloud/alibaba/rds/log-duration-disabled.yaml
  cloud/alibaba/rds/mssql-audit-disabled.yaml
  cloud/alibaba/rds/mysql-audit-disabled.yaml
  cloud/alibaba/rds/postgresql-audit-disabled.yaml
  cloud/alibaba/rds/rds-audit-disabled.yaml
  cloud/alibaba/rds/transparent-encryption-disabled.yaml
  cloud/alibaba/security-center/scheduled-vulnscan-disabled.yaml
  cloud/alibaba/security-center/security-notification-disabled.yaml
  cloud/alibaba/security-center/security-plan-disabled.yaml
  cloud/alibaba/vpc/vpc-flow-disabled.yaml
  profiles/alibaba-cloud-config.yml
Labels: Done

#11413 Severity Update
  dast/vulnerabilities/ssti/oob/blade-oob.yaml
  dast/vulnerabilities/ssti/oob/bottle-oob.yaml
  dast/vulnerabilities/ssti/oob/chameleon-oob.yaml
  dast/vulnerabilities/ssti/oob/dotjs-oob.yaml
  dast/vulnerabilities/ssti/oob/ejs-underscore-oob.yaml
  dast/vulnerabilities/ssti/oob/erb-erubi-erubis-oob.yaml
  dast/vulnerabilities/ssti/oob/freemarker-oob.yaml
  dast/vulnerabilities/ssti/oob/groovy-oob.yaml
  dast/vulnerabilities/ssti/oob/jinja2-oob.yaml
  dast/vulnerabilities/ssti/oob/latte-oob.yaml
  dast/vulnerabilities/ssti/oob/mako-oob.yaml
  dast/vulnerabilities/ssti/oob/pugjs-oob.yaml
  dast/vulnerabilities/ssti/oob/tornado-oob.yaml
  dast/vulnerabilities/ssti/oob/velocityjs-oob.yaml
Labels: Done

#11407 Rename folder from http to code CVE-2017-1000353
  code/cves/2017/CVE-2017-1000353.yaml
Labels: Done

#11269 Create CVE-2023-48788.yaml
  network/cves/2023/CVE-2023-48788.yaml
Labels: good first issue, Done, 🙋 Bounty claim

#11418 Fix FP CVE-2024-43919.yaml
  http/cves/2024/CVE-2024-43919.yaml
Labels: Done

#3915 Added jolokia templates
  http/misconfiguration/jolokia/jolokia-info-disclosure.yaml
  http/misconfiguration/jolokia/jolokia-list.yaml
  http/technologies/jolokia-detect.yaml
  http/vulnerabilities/jolokia/jolokia-acceslogvalve-rce.yaml
  http/vulnerabilities/jolokia/jolokia-createstandardhost-rce.yaml
  http/vulnerabilities/jolokia/jolokia-file-read-compilerdirectivesadd.yaml
  http/vulnerabilities/jolokia/jolokia-heap-info-disclosure.yaml
  http/vulnerabilities/jolokia/jolokia-tomcat-creds-leak.yaml
Labels: Status: On Hold

#11420 fix: should be self-contained
  http/osint/user-enumeration/mail-archive.yaml
Labels: Done

#9247 Added Token validation step using flow for token validity check
  http/exposures/tokens/github/github-personal-access.yaml
  http/exposures/tokens/gitlab/gitlab-personal-token.yaml
  http/exposures/tokens/mapbox/mapbox-token-disclosure.yaml
  http/exposures/tokens/npm/npm-access-token.yaml
  http/exposures/tokens/ruby/rubygems-api-key.yaml
  http/exposures/tokens/slack/slack-bot-token.yaml
  http/exposures/tokens/slack/slack-user-token.yaml
  http/exposures/tokens/slack/slack-webhook-token.yaml
  http/exposures/tokens/sonarqube/sonarqube-cloud-token.yaml
  http/exposures/tokens/square/square-access.yaml
  http/exposures/tokens/stackhawk/stackhawk-api.yaml
  http/exposures/tokens/stripe/stripe-secret-key.yaml
  http/exposures/tokens/telegram/telegram-bot-token.yaml
  http/exposures/tokens/zenserp/zenscrape-api-key.yaml
  http/exposures/tokens/zenserp/zenserp-api-key.yaml
Labels: Done

#11396 Create CVE-2024-11921.yaml
  http/cves/2024/CVE-2024-11921.yaml
Labels: Done

#10338 Bitrix admin panel
  http/exposed-panels/bitrix-panel.yaml
Labels: good first issue

#10968 Update php-debugbar-exposure.yaml
  http/misconfiguration/php-debugbar-exposure.yaml
Labels: Hacktoberfest
