Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-09, with the labels that each got.

#10644 Create CVE-2024-6670.yaml
  http/cves/2024/CVE-2024-6670.yaml
Labels: Done

#10646 ci(wordpress-plugins-update): fix no such device or address
  .github/workflows/wordpress-plugins-update.yml
Labels: Type: Maintenance

#10653 ci(readme-update): fix incorrect action ref
  .github/workflows/readme-update.yml
Labels: Done

#10654 ci(new-templates): rm `git pull` command
  .github/workflows/new-templates.yml
Labels: Done

#10648 fix-true-positive (Elementor DOM XSS)
  http/cves/2021/CVE-2021-24891.yaml
Labels: Done

#10651 Fix FP exposed-gitignore & mercurial-hgignore
  http/exposures/configs/exposed-gitignore.yaml
  http/exposures/configs/mercurial-hgignore.yaml
Labels: Done

#10652 Fix Gradio False Positive
  http/cves/2024/CVE-2024-1728.yaml
Labels: Done

#10655 Extractors fix x11-unauth-access.yaml
  javascript/misconfiguration/x11/x11-unauth-access.yaml
Labels: Done

#10656 add fastbee lfi
  http/vulnerabilities/other/fastbee-arbitrary-file-read.yaml
Labels: Done

#10643 Add CVE-2023-47684
  http/cves/2022/CVE-2022-21500.yaml
  http/cves/2023/CVE-2023-47684.yaml
  http/exposures/backups/php-backup-files.yaml
  http/exposures/configs/collibra-properties.yaml
  http/misconfiguration/installer/wp-install.yaml
  http/misconfiguration/phpmyadmin/phpmyadmin-setup.yaml
  http/token-spray/api-ipdata.yaml
  http/token-spray/api-ipinfo.yaml
  http/token-spray/api-networksdb.yaml
  http/token-spray/api-newrelic.yaml
  http/token-spray/api-notolytix.yaml
  http/token-spray/api-onyphe.yaml
  http/token-spray/api-opsgenie.yaml
  http/token-spray/api-ticketmaster.yaml
  http/token-spray/api-userstack.yaml
  http/token-spray/api-zerbounce.yaml
  http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
Labels: Done

#10658 Create CVE-2023-34105.yaml
  http/cves/2023/CVE-2023-34105.yaml
Labels: Done

#10660 Fixed FP - CVE-2017-12149.yaml
  http/cves/2017/CVE-2017-12149.yaml
Labels: Done

#10665 Fix FP -> tongda-arbitrary-login & Rename -> tongdaoa-auth-bypass
  http/vulnerabilities/tongda/tongdaoa-auth-bypass.yaml
Labels: Done

#10676 Create CVE-2023-35155.yaml
  http/cves/2023/CVE-2023-35155.yaml
Labels: Done

#10680 Create CVE-2024-20419.yaml
  http/cves/2024/CVE-2024-20419.yaml
Labels: Done

#10677 Update cookies-without-secure.yaml
  http/misconfiguration/cookies-without-secure.yaml
Labels: Done

#10668 Update projectsend-installer.yaml (New Path Added)
  http/misconfiguration/installer/projectsend-installer.yaml
Labels: Done

#10666 Create strapi-admin-installer.yaml
  http/misconfiguration/installer/strapi-admin-installer.yaml
Labels: Done

#10667 Create CVE-2023-22621.yaml
  http/cves/2023/CVE-2023-22621.yaml
Labels: Done

#10649 Update wordpress-detect.yaml
  http/technologies/wordpress-detect.yaml
Labels: Done

#10594 Fix false positive in Missing SRI template
  http/misconfiguration/missing-sri.yaml
Labels: Done

#10672 Create projectsend-auth-bypass.yaml
  http/vulnerabilities/projectsend-auth-bypass.yaml
Labels: Done

#10636 Create CVE-2024-28987.yaml
  http/cves/2024/CVE-2024-28987.yaml
Labels: Done

#10650 Create apache-hertzbeat-default-login.yaml
  http/default-logins/apache/apache-hertzbeat-default-login.yaml
Labels: Done

#10369 Add finereport-sqli-file-upload.yaml
  http/vulnerabilities/finereport/finereport-sqli-rce.yaml
Labels: good first issue, Done

#10683 Create CVE-2023-6329.yaml
  http/cves/2023/CVE-2023-6329.yaml
Labels: Done

#10682 Add Detection of Writebook. (http/technologies)
  http/technologies/writebook-detect.yaml
Labels: Done

#10685 Create CVE-2023-41621.yaml
  http/cves/2023/CVE-2023-41621.yaml
Labels: Done

#10684 Create emlog-installer.yaml
  http/misconfiguration/installer/emlog-installer.yaml
Labels: Done

#10670 Create CVE-2024-22120.yaml
  code/cves/2024/CVE-2024-22120.yaml
Labels: Done

#10673 Create CVE-2024-29889.yaml
  http/cves/2024/CVE-2024-29889.yaml
Labels: Done

#10681 Create CVE-2024-6586.yaml
  http/cves/2024/CVE-2024-6586.yaml
Labels: Done

#10679 Create CVE-2024-41955.yaml
  http/cves/2024/CVE-2024-41955.yaml
Labels: Done

#10686 Create repetier-unauth.yaml
  http/misconfiguration/repetier-unauth.yaml
Labels: Done

#10688 Create CVE-2024-20440.yaml (Cisco Smart Licensing Utility UnAuthentic…
  http/cves/2024/CVE-2024-20440.yaml
Labels: Done

#10687 Create CVE-2024-20439.yaml (Hardcoded Admin Credentials For Cisco Smart Licensing Utility API)
  http/cves/2024/CVE-2024-20439.yaml
Labels: Done

#10692 Create CVE-2024-29882.yaml (DOM - XSS on JSONP callback)
  headless/cves/2024/CVE-2024-29882.yaml
Labels: Done

#10661 Create CVE-2014-4577.yaml
  http/cves/2014/CVE-2014-4577.yaml
Labels: Done

#10663 Create CVE-2014-5187.yaml
  http/cves/2014/CVE-2014-5187.yaml
Labels: Done

#10662 Create CVE-2014-4941.yaml
  http/cves/2014/CVE-2014-4941.yaml
Labels: Done

#10664 Create CVE-2014-5181.yaml
  http/cves/2014/CVE-2014-5181.yaml
Labels: Done

#10674 Create CVE-2024-7029.yaml [KEV]
  http/cves/2024/CVE-2024-7029.yaml
Labels: Done

#10699 Create retool-dom-xss.yaml
  headless/vulnerabilities/retool/retool-dom-xss.yaml
Labels: Done

#10701 Create CVE-2024-45195.yaml
  http/cves/2024/CVE-2024-45195.yaml
Labels: Done

#10703 Create CVE-2023-41597.yaml
  http/cves/2023/CVE-2023-41597.yaml
Labels: Done

#10702 Create nginx-api-traversal.yaml
  http/misconfiguration/nginx/nginx-api-traversal.yaml
Labels: Done

#10697 add CVE-2024-6159
  http/cves/2024/CVE-2024-6159.yaml
Labels: Done

#10695 add CVE-2024-6926
  http/cves/2024/CVE-2024-6926.yaml
Labels: Done

#10694 add CVE-2024-6924
  http/cves/2024/CVE-2024-6924.yaml
Labels: Done

#10635 Added template for CVE-2024-38472
  http/cves/2024/CVE-2024-38472.yaml
Labels: Done

#10704 Create CVE-2024-45388.yaml
  http/cves/2024/CVE-2024-45388.yaml
Labels: Done

#10700 add CVE-2024-6846
  http/cves/2024/CVE-2024-6846.yaml
Labels: Done

#10698 add CVE-2024-7786
  http/cves/2024/CVE-2024-7786.yaml
Labels: Done

#10710 Update interlib-fileread.yaml
  http/vulnerabilities/other/interlib-fileread.yaml
Labels: Done

#10716 Create CVE-2007-2449.yaml
  http/cves/2007/CVE-2007-2449.yaml
Labels: Done

#10639 Create apache-jspwiki-detect.yaml and apache-jspwiki-IP-userenum.yaml
  http/exposures/configs/apache-jspwiki-ip-userenum.yaml
  http/technologies/apache/apache-jspwiki-detect.yaml
Labels: Done

#10713 Create imo-file-download.yaml
  http/vulnerabilities/imo/imo-file-download.yaml
Labels: Done

#10712 Create imo-rce.yaml
  http/vulnerabilities/imo/imo-rce.yaml
Labels: Done

#10711 Create fumasoft-sqli.yaml
  http/vulnerabilities/other/fumasoft-sqli.yaml
Labels: Done

#10706 Add detection of IBM API Connect login panel instances.
  http/exposed-panels/ibm/ibm-api-connect-panel.yaml
Labels: Done

#10637 Added an apache remote snoop vulnerability
  http/cves/2000/CVE-2000-0760.yaml
Labels: Done

#10719 update CNVD-C-2023-76801
  http/cnvd/2023/CNVD-C-2023-76801.yaml
Labels: Done

#10717 add CVE-2024-44849 - Unauthenticated Remote Code Execution 🔥
  http/cves/2024/CVE-2024-44849.yaml
Labels: Done

#10718 Create mpftvc-admin-panel.yaml
  http/exposed-panels/mpftvc-admin-panel.yaml
Labels: good first issue, Done

#10715 Kemp Loadmaster Panel
  http/exposed-panels/kemp-loadmaster-panel.yaml
Labels: Done

#10714 Authentik SSO Login Panel Detection
  http/exposed-panels/authentik-panel.yaml
Labels: Done

#10709 Create CVE-2024-8517.yaml (SPIP BigUp Plugin - Unauthenticated Remote Code Execution 🔥 )
  http/cves/2024/CVE-2024-8517.yaml
Labels: Done

#10707 update: wp-xmlrpc-pingback-detection
  http/vulnerabilities/wordpress/wp-xmlrpc-pingback-detection.yaml
Labels: Done

#10708 Create CVE-2024-41667.yaml (OpenAM Authd FreeMarker Template Injection)
  http/cves/2024/CVE-2024-41667.yaml
Labels: Done

#10696 add CVE-2024-6928
  http/cves/2024/CVE-2024-6928.yaml
Labels: Done

#10456 Notifying if no HTTP Host header yields directory listing
  http/misconfiguration/directory-listing-no-host-header.yaml
Labels: Done

#10678 Add detection of IBM API Connect Developer Portal instances.
  http/technologies/ibm/ibm-api-connect-developer-portal-detect.yaml
Labels: Done

#10614 Added InPost, InPost PL and GiveWP WordPress Plugins
  helpers/wordpress/plugins/give.txt
  helpers/wordpress/plugins/inpost-for-woocommerce.txt
  helpers/wordpress/plugins/woo-inpost.txt
  http/technologies/wordpress/plugins/give.yaml
  http/technologies/wordpress/plugins/inpost-for-woocommerce.yaml
  http/technologies/wordpress/plugins/woo-inpost.yaml
Labels: Done

#10727 Create webp-server-lfi.yaml
  http/vulnerabilities/other/webp-server-lfi.yaml
Labels: Done

#10726 Create nsfocus-auth-bypass.yaml
  http/vulnerabilities/other/nsfocus-auth-bypass.yaml
Labels: Done

#10725 Create nsfocus-lfi.yaml
  http/vulnerabilities/other/nsfocus-lfi.yaml
Labels: Done

#10720 add yonyou ufida cloud sqli
  http/vulnerabilities/yonyou/yonyou-ufida-nc-cloud-sqli.yaml
Labels: Done

#10728 Update CVE-2021-24274.yaml (Added Missing Tag)
  http/cves/2021/CVE-2021-24274.yaml
Labels: Done

#10729 Update visionhub-default-login.yaml (Fix False Positive)
  http/default-logins/visionhub/visionhub-default-login.yaml
Labels: Done

#10738 v10.0.0 prep
  helpers/wordlists/wordpress-plugins.txt
  http/cves/2007/CVE-2007-2449.yaml
  http/cves/2024/CVE-2024-41667.yaml
  http/technologies/wordpress/plugins/wp-mail-logging.yaml
  http/vulnerabilities/imo/imo-rce.yaml
Labels: Done

#10486 Added CVE-2024-23167 Template by songhee
  http/cves/2024/CVE-2024-23167.yaml
Labels: good first issue, Done

#10733 Create CVE-2023-38992.yaml
  http/cves/2023/CVE-2023-38992.yaml
Labels: Done

#10734 Create fumengyun-sqli.yaml
  http/vulnerabilities/other/fumengyun-sqli.yaml
Labels: Done

#10300 FP - Fix - minecraft-enum
  javascript/enumeration/minecraft-enum.yaml
Labels: Done

#10750 Update ibm-api-connect-developer-portal-detect.yaml (Fix-FP)
  http/technologies/ibm/ibm-api-connect-developer-portal-detect.yaml
Labels: Done

#10751 Update CVE-2024-41667.yaml (Fix-FP)
  http/cves/2024/CVE-2024-41667.yaml
Labels: Done

#10752 Refactor the "GITEA" template.
  http/technologies/gitea-detect.yaml
Labels: Done

#10764 Create bonita-portal-panel.yaml
  http/exposed-panels/bonita-portal-panel.yaml
Labels: Done

#10763 Create bonita-default-login.yaml
  http/default-logins/bonita/bonita-default-login.yaml
Labels: Done

#10762 Create CVE-2023-3188.yaml
  http/cves/2023/CVE-2023-3188.yaml
Labels: Done

#10753 Add detection of DOMIBUS instances.
  http/technologies/domibus-detect.yaml
Labels: Done

#10755 add CVE-2024-8752
  http/cves/2024/CVE-2024-8752.yaml
Labels: Done

#10754 Create nginx-proxy-manager-default-login.yaml
  http/default-logins/nginx/nginx-proxy-manager-default-login.yaml
Labels: Done

#10732 add motic file read
  http/vulnerabilities/other/motic-dsm-arbitrary-file-read.yaml
Labels: Done

#10731 add CVE-2023-39024
  http/cves/2023/CVE-2023-39024.yaml
Labels: Done

#10737 add CVE-2024-3673
  http/cves/2024/CVE-2024-3673.yaml
Labels: Done

#10768 Added template for symfony-profiler
  http/exposures/configs/symfony-profiler.yaml
Labels: Done

#10756 add CVE-2024-45622
  http/cves/2024/CVE-2024-45622.yaml
Labels: Done

#10765 Refactor the "kubelet-metrics" template.
  http/technologies/kubernetes/kubelet/kubelet-metrics.yaml
Labels: Done

#10766 Create open-web-analytics-installer.yaml
  http/misconfiguration/installer/open-web-analytics-installer.yaml
Labels: Done

#10767 Create open-web-analytics-panel.yaml
  http/exposed-panels/open-web-analytics-panel.yaml
Labels: Done

#10757 add CVE-2024-8503
  http/cves/2024/CVE-2024-8503.yaml
Labels: Done

#10769 Create CVE-2023-43654.yaml
  http/cves/2023/CVE-2023-43654.yaml
Labels: Done

#10771 Create CVE-2024-45507.yaml
  http/cves/CVE-2024-45507.yaml
Labels: Done

#10770 Create torchserve-detect.yaml
  http/technologies/torchserve-detect.yaml
Labels: Done

#10777 add CVE-2023-6275
  http/cves/2023/CVE-2023-6275.yaml
Labels: Done

#10772 Create CVE-2024-28397.yaml
  http/cves/2024/CVE-2024-28397.yaml
Labels: Done

#10773 Create CVE-2022-24637.yaml
  http/cves/2022/CVE-2022-24637.yaml
Labels: Done

#10785 Rename http/cves/CVE-2024-45507.yaml to http/cves/2024/CVE-2024-45507…
  http/cves/2024/CVE-2024-45507.yaml
Labels: Done

#10780 Create filecatalyst-panel.yaml
  http/exposed-panels/filecatalyst-panel.yaml
Labels: Done

#10778 add CVE-2024-44000
  http/cves/2024/CVE-2024-44000.yaml
Labels: Done

#10739 Added 3 Presta CVEs
  http/cves/2023/CVE-2023-27847.yaml
  http/cves/2023/CVE-2023-39650.yaml
  http/cves/2024/CVE-2024-36683.yaml
Labels: Done

#10775 Update CVE-2018-25031.yaml
  headless/cves/2018/CVE-2018-25031.yaml
Labels: Done

#10795 Create tplink-r470t-default-login.yaml
  http/default-logins/tplink/tplink-r470t-default-login.yaml
Labels: Done

#10794 Create canon-c3325-default-login.yaml
  http/default-logins/canon/canon-c3325-default-login.yaml
Labels: Done

#10793 Create canon-c3325-unauth.yaml
  http/misconfiguration/canon-c3325-unauth.yaml
Labels: Done

#10792 Create CVE-2023-38192.yaml
  http/cves/2023/CVE-2023-38192.yaml
Labels: Done

#10784 Create nginx-webui-rce.yaml
  http/vulnerabilities/other/nginx-webui-rce.yaml
Labels: Done

#10783 Create netpower-npfw-lfi.yaml
  http/vulnerabilities/other/netpower-npfw-lfi.yaml
Labels: Done

#10800 Removing CVE-2023-35489 - False Positives
  http/cves/2020/CVE-2020-35489.yaml
Labels: Done

#10805 Create pcoweb-default-login.yaml
  http/default-logins/pcoweb/pcoweb-default-login.yaml
Labels: Done

#10806 Create pcoweb-unauth.yaml
  http/misconfiguration/pcoweb-unauth.yaml
Labels: Done

#10807 Create filegator-default-login.yaml
  http/default-logins/filegator/filegator-default-login.yaml
Labels: Done

#10808 Create topaccess-default-login.yaml
  http/default-logins/topaccess/topaccess-default-login.yaml
Labels: Done

#10809 Create topaccess-panel.yaml
  http/exposed-panels/toshiba/topaccess-panel.yaml
Labels: Done

#10810 Create filegator-panel.yaml
  http/exposed-panels/filegator-panel.yaml
Labels: Done

#10811 Create pcoweb-panel.yaml
  http/exposed-panels/pcoweb-panel.yaml
Labels: Done

#10813 Create canon-iradv-c3325.yaml
  http/exposed-panels/canon/canon-iradv-c3325.yaml
Labels: Done

#10812 Create tplink-r470t-panel.yaml
  http/exposed-panels/tplink/tplink-r470t-panel.yaml
Labels: Done

#10817 Create CVE-2023-3578.yaml
  http/cves/2023/CVE-2023-3578.yaml
Labels: Done

#10816 Create tplink-wR940n-default-login.yaml
  http/default-logins/tplink/tplink-wR940n-default-login.yaml
Labels: Done

#10820 Create CVE-2024-47062.yaml
  http/cves/2024/CVE-2024-47062.yaml
Labels: Done

#10819 Create navidrome-admin-install.yaml
  http/misconfiguration/installer/navidrome-admin-install.yaml
Labels: Done

#10802 Create qualitor-itsm-panel.yaml
  http/exposed-panels/open-stack-dashboard-login.yaml
  http/exposed-panels/qualitor-itsm-panel.yaml
Labels: Done

#10818 Create onimai-rat-c2.yaml
  ssl/c2/onimai-rat-c2.yaml
Labels: good first issue, Done

#10796 add CVE-2023-47253
  http/cves/2023/CVE-2023-47253.yaml
Labels: Done

#10815 Create CVE-2019-0232.yaml
  http/cves/2019/CVE-2019-0232.yaml
Labels: Done

#10814 Create CVE-2024-22207.yaml
  http/cves/2024/CVE-2024-22207.yaml
Labels: Done

#10834 Create CVE-2019-6793.yaml
  http/cves/2019/CVE-2019-6793.yaml
Labels: Done

#10822 Create CVE-2017-3131.yaml
  http/cves/2017/CVE-2017-3131.yaml
Labels: Done

#10824 Create CVE-2017-3133.yaml
  http/cves/2017/CVE-2017-3133.yaml
Labels: Done

#10833 Create CVE-2020-11441.yaml
  http/cves/2020/CVE-2020-11441.yaml
Labels: Done

#10285 Optimized some templates due nuclei change and added new templates
  helpers/wordlists/adminer-paths.txt
  http/cves/2015/CVE-2015-4455.yaml
  http/cves/2016/CVE-2016-6195.yaml
  http/cves/2019/CVE-2019-7139.yaml
  http/cves/2022/CVE-2022-22897.yaml
  http/cves/2023/CVE-2023-27034.yaml
  http/cves/2023/CVE-2023-30150.yaml
  http/cves/2023/CVE-2023-45375.yaml
  http/cves/2023/CVE-2023-46347.yaml
  http/exposed-panels/adminer-panel.yaml
  http/exposed-panels/openbullet2-panel.yaml
  http/exposures/configs/phpinfo-files.yaml
  http/vulnerabilities/prestashop/prestashop-apmarketplace-sqli.yaml
  http/vulnerabilities/prestashop/prestashop-blocktestimonial-file-upload.yaml
  http/vulnerabilities/vbulletin/arcade-php-sqli.yaml
  http/vulnerabilities/vbulletin/vbulletin-ajaxreg-sqli.yaml
  http/vulnerabilities/vbulletin/vbulletin-search-sqli.yaml
Labels: Done

#10823 Create CVE-2017-3132.yaml
  http/cves/2017/CVE-2017-3132.yaml
Labels: Done

#10825 add nacos conf leak
  http/vulnerabilities/other/nacos-info-leak.yaml
Labels: Done

#10830 panmicro file read
  http/vulnerabilities/other/panmicro-arbitrary-file-read.yaml
Labels: Done

#10840 Severity Update jwk-json-leak.yaml
  http/exposures/tokens/jwk-json-leak.yaml
Labels: Done

#10837 Add detection of Maestro LISTSERV login panel instances.
  http/exposed-panels/maestro-listserv-panel.yaml
Labels: Done

#10836 Create CVE-2024-30188.yaml
  http/cves/2024/CVE-2024-30188.yaml
Labels: Done

#10835 Create CVE-2023-27584.yaml
  http/cves/2023/CVE-2023-27584.yaml
Labels: Done
