Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-08, with the labels that each got.

#10434 Create CVE-2024-7120.yaml
  http/cves/2024/CVE-2024-7120.yaml
Labels: Done

#10416 Create CVE-2023-5222.yaml
  http/cves/2023/CVE-2023-5222.yaml
Labels: Done

#10426 Update cs141-default-login.yaml
  http/default-logins/abb/cs141-default-login.yaml
Labels: Done

#10440 Create CVE-2023-43323.yaml
  http/cves/2023/CVE-2023-43323.yaml
Labels: Done

#10438 Create CVE-2024-34061.yaml
  http/cves/2024/CVE-2024-34061.yaml
Labels: Done

#10441 Create changedetection-unauth.yaml
  http/misconfiguration/changedetection-unauth.yaml
Labels: Done

#10439 Create CVE-2024-24763.yaml
  http/cves/2024/CVE-2024-24763.yaml
Labels: Done

#10444 Create x11-unauth-access.yaml
  javascript/misconfiguration/x11/x11-unauth-access.yaml
Labels: Done

#10420 Fix typo in CVE-2024-20767.yaml
  http/cves/2024/CVE-2024-20767.yaml
Labels: good first issue, Done

#10443 Create db2-discover.yaml
  javascript/udp/detection/db2-discover.yaml
Labels: Done

#10461 Yardi Voyager Detection Favicon Hash
  http/technologies/favicon-detect.yaml
Labels: Done

#10430 Create CVE-2024-6781.yaml
  http/cves/2024/CVE-2024-6781.yaml
Labels: Done

#10432 Create gitlab-ci-yml.yaml
  http/exposures/files/gitlab-ci-yml.yaml
Labels: Done

#10448 Create CVE-2024-7340.yaml
  http/cves/2024/CVE-2024-7340.yaml
Labels: Done

#10436 Create CVE-2024-6782.yaml
  http/cves/2024/CVE-2024-6782.yaml
Labels: Done

#10419 Add my name to dom-xss.yaml
  dast/vulnerabilities/xss/dom-xss.yaml
Labels: Done

#10450 add cve-2024-7332
  http/cves/2024/CVE-2024-7332.yaml
Labels: Done

#10464 Create CVE-2024-36104.yaml
  http/cves/2024/CVE-2024-36104.yaml
  http/cves/2024/CVE-2024-38856.yaml
Labels: Done

#10465 add CVE-2024-41628
  http/cves/2024/CVE-2024-41628.yaml
Labels: Done

#10449 add cve-2024-5975
  http/cves/2024/CVE-2024-5975.yaml
Labels: Done

#10469 Sites that show the Laravel debug panel on malformed URLs
  http/misconfiguration/laravel-debug-error.yaml
Labels: Done

#10494 Refactor the CheckMK template.
  http/exposed-panels/checkmk/checkmk-login.yaml
Labels: Done

#10431 Create CVE-2024-7008.yaml
  http/cves/2024/CVE-2024-7008.yaml
Labels: Done

#10497 CVE-2024-38856 kev tag
  http/cves/2024/CVE-2024-38856.yaml
Labels: Done

#10466 add CVE-2024-40422
  http/cves/2024/CVE-2024-40422.yaml
Labels: Done

#10354 Update reflected-xss.yaml
  dast/vulnerabilities/xss/reflected-xss.yaml
Labels: Done

#10422 Create cloudstack-default-login.yaml
  http/default-logins/apache/cloudstack-default-login.yaml
Labels: Done

#10508 Update .nuclei-ignore
  .nuclei-ignore
Labels: Done

#10505 Whatsup Gold Detection
  http/exposed-panels/whatsup-gold-panel.yaml
Labels: Done

#10502 Refactor the "Axway API Manager" template.
  http/exposed-panels/axway-api-manager-panel.yaml
Labels: Done

#10504 Apache OFbiz Detect
  http/technologies/apache/apache-ofbiz-detect.yaml
Labels: Done

#10513 SearXNG Detection
  http/technologies/favicon-detect.yaml
  http/technologies/searxng-detect.yaml
Labels: Done

#10472 fix CVE-2021-22053 fp
  http/cves/2021/CVE-2021-22053.yaml
Labels: Done

#10510 airOS Detect
  http/exposed-panels/airos-panel.yaml
Labels: Done

#10496 Progress Openedge Panel Detection
  http/exposed-panels/openedge-panel.yaml
Labels: Done

#10515 Refactor the "ActiveMQ" template.
  http/exposed-panels/activemq-panel.yaml
Labels: Done

#10512 Metube panel
  http/exposed-panels/metube-panel.yaml
Labels: Done

#10468 Added template for CVE-2024-7339
  CVE-2024-7339.yaml
Labels: Done

#10454 Create apache-shenyu-gateway-admin-detect.yaml
  http/technologies/apache/apache-shenyu-detect.yaml
Labels: Done

#10525 Rename thinkphp6-arbitrary-write.yaml to thinkphp6-arbitrary-write.yaml
  http/vulnerabilities/thinkphp6-arbitrary-write.yaml
Labels: Done

#10511 Photoprism Detection
  http/exposed-panels/photoprism-panel.yaml
Labels: Done

#10555 Create fossbilling-installer.yaml
  http/misconfiguration/installer/fossbilling-installer.yaml
Labels: Done

#10556 Create fossbilling-panel.yaml
  http/exposed-panels/fossbilling-panel.yaml
Labels: Done

#10554 Create privategpt-detect.yaml
  http/exposed-panels/privategpt-detect.yaml
Labels: Done

#10547 CVE-2022-3869.yaml
  http/cves/2022/CVE-2022-3869.yaml
  http/cves/2023/CVE-2023-5863.yaml
  http/cves/2024/CVE-2024-5936.yaml
Labels: Done

#10413 Update campaignmonitor-takeover.yaml
  http/takeovers/campaignmonitor-takeover.yaml
Labels: Done

#10418 Create CVE-2024-38288.yaml
  http/cves/2024/CVE-2024-38288.yaml
Labels: Done

#10442 Create CVE-2004-2687.yaml
  network/cves/2004/CVE-2004-2687.yaml
Labels: Done

#10447 Create CVE-2024-38514.yaml
  http/cves/2024/CVE-2024-38514.yaml
Labels: Done

#10488 add CVE-2023-6444
  http/cves/2023/CVE-2023-6444.yaml
Labels: Done

#10561 renamed templates-sync.yaml to templates-sync.yml
  .github/workflows/templates-sync.yml
  .github/workflows/tests.yml
Labels: Done

#10544 Added a new Template CVE-2023-3521
  http/cves/2023/CVE-2023-3521.yaml
Labels: Done

#10534 ivanti-traffic-manager hash
  http/technologies/favicon-detect.yaml
Labels: Done

#10536 Added CVE-2024-5420 Template
  http/cves/2024/CVE-2024-5420.yaml
Labels: good first issue, Done

#10538 Added CVE-2024-5421 Template
  http/cves/2024/CVE-2024-5421.yaml
Labels: good first issue, Done

#10462 Procore Detection
  http/exposed-panels/procore-panel.yaml
Labels: Done

#10501 add CVE-2024-6893
  http/cves/2024/CVE-2024-6893.yaml
Labels: Done

#10564 Added template for radarr-indexer-settings-exposure
  http/misconfiguration/radarr-dashboard-unauth.yaml
Labels: Done

#10565 Added template for readarr-settings-indexers
  http/misconfiguration/readarr-dashboard-unauth.yaml
Labels: Done

#10566 Added template for lidarr-settings-indexers
  http/misconfiguration/lidarr-dashboard-unauth.yaml
Labels: Done

#10567 Added template for whisparr-settings-indexers
  http/misconfiguration/whisparr-dashboard-unauth.yaml
Labels: Done

#10568 Added template for prowlarr-general-settings
  http/misconfiguration/prowlarr-dashboard-unauth.yaml
Labels: Done

#10563 Added template for sonarr-indexer-settings-exposure
  http/misconfiguration/sonarr-dashboard-unauth.yaml
Labels: Done

#10573 Add detection of KIALI login panel instances.
  http/exposed-panels/kiali-panel.yaml
Labels: Done

#10571 Fewer FPs for http/misconfiguration/mixed-active-content.yaml
  http/misconfiguration/mixed-active-content.yaml
Labels: Done

#10553 fix: update github takeover matchers to match new 404 page
  http/takeovers/github-takeover.yaml
Labels: good first issue, Done

#10452 add readymade xss
  http/vulnerabilities/other/readymade-unilevel-xss.yaml
Labels: Done

#10574 Create jackett-installer.yaml
  http/misconfiguration/installer/jackett-installer.yaml
Labels: Done

#10578 add CVE-2024-7928
  http/cves/2024/CVE-2024-7928.yaml
Labels: Done

#10575 add cve-2023-40504
  http/cves/2023/CVE-2023-40504.yaml
Labels: Done

#10579 Update phpmyadmin-panel.yaml
  http/exposed-panels/phpmyadmin-panel.yaml
Labels: Done

#10596 Add Akamai Bot Manager detection
  http/technologies/akamai/akamai-bot-manager-detect.yaml
Labels: Done

#10595 Create CVE-2024-24809.yaml 🔥 (Traccar - Unrestricted Upload of File with Dangerous Type)
  http/cves/2024/CVE-2024-24809.yaml
Labels: Done

#10593 Create CVE-2024-6095.yaml
  http/cves/2024/CVE-2024-6095.yaml
Labels: Done

#10591 Refactor the "Jaeger UI" template.
  http/misconfiguration/jaeger-ui-dashboard.yaml
Labels: Done

#10585 Create CVE-2024-7593.yaml
  http/cves/2024/CVE-2024-7593.yaml
Labels: Done

#10592 Create CVE-2024-32231.yaml
  http/cves/2024/CVE-2024-32231.yaml
Labels: Done

#10519 Create bigip-apm-detect.yaml
  http/technologies/bigip-apm-detect.yaml
Labels: Done

#10606 Create ispconfig-hcp-default-login.yaml
  http/default-logins/ispconfig/ispconfig-admin-default-login.yaml
  http/default-logins/ispconfig/ispconfig-hcp-default-login.yaml
Labels: Done

#10600 Add fuji-xerox apeosport/docucentre default login
  http/default-logins/fuji-xerox/fuji-xerox-default-login.yaml
Labels: good first issue, Done

#10532 Virtual Traffic Manager Detect
  http/exposed-panels/ivanti-traffic-manager-panel.yaml
Labels: Done

#10598 add spip detect
  http/technologies/spip-detect.yaml
Labels: Done

#10599 Update detection of HashiCorp Vault login panel instances.
  http/exposed-panels/vault-panel.yaml
Labels: Done

#10580 elgg install misconfig
  http/misconfiguration/installer/elgg-install.yaml
Labels: Done

#10453 add readymade sqli
  http/vulnerabilities/other/readymade-unilevel-sqli.yaml
Labels: Done

#10522 Cookie Form Detection
  headless/cookie-consent-detection.yaml
Labels: Done

#10427 Create CVE-2024-6842.yaml
  http/cves/2024/CVE-2024-6842.yaml
Labels: good first issue, Done

#10533 Fewer FPs for http/default-logins/xui-weak-login.yaml
  http/default-logins/xui/xui-default-login.yaml
Labels: Done

#10562 Malwared BYOB RCE
  http/exposed-panels/malwared-byob.yaml
  http/vulnerabilities/malwared-byob-rce.yaml
Labels: Done

#10613 Create rundeck-default-login.yaml
  http/default-logins/rundeck/rundeck-default-login.yaml
Labels: Done

#10435 Create jellyfin-default-login.yaml
  http/default-logins/jellyfin/jellyfin-default-login.yaml
Labels: good first issue, Done

#10433 Create couchdb-default-login.yaml
  http/default-logins/couchdb/couchdb-default-login.yaml
Labels: Done

#10423 Create CVE-2024-5765.yaml
  http/cves/2024/CVE-2024-5765.yaml
Labels: Done

#10429 CREATE CVE-2024-5827
  http/cves/2024/CVE-2024-5827.yaml
Labels: good first issue, Done

#10549 Adding CVE-2023-46818.yaml
  http/cves/2023/CVE-2023-46818.yaml
Labels: Done

#10377 Update wp-statistics-sqli.yaml
  http/vulnerabilities/wordpress/wp-statistics-sqli.yaml
Labels: Done

#10376 Update the time-based sql injection delay time to reduce false positi…
  http/cves/2023/CVE-2023-6063.yaml
Labels: Done

#10131 Added apache-streampipes-detect.yaml and CVE-2024-29868.yaml + moved …
  http/cves/2024/CVE-2024-29868.yaml
  http/technologies/apache/apache-allura-detect.yaml
  http/technologies/apache/apache-streampipes-detect.yaml
Labels: good first issue, Done

#10616 Rename headless/2024/CVE-2024-38526.yaml to headless/cves/2024/CVE-20…
  headless/cves/2024/CVE-2024-38526.yaml
Labels: Done

#10615 Fix misstyped key 'shodan-query' (had underscore)
  http/exposed-panels/airos-panel.yaml
Labels: Done

#10581 elgg sqli
  http/vulnerabilities/other/elgg-sqli.yaml
Labels: Done

#10617 ci(wordpress-plugins-update): update Git config
  .github/workflows/wordpress-plugins-update.yml
Labels: Type: Maintenance

#10367 Added template to check if a MobSF Instance is vulnerable to CVE-2024…
  http/vulnerabilities/mobsf/mobsf-apktool-lfi.yaml
Labels: good first issue, Done

#10586 add CVE-2024-6911
  http/cves/2024/CVE-2024-6911.yaml
Labels: Done

#10569 Added template for jackett-exposed-ui
  http/misconfiguration/jackett-unauth.yaml
Labels: Done

#10608 CVE-2024-29272
  http/cves/2024/CVE-2024-29272.yaml
Labels: Done

#10611 Adding CVE-2024-3850 and updating payload to match response match in CVE-2024-25669
  http/cves/2024/CVE-2024-25669.yaml
  http/cves/2024/CVE-2024-3850.yaml
Labels: Done

#10619 Create prest-sqli-auth-bypass.yaml
  http/vulnerabilities/other/prest-sqli-auth-bypass.yaml
Labels: Done

#10622 Update CVE-2014-6271.yaml
  http/cves/2014/CVE-2014-6271.yaml
Labels: good first issue, Done

#10624 Create CVE-2024-8181.yaml
  http/cves/2024/CVE-2024-8181.yaml
Labels: Done

#10489 Added CVE-2020-28429 by eeche
  http/cves/2020/CVE-2020-28429.yaml
  http/cves/2024/CVE-2024-23163.yaml
Labels: good first issue, Done

#10623 add CVE-2024-7954
  http/cves/2024/CVE-2024-7954.yaml
Labels: Done

#10628 Create CVE-2023-22893.yaml
  http/cves/2023/CVE-2023-22893.yaml
Labels: Done

#10626 Create CVE-2024-5932.yaml
  http/cves/2024/CVE-2024-5932.yaml
Labels: Done

#10631 Create CVE-2023-2624.yaml
  http/cves/2023/CVE-2023-2624.yaml
Labels: Done

#10630 Create CVE-2023-34754.yaml
  http/cves/2023/CVE-2023-34754.yaml
Labels: Done

#10629 Create CVE-2023-29506.yaml
  http/cves/2023/CVE-2023-29506.yaml
Labels: Done

#10633 Fixed CVE-2023-48023 severity
  http/cves/2023/CVE-2023-48023.yaml
Labels: Done
