Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-01, with the labels that each got.

#8887 One more way of detecting Symfony Profiler
  http/exposures/configs/symfony-profiler.yaml
Labels: Done

#8892 Create CVE-2021-3156.yaml
  code/cves/2021/CVE-2021-3156.yaml
Labels: Done

#8886 Create CVE-2019-14287.yaml
  code/cves/2019/CVE-2019-14287.yaml
Labels: Done

#8880 Create CVE-2023-51467 (Apache OFBiz < 18.12.11 - Remote Code Execution)
  http/cves/2023/CVE-2023-51467.yaml
Labels: Done

#8878 Create CVE-2020-12124.yaml
  http/cves/2020/CVE-2020-12124.yaml
Labels: Done

#8881 Create CVE-2023-50968 (Apache OFBiz < 18.12.11 - Server Side Request Forgery)
  http/cves/2023/CVE-2023-50968.yaml
Labels: Done

#8885 Symfony debug improvements
  http/misconfiguration/symfony-debug.yaml
Labels: Done

#8870 Fix Broken Template CVE-2021-40438
  http/cves/2021/CVE-2021-40438.yaml
Labels: Done

#8900 Update gitlab-public-signup.yaml
  http/misconfiguration/gitlab/gitlab-public-registration.yaml
  http/misconfiguration/gitlab/gitlab-public-signup.yaml
Labels: Done

#8708 Create php-composer-binary.yaml
  http/misconfiguration/php/php-composer-binary.yaml
Labels: Done

#8828 Break out build to make it more comparable
  http/exposed-panels/teamcity-login-panel.yaml
Labels: Done

#8901 Delete http/misconfiguration/httponly-cookie-detect.yaml
  http/misconfiguration/cookies-without-httponly.yaml
  http/misconfiguration/httponly-cookie-detect.yaml
Labels: Done

#8875 Added Cisco ASA Detection + Version Extractor
  http/technologies/cisco-asa-detect.yaml
Labels: Done

#8907 Moving ssh templates
  http/cves/2023/CVE-2023-46359.yaml
  javascript/enumeration/ssh/obsolete-ssh-version.yaml
  javascript/enumeration/ssh/ssh-cbc-mode-ciphers.yaml
  javascript/enumeration/ssh/ssh-diffie-hellman-logjam.yaml
  javascript/enumeration/ssh/ssh-password-auth.yaml
  javascript/enumeration/ssh/ssh-server-enumeration.yaml
  javascript/enumeration/ssh/ssh-sha1-hmac-algo.yaml
  javascript/enumeration/ssh/ssh-weak-algo-supported.yaml
  javascript/enumeration/ssh/ssh-weak-mac-algo.yaml
  javascript/enumeration/ssh/ssh-weak-public-key.yaml
  javascript/enumeration/ssh/ssh-weakkey-exchange-algo.yaml
Labels: Done

#8696 Create dlink-netgear-xss.yaml
  http/vulnerabilities/dlink/dlink-netgear-xss.yaml
Labels: Done

#8896 Update ms-exchange-user-enum.yaml
  http/misconfiguration/ms-exchange-user-enum.yaml
Labels: good first issue, Done

#8679 Create CVE-2023-44353.yaml
  http/cves/2023/CVE-2023-44353.yaml
Labels: Done

#8913 Added goodjob-dashboard Template
  http/exposed-panels/goodjob-dashboard.yaml
Labels: Done

#8903 template to detect the ONLYOFFICE documentation page
  http/exposed-panels/onlyoffice-login-panel.yaml
Labels: Done

#8904 Create piratebay.yaml
  http/osint/piratebay.yaml
Labels: Done

#8311 SMB -JS Templates
  javascript/network/smb/smb-anonymous-access.yaml
  javascript/network/smb/smb-shares.yaml
  javascript/network/smb/smb-signing-not-required.yaml
  javascript/network/smb/smb2-capabilities.yaml
Labels: Done

#8902 Create CVE-2023-6379.yaml
  http/cves/2023/CVE-2023-6379.yaml
Labels: Done

#8910 Added/apache server status Template
  http/misconfiguration/apache/apache-server-status.yaml
Labels: Done

#8905 Create CVE-2023-6623.yaml
  http/cves/2023/CVE-2023-6623.yaml
Labels: Done

#8921 Fix FP on open-proxy-external.yaml
  http/misconfiguration/proxy/open-proxy-external.yaml
Labels: Done

#8924 Added CVE-2024-0352 Template
  http/cves/2024/CVE-2024-0352.yaml
Labels: good first issue, Done

#8926 added internal:true
  http/cves/2019/CVE-2019-9978.yaml
  http/cves/2020/CVE-2020-24148.yaml
  http/cves/2021/CVE-2021-28164.yaml
  http/cves/2023/CVE-2023-0600.yaml
  http/cves/2023/CVE-2023-43177.yaml
  http/cves/2023/CVE-2023-46574.yaml
  http/cves/2023/CVE-2023-6553.yaml
  http/vulnerabilities/ruijie/ruijie-rg-eg-web-mis-rce.yaml
Labels: Done

#8918 Create camunda-default-credential.yaml
  http/default-logins/camunda/camunda-default-login.yaml
Labels: Done

#8922 Create CVE-2023-50917.yaml
  http/cves/2023/CVE-2023-50917.yaml
Labels: Done

#8932 Update cookies-without-httponly.yaml
  http/misconfiguration/cookies-without-httponly-secure.yaml
Labels: Done

#8931 Added wanhuoa-DownloadServlet-LFI Template
  http/vulnerabilities/wanhu/wanhuoa-downloadservlet-lfi.yaml
Labels: good first issue, Done

#8937 GitLab Account Takeover via Password Reset without user interactions - CVE-2023-7028
  http/cves/2023/CVE-2023-7028.yaml
Labels: Status: On Hold

#8939 Create CVE-2023-6063.yaml
  http/cves/2023/CVE-2023-6063.yaml
Labels: Done

#8940 Misc changes
  cloud/enum/azure-vm-cloud-enum.yaml
  http/exposed-panels/goodjob-dashboard.yaml
  network/misconfig/erlang-daemon.yaml
Labels: Done

#8941 Create CVE-2023-6634.yaml
  http/cves/2023/CVE-2023-6634.yaml
Labels: Done

#8945 Flow fix
  http/cves/2019/CVE-2019-9978.yaml
  http/cves/2020/CVE-2020-24148.yaml
  http/cves/2023/CVE-2023-26035.yaml
  http/cves/2023/CVE-2023-6063.yaml
  http/cves/2023/CVE-2023-6553.yaml
  http/cves/2023/CVE-2023-7028.yaml
  http/vulnerabilities/ruijie/ruijie-rg-eg-web-mis-rce.yaml
Labels: Done

#8955 Create CVE-2024-21887.yaml
  http/cves/2024/CVE-2024-21887.yaml
Labels: Done

#8953 CVE-2023-46805 - Ivanti Connect Secure Authentication Bypass
  http/cves/2023/CVE-2023-46805.yaml
Labels: Done

#8948 Create CVE-2020-27838.yaml
  http/cves/2020/CVE-2020-27838.yaml
Labels: Done

#8952 Create CVE-2023-50290.yaml
  http/cves/2023/CVE-2023-50290.yaml
Labels: Done

#8930 Create CVE-2022-47501 (Apache OFBiz < 18.12.07 - Local File Inclusion)
  http/cves/2022/CVE-2022-47501.yaml
Labels: Done

#8956 Create CVE-2023-6875.yaml
  http/cves/2023/CVE-2023-6875.yaml
Labels: Done

#8957 PowerShell Universal - Default Login
  http/default-logins/powershell/powershell-default-login.yaml
Labels: Done

#8963 Fix max-request for ftp-weak-credentials.yaml
  network/default-login/ftp-weak-credentials.yaml
Labels: Done

#8951 Updates the versions for Ad Inserter, Advance Custom Fields, Adminimize, Astra SItes, Amp and All In One SEO Wordpress plugins
  helpers/wordpress/plugins/ad-inserter.txt
  helpers/wordpress/plugins/adminimize.txt
  helpers/wordpress/plugins/advanced-custom-fields.txt
  helpers/wordpress/plugins/all-in-one-seo-pack.txt
  helpers/wordpress/plugins/amp.txt
  helpers/wordpress/plugins/astra-sites.txt
Labels: Done

#8965 Removing kev tags for CVE-2022-43769 and CVE-2023-25135
  http/cves/2022/CVE-2022-43769.yaml
  http/cves/2023/CVE-2023-25135.yaml
Labels: Done

#8969 Create junos-xss.yaml
  http/vulnerabilities/juniper/junos-xss.yaml
Labels: Done

#8970 misc metadata update
  http/misconfiguration/apache/apache-server-status.yaml
  http/technologies/springboot-whitelabel.yaml
  http/vulnerabilities/other/doorgets-info-disclosure.yaml
  http/vulnerabilities/other/phuket-cms-sqli.yaml
  http/vulnerabilities/wordpress/wp-yoast-user-enumeration.yaml
Labels: Done

#6765 Create Apache NIFI API RCE
  vulnerabilities/apache/apache-nifi-rce.yaml
Labels: help wanted, defcon31

#7042 Update open-proxy-internal.yaml
  http/misconfiguration/proxy/open-proxy-internal.yaml
Labels: good first issue, waiting for more info

#8972 Delete http/cves/2019/CVE-2019-6799.yaml
  http/cves/2019/CVE-2019-6799.yaml
Labels: Done

#8894 A festive templates and updates
  http/cves/2018/CVE-2018-10942.yaml
  http/cves/2023/CVE-2023-27639.yaml
  http/cves/2023/CVE-2023-27640.yaml
  http/exposed-panels/autoset-detect.yaml
  http/exposed-panels/compalex-detect.yaml
  http/exposures/backups/php-backup-files.yaml
  http/exposures/backups/settings-php-files.yaml
  http/exposures/backups/sql-dump.yaml
  http/exposures/backups/zip-backup-files.yaml
  http/exposures/configs/phpinfo-files.yaml
  http/exposures/configs/vbulletin-path-disclosure.yaml
  http/vulnerabilities/prestashop/prestashop-blocktestimonial-file-upload.yaml
  http/vulnerabilities/vbulletin/vbulletin-backdoor.yaml
  http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
Labels: Done

#8966 Update wordpress-detect.yaml
  http/technologies/wordpress-detect.yaml
Labels: good first issue, Done

#8973 Create node-red-default-login.yaml
  http/default-logins/node-red/nodered-default-login.yaml
Labels: Done

#8978 Added CVE-2023-48023 template
  http/cves/2023/CVE-2023-48023.yaml
Labels: good first issue, Done

#8919 Added more words to microsoft-azure-error template
  http/miscellaneous/microsoft-azure-error.yaml
Labels: good first issue, Done

#8979 Create doris-dashboard.yaml
  http/misconfiguration/doris-dashboard.yaml
Labels: Done

#8980 Create doris-panel.yaml
  http/exposed-panels/doris-panel.yaml
Labels: Done

#8974 Add version detection to vault-panel template
  http/exposed-panels/vault-panel.yaml
Labels: good first issue, Done

#8995 fix: wrong condition editor-exposure template
  http/exposures/configs/editor-exposure.yaml
Labels: Done

#8982 Added Template for CVE-2023-22527 (atlassian-confluence-ssti-remote-code-execution)
  http/cves/2023/CVE-2023-22527.yaml
Labels: Done

#8990 Added CVE-2023-6023 template
  http/cves/2023/CVE-2023-6023.yaml
Labels: Done

#8994 Create CVE-2024-0204.yaml (Fortra GoAnywhere MFT - Authentication Bypass 🔥 )
  http/cves/2024/CVE-2024-0204.yaml
Labels: Done

#8976 Add Template for DNS Rebinding Attack
  dns/dns-rebinding.yaml
Labels: Done

#8975 Add Defacement Detection Template
  http/miscellaneous/defacement-detect.yaml
Labels: Done

#8991 fixed fp CVE-2021-39327.yaml
  http/cves/2021/CVE-2021-39327.yaml
Labels: Done

#9013 Delete http/takeovers/flywheel-takeover.yaml
  http/takeovers/flywheel-takeover.yaml
Labels: Done

#9012 Create springboot-startup.yaml
  http/misconfiguration/springboot/springboot-startup.yaml
Labels: Done

#9018 Add detection of TIBCO BusinessConnect instances
  http/technologies/tibco-businessconnect-detect.yaml
Labels: Done

#9017 Add detection of Lomnido instances
  http/exposed-panels/lomnido-panel.yaml
Labels: Done

#9029 flow: remove temporary workaround
  http/cves/2023/CVE-2023-26035.yaml
  http/cves/2023/CVE-2023-7028.yaml
Labels: Done

#9025 Added CVE-2024-23897 (Jenkins < 2.441 - Arbitrary File Read)
  javascript/cves/2024/CVE-2024-23897.yaml
Labels: Done

#9031 Fix: fix apache solr log4j2 poc
  http/vulnerabilities/apache/apache-solr-log4j-rce.yaml
Labels: good first issue, Done

#8933 Added CVE-2023-44352 template
  http/cves/2023/CVE-2023-44352.yaml
Labels: good first issue, Done

#9035 Add detection of Friendica instances
  http/exposed-panels/friendica-panel.yaml
Labels: Done

#9044 Add detection for SAP public admin web interface
  http/misconfiguration/sap/sap-public-admin.yaml
Labels: good first issue, Done

#9043 Create CVE-2023-47115.yaml
  http/cves/2023/CVE-2023-47115.yaml
Labels: Done

#9042 Create CVE-2024-21644.yaml
  http/cves/2024/CVE-2024-21644.yaml
Labels: good first issue, Done
