Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-02, with the labels that each got.

#9073 Update CVE-2022-47003.yaml
  http/cves/2022/CVE-2022-47003.yaml
Labels: Done

#9080 Create CVE-2024-21893.yaml (Ivanti SAML - Server Side Request Forgery (SSRF) )
  http/cves/2024/CVE-2024-21893.yaml
Labels: Done

#9100 Create chromecast-detect.yaml
  http/technologies/google/chromecast-detect.yaml
Labels: Done

#9071 Add detection of Identity Server V3 instances
  http/technologies/identity-server-v3-detect.yaml
Labels: Done

#9093 Create CVE-2022-38131.yaml
  http/cves/2022/CVE-2022-38131.yaml
Labels: Done

#9092 Create CVE-2023-28662.yaml
  http/cves/2023/CVE-2023-28662.yaml
Labels: Done

#9066 Create juniper-panel.yaml
  http/exposed-panels/juniper-panel.yaml
Labels: Done

#9069 Create CVE-2024-21645.yaml
  http/cves/2024/CVE-2024-21645.yaml
Labels: Done

#9064 Add CVE-2023-6360.yaml
  http/cves/2023/CVE-2023-6360.yaml
Labels: Done

#9106 shodan-query update
  http/cves/2024/CVE-2024-0204.yaml
Labels: Done

#9107 Create webmethod-integration-server-default-login.yaml
  http/default-logins/webmethod/webmethod-integration-server-default-login.yaml
Labels: Done

#9103 Added Teampass LDAP template
  http/exposures/logs/teampass-ldap.yaml
Labels: good first issue, Done

#9020 Add case-insensitive flags to fingerprinthub and tech-detect templates
  http/exposed-panels/gitea-login.yaml
  http/misconfiguration/gitea-public-signup.yaml
  http/technologies/gitea-detect.yaml
  http/technologies/tech-detect.yaml
Labels: Done

#9112 Add detection of Vista Web login panel instances
  http/exposed-panels/vistaweb-panel.yaml
Labels: Done

#9056 Update js-libraries-detect.yaml
  headless/technologies/js-libraries-detect.yaml
Labels: Done

#9075 Create CVE-2023-52085.yaml
  http/cves/2023/CVE-2023-52085.yaml
Labels: good first issue, Done

#9101 Update dns-rebinding.yaml
  dns/dns-rebinding.yaml
Labels: Done

#9114 Create CVE-2024-22024.yaml (Ivanti Connect Secure - XXE)
  http/cves/2024/CVE-2024-22024.yaml
Labels: Done

#9120 Add detection of Apigee login panel instances
  http/exposed-panels/apigee-panel.yaml
Labels: Done

#9125 Updated fuzz tag to brute-force
  cloud/enum/azure-vm-cloud-enum.yaml
  config/bugbounty.yml
  config/pentest.yml
  config/recommended.yml
  http/cves/2017/CVE-2017-17562.yaml
  http/cves/2019/CVE-2019-17382.yaml
  http/cves/2022/CVE-2022-2034.yaml
  http/cves/2023/CVE-2023-24489.yaml
  http/default-logins/oracle/peoplesoft-default-login.yaml
  http/exposed-panels/adminer-panel-detect.yaml
  http/exposures/backups/php-backup-files.yaml
  http/fuzzing/cache-poisoning-fuzz.yaml
  http/fuzzing/header-command-injection.yaml
  http/fuzzing/iis-shortname.yaml
  http/fuzzing/linux-lfi-fuzzing.yaml
  http/fuzzing/mdb-database-file.yaml
  http/fuzzing/prestashop-module-fuzz.yaml
  http/fuzzing/ssrf-via-proxy.yaml
  http/fuzzing/valid-gmail-check.yaml
  http/fuzzing/waf-fuzz.yaml
  http/fuzzing/wordpress-plugins-detect.yaml
  http/fuzzing/wordpress-themes-detect.yaml
  http/fuzzing/wordpress-weak-credentials.yaml
  http/fuzzing/xff-403-bypass.yaml
  http/miscellaneous/defacement-detect.yaml
  http/miscellaneous/ntlm-directories.yaml
  http/misconfiguration/aem/aem-userinfo-servlet.yaml
  http/misconfiguration/gitlab/gitlab-user-enum.yaml
  http/misconfiguration/proxy/open-proxy-internal.yaml
  http/misconfiguration/proxy/open-proxy-localhost.yaml
  http/misconfiguration/proxy/open-proxy-portscan.yaml
  http/technologies/graylog/graylog-api-exposure.yaml
  http/vulnerabilities/tongda/tongda-auth-bypass.yaml
  http/vulnerabilities/wordpress/wp-xmlrpc-brute-force.yaml
  javascript/cves/2023/CVE-2023-34039.yaml
  javascript/default-logins/ssh-default-logins.yaml
  network/misconfig/mysql-native-password.yaml
  network/misconfig/tidb-native-password.yaml
Labels: Done

#9133 Author name change
  http/cves/2015/CVE-2015-2794.yaml
Labels: Done

#9140 Add more detection criteria for GoAnywhere Managed File Transfer Login Panel
  http/exposed-panels/goanywhere-mft-login.yaml
Labels: Done

#9142 Add more detection criteria for Kafka UI
  http/exposed-panels/kafka-topics-ui.yaml
Labels: Done

#9143 Add detection of Haivision Gateway login panel instances
  http/exposed-panels/haivision-gateway-panel.yaml
Labels: Done

#9144 Update wanhuoa-downloadservlet-lfi.yaml Title
  http/vulnerabilities/wanhu/wanhuoa-downloadservlet-lfi.yaml
Labels: good first issue

#9135 Create CVE-2023-40355.yaml
  http/cves/2023/CVE-2023-40355.yaml
Labels: good first issue, Done

#9146 FN Update CVE-2021-42013.yaml
  http/cves/2021/CVE-2021-42013.yaml
Labels: Done

#9147 detect lucee
  http/technologies/lucee-detect.yaml
Labels: Done

#9150 Add detection of Haivision Media Platform login panel instances
  http/exposed-panels/haivision-media-platform-panel.yaml
Labels: Done

#9151 Add detection of Gotify login panel instances
  http/exposed-panels/gotify-panel.yaml
Labels: Done

#9148 Added lucee-rce
  http/vulnerabilities/lucee-rce.yaml
Labels: Done

#9153 Create proofpoint-protection-server-panel.yaml
  http/exposed-panels/proofpoint-protection-server-panel.yaml
Labels: Done

#9165 fix: wrong tags CVE-2021-44910.yaml
  http/cves/2021/CVE-2021-44910.yaml
Labels: Done

#9155 template for cgi-bin awstats detection
  http/exposures/configs/awstats-script.yaml
Labels: good first issue, Done

#9161 Create glodon-linkworks-sqli.yaml
  http/vulnerabilities/other/glodon-linkworks-sqli.yaml
Labels: Done

#9156 Update js-analyse.yaml
  file/js/js-analyse.yaml
Labels: Done

#9105 Larger number of XSS params
  http/vulnerabilities/generic/top-xss-params.yaml
  http/vulnerabilities/generic/xss-fuzz.yaml
Labels: Done

#9166 moved misconfig templates
  javascript/enumeration/smb/smb-enum.yaml
  javascript/enumeration/smb/smb2-capabilities.yaml
  javascript/misconfiguration/smb/smb-anonymous-access.yaml
  javascript/misconfiguration/smb/smb-shares.yaml
  javascript/misconfiguration/smb/smb-signing-not-required.yaml
  javascript/misconfiguration/ssh/ssh-cbc-mode-ciphers.yaml
  javascript/misconfiguration/ssh/ssh-weak-algo-supported.yaml
  javascript/misconfiguration/ssh/ssh-weak-mac-algo.yaml
  javascript/misconfiguration/ssh/ssh-weak-public-key.yaml
  javascript/misconfiguration/ssh/ssh-weakkey-exchange-algo.yaml
Labels: Done

#9174 README for scan configs
  config/README.md
  config/privilege-escalation.yml
Labels: Done

#9175 Update and rename webmethod-integration-server-default-login.yaml to …
  http/default-logins/webmethod/webmethod-integration-default-login.yaml
Labels: Done

#9176 Fewer FPs for avideo installer
  http/misconfiguration/installer/avideo-install.yaml
Labels: Done

#9182 ConnectWise Setup Wizard - Exposure
  http/misconfiguration/installer/connectwise-setup.yaml
Labels: Done

#9184 ScreenConnect Authentication Bypass
  http/exposed-panels/fortinet/fortiauthenticator-detect.yaml
  http/misconfiguration/screenconnect-authentication-bypass.yaml
Labels: Done

#9157 Create fortiauthenticator-panel.yaml
  http/exposed-panels/fortinet/fortiauthenticator-detect.yaml
Labels: Done

#9181 Nuclei template for CVE-2024-25600
  http/cves/2024/CVE-2024-25600.yaml
Labels: good first issue, Done

#9162 Create dahua-bitmap-fileupload.yaml
  http/vulnerabilities/dahua/dahua-bitmap-fileupload.yaml
Labels: Done

#9172 Create yonyou-ufida-nc-lfi.yaml
  http/vulnerabilities/yonyou/yonyou-ufida-nc-lfi.yaml
Labels: Done

#9190 Create CVE-2023-48777.yaml
  http/cves/2023/CVE-2023-48777.yaml
Labels: Done

#9191 Update CVE-2023-42344.yaml
  http/cves/2023/CVE-2023-42344.yaml
Labels: Done

#9188 Update and rename http/misconfiguration/screenconnect-authentication-…
  http/cves/CVE-2024/CVE-2024-1709.yaml
Labels: Done

#9167 Create CVE-2024-0713.yaml
  http/cves/2024/CVE-2024-0713.yaml
Labels: Done

#9164 Create CNVD-2023-96945.yaml
  http/cnvd/2023/CNVD-2023-96945.yaml
Labels: Done

#9198 Update zip-backup-files.yaml [Delete Duplicate]
  http/exposures/backups/zip-backup-files.yaml
Labels: Done

#9200 Create ibm-dcbc-default-login.yaml
  http/default-logins/ibm/ibm-dcbc-default-login.yaml
Labels: Done

#9201 IBM Operational Decision Manager - JNDI Injection
  http/cves/2024/CVE-2024-22319.yaml
Labels: Done

#9197 Create ibm-decision-runner.yaml
  http/technologies/ibm/ibm-decision-runner.yaml
Labels: Done

#9202 Create ibm-dcec-panel.yaml
  http/exposed-panels/ibm/ibm-dcec-panel.yaml
Labels: Done

#9195 Create ibm-odm-panel.yaml
  http/exposed-panels/ibm/ibm-odm-panel.yaml
Labels: Done

#9194 Create ibm-host-trans-detect.yaml
  http/technologies/ibm/ibm-decision-server-runtime.yaml
Labels: Done

#9193 Create ibm-rule-execution-panel.yaml
  http/exposed-panels/ibm/ibm-decision-server-console.yaml
Labels: Done

#9206 Create ibm-odm-detect.yaml
  http/technologies/ibm-odm-detect.yaml
Labels: Done

#9203 Create ibm-dcec-default-login.yaml
  http/default-logins/ibm/ibm-dcec-default-login.yaml
Labels: Done

#9186 Add detection of LinShare login panel instances
  http/exposed-panels/linshare-panel.yaml
Labels: Done

#9216 Add the kev tag to CVE-2024-1709
  http/cves/2024/CVE-2024-1709.yaml
Labels: Done

#9221 Update Dockge Template Description
  http/exposed-panels/dockge-panel.yaml
Labels: Done

#9187 Add detection of Opinio login panel instances
  http/exposed-panels/opinio-panel.yaml
Labels: Done

#9235 Create CVE-2023-38203.yaml
  http/cves/2023/CVE-2023-38203.yaml
Labels: good first issue, Done

#9222 openvas detection
  http/exposed-panels/openvas-panel.yaml
Labels: Done

#9224 Add detection of Rocket.Chat login panel instances
  http/exposed-panels/rocketchat-panel.yaml
Labels: Done

#9220 Koel Detection Panel
  http/exposed-panels/koel-panel.yaml
Labels: Done

#9211 Added IBM HMC Default Login Template
  http/default-logins/ibm/ibm-hmc-default-login.yaml
Labels: good first issue, Done

#9229 Added CVE-2024-0305
  http/cves/2024/CVE-2024-0305.yaml
Labels: Done

#9249 Create CVE-2024-23334.yaml
  http/cves/2024/CVE-2024-23334.yaml
Labels: Done

#9250 Update bruteforce tags
  cloud/enum/azure-vm-cloud-enum.yaml
  http/cves/2017/CVE-2017-17562.yaml
  http/cves/2019/CVE-2019-17382.yaml
  http/cves/2022/CVE-2022-2034.yaml
  http/cves/2023/CVE-2023-24489.yaml
  http/default-logins/oracle/peoplesoft-default-login.yaml
  http/exposed-panels/adminer-panel-detect.yaml
  http/exposures/backups/php-backup-files.yaml
  http/fuzzing/cache-poisoning-fuzz.yaml
  http/fuzzing/header-command-injection.yaml
  http/fuzzing/iis-shortname.yaml
  http/fuzzing/linux-lfi-fuzzing.yaml
  http/fuzzing/mdb-database-file.yaml
  http/fuzzing/prestashop-module-fuzz.yaml
  http/fuzzing/ssrf-via-proxy.yaml
  http/fuzzing/valid-gmail-check.yaml
  http/fuzzing/waf-fuzz.yaml
  http/fuzzing/wordpress-plugins-detect.yaml
  http/fuzzing/wordpress-themes-detect.yaml
  http/fuzzing/wordpress-weak-credentials.yaml
  http/fuzzing/xff-403-bypass.yaml
  http/miscellaneous/defacement-detect.yaml
  http/miscellaneous/ntlm-directories.yaml
  http/misconfiguration/aem/aem-userinfo-servlet.yaml
  http/misconfiguration/gitlab/gitlab-user-enum.yaml
  http/misconfiguration/proxy/open-proxy-internal.yaml
  http/misconfiguration/proxy/open-proxy-localhost.yaml
  http/misconfiguration/proxy/open-proxy-portscan.yaml
  http/technologies/graylog/graylog-api-exposure.yaml
  http/vulnerabilities/tongda/tongda-auth-bypass.yaml
  http/vulnerabilities/wordpress/wp-xmlrpc-brute-force.yaml
  javascript/cves/2023/CVE-2023-34039.yaml
  javascript/default-logins/ssh-default-logins.yaml
  network/misconfig/mysql-native-password.yaml
  network/misconfig/tidb-native-password.yaml
Labels: Done

#9257 Rename docker-daemon-exposed.yaml to docker-daemon-exposed.yaml
  http/misconfiguration/docker-daemon-exposed.yaml
Labels: Done

#9255 fix(keycloak-cve-2020-27838): Fixing typo in tag
  http/cves/2020/CVE-2020-27838.yaml
Labels: good first issue, Done

#9256 Create CVE-2024-1071.yaml
  http/cves/2024/CVE-2024-1071.yaml
Labels: Done
