Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-10, with the labels that each got.

#10873 Fix FN adminer-panel-detect.yaml
  http/exposed-panels/adminer-panel-detect.yaml
Labels: Done

#10875 Create CVE-2021-25094.yaml
  http/cves/2021/CVE-2021-25094.yaml
Labels: Done

#10881 Rename kubernetes-pods.yaml to kubernetes-pods-api.yaml
  http/misconfiguration/kubernetes/kubernetes-pods-api.yaml
Labels: Done

#10879 fixfp
  http/cves/2024/CVE-2024-34982.yaml
Labels: Done

#10883 Create CVE-2017-5871.yaml
  http/cves/2017/CVE-2017-5871.yaml
Labels: Hacktoberfest, Done

#10458 Law Enforcement Site Seized Detection
  http/miscellaneous/seized-site.yaml
Labels: Done

#10886 Fix FP fumengyun-sqli.yaml
  http/vulnerabilities/other/fumengyun-sqli.yaml
Labels: Done

#10890 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Done

#10904 add netman detect panel
  http/exposed-panels/riello-netman204-panel.yaml
Labels: Hacktoberfest, Done

#10878 Umbraco Login Panel - Detect Template Update
  http/exposed-panels/umbraco-login.yaml
Labels: good first issue, Hacktoberfest, Done

#10861 Added new commonon used paths
  helpers/wordlists/adminer-paths.txt
  http/exposures/backups/php-backup-files.yaml
  http/exposures/configs/phpinfo-files.yaml
Labels: Done

#10774 add CVE-2024-43160
  http/cves/2024/CVE-2024-43160.yaml
Labels: Done

#10903 add CVE-2024-8877
  http/cves/2024/CVE-2024-8877.yaml
Labels: Hacktoberfest, Done

#10902 Add detection of the collection of ARCGIS products instances.
  http/technologies/arcgis-detect.yaml
Labels: Hacktoberfest, Done

#10900 Add detection of the collection of VERTIGIS products instances.
  http/technologies/vertigis-detect.yaml
Labels: Hacktoberfest, Done

#10905 Create wp-mail-logging.txt
  helpers/wordpress/plugins/extendify.txt
  helpers/wordpress/plugins/wp-mail-logging.txt
Labels: Done

#10907 Added CVE-2024-45409
  code/cves/2024/CVE-2024-45409.yaml
  http/exposed-panels/gitlab-saml.yaml
Labels: Hacktoberfest, Done

#10856 add CVE-2024-7714
  http/cves/2024/CVE-2024-7714.yaml
Labels: Done

#10858 Update and rename huawei-firewall-lfi.yaml to CVE-2019-19411.yaml
  http/cves/2019/CVE-2019-19411.yaml
  http/vulnerabilities/huawei/huawei-firewall-lfi.yaml
Labels: Done

#10859 Add ASP.NET Core Development Environment Exposure
  http/misconfiguration/microsoft/aspnetcore-dev-env.yaml
Labels: Done

#10870 Create CVE-2024-43917.yaml (WordPress TI WooCommerce Wishlist Plugin <= 2.8.2 - SQL Injection)
  http/cves/2024/CVE-2024-43917.yaml
Labels: Hacktoberfest, Done

#10868 Create CVE-2024-45440.yaml (Drupal Full Path Disclosure)
  http/cves/2024/CVE-2024-45440.yaml
Labels: Done

#10871 add CVE-2024-32964
  http/cves/2024/CVE-2024-32964.yaml
Labels: Hacktoberfest, Done

#10884 add CVE-2024-6517
  http/cves/2024/CVE-2024-6517.yaml
Labels: Hacktoberfest, Done

#10895 Add detection of Wiki.js instances.
  http/technologies/wiki-js-detect.yaml
Labels: Hacktoberfest, Done

#10885 Create CVE-2024-5488.yaml (SEOPress < 7.9 - Authentication Bypass)
  http/cves/2024/CVE-2024-5488.yaml
Labels: Hacktoberfest, Done

#10899 Create api-intigriti.yaml
  http/token-spray/api-intigriti.yaml
Labels: Done

#10898 Update api-sendgrid.yaml
  http/token-spray/api-sendgrid.yaml
Labels: Hacktoberfest, Done

#10896 Retool XSS
  helpers/payloads/retool-xss.svg
  http/vulnerabilities/retool/retool-svg-xss.yaml
Labels: Hacktoberfest, Done

#10913 Create CVE-2024-7354.yaml
  http/cves/2024/CVE-2024-7354.yaml
Labels: Done

#10925 Update CVE-2024-7354.yaml
  http/cves/2024/CVE-2024-7354.yaml
Labels: Done

#10877 Umbraco Install Exposure Template Update
  http/misconfiguration/installer/umbraco-installer.yaml
Labels: Hacktoberfest, Done

#10919 Create default-azure-function-app.yaml
  http/technologies/microsoft/default-azure-function-app.yaml
Labels: Hacktoberfest, Done

#10921 Create microsoft-runtime-error.yaml
  http/exposures/logs/microsoft-runtime-error.yaml
Labels: Hacktoberfest, Done

#10922 Create twig-runtime-error.yaml
  http/exposures/logs/twig-runtime-error.yaml
Labels: Hacktoberfest, Done

#10923 Create mako-runtime-error.yaml
  http/exposures/logs/mako-runtime-error.yaml
Labels: Hacktoberfest, Done

#10926 Create mongodb-exception-page.yaml
  http/exposures/logs/mongodb-exception-page.yaml
Labels: Hacktoberfest, Done

#10927 Create action-controller-exception.yaml
  http/exposures/logs/action-controller-exception.yaml
Labels: Hacktoberfest, Done

#10928 Create delphi-mvc-exception.yaml
  http/exposures/logs/delphi-mvc-exception.yaml
Labels: Hacktoberfest, Done

#10929 Create expression-engine-exception.yaml
  http/exposures/logs/expression-engine-exception.yaml
Labels: Hacktoberfest, Done

#10920 Create sap-logon-error-message.yaml
  http/exposures/logs/sap-logon-error-message.yaml
Labels: Hacktoberfest, Done

#10924 Create lua-runtime-error.yaml
  http/exposures/logs/lua-runtime-error.yaml
Labels: Hacktoberfest, Done

#10930 Create rstudio-panel.yaml
  http/exposed-panels/rstudio-panel.yaml
Labels: Hacktoberfest, Done

#10931 Create enablix-panel.yaml
  http/exposed-panels/enablix-panel.yaml
Labels: Hacktoberfest, Done

#10916 Update CVE-2018-11784.yaml (Fix FP)
  http/cves/2018/CVE-2018-11784.yaml
Labels: Hacktoberfest, Done

#10915 Update wordpress-detect.yaml (Fix True Positive
  http/technologies/wordpress-detect.yaml
Labels: Hacktoberfest, Done

#10887 Refactor the "Strapi" template.
  http/exposed-panels/strapi-panel.yaml
Labels: Hacktoberfest, Done

#10932 Create saia-pcd-panel.yaml
  http/exposed-panels/saia-pcd-panel.yaml
Labels: Hacktoberfest, Done

#10918 Create api-delighted.yaml
  http/token-spray/api-delighted.yaml
Labels: Done

#10938 Create CVE-2021-40272.yaml
  http/cves/2021/CVE-2021-40272.yaml
Labels: Hacktoberfest, Done

#10943 Create netdisco-default-login.yaml
  http/default-logins/netdisco/netdisco-default-login.yaml
Labels: Hacktoberfest, Done

#10941 Create CVE-2023-27641.yaml
  http/cves/2023/CVE-2023-27641.yaml
Labels: Hacktoberfest, Done

#10942 Create CVE-2023-0676.yaml
  http/cves/2023/CVE-2023-0676.yaml
Labels: Hacktoberfest, Done

#10939 Create CVE-2023-4151.yaml
  http/cves/2023/CVE-2023-4151.yaml
Labels: Hacktoberfest, Done

#10934 Create CVE-2024-4940.yaml (Gradio - Open Redirect)
  http/cves/2024/CVE-2024-4940.yaml
Labels: Hacktoberfest, Done

#10936 Create CVE-2024-3234.yaml (Chuanhu Chat - Directory Traversal)
  http/cves/2024/CVE-2024-3234.yaml
Labels: Hacktoberfest, Done

#10933 Create CVE-2024-35627.yaml (TileServer API - Cross Site Scripting)
  http/cves/2024/CVE-2024-35627.yaml
Labels: Hacktoberfest, Done

#10935 Create CVE-2024-8021.yaml (Gradio - Open Redirect Bypass via URL encoding)
  http/cves/2024/CVE-2024-8021.yaml
Labels: Hacktoberfest, Done

#10937 Add VMware Workspace One UEM SSP Login Panel Template
  http/exposed-panels/workspace-one-uem-ssp.yaml
Labels: good first issue, Hacktoberfest

#10940 Create CVE-2024-3753.yaml
  http/cves/2024/CVE-2024-3753.yaml
Labels: Hacktoberfest, Done

#10841 Adding WCF Detect
  http/technologies/windows-communication-foundation-detect.yaml
Labels: Done

#10912 Create CVE-2024-38816.yaml
  http/cves/2024/CVE-2024-38816.yaml
Labels: Hacktoberfest, Done

#10945 Update retool-xss.svg
  helpers/payloads/retool-xss.svg
  http/vulnerabilities/retool/retool-svg-xss.yaml
Labels: Hacktoberfest, Done

#10917 Create api-telegram.yaml
  http/token-spray/api-telegram.yaml
Labels: Done

#10911 Created gitlab-enum.yaml
  http/exposed-panels/gitlab-explore.yaml
Labels: good first issue, Hacktoberfest, Done

#10854 add CVE-2023-47105
  http/cves/2023/CVE-2023-47105.yaml
Labels: Done

#10948 Update javascript-env.yaml
  http/exposures/configs/javascript-env.yaml
Labels: Hacktoberfest, Done

#10914 Ivanti Endpoint Manager (EPM) Login Panel detection
  http/technologies/ivanti-epm-detect.yaml
Labels: Hacktoberfest, Done

#10947 Create ariang-debug-console.yaml
  http/misconfiguration/ariang-debug-console.yaml
Labels: Hacktoberfest, Done

#10950 add dizquetv detect
  http/technologies/dizquetv-detect.yaml
Labels: Hacktoberfest, Done

#10951 Create loxone-web-panel.yaml
  http/exposed-panels/loxone-web-panel.yaml
Labels: Hacktoberfest, Done

#10952 Create m-bus-panel.yaml
  http/exposed-panels/m-bus-panel.yaml
Labels: Hacktoberfest, Done

#10956 Create macos-server-panel.yaml
  http/exposed-panels/macos-server-panel.yaml
Labels: Hacktoberfest, Done

#10474 Create CVE-2024-4340
  code/cves/2024/CVE-2024-4340.yaml
Labels: Done

#10961 Create CVE-2023-39007.yaml
  http/cves/2023/CVE-2023-39007.yaml
Labels: Hacktoberfest, Done

#10657 Update http-missing-security-headers
  http/misconfiguration/http-missing-security-headers.yaml
Labels: Done

#10962 add dockwatch panel
  http/exposed-panels/dockwatch-panel.yaml
Labels: Hacktoberfest, Done

#10949 [swagger-api] check /docs/ with trailing slash
  http/exposures/apis/swagger-api.yaml
Labels: good first issue, Hacktoberfest, Done

#10973 Create CVE-2024-9465.yaml (Palo Alto Expedition - Unauthenticated SQL Injection 🔥 )
  http/cves/2024/CVE-2024-9465.yaml
Labels: Hacktoberfest, Done

#10986 Update CVE-2024-9465.yaml
  http/cves/2024/CVE-2024-9465.yaml
Labels: Done

#10996 improve error based sqli template
  dast/vulnerabilities/sqli/sqli-error-based.yaml
Labels: Done

#10999 add traccar panel
  http/exposed-panels/traccar-panel.yaml
Labels: Hacktoberfest, Done

#10993 add txadmin panel
  http/exposed-panels/txadmin-panel.yaml
Labels: Hacktoberfest, Done

#10991 Update ssh-default-logins.yaml (port update)
  javascript/default-logins/ssh-default-logins.yaml
Labels: Hacktoberfest, Done

#10989 Mirth Detection
  http/technologies/mirth-connect-detect.yaml
Labels: Done

#10970 Create CVE-2024-39713.yaml
  http/cves/2024/CVE-2024-39713.yaml
Labels: Hacktoberfest, Done

#10972 paloalto-expedition-project-panel + CVE-2024-5910
  http/cves/2024/CVE-2024-5910.yaml
  http/exposed-panels/paloalto-expedition-panel.yaml
Labels: Hacktoberfest, Done

#10971 Create CVE-2024-44349.yaml
  http/cves/2024/CVE-2024-44349.yaml
Labels: Hacktoberfest, Done

#10969 VMware-aria-operations-panel
  http/exposed-panels/vmware-aria-panel.yaml
Labels: Hacktoberfest, Done

#10967 Accellion Detection
  http/technologies/accellion-detect.yaml
Labels: Hacktoberfest, Done

#10966 Oracle Fusion Middleware Detect
  http/technologies/oracle-fusion-detect.yaml
Labels: Hacktoberfest, Done

#10965 Veritas Netbackup Panel
  http/exposed-panels/veritas-netbackup-panel.yaml
Labels: Hacktoberfest, Done

#10987 add CVE-2024-43360
  http/cves/2024/CVE-2024-43360.yaml
Labels: Done

#10964 add u8 tb sqli
  http/vulnerabilities/yonyou/yonyou-u8-crm-tb-sqli.yaml
Labels: Done

#10589 Update prototype pollution checks that bypasses insecure sanitization
  headless/prototype-pollution-check.yaml
Labels: good first issue, Done

#10705 Create CVE-2024-40711.yaml
  passive/cves/2024/CVE-2024-40711.yaml
Labels: Done

#10675 Create root-path-disclosure.yaml
  http/misconfiguration/root-path-disclosure.yaml
Labels: good first issue, Done

#10492 Added CVE-2015-8562.yaml
  http/cves/2015/CVE-2015-8562.yaml
Labels: good first issue, Done

#10983 Create CVE-2021-45811.yaml
  http/cves/2021/CVE-2021-45811.yaml
Labels: Hacktoberfest, Done

#10981 Create CVE-2023-1317.yaml
  http/cves/2023/CVE-2023-1317.yaml
Labels: Hacktoberfest, Done

#10979 Create CVE-2018-7196.yaml
  http/cves/2018/CVE-2018-7196.yaml
Labels: Hacktoberfest, Done

#10980 Create CVE-2023-1318.yaml
  http/cves/2023/CVE-2023-1318.yaml
Labels: Hacktoberfest, Done

#10977 Create CVE-2018-7192.yaml
  http/cves/2018/CVE-2018-7192.yaml
Labels: Hacktoberfest, Done

#10978 Create CVE-2018-7193.yaml
  http/cves/2018/CVE-2018-7193.yaml
Labels: Hacktoberfest, Done

#11010 Create CVE-2024-32735.yaml (CyberPower - Missing Authentication for Critical Function)
  http/cves/2024/CVE-2024-32735.yaml
Labels: Hacktoberfest, Done

#11011 Create CVE-2024-32736.yaml (CyberPower - SQL Injection in MCUDBHelper) (Verbose Query)
  http/cves/2024/CVE-2024-32736.yaml
Labels: Hacktoberfest, Done

#11012 Create CVE-2024-32737.yaml (CyberPower - SQL Injection in MCUDBHelper (Contract Result Query) )
  http/cves/2024/CVE-2024-32737.yaml
Labels: Hacktoberfest, Done

#11013 Create CVE-2024-32738.yaml (CyberPower - SQL Injection in MCUDBHelper (PTask Lean Query))
  http/cves/2024/CVE-2024-32738.yaml
Labels: Hacktoberfest, Done

#11015 Create CVE-2024-45488.yaml (SafeGuard for Privileged Passwords < 7.5.2 - Authentication Bypass)
  http/cves/2024/CVE-2024-45488.yaml
Labels: Hacktoberfest, Done

#11014 Create CVE-2024-32739.yaml (CyberPower - SQL Injection in MCUDBHelper (PTask Verbose Query))
  http/cves/2024/CVE-2024-32739.yaml
Labels: Hacktoberfest, Done

#11018 Update contributors.json
  contributors.json
Labels: Hacktoberfest, Done

#11017 Update Contributors
  contributors.json
Labels: Hacktoberfest, Done

#11023 Create Community-Rewards-FAQ.md
  Community-Rewards-FAQ.md
Labels: Done

#11027 fixed false negative - iam-user-password-change
  cloud/aws/iam/iam-user-password-change.yaml
Labels: Done

#11029 Fix time-based-sqli flow
  dast/vulnerabilities/sqli/time-based-sqli.yaml
Labels: Hacktoberfest, Done

#10963 add u8 sqli
  http/vulnerabilities/yonyou/yonyou-u8-crm-sqli.yaml
Labels: Done

#11025 Add Zebra default logins template
  http/default-logins/zebra/zebra-printer-default-login.yaml
Labels: Hacktoberfest, Done

#11031 add usermin panel
  http/exposed-panels/usermin-panel.yaml
Labels: Done

#11021 add sqlpad panel
  http/exposed-panels/sqlpad-panel.yaml
Labels: Hacktoberfest, Done

#11007 add freescout panel
  http/exposed-panels/freescout-panel.yaml
Labels: Hacktoberfest, Done

#11002 Update CVE-2019-7139.yaml
  http/cves/2019/CVE-2019-7139.yaml
Labels: Hacktoberfest, Done

#11039 Create CVE-2024-8698.yaml
  http/cves/2024/CVE-2024-8698.yaml
Labels: Hacktoberfest, Done

#11001 Update CVE-2023-39650.yaml
  http/cves/2023/CVE-2023-39650.yaml
Labels: Hacktoberfest, Done

#10523 Create wasabi-bucket-takeover.yaml
  http/takeovers/wasabi-bucket-takeover.yaml
Labels: Done

#11016 Create unauth-cyber-power-systems.yaml (Cyber Power Systems - Unauthenticated)
  http/misconfiguration/unauth-cyber-power-systems.yaml
Labels: Hacktoberfest, Done

#11024 Add SATO printers default login
  http/default-logins/sato/sato-default-login.yaml
Labels: Hacktoberfest, Done

#10506 Added 5 Templates for WordPress
  http/cves/2023/CVE-2023-2745.yaml
  http/cves/2023/CVE-2023-5561.yaml
  http/cves/2024/CVE-2024-4439.yaml
  http/vulnerabilities/wordpress/application-pass-xss.yaml
  http/vulnerabilities/wordpress/wp-footnote-xss.yaml
Labels: good first issue, Done

#11058 Create CVE-2023-40749.yaml
  http/cves/2023/CVE-2023-40749.yaml
Labels: Hacktoberfest, Done

#11059 Create CVE-2023-40750.yaml
  http/cves/2023/CVE-2023-40750.yaml
Labels: Hacktoberfest, Done

#11052 add CVE-2024-48914
  http/cves/2024/CVE-2024-48914.yaml
Labels: Hacktoberfest, Done

#11063 Create CVE-2023-40755.yaml
  http/cves/2023/CVE-2023-40755.yaml
Labels: Hacktoberfest, Done

#11062 Create CVE-2023-40753.yaml
  http/cves/2023/CVE-2023-40753.yaml
Labels: Hacktoberfest, Done

#11051 add CVE-2023-39560
  http/cves/2023/CVE-2023-39560.yaml
Labels: Hacktoberfest, Done

#11044 Refactor the "Django Admin Panel" template.
  http/exposed-panels/django-admin-panel.yaml
Labels: Hacktoberfest, Done

#11043 Fixed False Negative on CVE-2023-39650
  http/cves/2023/CVE-2023-39650.yaml
Labels: Hacktoberfest, Done

#11048 Create apache-doris-default-login.yaml
  http/default-logins/apache/doris-default-login.yaml
Labels: Hacktoberfest, Done

#11047 add CVE-2024-9234
  http/cves/2024/CVE-2024-9234.yaml
Labels: Hacktoberfest, Done

#11060 Create CVE-2023-40751.yaml
  http/cves/2023/CVE-2023-40751.yaml
Labels: Hacktoberfest, Done

#11055 Create CVE-2023-5558.yaml
  http/cves/2023/CVE-2023-5558.yaml
Labels: Hacktoberfest, Done

#11054 Create CVE-2023-38040.yaml
  http/cves/2023/CVE-2023-38040.yaml
Labels: Hacktoberfest, Done

#11061 Create CVE-2023-40752.yaml
  http/cves/2023/CVE-2023-40752.yaml
Labels: Hacktoberfest, Done

#11056 Create CVE-2023-43373.yaml
  http/cves/2023/CVE-2023-43373.yaml
Labels: Hacktoberfest, Done

#11057 Create CVE-2023-40748.yaml
  http/cves/2023/CVE-2023-40748.yaml
Labels: Hacktoberfest, Done

#10491 Added CVE-2024-2961.yaml
  dast/cves/2024/CVE-2024-2961.yaml
Labels: Done

#11053 Create CVE-2024-22476.yaml
  http/cves/2024/CVE-2024-22476.yaml
Labels: Hacktoberfest, Done

#11041 Add detection for Salesforce B2C WebDAV
  http/technologies/salesforce-b2c-commerce-webdav.yaml
Labels: good first issue, Hacktoberfest, waiting for more info

#11042 Add CVE-2019-8943.yaml Template - WP Crop RCE
  http/cves/2019/CVE-2019-8943.yaml
Labels: Hacktoberfest, Done, 🙋 Bounty claim

#11020 add CVE-2024-35584
  http/cves/2024/CVE-2024-35584.yaml
Labels: Hacktoberfest, Done

#11071 add danswer panel
  http/exposed-panels/danswer-panel.yaml
Labels: Hacktoberfest, Done

#11070 add CVE-2024-9617
  http/cves/2024/CVE-2024-9617.yaml
Labels: Hacktoberfest, Done
