Repository projectdiscovery/nuclei-templates, pull requests merged in 2024-04, with the labels that each got.

#9468 Update smb-default-creds.yaml
  javascript/enumeration/smb/smb-default-creds.yaml
Labels: Done

#9470 Create CVE-2016-5674.yaml
  http/cves/2016/CVE-2016-5674.yaml
Labels: Done

#9483 Update rsync-version.yaml
  javascript/enumeration/rsync/rsync-version.yaml
Labels: Done

#9484 Update oracle-tns-listener.yaml
  javascript/detection/oracle-tns-listener.yaml
Labels: Done

#9471 Add detection of Syfadis Xperience login panel instances.
  http/exposed-panels/syfadis-xperience-panel.yaml
Labels: Done

#9474 Create CVE-2018-10735.yaml
  http/cves/2018/CVE-2018-10735.yaml
Labels: Done

#9475 Create CVE-2018-10736.yaml
  http/cves/2018/CVE-2018-10736.yaml
Labels: Done

#9472 Add more detection criteria to the "Heroku App" template.
  http/technologies/herokuapp-detect.yaml
Labels: Done

#9487 Minecraft Server - enum
  javascript/enumeration/minecraft-enum.yaml
Labels: Done

#9473 YOURLS Detection Template
  http/technologies/yourls-detect.yaml
Labels: good first issue, Done

#9491 added windows payload
  http/cves/2021/CVE-2021-41277.yaml
Labels: Done

#9498 update CVE-2012-2122.yaml
  javascript/cves/2012/CVE-2012-2122.yaml
Labels: Done

#9477 Create CVE-2018-10738.yaml
  http/cves/2018/CVE-2018-10738.yaml
Labels: Done

#9481 Create CVE-2018-6605.yaml
  http/cves/2018/CVE-2018-6605.yaml
Labels: Done

#9493 Create CVE-2022-29013.yaml
  http/cves/2022/CVE-2022-29013.yaml
Labels: Done

#9495 Create CVE-2021-46419.yaml
  http/cves/2021/CVE-2021-46419.yaml
Labels: Done

#9500 Create 3ware-default-login.yaml
  http/default-logins/3ware-default-login.yaml
Labels: Done

#9501 Create 3Com-wireless-default-login.yaml
  http/default-logins/3com/3Com-wireless-default-login.yaml
Labels: Done

#9499 Create next-terminal-default-login.yaml
  http/default-logins/next-terminal/next-terminal-default-login.yaml
Labels: Done

#9497 CVE 2022 41412
  http/cves/2022/CVE-2022-41412.yaml
Labels: good first issue, Done

#9421 Create CVE-2024-28255.yaml
  http/cves/2024/CVE-2024-28255.yaml
Labels: Done

#9469 C2 - NT
  network/c2/darkcomet-trojan.yaml
  network/c2/darktrack-rat-trojan.yaml
  network/c2/orcus-rat-trojan.yaml
  network/c2/xtremerat-trojan.yaml
Labels: Done

#9463 Create voyager-path-traversal.yaml
  http/vulnerabilities/other/voyager-lfi.yaml
Labels: good first issue, Done

#9494 Create CVE-2021-46418.yaml
  http/cves/2021/CVE-2021-46418.yaml
Labels: Done

#9457 Create CVE-2024-27564.yaml
  http/cves/2024/CVE-2024-27564.yaml
Labels: Done

#9492 Create CVE-2022-32430.yaml
  http/cves/2022/CVE-2022-32430.yaml
Labels: Done

#9459 Add detection of simpleSAMLphp instances.
  http/technologies/simplesamlphp-detect.yaml
Labels: Done

#9509 Update php-debugbar-exposure.yaml
  http/exposures/logs/php-debug-bar.yaml
  http/misconfiguration/php-debugbar-exposure.yaml
Labels: Done

#9507 Create CVE-2024-29269.yaml
  http/cves/2024/CVE-2024-29269.yaml
Labels: Done

#9508 Create CVE-2023-47218.yaml
  http/cves/2023/CVE-2023-47218.yaml
Labels: Done

#9510 FP -Fix pop3 Capabilities
  javascript/enumeration/pop3/pop3-capabilities-enum.yaml
Labels: Done

#9427 JS - pgsql
  javascript/cves/2019/CVE-2019-9193.yaml
  javascript/enumeration/pgsql/pgsql-default-db.yaml
  javascript/enumeration/pgsql/pgsql-file-read.yaml
  javascript/enumeration/pgsql/pgsql-list-database.yaml
  javascript/enumeration/pgsql/pgsql-list-password-hashes.yaml
  javascript/enumeration/pgsql/pgsql-list-users.yaml
  javascript/enumeration/pgsql/pgsql-version-detect.yaml
  javascript/misconfiguration/pgsql/pgsql-extensions-rce.yaml
  javascript/misconfiguration/pgsql/postgresql-empty-password.yaml
Labels: Done

#9409 add CVE-2024-28734
  http/cves/2024/CVE-2024-28734.yaml
Labels: Done, community

#9480 Fix Wazuh default credentials template
  http/default-logins/wazuh-default-login.yaml
Labels: good first issue, Done

#9523 FP - Fix ftp-anonymous-login.yaml
  network/default-login/ftp-anonymous-login.yaml
Labels: Done

#9514 Update CVE-2022-0540.yaml
  http/cves/2022/CVE-2022-0540.yaml
Labels: good first issue, Done

#9512 Create CVE-2024-2879.yaml
  http/cves/2024/CVE-2024-2879.yaml
Labels: good first issue, Done

#9534 Create intelbras-dvr-unauth.yaml
  http/misconfiguration/intelbras-dvr-unauth.yaml
Labels: Done

#9535 fix-fp
  http/misconfiguration/intelbras-dvr-unauth.yaml
Labels: Done

#9533 Create dlink-unauth-cgi-script.yaml
  http/misconfiguration/dlink-unauth-cgi-script.yaml
Labels: Done

#9526 Create thanos-prometheus-exposure.yaml
  http/misconfiguration/thanos-prometheus-exposure.yaml
Labels: Done

#9458 Added local check for CVE-2024-3094
  code/cves/2024/CVE-2024-3094.yaml
Labels: Done

#9532 Create CVE-2024-3273.yaml
  http/cves/2024/CVE-2024-3273.yaml
Labels: Done

#9539 Minor improvement for CVE-2024-27497
  http/cves/2024/CVE-2024-27497.yaml
Labels: Done

#9518 Add detection of Mitel MiCollab login panel instances.
  http/exposed-panels/mitel-micollab-panel.yaml
Labels: Done

#9538 Create helm-dashboard-exposure.yaml
  http/misconfiguration/helm-dashboard-exposure.yaml
Labels: Done

#9524 Create zenml-dashboard-panel.yaml
  http/exposed-panels/zenml-dashboard-panel.yaml
Labels: Done

#9511 Add detection of BeyondTrust Privileged Remote Access login panel instances.
  http/exposed-panels/beyondtrust-priv-panel.yaml
Labels: Done

#9540 Updated CVE-2024-27497
  http/cves/2024/CVE-2024-27497.yaml
Labels: Done

#9541 Update profiles README
  profiles/README.md
Labels: Done

#9529 Add detection of SOAP-based ASP.NET web services ASMX.
  http/exposures/apis/aspnet-soap-webservices-asmx.yaml
Labels: Done

#9550 Create asus-rtn16-default-login.yaml
  http/default-logins/asus/asus-rtn16-default-login.yaml
Labels: Done

#9548 Create asus-wl500g-default-login.yaml
  http/default-logins/asus/asus-wl500g-default-login.yaml
Labels: Done

#9553 Update outsystems-servicecenter-panel.yaml
  http/exposed-panels/outsystems-servicecenter-panel.yaml
Labels: Done

#9545 add cve-2024-0337 open redirect
  http/cves/2024/CVE-2024-0337.yaml
Labels: Done

#9544 add cve-2022-0424
  http/cves/2022/CVE-2022-0424.yaml
Labels: Done

#9530 Added template for Citrix XenMobile technology and version detection …
  http/technologies/citrix-xenmobile-version.yaml
Labels: good first issue, Done

#9546 Create allnet-default-login.yaml
  http/default-logins/allnet/allnet-default-login.yaml
Labels: Done

#9424 Add splunkhec-detect.yaml
  http/technologies/splunkhec-detect.yaml
Labels: Done

#9517 Add detection of Mitric Checker login panel instances.
  http/exposed-panels/mitric-checker-panel.yaml
Labels: Done

#9525 Create akhq-panel.yaml
  http/exposed-panels/akhq-panel.yaml
Labels: Done

#9564 Create ni-web-based-panel.yaml
  http/exposed-panels/ni-web-based-panel.yaml
Labels: Done

#9565 Create rtm-web-panel.yaml
  http/exposed-panels/rtm-web-panel.yaml
Labels: Done

#9568 Create suprema-biostar-panel.yaml
  http/exposed-panels/suprema-biostar-panel.yaml
Labels: Done

#9396 Quick.CMS 6.7 SQL Injection add
  http/vulnerabilities/other/quick-cms-sqli.yaml
Labels: good first issue, Done

#9563 Create powerchute-network-panel.yaml
  http/exposed-panels/powerchute-network-panel.yaml
Labels: Done

#9562 Create apple-cups-exposure.yaml
  http/misconfiguration/apple-cups-exposure.yaml
Labels: Done

#9569 feat: convert paths with lots of elements to payloads
  http/cves/2013/CVE-2013-3827.yaml
  http/cves/2014/CVE-2014-2383.yaml
  http/cves/2014/CVE-2014-6271.yaml
  http/cves/2022/CVE-2022-48197.yaml
  http/cves/2023/CVE-2023-6379.yaml
  http/exposed-panels/openam-panel.yaml
  http/exposed-panels/phpmyadmin-panel.yaml
  http/exposed-panels/webeditors-check-detect.yaml
  http/exposures/apis/swagger-api.yaml
  http/exposures/backups/sql-dump.yaml
  http/exposures/configs/codeigniter-env.yaml
  http/exposures/configs/deployment-ini.yaml
  http/exposures/configs/git-config-nginxoffbyslash.yaml
  http/exposures/configs/github-workflows-disclosure.yaml
  http/exposures/configs/laravel-env.yaml
  http/exposures/configs/phpinfo-files.yaml
  http/exposures/configs/server-private-keys.yaml
  http/exposures/configs/zend-config-file.yaml
  http/exposures/files/routes-ini.yaml
  http/exposures/files/shellscripts.yaml
  http/exposures/logs/error-logs.yaml
  http/misconfiguration/aem/aem-default-get-servlet.yaml
  http/misconfiguration/aem/aem-gql-servlet.yaml
  http/misconfiguration/aem/aem-misc-admin.yaml
  http/misconfiguration/jolokia/jolokia-info-disclosure.yaml
  http/misconfiguration/phpmyadmin/phpmyadmin-server-import.yaml
  http/misconfiguration/phpmyadmin/phpmyadmin-setup.yaml
  http/technologies/graphql-detect.yaml
  http/technologies/telerik/telerik-dialoghandler-detect.yaml
  http/vulnerabilities/generic/generic-env.yaml
  http/vulnerabilities/generic/generic-j2ee-lfi.yaml
  http/vulnerabilities/generic/generic-linux-lfi.yaml
  http/vulnerabilities/generic/generic-windows-lfi.yaml
  http/vulnerabilities/other/bitrix-open-redirect.yaml
  http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
Labels: Done

#9573 Update CVE-2023-29489.yaml
  http/cves/2023/CVE-2023-29489.yaml
Labels: good first issue, Done

#9582 FP - Fix rsync-version.yaml
  javascript/enumeration/rsync/rsync-version.yaml
Labels: Done

#9570 backdoor account - update
  http/cves/2024/CVE-2024-3273.yaml
Labels: Done

#9583 fix the inconsistencies in the pgsql template ids
  javascript/enumeration/pgsql/pgsql-file-read.yaml
  javascript/enumeration/pgsql/pgsql-list-database.yaml
  javascript/enumeration/pgsql/pgsql-list-password-hashes.yaml
  javascript/misconfiguration/pgsql/pgsql-empty-password.yaml
Labels: Done

#9585 Update ms-exchange-server.yaml description
  http/technologies/microsoft/ms-exchange-server.yaml
Labels: good first issue, Done

#9578 Add detection of Algonomia Leaf Platform login panel instances.
  http/exposed-panels/algonomia-panel.yaml
Labels: Done

#9572 Create softr.yaml
  http/takeovers/softr-takeover.yaml
Labels: Done

#9490 opencart-core-sqli add
  http/vulnerabilities/other/opencart-core-sqli.yaml
Labels: Done

#9576 Add detection of TIBCO Spotfire Statistics Services instances.
  http/technologies/tibco-spotfire-services-detect.yaml
Labels: Done

#9450 add User-Registration-Login-and-User-Management-System admin panel sqli
  http/vulnerabilities/other/user-management-system-sqli.yaml
Labels: good first issue, Done

#9574 Add detection of Chemotargets Clarity Vista login panel instances.
  http/exposed-panels/chemotargets-clarityvista-panel.yaml
Labels: Done

#7387 Create CVE-2022-24627.yaml
  http/cves/2022/CVE-2022-24627.yaml
Labels: Done

#9590 Create CVE-2024-3400.yaml
  http/cves/2024/CVE-2024-3400.yaml
Labels: Done

#9593 Create sentinel-license-monitor.yaml
  http/misconfiguration/sentinel-license-monitor.yaml
Labels: Done

#9592 Create urbackup-panel.yaml
  http/exposed-panels/urbackup-panel.yaml
Labels: Done

#9560 Create sliver-c2.yaml
  ssl/c2/sliver-c2.yaml
Labels: Done

#9598 Update CVE-2024-3400.yaml
  http/cves/2024/CVE-2024-3400.yaml
Labels: Done

#9600 shodan-query sliver-c2.yaml
  ssl/c2/sliver-c2.yaml
Labels: Done

#9594 Create CVE-2024-3400.yaml
  http/cves/2024/CVE-2024-3400.yaml
Labels: Done

#9411 BIMI TXT Record Detection
  dns/bimi-detect.yaml
Labels: Done

#9536 Create gohire-takeover.yaml
  http/takeovers/gohire-takeover.yaml
Labels: Done

#9537 Create helpdocs.io-takeover.yaml
  http/takeovers/helpdocs-takeover.yaml
Labels: Done

#9543 Create betteruptime-takeover.yaml
  http/takeovers/uptime-takeover.yaml
Labels: Done

#9606 Create CVE-2024-2389.yaml
  http/cves/2024/CVE-2024-2389.yaml
Labels: Done

#9584 updated php fileupload templates
  http/cnvd/2021/CNVD-2021-49104.yaml
  http/cves/2012/CVE-2012-1823.yaml
  http/cves/2017/CVE-2017-6090.yaml
  http/cves/2017/CVE-2017-9841.yaml
  http/cves/2020/CVE-2020-28871.yaml
  http/cves/2021/CVE-2021-24145.yaml
  http/cves/2021/CVE-2021-24236.yaml
  http/cves/2021/CVE-2021-24284.yaml
  http/cves/2021/CVE-2021-24499.yaml
  http/cves/2021/CVE-2021-36260.yaml
  http/cves/2021/CVE-2021-40870.yaml
  http/cves/2022/CVE-2022-1952.yaml
  http/cves/2022/CVE-2022-25487.yaml
  http/cves/2022/CVE-2022-3982.yaml
  http/cves/2022/CVE-2022-4328.yaml
  http/cves/2023/CVE-2023-26469.yaml
  http/cves/2023/CVE-2023-2648.yaml
  http/cves/2023/CVE-2023-33440.yaml
  http/cves/2023/CVE-2023-35885.yaml
  http/cves/2023/CVE-2023-36844.yaml
  http/cves/2023/CVE-2023-37629.yaml
  http/cves/2023/CVE-2023-4596.yaml
  http/cves/2023/CVE-2023-5360.yaml
  http/vulnerabilities/other/core-chuangtian-cloud-rce.yaml
  http/vulnerabilities/ruijie/ruijie-nbr-fileupload.yaml
  http/vulnerabilities/secworld/secgate-3600-file-upload.yaml
  http/vulnerabilities/thinkcmf/thinkcmf-rce.yaml
  http/vulnerabilities/tongda/tongda-action-uploadfile.yaml
  http/vulnerabilities/weaver/weaver-group-xml-sqli.yaml
  http/vulnerabilities/weaver/weaver-lazyuploadify-file-upload.yaml
  http/vulnerabilities/weaver/weaver-office-server-file-upload.yaml
  http/vulnerabilities/weaver/weaver-uploadify-file-upload.yaml
  http/vulnerabilities/wordpress/3dprint-arbitrary-file-upload.yaml
  http/vulnerabilities/wordpress/ait-csv-import-export-rce.yaml
  http/vulnerabilities/wordpress/wordpress-rce-simplefilelist.yaml
  http/vulnerabilities/wordpress/wp-kadence-blocks-rce.yaml
Labels: Done

#9612 Add more detection criteria to the "GlassFish Server Default Page" template.
  http/technologies/default-glassfish-server-page.yaml
Labels: Done

#9618 Fixing CVSS score for 2x templates
  http/misconfiguration/jupyter-ipython-unauth.yaml
  http/misconfiguration/jupyter-lab-unauth.yaml
Labels: Done

#9616 Add detection of "BMC Remedy Single Sign-On domain data entry" login panel instances.
  http/exposed-panels/bmc/bmc-remedy-sso-panel.yaml
Labels: Done

#9609 Add detection of TIXEO login panel instances.
  http/exposed-panels/tixeo-panel.yaml
Labels: Done

#9620 [FIX] CVE-2022-23134
  http/cves/2022/CVE-2022-23134.yaml
Labels: Done

#9623 Create bonobo-git-server.yaml
  http/exposed-panels/bonobo-server-panel.yaml
Labels: Done

#9625 Create titannit-web-ssrf.yaml
  http/vulnerabilities/titan/titannit-web-ssrf.yaml
Labels: Done

#9626 Create titannit-web-exposure.yaml
  http/misconfiguration/titannit-web-exposure.yaml
Labels: Done

#9627 Create CVE-2023-31446.yaml
  http/cves/2023/CVE-2023-31446.yaml
Labels: Done

#9628 Create cassia-bluetooth-gateway-panel.yaml
  http/exposed-panels/cassia-bluetooth-gateway-panel.yaml
Labels: Done

#9634 Create CVE-2023-2949.yaml
  http/cves/2023/CVE-2023-2949.yaml
Labels: Done

#9635 Create CVE-2023-2948.yaml
  http/cves/2023/CVE-2023-2948.yaml
Labels: Done

#9632 Create sabnzbd-installer.yaml
  http/misconfiguration/installer/sabnzbd-installer.yaml
Labels: Done

#9633 Create CVE-2023-4973.yaml
  http/cves/2023/CVE-2023-4973.yaml
Labels: Done

#9641 Create CVE-2024-31621.yaml
  http/cves/2024/CVE-2024-31621.yaml
Labels: Done

#9645 Create CVE-2024-32399.yaml
  http/cves/2024/CVE-2024-32399.yaml
Labels: Done

#9643 Create CVE-2024-1183.yaml
  http/cves/2024/CVE-2024-1183.yaml
Labels: Done

#9650 Create crushftp-anonymous-login.yaml
  http/default-logins/crushftp/crushftp-anonymous-login.yaml
Labels: Done

#9649 CrushFTP Default Login
  http/default-logins/crushftp/crushftp-default-login.yaml
Labels: Done

#9648 Create monitorr-panel.yaml
  http/exposed-panels/monitorr-panel.yaml
Labels: Done

#9642 Add detection of Blue Coat Telnet Proxy services.
  network/detection/bluecoat-telnet-proxy-detect.yaml
Labels: Done

#9640 Add detection of IBM AIX Web-based System Manager services.
  network/detection/aix-websm-detect.yaml
Labels: Done

#9637 fix: network/c2/xtremerat-trojan.yaml replace matcher type
  network/c2/xtremerat-trojan.yaml
Labels: good first issue, Done

#9661 updated iterate to vpc templates
  cloud/aws/vpc/nacl-open-inbound.yaml
  cloud/aws/vpc/nacl-outbound-restrict.yaml
  cloud/aws/vpc/nat-gateway-usage.yaml
  cloud/aws/vpc/unrestricted-admin-ports.yaml
  cloud/aws/vpc/vpc-endpoint-exposed.yaml
  cloud/aws/vpc/vpc-endpoints-not-deployed.yaml
  cloud/aws/vpc/vpc-flowlogs-not-enabled.yaml
  cloud/aws/vpc/vpn-tunnel-down.yaml
Labels: Done

#9656 Create CVE-2024-0235.yaml
  http/cves/2024/CVE-2024-0235.yaml
Labels: Done

#9658 Create CVE-2024-24131.yaml
  http/cves/2024/CVE-2024-24131.yaml
Labels: Done

#9659 Create CVE-2024-31849.yaml
  http/cves/2024/CVE-2024-31849.yaml
Labels: Done

#9663 Create CVE-2024-27956.yaml
  http/cves/2024/CVE-2024-27956.yaml
Labels: Done

#9669 fix: typo splunk workflow
  workflows/splunk-workflow.yaml
Labels: Done

#9667 Rename titannit-web-ssrf.yaml to titannit-web-rce.yaml
  http/vulnerabilities/titan/titannit-web-rce.yaml
Labels: Done

#9666 Update ms-exchange-web-service.yaml
  http/exposed-panels/ms-exchange-web-service.yaml
Labels: good first issue, Done

#9664 Create CVE-2023-32077.yaml
  http/cves/2023/CVE-2023-32077.yaml
Labels: Done

#9668 Update vbulletin-workflow.yaml
  workflows/vbulletin-workflow.yaml
Labels: Done

#9670 Delete http/vulnerabilities/other/academy-lms-xss.yaml
  http/vulnerabilities/other/academy-lms-xss.yaml
Labels: Done
