Repository projectdiscovery/nuclei-templates, pull requests merged in 2025-06, with the labels that each got.

#12223 Update vscode-launch.yaml
  http/exposures/files/vscode-launch.yaml
Labels: Done

#12134 Create CVE-2021-25032.yaml
  http/cves/2021/CVE-2021-25032.yaml
Labels: Done

#12226 Create CVE-2023-4136.yaml
  http/cves/2023/CVE-2023-4136.yaml
Labels: Done

#12231 Create CVE-2017-14942.yaml
  http/cves/2017/CVE-2017-14942.yaml
Labels: Done

#12235 Create nextcloudpi-login.yaml
  http/exposed-panels/nextcloudpi-panel.yaml
Labels: Done

#12234 Create nextcloudpi-dashboard.yaml
  http/misconfiguration/nextcloudpi-dashboard.yaml
Labels: Done

#12093 Create CVE-2022-25061.yaml
  http/cves/2022/CVE-2022-25061.yaml
Labels: Done

#12198 Create CVE-2021-24522.yaml
  http/cves/2021/CVE-2021-24522.yaml
Labels: Done

#12255 Create Spark Application UI exposed
  http/misconfiguration/apachespark-ui-exposed.yaml
Labels: Done

#12259 Revert changes port
  http/cves/2018/CVE-2018-8024.yaml
  http/misconfiguration/apachespark-ui-exposed.yaml
Labels: Done

#12249 Create CVE-2025-4322.yaml (Motors <= 5.6.67 - Unauthenticated Privilege Escalation via Password Update/Account Takeover) - CISA
  http/cves/2025/CVE-2025-4322.yaml
Labels: Done

#12260 Fix FN jupyter-notebooks-exposed.yaml
  http/misconfiguration/jupyter-notebooks-exposed.yaml
Labels: Done

#12253 Create CVE-2021-40655.yaml (D-Link DIR-605 - Information Disclosure) - KEV
  http/cves/2021/CVE-2021-40655.yaml
Labels: Done

#12252 Create CVE-2024-0692.yaml (SolarWinds Security Event Manager - Unauthenticated RCE) CISA
  http/cves/2024/CVE-2024-0692.yaml
Labels: Done

#12123 Create CVE-2024-24328.yaml
  http/cves/2024/CVE-2024-24328.yaml
Labels: Done

#12250 Create CVE-2023-34990.yaml (FortiWLM - Directory Traversal) CISA
  http/cves/2023/CVE-2023-34990.yaml
Labels: Done

#12301 Create CVE-2019-13372.yaml (D-Link Central WiFi Manager CWM(100) - Remote Code Execution) KEV
  http/cves/2019/CVE-2019-13372.yaml
Labels: Done

#12300 Create CVE-2020-26879.yaml (Ruckus vRioT IoT Controller - API Backdoor Authentication Bypass) KEV
  http/cves/2020/CVE-2020-26879.yaml
Labels: Done

#12285 CVE-2023-30192 & Exposed Prestashop Panels
  http/cves/2023/CVE-2023-30192.yaml
  http/exposed-panels/prestashop-admin-panel.yaml
Labels: Done

#12076 Fortirecorder Detect
  http/exposed-panels/fortirecorder-panel.yaml
Labels: Done

#12046 Update phpwind-installer.yaml
  http/misconfiguration/installer/phpwind-installer.yaml
Labels: good first issue, Done

#12256 Create CVE-2019-9757.yaml
  http/cves/2019/CVE-2019-9757.yaml
Labels: Done

#12267 Update hfs-exposure
  http/misconfiguration/hfs-exposure.yaml
Labels: Done

#12279 Create CVE-2021-33558.yaml (Boa 0.94.13 - Information Disclosure) KEV
  http/cves/2021/CVE-2021-33558.yaml
Labels: Done

#12268 Added new template to detect MCP SSE endpoint
  http/exposures/apis/exposed-mcp-sse-server.yaml
Labels: Done

#12143 Fewer FP for Apache Tomcat
  http/cves/2025/CVE-2025-24813.yaml
Labels: Done

#12178 feat: add default login detection for SE-APC Network Management Card
  http/default-logins/apc-nmc/apc-nmc-default-login.yaml
Labels: Done

#12219 CVE 2017 8046
  http/cves/2017/CVE-2017-8046.yaml
Labels: Done, 🙋 Bounty claim

#12295 Update empirec2-default-login.yaml
  http/default-logins/empire/empirec2-default-login.yaml
Labels: Done

#12293 Update exposed-mcp-server.yaml
  http/exposures/apis/exposed-mcp-server.yaml
Labels: Done

#12284 Create CVE-2021-39341.yaml (OptinMonster Plugin < 2.6.5 - Unprotected REST-API) KEV
  http/cves/2021/CVE-2021-39341.yaml
Labels: Done

#12240 Create CVE-2023-2986.yaml (Abandoned Cart Lite for WooCommerce - Authentication Bypass)
  http/cves/2023/CVE-2023-2986.yaml
Labels: Done

#12241 Create CVE-2024-10443.yaml (Synology BeeStation BST150-4T - Unauthenticated Command Injection)
  code/cves/2024/CVE-2024-10443.yaml
Labels: Done

#12239 Create CVE-2023-3722.yaml (Avaya Aura Device Services - OS Command Injection)
  http/cves/2023/CVE-2023-3722.yaml
Labels: Done

#12137 Add topdesk detect
  http/technologies/topdesk-detect.yaml
Labels: Done

#11970 Assetlinks Detect
  http/miscellaneous/assetlinks-detect.yaml
Labels: Done

#12298 Create CVE-2021-27964.yaml (SonLogger - Arbitrary File Upload) KEV
  http/cves/2021/CVE-2021-27964.yaml
Labels: Done

#12297 Create CVE-2018-11133.yaml (Quest KACE SMA /common/run_cross_report.php 'fmt' XSS)
  http/cves/2018/CVE-2018-11133.yaml
Labels: Done

#12319 Create CVE-2025-4009.yaml (Evertz Unauthenticated Arbitrary Command Injection)
  http/cves/2025/CVE-2025-4009.yaml
Labels: Done

#12333 Update CVE-2025-24813.yaml
  http/cves/2025/CVE-2025-24813.yaml
Labels: Done

#12339 Create CVE-2025-0133.yaml (PAN-OS - Reflected Cross-Site Scripting)
  http/cves/2025/CVE-2025-0133.yaml
Labels: Done

#12341 Create bigant-db-install.yaml
  http/misconfiguration/installer/bigant-db-install.yaml
Labels: Done

#12337 Create joplin-default-login.yaml
  http/default-logins/joplin/joplin-default-login.yaml
Labels: Done

#12338 Create joplin-panel-detect.yaml
  http/exposed-panels/joplin-panel.yaml
Labels: Done

#12032 Added CVE-2025-27134 Template
  http/cves/2025/CVE-2025-27134.yaml
Labels: good first issue, Done

#12126 Create CVE-2024-36858.yaml
  http/cves/2024/CVE-2024-36858.yaml
Labels: Done

#11888 Create raisecom-rce.yaml
  http/vulnerabilities/others/raisecom-rce.yaml
Labels: Done

#12321 Create CVE-2015-9499.yaml
  http/cves/2015/CVE-2015-9499.yaml
Labels: Done

#11834 Create android-minSDK-check.yaml
  file/android/android-minsdk-21.yaml
Labels: Done

#12305 Create CVE-2014-9735.yaml (WordPress RevSlider - Remote Code Execution via File Upload) KEV
  http/cves/2014/CVE-2014-9735.yaml
Labels: Done

#12214 Added Rocket LMS default login
  http/default-logins/rocketlms/rocketlms-default-login.yaml
Labels: Done

#12248 Create CVE-2022-45699.yaml
  http/cves/2022/CVE-2022-45699.yaml
Labels: Done

#12247 Create CVE-2023-26802.yaml
  http/cves/2023/CVE-2023-26802.yaml
Labels: Done

#11844 ssh-gssapiauthentication-disabled
  code/audit/cis/ubuntu/ssh-gssapiauthentication-disabled.yaml
Labels: Done

#11005 Create get-stored-credentials-cmdkey.yaml
  code/windows/get-stored-credentials-cmdkey.yaml
Labels: Done

#12367 Added template for Motive eSIM Secure Connect Panel
  http/exposed-panels/motive-eim-panel.yaml
Labels: Done

#12385 Rename raisecom-rce.yaml to raisecom-rce.yaml
  http/vulnerabilities/other/raisecom-rce.yaml
Labels: Done

#12379 Create photoprism-default-login.yaml
  http/default-logins/photoprism-default-login.yaml
Labels: Done

#12378 Create photoprism-unauth.yaml
  http/misconfiguration/photoprism-unauth.yaml
Labels: Done

#12376 Create nuuo-nvr-default-login.yaml
  http/default-logins/nuuo-nvr-default-login.yaml
Labels: Done

#12377 Create photoprism-login.yaml
  http/exposed-panels/photoprism-panel.yaml
Labels: Done

#12372 Create opensearch-default-login.yaml
  http/default-logins/opensearch-default-login.yaml
Labels: Done

#12373 Create opensearch-dashboard-unauth.yaml
  http/misconfiguration/opensearch-dashboard-unauth.yaml
Labels: Done

#12045 Added template for evo-api-getclassvalue
  http/vulnerabilities/dahua/dahua-icc-getclassvalue-rce.yaml
Labels: Done

#12401 Create CVE-2025-30220.yaml (GeoServer WFS - XXE Processing Vulnerability)
  http/cves/2025/CVE-2025-30220.yaml
Labels: Done

#12262 feat: detect greatpages.com.br domain takeover
  http/takeovers/greatpages-takeover.yaml
Labels: good first issue, Done

#12411 Create CVE-2025-47423.yaml
  http/cves/2025/CVE-2025-47423.yaml
Labels: Done

#12410 add CVE-2025-3415.yaml - (Grafana - Exposes DingDing API Keys)
  http/cves/2025/CVE-2025-3415.yaml
Labels: good first issue, Done

#12381 Create CVE-2018-19207.yaml (WP GDPR Compliance < 1.4.3 - Unauthenticated Call Any Action or Update Any Option) KEV
  http/cves/2018/CVE-2018-19207.yaml
Labels: Done

#12424 Create totolink-setup-page-detect.yaml
  http/misconfiguration/installer/totolink-installer.yaml
Labels: Done

#12425 Create totolink-boaform-rce.yaml
  http/vulnerabilities/totolink-boaform-rce.yaml
Labels: Done

#12415 Create CVE-2025-47646.yaml
  http/cves/2025/CVE-2025-47646.yaml
Labels: Done

#12448 Create CVE-2018-11686.yaml
  http/cves/2018/CVE-2018-11686.yaml
Labels: Done

#12417 Create CVE-2024-4325.yaml (Gradio - Unauthenticated SSRF via /queue/join) KEV
  http/cves/2024/CVE-2024-4325.yaml
Labels: Done

#12368 Create mitel-micollab-ucs-version-detect.yaml
  http/technologies/mitel-version-detect.yaml
Labels: Done

#12445 FP-Fix revoked-ssl-certificate.yaml
  ssl/revoked-ssl-certificate.yaml
Labels: Done

#12289 Update apachespark-ui-exposed.yaml
  http/misconfiguration/apachespark-ui-exposed.yaml
Labels: Done

#12452 add CVE-2020-11984
  code/cves/2020/CVE-2020-11984.yaml
Labels: good first issue, Done, 🙋 Bounty claim

#12296 Created CVE-2021-33045.yaml (Dahua IPC/VTH/VTO - Authentication Bypass) KEV
  http/cves/2021/CVE-2021-33045.yaml
Labels: good first issue, Done

#12464 Create CVE-2025-45985.yaml (Blink Router - Command Injection)
  http/cves/2025/CVE-2025-45985.yaml
Labels: Done

#12469 Rename CVE-2020-11984.yaml to CVE-2020-11984.yaml
  http/cves/2020/CVE-2020-11984.yaml
Labels: Done

#11988 Create apache-kyuubi-detect.yaml and apache-kyuubi-config.yaml
  http/exposures/configs/apache-kyuubi-config.yaml
  http/technologies/apache/apache-kyuubi-detect.yaml
Labels: Done

#12443 add CVE-2020-0646
  code/cves/2020/CVE-2020-0646.yaml
Labels: Done, 🙋 Bounty claim

#12479 Update CVE-2019-0604.yaml
  code/cves/2019/CVE-2019-0604.yaml
Labels: Done

#12290 Create CVE-2019-9194.yaml
  http/cves/2019/CVE-2019-9194.yaml
Labels: Done, 🙋 Bounty claim

#12272 QNAP Photo Station < 6.0.3 - Remote Code Execution (CVE-2019-7194)
  http/cves/2019/CVE-2019-7194.yaml
Labels: Done, 🙋 Bounty claim

#12477 Update cisco-ise-admin-panel
  http/exposed-panels/cisco/cisco-ise-admin-panel.yaml
Labels: Done

#12462 Added CVE-2019-17564: Apache Dubbo insecure deserialization template
  http/cves/2019/CVE-2019-17564.yaml
Labels: good first issue, Done, 🙋 Bounty claim

#12463 Add beyondtrust-remotesupport-version
  http/technologies/beyondtrust-remotesupport-version.yaml
Labels: Done

#12471 Create CVE-2024-51977.yaml
  http/cves/2024/CVE-2024-51977.yaml
Labels: Done

#12426 Create totolink-n150rt-password-exposure.yaml
  http/vulnerabilities/totolink-n150rt-password-exposure.yaml
Labels: Done

#12396 redhat-openshift-login-detect
  http/exposed-panels/openshift-oauth-proxy-panel.yaml
Labels: Done
