Repository projectdiscovery/nuclei-templates, pull requests merged in 2025-07, with the labels that each got.

#12511 Release Prep v10.2.4
  http/cves/2024/CVE-2024-51977.yaml
  http/cves/2024/CVE-2024-51978.yaml
  http/cves/2025/CVE-2024-51977.yaml
  http/technologies/wordpress/plugins/blocksy-companion.yaml
  http/technologies/wordpress/plugins/gosmtp.yaml
  http/technologies/wordpress/plugins/honeypot.yaml
  http/technologies/wordpress/plugins/pagelayer.yaml
  http/technologies/wordpress/plugins/siteseo.yaml
  http/technologies/wordpress/plugins/unlimited-elements-for-elementor.yaml
Labels: Done

#12523 Updated missing KEV tags
  code/cves/2014/CVE-2014-0160.yaml
  code/cves/2024/CVE-2024-12356.yaml
  code/cves/2025/CVE-2025-32433.yaml
  dast/cves/2021/CVE-2021-45046.yaml
  http/cves/2016/CVE-2016-8735.yaml
  http/cves/2017/CVE-2017-12637.yaml
  http/cves/2017/CVE-2017-3506.yaml
  http/cves/2019/CVE-2019-16278.yaml
  http/cves/2021/CVE-2021-32030.yaml
  http/cves/2023/CVE-2023-1389.yaml
  http/cves/2023/CVE-2023-20198.yaml
  http/cves/2024/CVE-2024-20439.yaml
  http/cves/2024/CVE-2024-41713.yaml
  http/cves/2024/CVE-2024-48248.yaml
  http/cves/2024/CVE-2024-56145.yaml
  http/cves/2025/CVE-2025-24016.yaml
  passive/cves/2024/CVE-2024-40711.yaml
Labels: Done

#12535 Fix: incorrect CWE classification for CVE-2025-45854
  http/cves/2025/CVE-2025-45854.yaml
Labels: Done

#12542 Create CVE-2025-5777.yaml (Citrix NetScaler Memory Disclosure - CitrixBleed 2)
  http/cves/2025/CVE-2025-5777.yaml
Labels: Done

#12543 Create CVE-2024-50334.yaml (Scoold < 1.64.0 - Authentication Bypass)
  http/cves/2024/CVE-2024-50334.yaml
Labels: Done

#12538 feat: add Molgenis EMX2 panel detection template
  http/exposed-panels/molgenis-panel.yaml
Labels: good first issue, Done

#12557 Create CVE-2025-32813.yaml (Infoblox NetMRI < 7.6.1 - Unauthenticated Command Injection in get_saml_request)
  http/cves/2025/CVE-2025-32813.yaml
Labels: Done

#12567 Create CVE-2025-4380.yaml
  http/cves/2025/CVE-2025-4380.yaml
Labels: Done

#12566 Create peplink-panel.yaml
  http/exposed-panels/peplink-panel.yaml
Labels: Done

#12561 Create jdwp-detect.yaml
  network/detection/jdwp-detect.yaml
Labels: Done

#12539 refactor: fix matchers for CVE-2024-51977
  http/cves/2024/CVE-2024-51977.yaml
Labels: good first issue, Done

#12544 Cisco Unified Communications Manager Detection
  http/exposed-panels/cisco-cm-panel.yaml
Labels: Done

#12559 Create CVE-2025-34040.yaml (Zhiyuan OA Platform - Arbitrary File Upload)
  http/cves/2025/CVE-2025-34040.yaml
Labels: Done

#11600 KISA Cloud Vulnerability Inspection Guide 2024
  code/windows/audit/kisa/account-lockout-threshold.yaml
  code/windows/audit/kisa/admin-account-rename.yaml
  code/windows/audit/kisa/admin-group-minimal.yaml
  code/windows/audit/kisa/autologon-control.yaml
  code/windows/audit/kisa/crash-on-audit-fail.yaml
  code/windows/audit/kisa/dns-zone-transfer-check.yaml
  code/windows/audit/kisa/ftp-access-control-check.yaml
  code/windows/audit/kisa/ftp-anonymous-check.yaml
  code/windows/audit/kisa/ftp-directory-permission-check.yaml
  code/windows/audit/kisa/hard-disk-default-share.yaml
  code/windows/audit/kisa/password-cleartext-encryption.yaml
  code/windows/audit/kisa/password-never-expires.yaml
  code/windows/audit/kisa/rds-removal-check.yaml
  code/windows/audit/kisa/remote-registry-access-check.yaml
  code/windows/audit/kisa/remote-system-shutdown.yaml
  code/windows/audit/kisa/sam-file-access-control.yaml
  code/windows/audit/kisa/service-pack-check.yaml
  code/windows/audit/kisa/shutdown-without-logon.yaml
  code/windows/audit/kisa/unnecessary-accounts-check.yaml
  code/windows/audit/kisa/unnecessary-service-check.yaml
Labels: Done

#12572 Create CVE-2025-53624 - docusaurus-plugin-content-gists < 4.0.0 - GitHub Personal Access Token Exposure
  http/cves/2025/CVE-2025-53624.yaml
Labels: Done

#2563 Create graphql-detect
  technologies/graphql/graphql-apiforwp-detect.yaml
  technologies/graphql/graphql-apollo-detect.yaml
  technologies/graphql/graphql-ariadne-detect.yaml
  technologies/graphql/graphql-dianajl-detect.yaml
  technologies/graphql/graphql-flutter-detect.yaml
  technologies/graphql/graphql-go-detect.yaml
  technologies/graphql/graphql-gqlgen-detect.yaml
  technologies/graphql/graphql-graphene-detect.yaml
  technologies/graphql/graphql-hasura-detect.yaml
  technologies/graphql/graphql-hypergraphql-detect.yaml
  technologies/graphql/graphql-java-detect.yaml
  technologies/graphql/graphql-juniper-detect.yaml
  technologies/graphql/graphql-php-detect.yaml
  technologies/graphql/graphql-ruby-detect.yaml
  technologies/graphql/graphql-sangria-detect.yaml
  technologies/graphql/graphql-strawberry-detect.yaml
  technologies/graphql/graphql-tartiflette-detect.yaml
  technologies/graphql/graphql-wpgraphql-detect.yaml
Labels: Done

#12565 Create CVE-2023-49230.yaml
  http/cves/2023/CVE-2023-49230.yaml
Labels: Done

#12555 Create CVE-2025-32815.yaml (NetMRI Authentication Bypass via Hardcoded Credentials)
  http/cves/2025/CVE-2025-32815.yaml
Labels: Done

#12549 Create dd-wrt-controlpanel-exposure.yaml (DD-WRT Control Panel - Exposure)
  http/misconfiguration/dd-wrt-controlpanel-exposure.yaml
Labels: Done

#12548 Create twonky-server-exposure.yaml (Twonky Server - Exposure)
  http/misconfiguration/twonky-server-exposure.yaml
Labels: Done

#12570 Updated CVE-2024-51978
  http/cves/2024/CVE-2024-51978.yaml
Labels: Done

#12154 add CVE-2022-42475
  code/cves/2022/CVE-2022-42475.yaml
Labels: Done, 🙋 Bounty claim

#12510 Create CVE-2025-49493.yaml (Akamai CloudTest - XML External Entity)
  http/cves/2025/CVE-2025-49493.yaml
Labels: Done

#12571 Create CVE-2025-52488.yaml (Unicode Path Normalization in DNN FileUploader)
  http/cves/2025/CVE-2025-52488.yaml
Labels: Done

#12588 Update and rename wordpress-rce-simplefilelist.yaml to CVE-2025-34085
  http/cves/2025/CVE-2025-34085.yaml
Labels: Done

#12573 Create CVE-2025-27505 - GeoServer - Missing Authorization on REST API Index
  http/cves/2025/CVE-2025-27505.yaml
Labels: Done

#12591 Create CVE-2022-23397.yaml (Cedar Gate EZ-NET <= 6.8.0 - Reflected XSS)
  http/cves/2022/CVE-2022-23397.yaml
Labels: Done

#12583 Create CVE-2025-6216.yaml
  code/cves/2025/CVE-2025-6216.yaml
Labels: Done

#12582 Create infoblox-netmri-rails-cookie-rce.yaml
  http/vulnerabilities/infoblox/infoblox-netmri-rails-cookie-rce.yaml
Labels: Done

#12593 Nuclei Templates v10.2.5 - Release Prep
  http/technologies/graphql/graphql-apiforwp-detect.yaml
  http/technologies/graphql/graphql-apollo-detect.yaml
  http/technologies/graphql/graphql-ariadne-detect.yaml
  http/technologies/graphql/graphql-dianajl-detect.yaml
  http/technologies/graphql/graphql-flutter-detect.yaml
  http/technologies/graphql/graphql-go-detect.yaml
  http/technologies/graphql/graphql-gqlgen-detect.yaml
  http/technologies/graphql/graphql-graphene-detect.yaml
  http/technologies/graphql/graphql-hasura-detect.yaml
  http/technologies/graphql/graphql-hypergraphql-detect.yaml
  http/technologies/graphql/graphql-java-detect.yaml
  http/technologies/graphql/graphql-juniper-detect.yaml
  http/technologies/graphql/graphql-php-detect.yaml
  http/technologies/graphql/graphql-ruby-detect.yaml
  http/technologies/graphql/graphql-sangria-detect.yaml
  http/technologies/graphql/graphql-strawberry-detect.yaml
  http/technologies/graphql/graphql-tartiflette-detect.yaml
  http/technologies/graphql/graphql-wpgraphql-detect.yaml
  http/technologies/wordpress/plugins/blocksy-companion.yaml
  http/technologies/wordpress/plugins/gosmtp.yaml
  http/technologies/wordpress/plugins/honeypot.yaml
  http/technologies/wordpress/plugins/pagelayer.yaml
  http/technologies/wordpress/plugins/siteseo.yaml
  http/technologies/wordpress/plugins/unlimited-elements-for-elementor.yaml
Labels: Done

#12600 Create wp-ninja-tables-lfi.yaml (Ninja Tables <4.1.9 - Unauthenticated Arbitrary File Read)
  http/vulnerabilities/wordpress/wp-ninja-tables-lfi.yaml
Labels: Status: In Progress, Done

#12608 Create CVE-2020-29390.yaml (Zeroshell - Command Injection)
  http/cves/2020/CVE-2020-29390.yaml
Labels: Done

#12610 moved code CVEs
  code/cves/2023/CVE-2023-2986.yaml
  code/cves/2024/CVE-2024-9487.yaml
Labels: Done

#12596 fix: update printer info leak template to print more context
  network/misconfig/printers-info-leak.yaml
Labels: good first issue, Done

#12617 Create CVE-2025-2711.yaml
  http/cves/2025/CVE-2025-2711.yaml
Labels: Done

#12614 Create saltbo-zpan-panel.yaml
  http/exposed-panels/saltbo-zpan-panel.yaml
Labels: Done

#12612 Create CVE-2025-2712.yaml
  http/cves/2025/CVE-2025-2712.yaml
Labels: Done

#12620 Create CVE-2024-9007.yaml
  http/cves/2024/CVE-2024-9007.yaml
Labels: Done

#12615 Create CVE-2025-2709.yaml
  http/cves/2025/CVE-2025-2709.yaml
Labels: Done

#12604 Create CVE-2025-6970.yaml (WordPress Events Manager <= 7.0.3 - Unauthenticated SQL Injection via orderby Parameter)
  http/cves/2025/CVE-2025-6970.yaml
Labels: Done

#12611 Create CVE-2025-34300.yaml (SawtoothSoftware Lighthouse Studio <9.16.14 – Pre‑Auth Remote Code Execution)
  http/cves/2025/CVE-2025-34300.yaml
Labels: Status: In Progress, Done

#12638 Create CVE-2024-33832.yaml
  http/cves/2024/CVE-2024-33832.yaml
Labels: Done

#12671 Rename access-log.yaml to access-log-file.yaml
  http/exposures/logs/access-log-file.yaml
Labels: Done

#12672 Update and rename arcgis-tokens.yaml to arcgis-token-service-detect.yaml
  http/technologies/arcgis-token-service-detect.yaml
Labels: Done

#12673 Update cisco-asa-panel.yaml
  http/exposed-panels/cisco/cisco-asa-panel.yaml
Labels: Done

#12674 Rename citrix-adc-gateway-detect.yaml to citrix-adc-gateway-panel.yaml
  http/exposed-panels/citrix-adc-gateway-panel.yaml
Labels: Done

#12664 Add flow optimization to multiple paylaods/ reqs templates for performance improvement
  http/cves/2014/CVE-2014-2383.yaml
  http/cves/2017/CVE-2017-17562.yaml
  http/cves/2021/CVE-2021-26084.yaml
  http/cves/2022/CVE-2022-2034.yaml
  http/cves/2023/CVE-2023-24489.yaml
  http/cves/2023/CVE-2023-27524.yaml
  http/cves/2023/CVE-2023-2825.yaml
  http/cves/2023/CVE-2023-6379.yaml
  http/default-logins/apache/tomcat-default-login.yaml
  http/default-logins/couchdb/couchdb-default-login.yaml
  http/default-logins/esafenet-cdg-default-login.yaml
  http/default-logins/goip-default-login.yaml
  http/default-logins/jboss/jboss-jbpm-default-login.yaml
  http/default-logins/jboss/jmx-default-login.yaml
  http/default-logins/oracle/peoplesoft-default-login.yaml
  http/default-logins/phpmyadmin/phpmyadmin-default-login.yaml
  http/default-logins/weblogic/weblogic-weak-login.yaml
  http/exposures/apis/swagger-api.yaml
  http/fuzzing/wordpress-plugins-detect.yaml
  http/fuzzing/wordpress-themes-detect.yaml
  http/vulnerabilities/generic/generic-j2ee-lfi.yaml
  http/vulnerabilities/generic/generic-linux-lfi.yaml
  http/vulnerabilities/generic/generic-windows-lfi.yaml
Labels: Done

#12681 Fix FP molgenis-default-login.yaml
  http/default-logins/molgenis/molgenis-default-login.yaml
Labels: Done

#12683 FN Fix nacos-create-user.yaml
  http/misconfiguration/nacos/nacos-create-user.yaml
Labels: Done

#12632 Create CVE-2025-49029.yaml
  http/cves/2025/CVE-2025-49029.yaml
Labels: Done

#12627 Update ms-exchange-local-domain.yaml
  http/misconfiguration/microsoft/ms-exchange-local-domain.yaml
Labels: Done

#12625 Create nats-server-enum.yaml
  network/enumeration/nats-server-enum.yaml
Labels: Done

#12647 FP - Fix phpmyadmin-misconfiguration.yaml
  http/misconfiguration/phpmyadmin/phpmyadmin-misconfiguration.yaml
Labels: Done

#12694 Create bofamet-stealer-panel.yaml
  http/exposed-panels/c2/bofamet-stealer-panel.yaml
Labels: Done

#12693 Create cyber-stealer-panel.yaml
  http/exposed-panels/c2/cyber-stealer-panel.yaml
Labels: Done

#12631 Create CVE-2025-5961.yaml
  http/cves/2025/CVE-2025-5961.yaml
Labels: Status: In Progress, Done

#12689 Create CVE-2025-34141.yaml (ETQ Reliance Reflected XSS via `SQLConverterServlet`)
  http/cves/2025/CVE-2025-34141.yaml
Labels: Done

#12713 Update CVE-2025-53770.yaml
  http/cves/2025/CVE-2025-53770.yaml
Labels: Done

#12745 Update kev tags for vulnerabilities
  http/cves/2016/CVE-2016-10033.yaml
  http/cves/2019/CVE-2019-5418.yaml
  http/cves/2024/CVE-2024-58136.yaml
  http/cves/2025/CVE-2025-2775.yaml
  http/cves/2025/CVE-2025-2776.yaml
  http/cves/2025/CVE-2025-47812.yaml
  http/cves/2025/CVE-2025-5777.yaml
  http/vulnerabilities/other/apache-druid-log4j.yaml
  http/vulnerabilities/other/xenmobile-server-log4j.yaml
Labels: Done

#12738 Update papercut-ng-panel
  http/exposed-panels/papercut-ng-panel.yaml
Labels: Done, reviewed-by-bot

#12643 Update aspect-control-panel
  http/exposed-panels/aspect-control-panel.yaml
Labels: Done

#12746 Fix FN CVE-2025-4388.yaml
  http/cves/2025/CVE-2025-4388.yaml
Labels: Done

#12708 Address false negative in iDRAC 9 Default Login
  http/default-logins/dell/dell-idrac9-default-login.yaml
Labels: Done

#12714 Create CVE-2025-6197.yaml (Open Redirect via Organization Switching)
  http/cves/2025/CVE-2025-6197.yaml
Labels: Done

#12652 Added template for easycvr-user-info-leak
  http/vulnerabilities/other/easycvr-user-info-disclosure.yaml
Labels: Done

#11972 DNT Policy Detect
  http/miscellaneous/dnt-policy-detect.yaml
Labels: Done

#11984 Add NocoBase Detect
  http/technologies/nocobase-detect.yaml
Labels: Done

#12751 Create apache-inlong-detect.yaml and apache-inlong-default-login.yaml
  http/default-logins/apache/apache-inlong-default-login.yaml
  http/technologies/apache/apache-inlong-detect.yaml
Labels: Done

#12754 Create CVE-2024-2053.yaml
  http/cves/2024/CVE-2024-2053.yaml
Labels: Done
