Repository projectdiscovery/nuclei-templates, pull requests merged in 2025-08, with the labels that each got.

#12706 Fixes to OSINT Templates
  http/osint/user-enumeration/9gag.yaml
  http/osint/user-enumeration/apple-developer.yaml
  http/osint/user-enumeration/apple-discussions.yaml
  http/osint/user-enumeration/atcoder.yaml
  http/osint/user-enumeration/bluesky.yaml
  http/osint/user-enumeration/cgtrader.yaml
  http/osint/user-enumeration/codechef.yaml
  http/osint/user-enumeration/geeksforgeeks.yaml
  http/osint/user-enumeration/genius-users.yaml
  http/osint/user-enumeration/giant-bomb.yaml
  http/osint/user-enumeration/hudsonrock.yaml
  http/osint/user-enumeration/kaskus.yaml
  http/osint/user-enumeration/lastfm.yaml
  http/osint/user-enumeration/letterboxd.yaml
  http/osint/user-enumeration/mixcloud.yaml
  http/osint/user-enumeration/monkeytype.yaml
  http/osint/user-enumeration/mydramalist.yaml
  http/osint/user-enumeration/nationstates-nation.yaml
  http/osint/user-enumeration/replit.yaml
  http/osint/user-enumeration/reverbnation.yaml
  http/osint/user-enumeration/runescape.yaml
  http/osint/user-enumeration/scribd.yaml
  http/osint/user-enumeration/sketchfab.yaml
  http/osint/user-enumeration/slack.yaml
  http/osint/user-enumeration/strava.yaml
  http/osint/user-enumeration/topcoder.yaml
  http/osint/user-enumeration/weblate.yaml
  http/osint/user-enumeration/younow.yaml
Labels: Done

#12579 CVE-2025-25257 (Critical, CVSS: 9.8) - FortiWeb Vulnerability
  http/cves/2025/CVE-2025-25257.yaml
Labels: Done

#12785 Create zipline-installer.yaml
  http/misconfiguration/installer/zipline-installer.yaml
Labels: Done

#12771 Create CVE-2025-53558.yaml (ZTE ZXHN-F660T/F660A - Default Credentials)
  http/cves/2025/CVE-2025-53558.yaml
Labels: Done

#12769 Create CVE-2025-5394.yaml (Unauthenticated Arbitrary Plugin Upload in Alone Theme)
  http/cves/2025/CVE-2025-5394.yaml
Labels: Done

#12800 Added template for CVE-2025-48954
  http/cves/2025/CVE-2025-48954.yaml
Labels: Done

#12803 Swagger UI XSS - CVE-2025-8191
  headless/cves/2025/CVE-2025-8191.yaml
  helpers/payloads/swagger.json
  helpers/payloads/swagger.yaml
Labels: Done

#12739 Create meddream-dicom-viewer-panel.yaml
  http/exposed-panels/meddream-dicom-viewer-panel.yaml
Labels: Done

#12743 Create titiler-ssrf.yaml (TiTiler - Blind Server Side Request Forgery)
  http/misconfiguration/titiler-ssrf.yaml
Labels: Done

#12765 Add CVE-2025-8286 - Güralp Systems FMUS
  http/cves/2025/CVE-2025-8286.yaml
Labels: Done

#12757 Create exposed-venv-dir.yaml
  http/exposures/files/python-venv-exposure.yaml
Labels: good first issue, Done

#12775 Create diced-zipline-detect.yaml
  http/exposed-panels/zipline-panel.yaml
Labels: Done

#12598 Add huawei-holosense-panel
  http/exposed-panels/huawei-holosense-panel.yaml
Labels: Done

#12828 fix(gcloud-default-vpc-in-use) update matcher for default VPC detection
  cloud/gcp/vpc/gcloud-default-vpc-in-use.yaml
Labels: good first issue

#12846 Add detection of HYPERDX data panel instances.
  http/exposed-panels/hyperdx-panel.yaml
Labels: Done

#12877 FN - Fix swagger-api.yaml
  http/exposures/apis/swagger-api.yaml
Labels: Done

#12885 Update ncentral-panel
  http/exposed-panels/ncentral-panel.yaml
Labels: Done

#12816 fix: reduce false positives in CVE-2022-1595.yaml
  http/cves/2022/CVE-2022-1595.yaml
Labels: Done

#12780 Add CVE-2025-34073.yaml
  http/cves/2025/CVE-2025-34073.yaml
Labels: good first issue, Done

#12633 Create CVE-2025-6934.yaml
  http/cves/2025/CVE-2025-6934.yaml
Labels: Done

#12759 Improve and Update CVE-2024-36104 and CVE-2024-38856
  http/cves/2024/CVE-2024-36104.yaml
  http/cves/2024/CVE-2024-38856.yaml
Labels: Done

#12791 feat(sqli): Add multiple payloads and author to time-based-sqli template
  dast/vulnerabilities/sqli/time-based-sqli.yaml
Labels: Done

#12903 Update fortinet-fortimanager-panel
  http/exposed-panels/fortinet/fortinet-fortimanager-panel.yaml
Labels: Done

#12645 Delete http/takeovers/tumblr-takeover.yaml
  http/takeovers/tumblr-takeover.yaml
Labels: Done

#12912 Create bugzilla-detect.yaml and bugzilla-config-exposed.yaml
  http/exposures/configs/bugzilla-config.yaml
  http/technologies/bugzilla-detect.yaml
Labels: Done

#12904 Create nfs-v3-exposed.yaml
  network/detection/nfs-v3-exposed.yaml
Labels: Done

#12922 Add detection of ROADIZ CMS instances.
  http/technologies/roadiz-cms-detect.yaml
Labels: reviewed-by-bot

#12419 Ubuntu CIS Phase-3 Template
  code/audit/cis/ubuntu/ftp-client.yaml
  code/audit/cis/ubuntu/inactive-password-lock-default.yaml
  code/audit/cis/ubuntu/ldap-client.yaml
  code/audit/cis/ubuntu/nis-client.yaml
  code/audit/cis/ubuntu/password-expiration.yaml
  code/audit/cis/ubuntu/password-min-days.yaml
  code/audit/cis/ubuntu/password-warn-age.yaml
  code/audit/cis/ubuntu/rsh-client.yaml
  code/audit/cis/ubuntu/strong-password-hashing.yaml
  code/audit/cis/ubuntu/talk-client.yaml
  code/audit/cis/ubuntu/telnet-client.yaml
Labels: Done

#12909 feat: add CVE-2025-55169 Nuclei Template
  http/cves/2025/CVE-2025-55169.yaml
Labels: good first issue, Done

#12918 Create CVE-2025-34152.yaml (Shenzhen Aitemi M300 Wi-Fi Repeater – Unauthenticated Remote Command Execution via `time` Parameter)
  http/cves/2025/CVE-2025-34152.yaml
Labels: Done

#12934 Create microweber-install.yaml
  http/misconfiguration/installer/microweber-install.yaml
Labels: Done

#12931 Add CVE-2025-34035 - EnGenius EnShare Cloud Service Command Injection
  http/cves/2025/CVE-2025-34035.yaml
Labels: good first issue, Done, 🙋 Bounty claim

#12827 fix(gcloud-public-access-prevention-not-enabled) enhance matchers
  cloud/gcp/storage/gcloud-public-access-prevention-not-enabled.yaml
Labels: good first issue, Done

#12768 feat: added 2018-19127
  http/cves/2018/CVE-2018-19127.yaml
Labels: Done, 🙋 Bounty claim

#12723 add CVE-2023-27163 template
  http/cves/2023/CVE-2023-27163.yaml
Labels: Done

#12831 Add sensitive system file permission checks
  code/linux/audit/rw-hosts-file.yaml
Labels: Done

#12849 Add Sendmail/SMTP and DNS related security check templates
  code/linux/audit/dns-zone-transfer-any.yaml
  code/linux/audit/sendmail-postfix-execution-restrictions.yaml
  code/linux/audit/smtp-open-relay.yaml
Labels: Done

#12836 Add SUID/SGID sticky bit check template
  code/linux/audit/suid-sgid.yaml
Labels: Done

#12825 add CVE-2025-51502 template for Microweber CMS XSS vulnerability
  http/cves/2025/CVE-2025-51502.yaml
Labels: Done

#12967 Create CVE-2018-7841.yaml
  http/cves/2018/CVE-2018-7841.yaml
Labels: Done, 🙋 Bounty claim

#12983 chore: update TFTP - add additional matchers
  javascript/udp/detection/tftp-detect.yaml
Labels: Done

#12971 Add detection of MESHERY instances.
  http/technologies/meshery-detect.yaml
Labels: Done

#12490 Update CVE-2024-36404 and CVE-2025-30220
  http/cves/2024/CVE-2024-36404.yaml
  http/cves/2025/CVE-2025-30220.yaml
Labels: Done

#12436 Add Atlona AT-OME-MS42 default login template
  http/default-logins/atlona/atlona-default-login.yaml
Labels: Done

#12988 Revise name and description in addeventlistener-detect.yaml
  http/miscellaneous/addeventlistener-detect.yaml
Labels: Done

#12835 Add Templates for Ownerless Files, Home Directory, and World-Writable Files
  code/linux/audit/home-env-permission.yaml
  code/linux/audit/linux-world-writable-file.yaml
Labels: Done

#12962 CVE-2025-1562 - Recover WooCommerce Cart Abandonment, Newsletter, Email Marketing, Marketing Automation By FunnelKit - Broken Access Control
  http/cves/2025/CVE-2025-1562.yaml
Labels: Done, 🙋 Bounty claim

#13002 Add Case Sensitive entry for phpMyAdmin setup path
  http/misconfiguration/phpmyadmin/phpmyadmin-setup.yaml
Labels: Done

#13004 Update opnsense-panel
  http/exposed-panels/opnsense-panel.yaml
Labels: Done

#13010 Update tomcat-stacktraces.yaml Severity
  http/misconfiguration/tomcat-stacktraces.yaml
Labels: Done

#12997 Revise CVE-2025-57788 with updated details and extractors
  http/cves/2025/CVE-2025-57788.yaml
Labels: Done

#12996 Create CVE-2025-54309.yaml (CrushFTP - Authentication Bypass Race Condition)
  code/cves/2025/CVE-2025-54309.yaml
Labels: Done

#13017 Create CVE-2025-32970.yaml
  http/cves/2025/CVE-2025-32970.yaml
Labels: Done

#13015 Create CVE-2025-54125.yaml
  http/cves/2025/CVE-2025-54125.yaml
Labels: Done

#12990 feat: add template for Microsoft SCCM - Anonymous DP Accesss
  http/misconfiguration/microsoft/anonymous-distribution-point-sccm.yaml
Labels: Done

#13001 Create ajp-protocol-detect.yaml
  javascript/detection/ajp-protocol-detect.yaml
Labels: Done

#13034 Create CVE-2025-25231.yaml (Omnissa Workspace ONE UEM - Path Traversal)
  http/cves/2025/CVE-2025-25231.yaml
Labels: Done
