Repository projectdiscovery/nuclei-templates, pull requests merged in 2025-09, with the labels that each got.

#13014 Add CVE-2025-53118 - (Securden Unified PAM - Authentication Bypass)
  http/cves/2025/CVE-2025-53118.yaml
Labels: Done

#13085 Add stop-at-first-match option to heapdump config
  http/misconfiguration/springboot/springboot-heapdump.yaml
Labels: Done

#13090 Fix FN retool-svg-xss (wrong matchers)
  http/vulnerabilities/retool/retool-svg-xss.yaml
Labels: Done

#13093 Create CVE-2024-29028.yaml
  http/cves/2024/CVE-2024-29028.yaml
Labels: Done

#13073 Create n8n-config.yaml
  http/exposures/configs/n8n-config.yaml
Labels: Done

#13074 feat(templates): Add Nuclei template for clients6 CSP bypass
  dast/vulnerabilities/xss/csp-bypass/clients6-csp-bypass.yaml
Labels: Done

#13061 Add template for CVE-2025-57822
  http/cves/2025/CVE-2025-57822.yaml
Labels: Done

#13095 Update netstat detection template
  http/exposed-panels/netdata-panel.yaml
Labels: Done

#12941 Add CVE-2025-23061 template for Mongoose NoSQL injection vulnerability
  http/cves/2025/CVE-2025-23061.yaml
Labels: good first issue, Done

#13108 Create netstat-service-expose.yaml
  javascript/misconfiguration/netstat-service-expose.yaml
Labels: Done

#13107 Create sap-router-detect.yaml
  network/detection/sap-router-detect.yaml
Labels: Done

#13106 Create sap-dispatcher-detect.yaml
  network/detection/sap-dispatcher-detect.yaml
Labels: Done

#13110 Create pigeonhole-sieve-detect.yaml
  javascript/detection/pigeonhole-sieve-detect.yaml
Labels: Done

#13120 Create zeroconf-detect.yaml
  javascript/udp/detection/zeroconf-detect.yaml
Labels: Done

#13105 Create hugegraph-studio-detect.yaml
  http/technologies/hugegraph-studio-detect.yaml
Labels: Done

#12541 feat: Add hikvision-cam-info-exposure.yaml
  vulnerabilities/iot/hikvision/hikvision-cam-info-exposure.yaml
Labels: good first issue, Done

#13166 Add CVE-2024-33326 XSS template for LumisXP
  http/cves/2024/CVE-2024-33326.yaml
Labels: Done

#13173 Edited wazuh-panel.yaml
  http/exposed-panels/wazuh-panel.yaml
Labels: Done

#13148 Make Canon iR-ADV panel generic detection
  http/exposed-panels/canon/canon-ir-adv.yaml
Labels: Done

#13115 feat(template): add Salesforce CSP bypass detection
  dast/vulnerabilities/xss/csp-bypass/salesforce-csp-bypass.yaml
Labels: Done

#13151 Added CVE-2022-4971 Template vKEV
  http/cves/2022/CVE-2022-4971.yaml
Labels: Done

#13180 Fix FP airflow-v3-default-login.yaml
  http/default-logins/apache/airflow-v3-default-login.yaml
Labels: Done

#13124 Create apache-streampark-detect.yaml and apache-streampark-default-login.yaml
  http/default-logins/apache/apache-streampark-default-login.yaml
  http/technologies/apache/apache-streampark-detect.yaml
Labels: Done

#13128 add CVE-2022-0429 vKEV
  http/cves/2022/CVE-2022-0429.yaml
Labels: Done

#13094 mitel-nupoint-unified-messaging-panel
  http/exposed-panels/mitel-nupoint-panel.yaml
Labels: Done

#13152 add CVE-2025-8085
  http/cves/2025/CVE-2025-8085.yaml
Labels: Done

#13244 NEST OWASP User OSINT
  http/osint/user-enumeration/nest-owasp.yaml
Labels: Done

#13213 Create openmetadata-admin-userenum.yaml
  http/exposures/configs/openmetadata-admin-userenum.yaml
Labels: Done

#13145 CVE-2020-23814.yaml
  http/cves/2020/CVE-2020-23814.yaml
Labels: Done

#13190 Add CVE-2014-8739: Creative Contact Form 0.9.7 - Arbitrary File Upload
  http/cves/2014/CVE-2014-8739.yaml
Labels: Done, 🙋 Bounty claim

#13230 CVE-2021-24170 vKEV
  http/cves/2021/CVE-2021-24170.yaml
Labels: Done

#13240 Fix False Positive redirect from Cloudflare for CVE-2022-40022
  http/cves/2022/CVE-2022-40022.yaml
Labels: Done

#13265 Create flowise-installer.yaml
  http/misconfiguration/installer/flowise-installer.yaml
Labels: Done

#13113 Barracuda Message Archiver exposed panel
  http/exposed-panels/barracuda-message-panel.yaml
Labels: Done

#13177 CVE-2019-9881 WPGraphQL <= 0.2.3 - Unauthenticated Comment Posting (vKEV)
  http/cves/2019/CVE-2019-9881.yaml
Labels: Done

#13192 Add CVE-2024-4898 (vKEV)
  http/cves/2024/CVE-2024-4898.yaml
Labels: Done

#13269 add CVE-2020-11515 (vKEV)
  http/cves/2020/CVE-2020-11515.yaml
Labels: Done

#13171 Add CVE-2023-6000 (vKEV)
  http/cves/2023/CVE-2023-6000.yaml
Labels: Done

#13268 add CVE-2020-11514 (vKEV)
  http/cves/2020/CVE-2020-11514.yaml
Labels: Done

#13198 Add CVE-2023-0037 (vKEV)
  http/cves/2023/CVE-2023-0037.yaml
Labels: Done

#13221 CVE-2023-0876 (vKEV)
  http/cves/2023/CVE-2023-0876.yaml
Labels: Done

#13274 Add CVE-2022-3124 (vKEV)
  http/cves/2022/CVE-2022-3124.yaml
Labels: Done

#13272 Add CVE-2022-2461 (vKEV)
  http/cves/2022/CVE-2022-2461.yaml
Labels: Done

#13276 Add CVE-2024-2771.yaml (vKEV)
  http/cves/2024/CVE-2024-2771.yaml
Labels: Done

#13281 Update CVE-2020-27615.yaml with new HTTP flow and matchers
  http/cves/2020/CVE-2020-27615.yaml
Labels: Done

#13227 Add CVE-2021-34624.yaml (vKEVs)
  http/cves/2021/CVE-2021-34624.yaml
Labels: Done, reviewed-by-bot

#13266 Add CVE-2020-36155 (vKEV)
  http/cves/2020/CVE-2020-36155.yaml
Labels: Done, reviewed-by-bot

#13285 ADD CVE-2019-9880 (vKEV)
  http/cves/2019/CVE-2019-9880.yaml
Labels: Done

#13195 Add CVE-2025-55161 template
  http/cves/2025/CVE-2025-3605.yaml
  http/cves/2025/CVE-2025-55161.yaml
Labels: Done

#11950 Added CVE-2023-47873 Template
  http/cves/2023/CVE-2023-47873.yaml
Labels: Done

#13293 Update hikvision-cam-info-exposure.yaml
  http/iot/hikvision-cam-info-exposure.yaml
Labels: Done

#13287 ADD CVE-2023-40000 (vKEV)
  http/cves/2023/CVE-2023-40000.yaml
Labels: Done

#13296 Add CVE-2019-17231 (vKEV)
  http/cves/2019/CVE-2019-17231.yaml
Labels: Done

#13302 Create dell-remote-web-access-panel.yaml
  http/exposed-panels/dell-remote-web-access-panel.yaml
Labels: Done

#13303 Create unauth-dell-laser-printer.yaml
  http/iot/dell-laser-printer-unauth.yaml
Labels: Done

#13305 Create hpe-officeconnect-panel-detect.yaml
  http/exposed-panels/hpe-officeconnect-panel.yaml
Labels: Done

#13297 Added CVE-2019-15774(vKEV)
  http/cves/2019/CVE-2019-15774.yaml
Labels: Done

#13174 Added CVE 2021 24878 vKEV
  http/cves/2021/CVE-2021-24878.yaml
Labels: Done

#13312 Add CVE-2019-17228 (vKEV)
  http/cves/2019/CVE-2019-17228.yaml
Labels: Done

#13313 feat: add Scan2Net panel detection template
  http/exposed-panels/scan2net-panel.yaml
Labels: Done

#12812 Added/CVE-2022-37932
  network/cves/2022/CVE-2022-37932.yaml
Labels: good first issue, Done

#12719 Refactored robots-txt-endpoint: improved extractor regex, reduced requests, simplified matchers
  http/exposures/files/bitbucket-oauth-exposure.yaml
  http/miscellaneous/robots-txt-endpoint.yaml
  http/miscellaneous/robots-txt.yaml
  http/misconfiguration/springboot/springboot-health.yaml
  http/misconfiguration/springboot/springboot-info.yaml
  http/misconfiguration/springboot/springboot-loggers.yaml
  http/misconfiguration/springboot/springboot-metrics.yaml
  http/technologies/springboot-actuator.yaml
Labels: Done

#13318 Add condition to CVE-2024-43441.yaml
  http/cves/2024/CVE-2024-43441.yaml
Labels: Done

#13324 Add CVE-2021-32648 (vKEV and KEV)
  http/cves/CVE-2021-32648.yaml
Labels: Done

#13323 Add CVE-2024-31839 (vKEV)
  http/cves/2024/CVE-2024-31839.yaml
Labels: Done

#13322 Salesloft Drift Detection
  dns/txt-service-detect.yaml
Labels: Done

#13308 Add CVE-2019-11886 (vKEV)
  http/cves/2019/CVE-2019-11886.yaml
Labels: Done

#13370 Add CVE-2022-25322 (vKEV)
  http/cves/2022/CVE-2022-25322.yaml
Labels: Done

#13383 Rename CVE-2021-24295.yaml to CVE-2021-24295.yaml
  passive/cves/2021/CVE-2021-24295.yaml
Labels: Done

#13387 Move passive templates to respective CVE directories and add passive …
  http/cves/2015/CVE-2015-9406.yaml
  http/cves/2018/CVE-2018-17207.yaml
  http/cves/2020/CVE-2020-36705.yaml
  http/cves/2021/CVE-2021-24295.yaml
  http/cves/2022/CVE-2022-3805.yaml
  http/cves/2022/CVE-2022-41352.yaml
  http/cves/2023/CVE-2023-4666.yaml
  http/cves/2024/CVE-2024-25723.yaml
  http/cves/2024/CVE-2024-32651.yaml
  http/cves/2024/CVE-2024-40711.yaml
Labels: Done

#13386 Create CVE-2016-10972.yaml
  http/cves/2016/CVE-2016-10972.yaml
Labels: Done

#13389 Create CVE-2020-36723.yaml
  http/cves/2020/CVE-2020-36723.yaml
Labels: Done

#13394 Create CVE-2023-6933.yaml (Passive) -KEV
  http/cves/2023/CVE-2023-6933.yaml
Labels: Done

#13399 Create CVE-2022-3481.yaml
  http/cves/2022/CVE-2022-3481.yaml
Labels: Done

#13405 docs: Fix broken links in contribution guide
  CONTRIBUTING.md
Labels: Done

#13407 Create CVE-2021-20021.yaml (Passive) KEV
  http/cves/2021/CVE-2021-20021.yaml
Labels: Done

#13396 Add CVE-2023-23063 (vKEV)
  http/cves/2023/CVE-2023-23063.yaml
Labels: Done

#13382 Add CVE-2022-38840 (vKEV)
  http/cves/2022/CVE-2022-38840.yaml
Labels: Done

#13403 Added CVE-2022-3805 (vKEV)
  http/cves/2022/CVE-2022-3805.yaml
Labels: Done

#13355 Create CVE-2020-8656.yaml (EyesOfNetwork - Hardcoded API Key & SQLi) KEV
  http/cves/2020/CVE-2020-8656.yaml
Labels: Done

#13373 CVE-2021-24219 - All Thrive Themes and Plugins - Unauthenticated Option Update
  http/cves/2021/CVE-2021-24219.yaml
Labels: Done

#13427 CVE-2022-37932: fix flow to remove false positives
  network/cves/2022/CVE-2022-37932.yaml
Labels: Done

#13418 Add CVE-2018-1217 (vKEV)
  http/cves/2018/CVE-2018-1217.yaml
Labels: Done

#13428 Add Mitel 6000 default login template
  http/default-logins/mitel/mitel-6000-default-login.yaml
Labels: Done

#13421 CVE-2025-54251 - Adobe Experience Manager - XXE
  http/cves/2025/CVE-2025-54251.yaml
Labels: Done
